- requirement: 1
  text: |-
    Explain to your counselor the precautions that must be followed for the
    safe use and operation of a sculptor’s tools, equipment, and other
    materials.
- requirement: 2
  text: |-
    Do TWO of the following:
  children:
    - requirement: a
      text: |-
        Model in clay a life-size human head. Then sculpt in modeling clay,
        carve in wood or plaster, or use 3D modeling software to make a
        small-scale model of an animal or person. Explain to your counselor
        the method and tools you used to sculpt the figure.
    - requirement: b
      text: |-
        Make a plaster mold of a fruit or vegetable. In this mold, make a
        copy of the fruit or vegetable. Explain to your counselor the
        method and tools you used to make the copy.
    - requirement: c
      text: |-
        With your parent’s permission and your counselor’s approval, visit
        a museum, art exhibit, art gallery, artists’ co-op, or artist’s
        studio. After your visit, share with your counselor what you have
        learned. Discuss the importance of visual arts and how it
        strengthens social tolerance and helps stimulate cultural,
        intellectual, and personal development.
- requirement: 3
  text: |-
    Find out about career opportunities in sculpture. Pick one and find out
    the education, training, and experience required for this profession.
    Discuss this with your counselor, and explain why this profession might
    interest you.
