# 2b uses a double hyphen and the rest use single. Adjusted to be single.
# Requirement 7 doesn't have a period, like "7."
- requirement: 1
  text: |-
    Safety. Do the following:
  children:
    - requirement: a
      text: |-
        Explain to your counselor the most likely hazards you may encounter
        while working with photography and what you should do to anticipate,
        mitigate, prevent, and respond to these hazards. Explain how you would
        prepare for exposure to environmental situations such as weather, sun,
        and water.
    - requirement: b
      text: |-
        View the <a
        href="https://www.scouting.org/training/youth-protection/scouts-bsa/"
        >Personal Safety Awareness "Digital Safety" video</a> (with your parent
        or guardian's permission).
- requirement: 2
  text: |-
    Explain how the following elements and terms can affect the quality of a
    picture:
  children:
    - requirement: a
      text: |-
        Light - natural light (ambient/existing), low light (such as at night),
        and artificial light (such as from a flash)
    - requirement: b
      text: |-
        Exposure -- aperture (f-stops), shutter speed, ISO
    - requirement: c
      text: |-
        Depth of field
    - requirement: d
      text: |-
        Composition - rule of thirds, leading lines, framing, depth
    - requirement: e
      text: |-
        Angle of view
    - requirement: f
      text: |-
        Stop action and blur motion
    - requirement: g
      text: |-
        Decisive moment (action or expression captured by the photographer).
- requirement: 3
  text: |-
    Explain the basic parts and operation of a camera. Explain how an exposure
    is made when you take a picture.
- requirement: 4
  text: |-
    Do TWO of the following, then share your work with your counselor.
  children:
    - requirement: a
      text: |-
        Photograph one subject from two different angles or perspectives.
    - requirement: b
      text: |-
        Photograph one subject from two different light sources - artificial
        and natural.
    - requirement: c
      text: |-
        Photograph one subject with two different depth of fields.
    - requirement: d
      text: |-
        Photograph one subject with two different compositional techniques.
- requirement: 5
  text: |-
    Photograph THREE of the following, then share your work with your
    counselor.
  children:
    - requirement: a
      text: |-
        Close-up of a person
    - requirement: b
      text: |-
        Two to three people interacting
    - requirement: c
      text: |-
        Action shot
    - requirement: d
      text: |-
        Animal shot
    - requirement: e
      text: |-
        Nature shot
    - requirement: f
      text: |-
        Picture of a person - candid, posed, or camera aware.
- requirement: 6
  text: |-
    Describe how software allows you to enhance your photograph after it is
    taken. Select a photo you have taken, then do ONE of the following, and
    share what you have done with your counselor.
  children:
    - requirement: a
      text: |-
        Crop your photograph
    - requirement: b
      text: |-
        Adjust the exposure or make a color correction
    - requirement: c
      text: |-
        Show another way you could improve your picture for impact.
- requirement: 7
  text: |-
    Using images other than those created for requirements 4, 5, and 6, produce
    a visual story to document an event to photograph OR choose a topic that
    interests you to photograph. Do the following:
  children:
    - requirement: a
      text: |-
        Plan the images you need to photograph for your photo story.
    - requirement: b
      text: |-
        Share your plan with your counselor, and get your counselor's input and
        approval before you proceed.
    - requirement: c
      text: |-
        Select eight to 12 images that best tell your story. Arrange your
        images in order and mount the prints on a poster board, OR create an
        electronic presentation. Share your visual story with your counselor.
- requirement: 8
  text: |-
    Identify three career opportunities in photography. Pick one and explain to
    your counselor how to prepare for such a career. Discuss what education and
    training are required, and why this profession might interest you.
