- requirement: 1
  text: |-
      Safety. Do the following:
  children:
      - requirement: a
        text: |-
            Show your counselor your current [Cyber
            Chip](/other-awards/cyber-chip/).
        workbook:
            - signature: Adult Scout Leader
      - requirement: b
        text: |-
            Explain to your counselor the most likely hazards you may encounter
            while working with photography and what you should do to
            anticipate, mitigate, prevent, and respond to these hazards.
            Explain how you would prepare for exposure to environmental
            situations such as weather, sun, and water.
        workbook:
            - lines: 8
              text: |-
                  Most likely hazards
            - lines: 8
              text: |-
                  Anticipate hazards
            - lines: 8
              text: |-
                  Prevent hazards
            - lines: 8
              text: |-
                  Mitigate hazards
            - lines: 8
              text: |-
                  Respond to hazards
            - lines: 8
              text: |-
                  How you would prepare for exposure to environmental
                  situations
- requirement: 2
  text: |-
      Explain how the following elements and terms can affect the quality of a
      picture:
  children:
      - requirement: a
        text: |-
            Light—natural light (ambient/existing), low light (such as at
            night), and artificial light (such as from a flash)
        workbook:
            - lines: 8
      - requirement: b
        text: |-
            Exposure—aperture (f-stops), shutter speed, ISO
        workbook:
            - lines: 8
      - requirement: c
        text: |-
            Depth of field
        workbook:
            - lines: 8
      - requirement: d
        text: |-
            Composition—rule of thirds, leading lines, framing, depth
        workbook:
            - lines: 8
      - requirement: e
        text: |-
            Angle of view
        workbook:
            - lines: 8
      - requirement: f
        text: |-
            Stop action and blur motion
        workbook:
            - lines: 8
      - requirement: g
        text: |-
            Decisive moment (action or expression captured by the photographer)
        workbook:
            - lines: 8
- requirement: 3
  text: |-
      Explain the basic parts and operation of a camera. Explain how an
      exposure is made when you take a picture.
  workbook:
      - lines: 8
- requirement: 4
  text: |-
      Do TWO of the following, then share your work with your counselor.
  children:
      - requirement: a
        text: |-
            Photograph one subject from two different angles or perspectives.
        workbook:
            - lines: 4
      - requirement: b
        text: |-
            Photograph one subject from two different light sources—artificial
            and natural.
        workbook:
            - lines: 4
      - requirement: c
        text: |-
            Photograph one subject with two different depths of field.
        workbook:
            - lines: 4
      - requirement: d
        text: |-
            Photograph one subject with two different compositional techniques.
        workbook:
            - lines: 4
- requirement: 5
  text: |-
      Photograph THREE of the following, then share your work with your
      counselor.
  workbook:
      - task: true
        text: |-
            a. Close-up of a person
      - task: true
        text: |-
            b. Two to three people interacting
      - task: true
        text: |-
            c. Action shot
      - task: true
        text: |-
            d. Animal shot
      - task: true
        text: |-
            e. Nature shot
      - task: true
        text: |-
            f. Picture of a person—candid, posed, or camera aware
  children:
      - requirement: a
        text: |-
            Close-up of a person
        workbookHide: true
      - requirement: b
        text: |-
            Two to three people interacting
        workbookHide: true
      - requirement: c
        text: |-
            Action shot
        workbookHide: true
      - requirement: d
        text: |-
            Animal shot
        workbookHide: true
      - requirement: e
        text: |-
            Nature shot
        workbookHide: true
      - requirement: f
        text: |-
            Picture of a person—candid, posed, or camera aware
        workbookHide: true
- requirement: 6
  text: |-
      Describe how software allows you to enhance your photograph after it is
      taken. Select a photo you have taken, then do ONE of the following, and
      share what you have done with your counselor.
  workbook:
      - lines: 8
        text: |-
            How software allows you to enhance your photograph
      - task: true
        text: |-
            a. Crop your photograph.
      - task: true
        text: |-
            b. Adjust the exposure or make a color correction.
      - task: true
        text: |-
            c. Show another way you could improve your picture for impact.
  children:
      - requirement: a
        text: |-
            Crop your photograph.
        workbookHide: true
      - requirement: b
        text: |-
            Adjust the exposure or make a color correction.
        workbookHide: true
      - requirement: c
        text: |-
            Show another way you could improve your picture for impact.
        workbookHide: true
- requirement: 7
  text: |-
      Using images other than those created for requirements 4, 5, and 6,
      produce a visual story to document an event to photograph OR choose a
      topic that interests you to photograph. Do the following:
  children:
      - requirement: a
        text: |-
            Plan the images you need to photograph for your photo story.
        workbook:
            - lines: 8
      - requirement: b
        text: |-
            Share your plan with your counselor, and get your counselor’s input
            and approval before you proceed.
        workbook:
            - lines: 8
      - requirement: c
        text: |-
            Select eight to 12 images that best tell your story.  Arrange your
            images in order and mount the prints on a poster board, OR create
            an electronic presentation.  Share your visual story with your
            counselor.
        workbook:
            - lines: 8
- requirement: 8
  text: |-
      Identify three career opportunities in photography. Pick one and explain
      to your counselor how to prepare for such a career. Discuss what
      education and training are required, and why this profession might
      interest you.
  workbook:
      - lines: 8
