- requirement: 1
  text: |-
      Before fulfilling the following requirements, you must successfully
      complete the BSA swimmer classification test.
- requirement: 2
  text: |-
      Review how each point of BSA Safety Afloat applies to boardsailing.
- requirement: 3
  text: |-
      Explain precautions for the following environmental factors: dying wind,
      high wind, offshore winds, currents, waves, and lightning.
- requirement: 4
  text: |-
      Discuss the prevention, recognition, and treatment of the following
      health concerns that could arise while boardsailing: hypothermia,
      sunburn, dehydration, and heat exhaustion.
- requirement: 5
  text: |-
      Properly rig and prepare the sailboard you are using.  Identify each of
      the following: uphaul, outhaul, downhaul, cleat, leach, tack, clew, foot,
      luff, skeg, centerboard, wishbone boom, and universal. Explain luffing.
      Explain how to steer the sailboard by adjusting the center of effort.
- requirement: 6
  text: |-
      Demonstrate your ability to uphaul the sail, find the neutral position to
      the wind (sail luffing), and control the board’s position with foot
      movement.
- requirement: 7
  text: |-
      With supervision from your instructor, sail a course that involves beating, reaching, and running. Change direction by tacking into the wind.
