- requirement: 1
  text: |-
      Discuss the role and value of laws in society with regard to crime and crime prevention. Include in your discussion the definitions of “crime” and “crime prevention.”
  workbook:
    - lines: 8
      text: |-
        Definition of "crime"
    - lines: 8
      text: |-
        Definition of "crime prevention"
    - lines: 8
      text: |-
        Role and value of laws in society with regard to crime and crime prevention
  children:
    - note:
      - inPerson
      - online
      text: |-
        Scouts should consider writing this out to show the counselor that some thought and research has gone into this requirement and Scouts should be prepared to discuss their findings.  Scouts will not automatically be signed off on this requirement just for attending as the requirement states that they must discuss several items and will be required to partake in group and/or individual discussion to obtain credit.
- requirement: 2
  text: |-
      Prepare a journal from various sources that address crime and crime prevention efforts in your community.
  workbook:
    - task: true
  children:
    - note:
      - inPerson
      - online
      text: |-
        Scouts will be engaged in discussion on their findings, their source of this information, and discuss how these issues they feel affect their community.  It is recommended that Scouts bring their notebook completed (if possible) as there will NOT be time allocated in the class for working on this requirement.  Scouts who bring a completed notebook will have an opportunity to review this requirement with the class counselor.
- requirement: 3
  text: |-
      Discuss the following with your counselor:
  children:
      - requirement: a
        text: |-
            The role of citizens, including youth, in crime prevention.
        workbook:
          - lines: 8
      - requirement: b
        text: |-
            Gangs and their impact on the community.
        workbook:
          - lines: 8
      - requirement: c
        text: |-
            When and how to report a crime.
        workbook:
          - lines: 8
      - note:
        - inPerson
        - online
        text: |-
          Scouts should review this requirement and its components and be prepared to discuss.
- requirement: 4
  text: |-
      After doing EACH of the following, discuss with your counselor what you have learned.
  children:
      - requirement: a
        text: |-
            Inspect your neighborhood for opportunities that may lead to crime.  Learn how to do a crime prevention survey.
        workbook:
          - lines: 8
            text: |-
              Inspect your neighborhood for opportunities that may lead to crime
          - lines: 8
            text: |-
              How to do a crime prevention survey
      - requirement: b
        text: |-
            Using the checklist in this pamphlet, conduct a security survey of your home and discuss the results with your family.
        workbook:
          - lines: 8
      - note:
        - inPerson
        - online
        text: |-
          Scouts will be engaged in discussion on their findings, review of their completed checklist, and discuss their findings and results.  It is recommended that Scouts bring their notes for requirement 4a and completed checklist and notes for requirement 4b.  This requirement will be discussed in the class, however only Scouts who have fully completed the requirements (which includes bringing the preparation work COMPLETED to class) will have an opportunity to be signed off on this requirement.
- requirement: 5
  text: |-
      Teach your family or patrol members how to protect themselves from crime at home, at school, in your community, and while traveling.
  workbook:
    - lines: 8
  children:
    - note:
      - inPerson
      - online
      text: |-
        Scouts should bring some sort of note from their parent or Patrol Leader validating that they have completed this requirement.  Only Scout who can show proof of doing this requirement prior to the class will have the opportunity to be considered for sign off on this requirement by the counselor.
- requirement: 6
  text: |-
      Help raise awareness about one school safety issue facing students by doing ONE of the following:
  children:
      - requirement: a
        text: |-
            Create a poster for display on a school bulletin board.
        workbook:
          - task: true
      - requirement: b
        text: |-
            With permission from school officials, create a pagelong public service announcement that could be read over the public address system at school or posted on the school’s website.
        workbook:
          - task: true
      - requirement: c
        text: |-
            Make a presentation to a group such as a Cub Scout den that addresses the issue.
        workbook:
          - task: true
      - note:
        - inPerson
        - online
        text: |-
          Scouts are encouraged to gather material ahead of time for use in creating their poster or presentation.  Time will be allotted during the class to share their work.  While some time may be available during the class for finishing touches on their work, only Scouts having completed most or all of the work ahead of time will have an opportunity to be considered for sign off on this requirement during the class.  In other words, don't expect to show up at the class and begin working on this AND completing it within the class time. Be Prepared.
- requirement: 7
  text: |-
      Do ONE of the following:
  children:
      - requirement: a
        text: |-
            Assist in the planning and organization of a crime prevention program in your community such as Neighborhood Watch, Community Watch, or Crime Stoppers. Explain how this program can benefit your neighborhood.
        workbook:
          - lines: 8
      - requirement: b
        text: |-
            With your parent’s and counselor’s approval, visit a jail or detention facility or a criminal court hearing. Discuss your experience with your counselor.
        workbook:
          - lines: 8
      - note:
        - inPerson
        - online
        text: |-
          Scouts will be working on requirement 7a as a part of this class, reviewing the Merit Badge pamphlet ahead of time will give Scouts all the resources necessary for participation in the classroom activity.
- requirement: 8
  text: |-
      Discuss the following with your counselor:
  children:
      - requirement: a
        text: |-
            How drug abuse awareness programs help prevent crime.
        workbook:
          - lines: 8
      - requirement: b
        text: |-
            Why alcohol, tobacco, and marijuana are sometimes called “gateway drugs” and how gateway drugs can lead to the use of other drugs.
        workbook:
          - lines: 8
      - requirement: c
        text: |-
            The potential consequences from the misuse of prescription drugs.
        workbook:
          - lines: 8
      - requirement: d
        text: |-
            How the illegal sale and use of drugs lead to other crimes.
        workbook:
          - lines: 8
      - requirement: e
        text: |-
            Three resources in your city where a person with a drug problem or drugrelated problem can go for help.
        workbook:
          - lines: 8
      - requirement: f
        text: |-
            How to recognize child abuse.
        workbook:
          - lines: 8
      - requirement: g
        text: |-
            The three R’s of Youth Protection.
        workbook:
          - lines: 8
      - note:
        - inPerson
        - online
        text: |-
          Scouts should review this requirement and its components and be prepared to discuss.  It is strongly recommended that Scouts bring any notes or supporting documents they may have to help show the counselor that they have prepared for discussion of these items.
- requirement: 9
  text: |-
      Discuss the following with your counselor:
  children:
      - requirement: a
        text: |-
            The role of a sheriff’s or police department in crime prevention.
        workbook:
          - lines: 8
      - requirement: b
        text: |-
            The purpose and operation of agencies in your community that help law enforcement personnel prevent crime, and how those agencies function during emergency situations.
        workbook:
          - lines: 8
      - requirement: c
        text: |-
            Explain the role private security plays in crime prevention.
        workbook:
          - lines: 8
      - requirement: d
        text: |-
            Choose a career in the crime prevention or security industry that interests you. Describe the level of education required and responsibilities of a person in that position. Tell why this position interests you.
        workbook:
          - lines: 8
      - note:
        - inPerson
        - online
        text: |-
          Scouts should review this requirement and its components and be prepared to discuss.  It is strongly recommended that Scouts bring any notes or supporting documents they may have to help show the counselor that they have prepared for discussion of these items.
