- requirement: 1
  text: |-
    Discuss the role and value of laws in society with regard to crime and crime prevention. Include in your discussion the definitions of “crime” and “crime prevention.”
- requirement: 2
  text: |-
    Prepare a journal from various sources that address crime and crime prevention efforts in your community.
- requirement: 3
  text: |-
    Discuss the following with your counselor:
  children:
    - requirement: a
      text: |-
        The role of citizens, including youth, in crime prevention.
    - requirement: b
      text: |-
        Gangs and their impact on the community.
    - requirement: c
      text: |-
        When and how to report a crime.
- requirement: 4
  text: |-
    After doing EACH of the following, discuss with your counselor what you have learned.
  children:
    - requirement: a
      text: |-
        Inspect your neighborhood for opportunities that may lead to crime.  Learn how to do a crime prevention survey.
    - requirement: b
      text: |-
        Using the checklist in this pamphlet, conduct a security survey of your home and discuss the results with your family.
- requirement: 5
  text: |-
    Teach your family or patrol members how to protect themselves from crime at home, at school, in your community, and while traveling.
- requirement: 6
  text: |-
    Help raise awareness about one school safety issue facing students by doing ONE of the following:
  children:
    - requirement: a
      text: |-
        Create a poster for display on a school bulletin board.
    - requirement: b
      text: |-
        With permission from school officials, create a pagelong public service announcement that could be read over the public address system at school or posted on the school’s website.
    - requirement: c
      text: |-
        Make a presentation to a group such as a Cub Scout den that addresses the issue.
- requirement: 7
  text: |-
    Do ONE of the following:
  children:
    - requirement: a
      text: |-
        Assist in the planning and organization of a crime prevention program in your community such as Neighborhood Watch, Community Watch, or Crime Stoppers. Explain how this program can benefit your neighborhood.
    - requirement: b
      text: |-
        With your parent’s and counselor’s approval, visit a jail or detention facility or a criminal court hearing. Discuss your experience with your counselor.
- requirement: 8
  text: |-
    Discuss the following with your counselor:
  children:
    - requirement: a
      text: |-
        How drug abuse awareness programs help prevent crime.
    - requirement: b
      text: |-
        Why alcohol, tobacco, and marijuana are sometimes called “gateway drugs” and how gateway drugs can lead to the use of other drugs.
    - requirement: c
      text: |-
        The potential consequences from the misuse of prescription drugs.
    - requirement: d
      text: |-
        How the illegal sale and use of drugs lead to other crimes.
    - requirement: e
      text: |-
        Three resources in your city where a person with a drug problem or drug-related problem can go for help.
    - requirement: f
      text: |-
        How to recognize child abuse.
    - requirement: g
      text: |-
        The three R’s of Youth Protection.
- requirement: 9
  text: |-
    Discuss the following with your counselor:
  children:
    - requirement: a
      text: |-
        The role of a sheriff’s or police department in crime prevention.
    - requirement: b
      text: |-
        The purpose and operation of agencies in your community that help law enforcement personnel prevent crime, and how those agencies function during emergency situations.
    - requirement: c
      text: |-
        Explain the role private security plays in crime prevention.
    - requirement: d
      text: |-
        Choose a career in the crime prevention or security industry that interests you. Describe the level of education required and responsibilities of a person in that position. Tell why this position interests you.
