# Requirement 10 is missing a dot after "10."
# 10b's note is missing a trailing period.
- requirement: 1
  text: |-
    Tell what archaeology is and explain to your counselor how it differs or
    relates to other fields of study such as anthropology, geology,
    paleontology, and history. Explain how archaeology is different than
    artifact collecting or treasure hunting.
- requirement: 2
  text: |-
    Describe the following steps of the archaeological process: site location,
    development of background research and a research design, site survey and
    fieldwork, artifact identification and examination, interpretation,
    preservation, and information sharing.
- requirement: 3
  text: |-
    Describe at least two ways in which archaeologists determine the age of
    sites, structures, or artifacts. Explain what absolute dating and relative
    dating are.
- requirement: 4
  text: |-
    Learn about a combined total of five archaeological sites located both
    within and outside the United States.
  children:
    - requirement: a
      text: |-
        For EACH site you research, point it out on a map and explain how it
        became known to archaeologists. Describe some of the information about
        the past that has been found at each site. Explain how the information
        gained from the study of these sites answers questions that
        archaeologists are asking and how the information may be important to
        modern people. Compare the relative ages of the sites you research.
    - requirement: b
      text: |-
        Choose ONE of the sites you picked and give a short presentation about
        your findings to a Cub Scout pack, your Scout troop, your school class,
        or another group.
- requirement: 5
  text: |-
    Do the following:
  children:
    - requirement: a
      text: |-
        Learn about the federal laws and international conventions that protect
        archaeological sites. Find out if your state, county, or local
        government has regulations that apply to archaeological or historic
        sites.
    - requirement: b
      text: |-
        Identify a national, international, or local organization that helps to
        protect archaeological sites.
- requirement: 6
  text: |-
    Do the following:
  children:
    - requirement: a
      text: |-
        Explain why it is important to protect archaeological sites.
    - requirement: b
      text: |-
        Explain what people should do if they think they have found an
        artifact.
    - requirement: c
      text: |-
        Describe the ways in which you can be a protector of the past.
- requirement: 7
  text: |-
    Do ONE of the following and discuss your findings with your counselor.
  children:
    - requirement: a
      text: |-
        Visit a museum to observe how artifacts aid in conveying history.
    - requirement: b
      text: |-
        Present to your counselor a significant family artifact/heirloom and
        discuss its history.
    - requirement: c
      text: |-
        Make a list of the trash your family throws out during one week.
        Discuss with your counselor what archaeologists might learn about you
        and your family if they found your trash a thousand years from now.
- requirement: 8
  text: |-
    Research a group of people who lived in your area more than 100 years ago.
    Find out about their ways of life, including housing, clothing, arts and
    crafts, tools, trade and markets, rituals and religions, and diets, and
    their relationships with other groups of people in the area. Describe what
    you would expect to find at an archaeological site where these people
    lived. Explain how these people influenced your current community.
- requirement: 9
  text: |-
    Identify three career opportunities in archaeology. Pick one and explain
    how to prepare for such a career. Discuss with your counselor what
    education and training are required, and explain why this profession might
    interest you.
- requirement: 10
  text: |-
    Do ONE of the following:
  children:
    - requirement: a
      markdown: true
      text: |-
        With your parent or guardian's and counselor's permission, assist a
        qualified archaeologist for at least eight hours with a project being
        worked on. Projects may include surveying, site monitoring, site
        stabilization, excavation, laboratory analysis, use of digital
        archaeological technology, or public outreach. Describe your
        involvement in the project, what you learned about archaeology, and the
        steps of archaeological inquiry.

        <em>Note: Visiting an archaeological site will require advance
        planning. An archaeological site during study can be a dangerous
        place. While there, you will need to closely follow the archaeologist's
        directions and comply with all the safety procedures. Be aware of the
        changing conditions at the site.</em>
    - requirement: b
      markdown: true
      text: |-
        With your counselor's approval, take part in a simulated archaeological
        project designed by a qualified archaeologist. The project must include
        the use of a simulated archaeological site including artifacts and
        features for the site. Using the steps of archaeological inquiry,
        analyze the "artifacts and features" and document the spatial
        relationships of the "artifacts and features" at the simulated site.

        Explain how the environment and time can affect the interpretation of
        an artifact and the overall archaeological site. Tell how you would
        share the results of your analysis with other researchers and the
        public.

        <em>Note: To find out how to make a simulated archaeological site, talk
        with a professional archaeologist, trained avocational archaeologist,
        museum school instructor, junior high or high school science teacher,
        advisor from a local archaeology society, or other qualified
        instructor.</em>
- requirement: 11
  text: |-
    Under the supervision of a qualified archaeologist or instructor, do ONE of
    the following:
  children:
    - requirement: a
      text: |-
        Help prepare an archaeological exhibit for display in a museum, visitor
        center, school, or other public area.
    - requirement: b
      text: |-
        Use the methods of experimental archaeology to re-create an item or to
        practice a skill from the past. Write a brief report explaining the
        experiment and its results.
