- requirement: 1
  text: |-
    Do the following:
  children:
    - requirement: a
      text: |-
        Explain to your counselor the most likely hazards you may encounter
        while participating in astronomy activities, and what you should do
        to anticipate, help prevent, mitigate, and respond to these
        hazards.
      children:
        - note:
            - inPerson
            - online
          text: |-
            It should go without saying that Scouts should review the
            merit badge pamphlet for this requirement as all the required
            knowledge and recommendations will be found within the
            contents of the Merit Badge Pamphlet for this requirement. It
            is strongly recommended that Scouts make notes of their
            findings by either marking their pamphlet or making notes on
            their Merit Badge Workbook for easy reference when explaining
            their findings to the counselor and/or class.
    - requirement: b
      text: |-
        Explain first aid for injuries or illnesses such as heat and cold
        reactions, dehydration, bites and stings, and damage to your eyes
        that could occur during observation.
      children:
        - note:
            - inPerson
            - online
          text: |-
            Most of the injuries and illnesses listed in this requirement
            are recurring throughout a Scout's journey through rank and
            merit badges. Newer Scouts may need to spend more time than
            more advanced Scouts on this requirement. Scouts who are
            first class and above should find this a review of common
            first aid ailments and responses. Regardless, do not take
            this requirement for granted as most counselors will still
            want to validate that you remember and understand the details
            of this requirement. Be sure to follow the Boy Scout Motto
            and "Be Prepared" to explain your knowledge for consideration
            of completion on this requirement.
    - requirement: c
      text: |-
        Describe the proper clothing and other precautions for safely
        making observations at night and in cold weather.
      children:
        - note:
            - inPerson
            - online
          text: |-
            There are two parts to this portion of requirement 1c. Both
            parts can be found by reviewing the Merit Badge Pamphlet. It
            is recommended that Scouts make notes of their findings and
            be prepared to share their results during the class. The
            first part of the requirement deals with the clothing and
            equipment necessary for cold weather and night time
            observations while the second part of the requirement
            specifically deals with the methods and equipments for safe
            observations of or around the Sun.
    - requirement: d
      text: |-
        Explain how to safely observe the Sun, objects near the Sun and
        solar eclipses.
- requirement: 2
  text: |-
    Explain what light pollution is and how it and air pollution affect
    astronomy.
  children:
    - note:
        - inPerson
        - online
      text: |-
        This requirement can easily be prepared for through the reviewal of
        the Merit Badge Pamphlet. All the necessary information and
        explanation can be found in the pamphlet for preparing for
        completion of this requirement. Finding the information however is
        only a part of the requirement. Scouts must actively be ready and
        successfully explain what is asked for in this requirement during
        the class in order to be considered for completion of this
        requirement.
- requirement: 3
  text: |-
    With the aid of diagrams (or real telescopes if available), do each of
    the following:
  children:
    - note:
        - inPerson
        - online
      markdown: true
      text: |-
        It is preferred that Scouts having their own binoculars and/or
        telescope (if practical) bring their equipment for use and
        demonstration during the class. Please note that it is the Scout's
        responsibility to manage and maintain their personal equipment and
        any damage or loss of these items is strictly the Scout's
        responsibility.

        NOTE: This requirement clearly states that the requirement
          components for requirement 3 need to be done with the aid of
          diagrams (or a real telescope). Scouts should have their diagrams
          ready for this requirement during the class. Be Prepared.
    - requirement: a
      text: |-
        Explain why binoculars and telescopes are important astronomical
        tools. Demonstrate or explain how these tools are used.
      children:
        - note:
            - inPerson
            - online
          text: |-
            Half of this requirement can easily be discovered and
            understood through the reviewal of the appropriate section of
            the Merit Badge Pamphlet. Scouts should be sure to have
            reviewed this section and be prepared the best way they can
            to explain their findings. If the Scout does not have a set
            of binoculars, there will be a pair for demonstration
            purposes available during the class to fulfill the second
            part of this requirement component.
    - requirement: b
      text: |-
        Describe the similarities and differences of several types of
        astronomical telescopes, including at least one that observes light
        beyond the visible part of the spectrum (i.e., radio, X-ray,
        ultraviolet, or infrared).
      children:
        - note:
            - inPerson
            - online
          text: |-
            Scouts will find all they need to know to complete this
            requirement by reviewing the Merit Badge Pamphlet. The
            Counselor for the class will assist in further understanding
            through sharing of knowledge to ensure the Scout has a
            complete understanding in order to complete this requirement.
            The Counselors known expertise for this requirement should
            NOT be a reason Scouts minimize the importance of researching
            this requirement. Scouts still need to show that they have a
            basic understanding through their preparation work in order
            to be considered for completion of this requirement.
    - requirement: c
      text: |-
        Explain the purposes of at least three instruments used with
        astronomical telescopes.
      children:
        - note:
            - inPerson
            - online
          text: |-
            While there are many more than three instruments used with
            telescopes, Scouts should be prepared to share their
            understanding of at least three as the requirement states.
            The Counselor will help facilitate and explanatory discussion
            with all Scout participants in the class to complete this
            requirement. Active participation in this discussion is
            required and only Scouts who have come prepared AND actively
            participate in the discussion will be able to complete this
            requirement.
    - requirement: d
      text: |-
        Describe the proper care and storage of telescopes and binoculars
        both at home and in the field.
      children:
        - note:
            - inPerson
            - online
          text: |-
            While the Counselor will cover important points for this
            requirement in the class, it is the Scout's responsibility to
            review the Merit Badge pamphlet ahead of time to have a basis
            in which they can share their understanding of this
            requirement. Only Scouts that actively participate in the
            discussion AND show they have reviewed the materials prior to
            the class will likely be able to complete this requirement.
- detail: true
  text: |-
    For requirement 4, if instruction is done in a planetarium, Scouts must
    still identify the required stars and constellations under the natural
    night sky.
- requirement: 4
  text: |-
    Do the following:
  children:
    - requirement: a
      text: |-
        Identify in the sky at least 10 constellations, at least four of
        which are in the zodiac.
    - requirement: b
      text: |-
        Identify in the sky at least eight conspicuous stars, five of which
        are of magnitude 1 or brighter.
    - requirement: c
      text: |-
        Make two sketches of the Big Dipper. In one sketch, show the Big
        Dipper’s orientation in the early evening sky. In another sketch,
        show its position several hours later. In both sketches, show the
        North Star and the horizon. Record the date and time each sketch
        was made.
    - requirement: d
      text: |-
        Explain what we see when we look at the Milky Way.
    - note:
        - inPerson
        - online
      markdown: true
      text: |-
        While Scouts will have an opportunity to share their work and research during the class discussion, however without preparation work, these requirement components will be impossible for Scouts to complete at or during the class.  Scouts should come to class with notes, drawings, sketches, and/or other documentation showing that they have completed their observations and identification of the required constellations and stars along with their sketches.

        NOTE: Stars and Constellations move about the sky depending on the time of year and time of night they are observed, so the tracking of date and time of the observation is crucial. Many online resources are available to aid in the identification of these stars and constellations. Drawing the constellation as it appears during your observation in the sky may be helpful as well. It must also be noted that just saying you have done these components of requirement 4 will NOT be enough to be signed off during the class. You must provide some sort of supporting documentation to the counselor to show that you have worked on and met the expectations of these components in Requirement 4.
- requirement: 5
  text: |-
    Do the following:
  children:
    - requirement: a
      text: |-
        List the names of the five most visible planets. Explain which ones
        can appear in phases similar to lunar phases and which ones cannot,
        and explain why.
      children:
        - note:
            - inPerson
            - online
          text: |-
            EXPLAIN
    - requirement: b
      text: |-
        Using the internet (with your parent’s permission) and other
        resources, find out when each of the five most visible planets that
        you identified in requirement 5a will be observable in the evening
        sky during the next 12 months. Then compile this information in the
        form of a chart or table.
      children:
        - note:
            - inPerson
            - online
          text: |-
            EXPLAIN
    - requirement: c
      text: |-
        Describe the motion of the planets across the sky.
      children:
        - note:
            - inPerson
            - online
          text: |-
            EXPLAIN
    - requirement: d
      text: |-
        Observe a planet and describe what you saw.
      children:
        - note:
            - inPerson
            - online
          text: |-
            EXPLAIN
- requirement: 6
  text: |-
    Do the following:
  children:
    - requirement: a
      text: |-
        Sketch the face of the Moon and indicate at least five seas and
        five craters. Label these landmarks.
      children:
        - note:
            - inPerson
            - online
          text: |-
            EXPLAIN
    - requirement: b
      text: |-
        Sketch the phase and position of the Moon, at the same hour and
        place, for four nights within a one week period. Include landmarks
        on the horizon such as hills, trees, and buildings. Explain the
        changes you observe.
      children:
        - note:
            - inPerson
            - online
          text: |-
            EXPLAIN
    - requirement: c
      text: |-
        List the factors that keep the Moon in orbit around Earth.
      children:
        - note:
            - inPerson
            - online
          text: |-
            EXPLAIN
    - requirement: d
      text: |-
        With the aid of diagrams, explain the relative positions of the
        Sun, Earth, and the Moon at the times of lunar and solar eclipses,
        and at the times of new, first-quarter, full, and last-quarter
        phases of the Moon.
      children:
        - note:
            - inPerson
            - online
          text: |-
            EXPLAIN
- requirement: 7
  text: |-
    Do the following:
  children:
    - requirement: a
      text: |-
        Describe the composition of the Sun, its relationship to other
        stars, and some effects of its radiation on Earth’s weather and
        communications.
      children:
        - note:
            - inPerson
            - online
          text: |-
            EXPLAIN
    - requirement: b
      text: |-
        Define sunspots and describe some of the effects they may have on
        solar radiation.
      children:
        - note:
            - inPerson
            - online
          text: |-
            EXPLAIN
    - requirement: c
      text: |-
        Identify at least one red star, one blue star, and one yellow star
        (other than the Sun). Explain the meaning of these colors.
      children:
        - note:
            - inPerson
            - online
          text: |-
            EXPLAIN
- requirement: 8
  text: |-
    With your counselor’s approval and guidance, do ONE of the following:
  children:
    - requirement: a
      text: |-
        Visit a planetarium or astronomical observatory.  Submit a written
        report, a scrapbook, or a video presentation afterward to your
        counselor that includes the following information:
      children:
        - requirement: 1
          text: |-
            Activities occurring there
        - requirement: 2
          text: |-
            Exhibits and displays you saw
        - requirement: 3
          text: |-
            Telescopes and other instruments being used
        - requirement: 4
          text: |-
            Celestial objects you observed
    - requirement: b
      markdown: true
      text: |-
        Plan and participate in a three-hour observation session that
        includes using binoculars or a telescope. List the celestial
        objects you want to observe, and find each on a star chart or in a
        guidebook. Prepare a log or notebook. Discuss with your counselor
        what you hope to observe prior to your observation session.  Review
        your log or notebook with your counselor afterward.`*`

        `*` To complete requirement 8b, you may use the Scout Planning
        Worksheet:
        troopleader.org/wp-content/uploads/2016/03/512-505_16_Wksht_WEB.pdf
    - requirement: c
      text: |-
        Plan and host a star party for your Scout troop or other group such
        as your class at school. Use binoculars or a telescope to show and
        explain celestial objects to the group.
    - requirement: d
      text: |-
        Help an astronomy club in your community hold a star party that is
        open to the public.
    - requirement: e
      text: |-
        Personally take a series of photographs or digital images of the
        movement of the Moon, a planet, an asteroid, meteor, or a comet. In
        your visual display, label each image and include the date and time
        it was taken. Show all positions on a star chart or map. Show your
        display at school or at a troop meeting. Explain the changes you
        observed.
      children:
        - note:
            - inPerson
            - online
          text: |-
            EXPLAIN
- requirement: 9
  text: |-
    Find out about three career opportunities in astronomy. Pick one and find
    out the education, training, and experience required for this profession.
    Discuss this with your counselor, and explain why this profession might
    interest you.
  children:
    - note:
        - inPerson
        - online
      text: |-
        EXPLAIN
