- requirement: 1
  text: |-
      Do the following:
  children:
      - requirement: a
        text: |-
            Explain to your counselor the most likely hazards you may encounter while hiking, and what you should do to anticipate, help prevent, mitigate, and respond to these hazards.
        workbook:
          - lines: 8
            text: |-
              Most likely hazards
          - lines: 8
            text: |-
              Anticipate hazards
          - lines: 8
            text: |-
              Prevent hazards
          - lines: 8
            text: |-
              Mitigate hazards
          - lines: 8
            text: |-
              Respond to hazards
      - requirement: b
        text: |-
          Show that you know first aid for injuries or illnesses that could occur while hiking, including hypothermia, frostbite, dehydration, heat exhaustion, heatstroke, sunburn, hyperventilation, altitude sickness, sprained ankle, blisters, insect stings, tick bites, and snakebite.
        workbook:
          - split:
            - task: true
              text: |-
                Hypothermia
            - task: true
              text: |-
                Frostbite
            - task: true
              text: |-
                Dehydration
          - split:
            - task: true
              text: |-
                Heat exhaustion
            - task: true
              text: |-
                Heatstroke
            - task: true
              text: |-
                Sunburn
          - split:
            - task: true
              text: |-
                Hyperventilation
            - task: true
              text: |-
                Altitude sickness
            - task: true
              text: |-
                Sprained ankle
          - split:
            - task: true
              text: |-
                Blisters
            - task: true
              text: |-
                Insect stings
            - task: true
              text: |-
                Tick bites
          - split:
            - task: true
              text: |-
                Snakebite
- requirement: 2
  text: |-
    Explain and, where possible, show the points of good hiking practices including proper outdoor ethics, hiking safety in the daytime and at night, courtesy to others, choice of footwear, and proper care of feet and footwear.
  workbook:
    - lines: 8
- requirement: 3
  text: |-
    Explain how hiking is an aerobic activity. Develop a plan for conditioning yourself for 10-mile hikes, and describe how you will increase your fitness for longer hikes.
  workbook:
    - lines: 8
      text: |-
        Explain how hiking is an aerobic activity
    - lines: 8
      text: |-
        A plan for conditioning yourself for 10-mile hikes
    - lines: 8
      text: |-
        Describe how you will increase your fitness for longer hokes
- requirement: 4
  markdown: true
  text: |-
    Take the five following hikes, each on a different day, and each of continuous miles. These hikes MUST be taken in the following order:

    One 5-mile hike<br/>
    Three 10-mile hikes
    One 15-mile hike

    You may stop for as many short rest periods as needed, as well as one meal, during each hike, but ***not*** for an extended period (example: overnight). Prepare a written hike plan before each hike and share it with your Scoutmaster or a designee. Include map routes, a clothing and equipment list, and a list of items for a trail lunch.`*`
  workbook:
    - split:
      - task: true
        text: |-
          One 5-mile hike
      - task: true
        text: |-
          First 10-mile hike
    - split:
      - task: true
        text: |-
          Second 10-mile hike
      - task: true
        text: |-
          Third 10-mile hike
    - split:
      - task: true
        text: |-
          One 15-mile hike
- requirement: 5
  markdown: true
  text: |-
    Take a hike of 20 continuous miles in one day following a hike plan you have prepared. You may stop for as many short rest periods as needed, as well as one meal, but not for an extended period (example: overnight).`*`
  workbook:
    - task: true
- requirement: 6
  text: |-
    After each of the hikes (or during each hike if on one continuous “trek”) in requirements 4 and 5, write a short reflection of your experience. Give dates and descriptions of routes covered, the weather, and any interesting things you saw. It may include something you learned about yourself, about the outdoors, or about others you were hiking with. Share this with your merit badge counselor.
  workbook:
    - lines: 8
      text: |-
        One 5-mile hike
    - lines: 8
      text: |-
        First 10-mile hike
    - lines: 8
      text: |-
        Second 10-mile hike
    - lines: 8
      text: |-
        Third 10-mile hike
    - lines: 8
      text: |-
        One 15-mile hike
    - lines: 8
      text: |-
        One 20-mile hike
- detail: true
  markdown: true
  text: |-
      `*` The required hikes for this badge may be used in fulfilling hiking requirements for rank advancement.  However, these hikes cannot be used to fulfill requirements of other merit badges.
