- requirement: 1
  text: |-
      Discuss with your counselor the importance of signs, signals, and codes,
      and why people need these different methods of communication. Briefly
      discuss the history and development of signs, signals, and codes.
  workbook:
    - lines: 8
  children:
      - note:
            - inPerson
            - online
        text: |-
            Scouts should utilize the Signs, Signals, and Codes Merit Badge
            pamphlet and other sources to compile an understanding and response
            for sharing during the class. Scouts should also be prepared to
            discuss the history of signs, signals, and codes. Only Scouts
            having prepared for this requirement will have an opportunity to be
            signed off on this requirement. While Scouts may learn in the
            class, they must bring some knowledge or proof of preparation for
            this requirement and actively participate in the class discussion
            in order to be considered for sign off.
- requirement: 2
  text: |-
      Explain the importance of signaling in emergency communications. Discuss
      with your counselor the types of emergency or distress signals one might
      use to attract airborne search-and-rescue personnel if lost in the
      outdoors or trying to summon assistance during a disaster. Illustrate
      these signaling examples by the use of photos or drawings.
  workbook:
    - lines: 8
    - area: 8
  children:
      - note:
            - inPerson
            - online
        text: |-
            Scouts will have some time during the class to complete parts of
            this requirement. Because this merit badge has a lot of items to
            complete, Scouts will find it beneficial to have their drawings or
            photos ready prior to the class. There will be time allotted to
            review any drawings or photos Scouts bring for this requirement,
            however it cannot be guaranteed that the class will have enough
            time to complete the drawings during the class time allotted.
            Scouts should consider this potential and decide how they want to
            approach potential completion of this requirement. It is strongly
            recommended to consider doing this ahead of the class.
- requirement: 3
  text: |-
      Do the following:
  children:
      - requirement: a
        text: |-
            Describe what Morse code is and the various means by which it can
            be sent. Spell your first name using Morse code. Send or receive a
            message of six to 10 words using Morse code.
        workbook:
          - lines: 8
          - area: 8
            text: |-
              Your name in Morse code
      - requirement: b
        text: |-
            Describe what American Sign Language (ASL) is and how it is used
            today. Spell your first name using American Sign Language. Send or
            receive a message of six to 10 words using ASL.
        workbook:
          - lines: 8
          - area: 8
      - note:
            - inPerson
            - online
        text: |-
            Scouts will want to review the Signs, Signals, and Codes Merit
            Badge pamphlet prior to the class and make sure they have a basic
            understanding of Morse Code and American Sign Language. The class
            will allot time for each Scout to demonstrate their knowledge and
            complete the rest of each of these components for requirement 3.
- requirement: 4
  text: |-
      Give your counselor a brief explanation about semaphore, why it is used,
      how it is used, and where it is used. Explain the difference between
      semaphore flags and nautical flags. Then do the following:
  children:
      - note:
            - inPerson
            - online
        text: |-
            Scouts should review the Signs, Signals, and Codes Merit Badge
            pamphlet and have a solid understanding of semaphore and nautical
            flags, their differences, and the basics for using them.
      - requirement: a
        text: |-
            Spell your first name using semaphore. Send or receive a message of
            six to 10 words using semaphore.
        workbook:
          - area: 8
        children:
            - note:
                  - inPerson
                  - online
              text: |-
                  Scouts will be given the opportunity to complete this
                  requirement component during the class.
      - requirement: b
        text: |-
            Using illustrations or photographs, identify 10 examples of
            nautical flags and discuss their importance.
        workbook:
          - split:
            - area: 8
            - area: 8
          - split:
            - area: 8
            - area: 8
          - split:
            - area: 8
            - area: 8
          - split:
            - area: 8
            - area: 8
          - split:
            - area: 8
            - area: 8
        children:
            - note:
                  - inPerson
                  - online
              text: |-
                  Scouts should prepare for the class by putting together the
                  10 examples asked for in this requirement component ahead of
                  time. The counselor will allow all Scouts to share their work
                  during the class for consideration and sign off. Only Scouts
                  coming to the class with this requirement component ready
                  will have the opportunity to get signed off.
- requirement: 5
  text: |-
      Explain the braille reading technique and how it helps individuals with
      sight impairment to communicate. Then do the following:
  workbook:
    - lines: 8
  children:
      - note:
            - inPerson
            - online
        text: |-
            Scouts MUST utilize the Braille supplement in the Signs, Signals,
            and Codes Merit Badge pamphlet to familiarize themselves with
            Braille prior to the class. Scout attending the class that have not
            done this review work will find it difficult, if not impossible, to
            complete this requirement during the class.
      - requirement: a
        text: |-
            Either by sight or by touch, identify the letters of the braille
            alphabet that spell your name. By sight or touch, decode a braille
            message at least six words long.
        workbook:
          - area: 8
      - requirement: b
        markdown: true
        text: |-
            Create a message in braille at least six words long, and share this
            with your counselor.

            To satisfy the braille writing requirement 5b for this merit badge,
            you do not need to emboss braille dots in thick paper. Rather, you
            may use a pencil or pen to draw the dots on ordinary paper, copying
            the characters of the braille alphabet to spell out your message
            letter by letter.
        workbook:
          - area: 8
        children:
            - note:
                  - inPerson
                  - online
              text: |-
                  Scouts will have time during the class to complete these two
                  components of the class, providing they can satisfactorily
                  show that they have done preparation work prior to class in
                  familiarizing themselves with the Braille system.
- requirement: 6
  text: |-
      Do the following:
  children:
      - requirement: a
        text: |-
            Describe to your counselor six sound-only signals that are in use
            today. Discuss the pros and cons of using sound signals versus
            other types of signals.
        workbook:
          - lines: 8
        children:
            - note:
                  - inPerson
                  - online
              text: |-
                  Scouts should make notes prior to the class to utilize during
                  the discussion in the class to helpful fulfill and completed
                  this component of the requirement.
      - requirement: b
        text: |-
            Demonstrate to your counselor six different silent Scout signals.
            Use these Scout signals to direct the movements and actions of your
            patrol or troop.
        workbook:
          - lines: 8
        children:
            - note:
                  - inPerson
                  - online
              text: |-
                  Scouts should review the respective section in the Signs,
                  Signals, and Codes Merit Badge pamphlet on Scout and Silent
                  Signals. Scouts will be placed into small groups or patrols
                  to demonstrate their understanding of these signals. Only
                  Scouts showing proficiency in giving and receiving these
                  signals, and properly executing them, will be considered for
                  sign off on this requirement component.
- requirement: 7
  text: |-
      On a Scout outing, lay out a trail for your patrol or troop to follow.
      Cover at least one mile in distance and use at least six different trail
      signs and markers. After the Scouts have completed the trail, follow
      no-trace principles by replacing or returning trail markers to their
      original locations.
  workbook:
    - area: 8
  children:
      - note:
            - inPerson
        text: |-
            This requirement will take place outdoors and likely will take a
            significant portion of the class.  Scouts will lay a course and
            follow one of the other groups' courses to complete this
            requirement. It is strongly recommended that Scouts familiarize
            themselves with the different types of trail markings and methods
            in order to successfully complete this requirement.
- requirement: 8
  text: |-
      For THREE of the following activities, demonstrate five signals each.
      Tell what the signals mean and why they are used:
  children:
      - requirement: a
        text: |-
            Sports official’s hand signs/signals
        workbook:
          - lines: 8
      - requirement: b
        text: |-
            Heavy-equipment operator’s hand signals
        workbook:
          - lines: 8
      - requirement: c
        text: |-
            Aircraft carrier catapult crew signals
        workbook:
          - lines: 8
      - requirement: d
        text: |-
            Cyclist’s hand signals
        workbook:
          - lines: 8
      - requirement: e
        text: |-
            An activity selected by you and your counselor
        workbook:
          - lines: 8
      - note:
            - inPerson
            - online
        text: |-
            This requirement will be completed during the class. Scouts should
            be familiar with the hand signals for components a thru d to ensure
            successful completion of this requirement during the class. This
            familiarization can easily be accomplished by reviewing the Signs,
            Signals, and Codes Merit Badge pamphlet. For those not coming with
            a Signs, Signals, and Codes Merit Badge pamphlet and/or not
            reviewing this requirement prior to the class, will find it
            extremely difficult to complete this requirement during the class.
- requirement: 9
  text: |-
      Share with your counselor 10 examples of symbols used in everyday life.
      Design your own symbol. Share it with your counselor and explain what it
      means. Then do the following:
  workbook:
    - lines: 8
    - area: 8
      text: |-
        Design your own symbol
  children:
      - note:
            - inPerson
            - online
        text: |-
            Scouts should come to the class with their symbol designed and
            ready to share it along with an explanation.
      - requirement: a
        text: |-
            Show examples of 10 traffic signs and explain their meaning.
        workbook:
          - area: 8
        children:
            - note:
                  - inPerson
                  - online
              text: |-
                  Scouts should have a general knowledge of this prior to the
                  class and be prepared to share their knowledge during class
                  discussion.
      - requirement: b
        text: |-
            Using a topographical map, explain what a map legend is and discuss
            its importance. Point out 10 map symbols and explain the meaning of
            each.
        workbook:
          - area: 8
        children:
            - note:
                  - inPerson
                  - online
              text: |-
                  Scouts should try and do this requirement prior to the class
                  and bring their work and resources with to share in the
                  class.
      - requirement: c
        text: |-
            Discuss text-message symbols and why they are commonly used. Give
            examples of your favorite 10 text symbols or emoticons. Then see if
            your counselor or parent can identify the meaning or usage of each
            symbol.
        workbook:
          - area: 8
        children:
            - note:
                  - inPerson
                  - online
              text: |-
                  Scouts should think about this requirement and come with an
                  idea for, or a rendering of, their 10 emoticons to share with
                  the counselor and class.
- requirement: 10
  text: |-
      Briefly discuss the history of secret code writing (cryptography). Make
      up your own secret code and write a message of up to 25 words using this
      code. Share the message with a friend or fellow Scout. Then share the
      message and code key with your counselor and discuss the effectiveness of
      your code.
  workbook:
    - lines: 8
      text: |-
        History of secret code writing
    - lines: 8
      text: |-
        Your own code
    - lines: 8
      text: |-
        Message in your code
  children:
      - note:
            - inPerson
            - online
        text: |-
            Scout may want to have their own secret code started prior to the
            class. While time will be allotted for this activity, it may not be
            enough time for those who have not started this requirement ahead
            of time.
