- requirement: 1
  text: |-
    Do the following:
  children:
    - requirement: a
      text: |-
        Explain to your counselor the most likely hazards you may encounter
        while participating in fishing activities, and what you should do
        to anticipate, help prevent, mitigate, and respond to these
        hazards.
    - requirement: b
      text: |-
        Discuss the prevention of and treatment for the following health
        concerns that could occur while fishing, including cuts and
        scratches, puncture wounds, insect bites, hypothermia, dehydration,
        heat exhaustion, heatstroke, and sunburn.
    - requirement: c
      text: |-
        Explain how to remove a hook that has lodged in your arm.
    - requirement: d
      text: |-
        Name and explain five safety practices you should always follow
        while fishing.
- requirement: 2
  text: |-
    Discuss the differences between two types of fishing outfits.  Point out
    and identify the parts of several types of rods and reels. Explain how
    and when each would be used. Review with your counselor how to care for
    this equipment.
- requirement: 3
  text: |-
    Demonstrate the proper use of two different types of fishing equipment.
- requirement: 4
  text: |-
    Demonstrate how to tie the following knots: improved clinch knot, Palomar
    knot, uni knot, uni to uni knot, and arbor knot. Explain how and when
    each knot is used.
- requirement: 5
  text: |-
    Name and identify five basic artificial lures and five natural baits and
    explain how to fish with them. Explain why baitfish are not to be
    released.
- requirement: 6
  text: |-
    Do the following:
  children:
    - requirement: a
      text: |-
        Explain the importance of practicing Leave No Trace techniques.
        Discuss the positive effects of Leave No Trace on fishing
        resources.
    - requirement: b
      text: |-
        Discuss the meaning and importance of catch and release.  Describe
        how to properly release a fish safely to the water.
- requirement: 7
  text: |-
    Obtain and review the regulations affecting game fishing where you live.
    Explain why they were adopted and what is accomplished by following them.
- requirement: 8
  text: |-
    Explain what good outdoor sportsmanlike behavior is and how it relates to
    anglers. Tell how the Outdoor Code of the Boy Scouts of America relates
    to a fishing sports enthusiast, including the aspects of littering,
    trespassing, courteous behavior, and obeying fishing regulations.
- requirement: 9
  text: |-
    Catch at least one fish and identify it.
- requirement: 10
  text: |-
    If regulations and health concerns permit, clean and cook a fish you have
    caught. If you are unable to catch a fish for eating, acquire a fish,
    clean the fish you acquired, and cook the fish you acquired. (It is not
    required that you eat the fish.)
