- requirement: 1
  text: |-
      Do the following:
  children:
      - requirement: a
        text: |-
            Repeat from memory the Scout Oath, Scout Law, Scout motto, and
            Scout slogan. In your own words, explain their meaning.
      - requirement: b
        text: |-
            Explain what Scout spirit is. Describe some ways you have shown
            Scout spirit by practicing the Scout Oath, Scout Law, Scout motto,
            and Scout slogan.
      - requirement: c
        text: |-
            Demonstrate the Scout sign, salute, and handshake. Explain when
            they should be used.
      - requirement: d
        markdown: true
        text: |-
            Describe the <a href="../first-class/">First Class</a> Scout badge
            and tell what each part stands for. Explain the significance of
            the First Class Scout badge.
      - requirement: e
        text: |-
            Repeat from memory the Outdoor Code. List the
            Leave No Trace Seven Principles. Explain the difference between the two.
      - requirement: f
        text: |-
            Repeat from memory the Pledge of Allegiance. In your own words,
            explain its meaning.
- requirement: 2
  text: |-
      After attending at least one Scout troop meeting, do the following:
  children:
      - requirement: a
        text: |-
            Describe how the Scouts in the troop provide its leadership.
      - requirement: b
        text: |-
            Describe the four steps of Scout advancement.
      - requirement: c
        text: |-
            Describe what the <a href="../">Scouts BSA ranks</a> are and how
            they are earned.
      - requirement: d
        text: |-
            Describe what <a href="../../merit-badges/">merit badges</a> are
            and how they are earned.
- requirement: 3
  text: |-
      Do the following:
  children:
      - requirement: a
        text: |-
            Explain the patrol method. Describe the types of patrols that are
            used in your troop.
      - requirement: b
        text: |-
            Become familiar with your patrol name, emblem, flag, and yell.
            Explain how these items create patrol spirit.
- requirement: 4
  text: |-
      Do the following:
  children:
      - requirement: a
        text: |-
            Show how to tie a square knot, two half-hitches, and a taut-line
            hitch. Explain how each knot is used.
      - requirement: b
        text: |-
            Show the proper care of a rope by learning how to whip and fuse the
            ends of different kinds of rope.
- requirement: 5
  text: |-
      Tell what you need to know about pocketknife safety and responsibility.
- requirement: 6
  markdown: true
  text: |-
      With your parent or guardian, complete the exercises in the pamphlet How
      to Protect Your Children From Child Abuse: A Parent’s Guide view the Personal
      Safety Awareness videos (with your parent or guardian’s permission).`*`

      `*` If your family does not have internet access at home AND you do not
      have ready internet access at school or another public place or via a
      mobile device, the Personal Safety Awareness videos portion of this
      requirement may be waived by your Scoutmaster in consultation with your
      parent or guardian.
- requirement: 7
  text: |-
      Since joining the troop and while working on the Scout rank, participate
      in a Scoutmaster conference.
