- requirement: 1
  text: |-
      Since earning the Eagle Scout rank or your last Eagle Palm, demonstrate
      Scout spirit by living the Scout Oath and Scout Law. Tell how you have
      done your duty to God and how you have lived the Scout Oath and Scout Law
      in your everyday life.
- requirement: 2
  text: |-
      Continue to set a satisfactory example of accepting responsibility or
      demonstrating leadership ability.
- requirement: 3
  markdown: true
  text: |-
      Earn five additional merit badges beyond those required for Eagle or last
      Palm.`*`

      `*` Merit badges earned any time since joining Scouts BSA may be used to
      meet this requirement.
