- requirement: 1
  markdown: true
  text: |-
      Be active in the Boy Scouts of America for at least three months after
      becoming an Eagle Scout or after the last Palm was earned.`*`

      `*` Eagle Palms must be earned in sequence, and the three-month tenure
      requirement must be observed for each Palm.
- requirement: 2
  text: |-
      Since earning the Eagle Scout rank or your last Eagle Palm, demonstrate
      Scout spirit by living the Scout Oath and Scout Law. Tell how you have
      done your duty to God and how you have lived the Scout Oath and Scout Law
      in your everyday life.
- requirement: 3
  text: |-
      Continue to set a satisfactory example of accepting responsibility or
      demonstrating leadership ability.
- requirement: 4
  markdown: true
  text: |-
      Earn five additional merit badges beyond those required for Eagle or last
      Palm.`*`

      `*` Merit badges earned any time since joining Scouts BSA may be used to
      meet this requirement.
- requirement: 5
  text: |-
      While an Eagle Scout, participate in a Scoutmaster conference.
