- requirement: 1
  text: |-
      Show that you know first aid for the types of injuries that could occur
      while orienteering, including cuts, scratches, blisters, snakebite,
      insect stings, tick bites, heat and cold reactions (sunburn, heatstroke,
      heat exhaustion, hypothermia), and dehydration. Explain to your counselor
      why you should be able to identify poisonous plants and poisonous animals
      that are found in your area.
  workbook:
      - lines: 8
        text: |-
            Cuts, scratches
      - lines: 8
        text: |-
            Blisters
      - lines: 8
        text: |-
            Snakebite
      - lines: 8
        text: |-
            Insect stings
      - lines: 8
        text: |-
            Tick bites
      - lines: 8
        text: |-
            Sunburn
      - lines: 8
        text: |-
            Heatstroke
      - lines: 8
        text: |-
            Heat exhaustion
      - lines: 8
        text: |-
            Hypothermia
      - lines: 8
        text: |-
            Dehydration
      - lines: 8
        text: |-
            Why should you be able to identify poisonous plants and poisonous
            animals in your area
- requirement: 2
  text: |-
      Explain what orienteering is.
  workbook:
      - lines: 8
- requirement: 3
  text: |-
      Do the following:
  children:
      - requirement: a
        text: |-
            Explain how a compass works. Describe the features of an
            orienteering compass.
        workbook:
            - lines: 8
      - requirement: b
        text: |-
            In the field, show how to take a compass bearing and follow it.
        workbook:
            - task: true
- requirement: 4
  text: |-
      Do the following:
  children:
      - requirement: a
        text: |-
            Explain how a topographic map shows terrain features.  Point out
            and name five terrain features on a map and in the field.
        workbook:
            - lines: 8
            - task: true
              text: |-
                  Pointed out and named five terrain features
      - requirement: b
        text: |-
            Point out and name 10 symbols on a topographic map.
        workbook:
            - task: true
      - requirement: c
        markdown: true
        text: |-
            Explain the meaning of *declination*. Tell why you must consider
            declination when using map and compass together.
        workbook:
            - lines: 8
      - requirement: d
        text: |-
            Show a topographic map with magnetic north-south lines.
        workbook:
            - task: true
      - requirement: e
        text: |-
            Show how to measure distances on a map using an orienteering
            compass.
        workbook:
            - task: true
      - requirement: f
        text: |-
            Show how to orient a map using a compass.
        workbook:
            - task: true
- requirement: 5
  text: |-
      Set up a 100-meter pace course. Determine your walking and running pace
      for 100 meters. Tell why it is important to pace-count.
  workbook:
      - task: true
- requirement: 6
  text: |-
      Do the following:
  children:
      - requirement: a
        text: |-
            Identify 20 international control description symbols.  Tell the
            meaning of each symbol.
        workbook:
            - area: 30
      - requirement: b
        text: |-
            Show a control description sheet and explain the information
            provided.
        workbook:
            - task: true
      - requirement: c
        text: |-
            Explain the following terms and tell when you would use them:
            attack point, collecting feature, catching feature, aiming off,
            contouring, reading ahead, handrail, relocation, rough versus
            fine orienteering.
        workbook:
            - lines: 8
              text: |-
                  Attack point
            - lines: 8
              text: |-
                  Collecting feature
            - lines: 8
              text: |-
                  Catching feature
            - lines: 8
              text: |-
                  Aiming off
            - lines: 8
              text: |-
                  Contouring
            - lines: 8
              text: |-
                  Reading ahead
            - lines: 8
              text: |-
                  Handrail
            - lines: 8
              text: |-
                  Relocation
            - lines: 8
              text: |-
                  Rough versus fine orienteering
- requirement: 7
  text: |-
      Do the following:
  children:
      - requirement: a
        text: |-
            Take part in three orienteering events. One of these must be a
            cross-country course.
        workbook:
            - task: true
              text: |-
                  Cross-country course
            - task: true
              text: |-
                  Another orienteering course
            - task: true
              text: |-
                  Another orienteering course
      - requirement: b
        text: |-
            After each event, write a report with (1) a copy of the master map
            and control description sheet, (2) a copy of the route you took on
            the course, (3) a discussion of how you could improve your time
            between control points, and (4) a list of your major weaknesses on
            this course. Describe what you could do to improve.
        workbook:
            - lines: 8
            - lines: 8
            - lines: 8
- requirement: 8
  text: |-
      Do ONE of the following:
  children:
      - requirement: a
        text: |-
            Set up a cross-country course that is at least 2,000 meters long
            with at least five control markers. Prepare the master map and
            control description sheet.
        workbook:
            - task: true
      - requirement: b
        text: |-
            Set up a score orienteering course with at least 12 control points
            and a time limit of at least 60 minutes. Set point values for each
            control. Prepare the master map and control description sheet.
        workbook:
            - task: true
- requirement: 9
  text: |-
      Act as an official during an orienteering event. This may be during the
      running of the course you set up for requirement 8.
  workbook:
      - task: true
- requirement: 10
  text: |-
      Teach orienteering techniques to your patrol, troop, or crew.
  workbook:
      - task: true
