- requirement: 1
  text: |-
    Discuss with your counselor the life and times of Lord Baden-Powell of
    Gilwell. Explain why he felt a program like Scouting would be good for the
    young men of his day. Include in your discussion how Scouting was
    introduced in the United States, and the origins of Boy Scouting and Cub
    Scouting under Baden-Powell.
- requirement: 2
  text: |-
    Do the following:
  children:
    - requirement: a
      text: |-
        Give a short biographical summary of any TWO of the following, and tell
        of their roles in how Scouting developed and grew in the United States.
      children:
        - requirement: 1
          text: |-
            Daniel Carter Beard
        - requirement: 2
          text: |-
            William D. Boyce
        - requirement: 3
          text: |-
            Waite Phillips
        - requirement: 4
          text: |-
            Ernest Thompson Seton
        - requirement: 5
          text: |-
            James E. West
        - requirement: 6
          text: |-
            “Green Bar Bill” Hillcourt
    - requirement: b
      text: |-
        Discuss the significance to Scouting of any TWO of the following:
      children:
        - requirement: 1
          text: |-
            Brownsea Island
        - requirement: 2
          text: |-
            The First World Scout Jamboree
        - requirement: 3
          markdown: true
          text: |-
            <em>Boy Scout Handbook</em>
        - requirement: 4
          markdown: true
          text: |-
            <em>Scout Life</em> magazine (formerly Boys' Life).
- requirement: 3
  text: |-
    Discuss with your counselor how Scouting's programs have developed over
    time and been adapted to fit different age groups and interests (Cub
    Scouting, Boy Scouting, Exploring, Venturing).
- requirement: 4
  text: |-
    Do ONE of the following:
  children:
    - requirement: a
      text: |-
        Attend either a Scouting America National Jamboree, OR World Scout
        Jamboree, OR a national Scouting America high-adventure base. While
        there, keep a journal documenting your day-to-day experiences. Upon
        your return, report to your counselor what you did, saw, and learned.
        You may include photos, brochures, and other documents in your report.
    - requirement: b
      text: |-
        Write or visit the National Scouting Museum. Obtain information about
        this facility. Give a short report on what you think the role of this
        museum is in the Scouting program.
    - requirement: c
      text: |-
        Visit an exhibit of Scouting memorabilia or a local museum with a
        Scouting history gallery, or (with your parent or guardian's permission
        and counselor's approval) visit with someone in your council who is
        recognized as a dedicated Scouting historian or memorabilia collector.
        Learn what you can about the history of Boy Scouting. Give a short
        report to your counselor on what you saw and learned.
- requirement: 5
  text: |-
    Learn about the history of your unit or Scouting in your area. Interview at
    least two people (one from the past and one from the present) associated
    with your troop. These individuals could be adult unit leaders, Scouts,
    troop committee members, or representatives of your troop's chartered
    organization. Find out when your unit was originally chartered. Create a
    report of your findings on the history of your troop, and present it to
    your patrol or troop or at a court of honor, and then add it to the troop's
    library. This presentation could be in the form of an oral/written report,
    an exhibit, a scrapbook, or a computer presentation such as a slide show.
- requirement: 6
  text: |-
    Make a collection of some of your personal patches and other Scouting
    memorabilia. With their permission, you may include items borrowed from
    family members or friends who have been in Scouting in the past, or you may
    include photographs of these items. Show this collection to your counselor,
    and share what you have learned about items in the collection. (There is no
    requirement regarding how large or small this collection must be.)
- requirement: 7
  text: |-
    Reproduce the equipment for an old-time Scouting game such as those played
    at Brownsea Island. You may find one on your own (with your counselor's
    approval), or pick one from the <em>Scouting Heritage</em> merit badge
    pamphlet. Teach and play the game with other Scouts.
- requirement: 8
  text: |-
    Interview at least three people (different from those you interviewed for
    requirement 5) over the age of 40 who were Scouts. Find out about their
    Scouting experiences.  Ask about the impact that Scouting has had on their
    lives. Share what you learned with your counselor.
