# Note: 7d says "Aqua bike" in pamphlet
# Note: pamphlets don't have periods after lists, like 3d and 7d.
- requirement: 1
  text: |-
    Do the following:
  children:
    - requirement: a
      text: |-
        Explain to your counselor the most likely hazards you may encounter
        during multisport activities and what you should do to anticipate,
        prevent, mitigate, and respond to these hazards.
    - requirement: b
      text: |-
        Show that you know first aid for injuries or illnesses that could occur
        while participating in multisport events, including abrasions,
        blisters, concussions, contusions, dehydration, hypothermia,
        overheating, sprains, and strains.
- requirement: 2
  text: |-
    Do the following:
  children:
    - requirement: a
      text: |-
        Explain the importance of a physical exam and have your health care
        practitioner give you a physical examination using the Scouting America
        Annual Health and Medical Record.
    - requirement: b
      text: |-
        Explain the importance of maintaining good health habits, especially
        during training, and how the use of tobacco products, alcohol, and
        other harmful substances can negatively affect your health and your
        performance in athletic activities.
    - requirement: c
      text: |-
        Define a healthy diet and explain the importance of maintaining a
        healthy diet.
- requirement: 3
  text: |-
    Do the following:
  children:
    - requirement: a
      text: |-
        Discuss with your counselor your level of familiarity and experience
        with the multisport events (swimming, biking, and running) and the
        order and distance of each sports segment.
    - requirement: b
      text: |-
        Explain to your counselor which multisport event (swimming, biking, or
        running) you feel is your strongest and which you could improve upon
        the most.
    - requirement: c
      text: |-
        Identify the required equipment for each of the three common multisport
        events (swimming, biking, and running).
    - requirement: d
      text: |-
        Based on your interests, experience, and discussion with your
        counselor, select ONE of the following multisport formats to
        concentrate on for the remaining requirements:
      children:
        - requirement: 1
          text: |-
            Triathlon: swimming, biking, and running
        - requirement: 2
          text: |-
            Duathlon: running and biking
        - requirement: 3
          text: |-
            Aquathlon: swimming and running
        - requirement: 4
          text: |-
            Aquabike: swimming and biking
- requirement: 4
  text: |-
    Complete ALL of the activities that apply to the multisport format that you
    selected in requirement 3(d) (Triathlon, Duathlon, Aquathlon, or Aquabike):
  children:
    - requirement: a
      text: |-
        <b>Swimming</b>
      children:
        - requirement: 1
          text: |-
            Before doing requirements 5 through 8, earn the Swimming merit
            badge.
        - requirement: 2
          text: |-
            Explain the components of the Scouting America Safe Swim Defense
            program and how you will ensure they are in place when you swim.
        - requirement: 3
          text: |-
            Explain to your counselor the difference between a pool swim and an
            open water swim, including at what temperature it is appropriate to
            wear a wet suit.
    - requirement: b
      text: |-
        <b>Biking</b>
      children:
        - requirement: 1
          text: |-
            Explain to your counselor how to ride predictably, be conspicuous,
            think ahead, and ride ready.
        - requirement: 2
          text: |-
            Discuss what should be checked regularly to make sure the bicycle
            is safe to ride.
        - requirement: 3
          text: |-
            Explain the importance of wearing a properly sized and fitted
            helmet while cycling and of wearing the right clothing for the
            weather.
    - requirement: c
      text: |-
        <b>Running</b>
      children:
        - requirement: 1
          text: |-
            Demonstrate a proper run warmup and cool-down. Explain to your
            counselor the importance of maintaining healthy habits, including
            hydration, nutrition, injury prevention, and rest.
        - requirement: 2
          text: |-
            Learn and state the basic rules of the road for runners.
        - requirement: 3
          text: |-
            Demonstrate important running drills, including high knees, butt
            kicks, lunges, inchworms, and soldier kicks.
- requirement: 5
  text: |-
    Do the following:
  children:
    - requirement: a
      text: |-
        With guidance from your counselor, establish a four-week training plan
        that combines your chosen multisport format to develop proper
        techniques, gain self-confidence, and increase endurance. Each session
        should last at least 25 minutes and include a proper warmup before the
        session and stretching afterward.
    - requirement: b
      text: |-
        Use a chart or other tracking method to monitor your training and
        development during this period.
    - requirement: c
      text: |-
        Set a personal goal for improvement based on one or more of the
        following criteria: time, technique, or distance.
    - requirement: d
      text: |-
        At the end of four weeks, discuss your progress with your counselor and
        tell how your development has affected you mentally and physically.
- requirement: 6
  text: |-
    Learn the methods of setting up your transition area, which is where your
    bike equipment and/or running gear will be. Discuss with your counselor how
    to smoothly and safely transition from one element to the next, such as
    mounting and dismounting your bike or adjusting your gear.
- requirement: 7
  text: |-
    After completing requirements 1-6, complete all of the activities (on the
    same day and consecutively) for the multisport focus area that you selected
    in requirement 3(d), including demonstrating a smooth and safe transition
    between each:
  children:
    - requirement: a
      text: |-
        Triathlon: swim (100 m), bike (3 km), and run (1 km)
    - requirement: b
      text: |-
        Duathlon: run (1.5 km), bike (3 km), and run (.75 km)
    - requirement: c
      text: |-
        Aquathlon: swim (100 m) and run (1 km)
    - requirement: d
      text: |-
        Aqua bike: swim (100 m) and bike (3 km)
- requirement: 8
  text: |-
    Do TWO of the following and discuss with your counselor:
  children:
    - requirement: a
      text: |-
        Research and identify two ways you can continue participating in
        multisport after completing this merit badge.
    - requirement: b
      text: |-
        Research an Olympic, Paralympic, or professional triathlete (past or
        current). Share information on their background in the sport and what
        inspires you most about this individual.
    - requirement: c
      text: |-
        Demonstrate leadership by starting a training group and educating your
        peers on the importance of physical activity, nutrition, and the
        disciplines of multisport.
    - requirement: d
      text: |-
        Sign up for and participate in a sanctioned multisport event in your
        area.
    - requirement: e
      text: |-
        Volunteer at a local multisport event, running race, biking event, swim
        meet, or adaptive sporting event.
