/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    FeaturedItem: typeof import('./src/components/FeaturedItem.vue')['default']
    FeaturedItemDungeonsAndDragons: typeof import('./src/components/FeaturedItemDungeonsAndDragons.vue')['default']
    FeaturedItemYoutubeVideo: typeof import('./src/components/FeaturedItemYoutubeVideo.vue')['default']
    FigureContainer: typeof import('./src/components/FigureContainer.vue')['default']
    Head: typeof import('@unhead/vue/components')['Head']
    Island: typeof import('./node_modules/iles/dist/client/app/components/Island.vue')['default']
    MeritBadge: typeof import('./src/components/MeritBadge.vue')['default']
    MeritBadgeImage: typeof import('./src/components/MeritBadgeImage.vue')['default']
    MeritBadgeList: typeof import('./src/components/MeritBadgeList.vue')['default']
    MeritBadgePage: typeof import('./src/components/MeritBadgePage.vue')['default']
    Requirements: typeof import('./src/components/Requirements.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScaledContent: typeof import('./src/components/ScaledContent.vue')['default']
    SmbBannerMenu: typeof import('./src/components/SmbBannerMenu.vue')['default']
    SmbBannerMenuButton: typeof import('./src/components/SmbBannerMenuButton.vue')['default']
    SmbFlyoutMenu: typeof import('./src/components/SmbFlyoutMenu.vue')['default']
    SmbFooter: typeof import('./src/components/SmbFooter.vue')['default']
    SmbHeaderBannerImage: typeof import('./src/components/SmbHeaderBannerImage.vue')['default']
    SmbNews: typeof import('./src/components/SmbNews.vue')['default']
    TestLab: typeof import('./src/components/TestLab.vue')['default']
    TestLabTile: typeof import('./src/components/TestLabTile.vue')['default']
    Tile: typeof import('./src/components/Tile.vue')['default']
    TileWrapper: typeof import('./src/components/TileWrapper.vue')['default']
  }
}
