/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    FeaturedItemDungeonsAndDragons: typeof import('./src/components/FeaturedItemDungeonsAndDragons.vue')['default']
    FeaturedItemYoutubeVideo: typeof import('./src/components/FeaturedItemYoutubeVideo.vue')['default']
    FlyoutMenu: typeof import('./src/components/FlyoutMenu.vue')['default']
    Head: typeof import('@unhead/vue/components')['Head']
    Island: typeof import('./node_modules/iles/dist/client/app/components/Island.vue')['default']
    MenuButton: typeof import('./src/components/MenuButton.vue')['default']
    MeritBadge: typeof import('./src/components/MeritBadge.vue')['default']
    MeritBadgeImage: typeof import('./src/components/MeritBadgeImage.vue')['default']
    MeritBadgeList: typeof import('./src/components/MeritBadgeList.vue')['default']
    MeritBadgePage: typeof import('./src/components/MeritBadgePage.vue')['default']
    Modal: typeof import('./src/components/Modal.vue')['default']
    NovaBannerHeader: typeof import('./src/components/NovaBannerHeader.vue')['default']
    NovaBannerMenu: typeof import('./src/components/NovaBannerMenu.vue')['default']
    NovaFooter: typeof import('./src/components/NovaFooter.vue')['default']
    OnlineBanner: typeof import('./src/components/OnlineBanner.vue')['default']
    OtherAward: typeof import('./src/components/OtherAward.vue')['default']
    OtherAwardBucky: typeof import('./src/components/OtherAwardBucky.vue')['default']
    Requirements: typeof import('./src/components/Requirements.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScaledContent: typeof import('./src/components/ScaledContent.vue')['default']
    ScoutRank: typeof import('./src/components/ScoutRank.vue')['default']
    ScoutRankBucky: typeof import('./src/components/ScoutRankBucky.vue')['default']
    SmbBannerMenu: typeof import('./src/components/SmbBannerMenu.vue')['default']
    SmbFooter: typeof import('./src/components/SmbFooter.vue')['default']
    SmbHeaderBannerImage: typeof import('./src/components/SmbHeaderBannerImage.vue')['default']
    SmbNews: typeof import('./src/components/SmbNews.vue')['default']
    TestLab: typeof import('./src/components/TestLab.vue')['default']
    TestLabTile: typeof import('./src/components/TestLabTile.vue')['default']
    Tile: typeof import('./src/components/Tile.vue')['default']
    TileWrapper: typeof import('./src/components/TileWrapper.vue')['default']
    UpcomingEvent: typeof import('./src/components/UpcomingEvent.vue')['default']
    UpcomingEventCalendar: typeof import('./src/components/UpcomingEventCalendar.vue')['default']
    UpcomingEventDetails: typeof import('./src/components/UpcomingEventDetails.vue')['default']
    UpcomingEventIcon: typeof import('./src/components/UpcomingEventIcon.vue')['default']
    UpcomingEventLocation: typeof import('./src/components/UpcomingEventLocation.vue')['default']
    UpcomingEventMeritBadges: typeof import('./src/components/UpcomingEventMeritBadges.vue')['default']
    UpcomingEventRegistration: typeof import('./src/components/UpcomingEventRegistration.vue')['default']
    UpcomingEvents: typeof import('./src/components/UpcomingEvents.vue')['default']
  }
}
