#!/usr/bin/env bash

cd "${0%/*}" || exit

# Download the list of merit badges
html=$(curl -s -o - https://www.scouting.org/programs/scouts-bsa/advancement-and-awards/merit-badges/)

# Look for links formatted like this:
# <h3>...<a href="https://filestore.scouting.org/filestore/Merit_Badge_ReqandRes/Swimming.pdf">Swimming</a></h3>
processedHtml=$(echo "$html" | pup 'h3 a[href*=".pdf"]' | tr -d '\n' | sed 's/> />/g')

# Now the HTML looks like a bunch of links
# ...<a href="https://filestore.scouting.org/filestore/Merit_Badge_ReqandRes/Rifle_Shooting.pdf">Rifle Shooting</a>...

links=()

while read -r line; do
    links+=("$line");
done < <(echo "$processedHtml" | pup 'a attr{href}')

labels=()

while read -r line; do
    labels+=("$line");
done < <(echo "$processedHtml" | pup 'a text{}')

if [[ "${#links[@]}" != "${#labels[@]}" ]]; then
    echo "Number of links and labels do not match"
    exit 1
fi

i=0

while [[ $i -lt "${#links[@]}" ]]; do
    link="${links[i]}"
    label="${labels[i]}"
    label="${label//&amp;/and}" # Fish & Wildlife Management

    # shellcheck disable=SC2018 disable=SC2019
    saveAsBase="$(echo "$label" | tr A-Z a-z | tr -cs a-z0-9 - | sed 's/^-//' | sed 's/-$//')"
    echo "$saveAsBase"

    (
        outputFolder="site/merit-badges/${saveAsBase}"
        cd "$outputFolder" || (echo "Merit badge output folder not found: $outputFolder" ; echo "Using current folder as a fallback")
        curl -s -o "${saveAsBase}.pdf" "$link"
        pdftotext -nopgbrk "${saveAsBase}.pdf" "${saveAsBase}.txt"
    )

    i=$((i + 1))
done

date -I > merit-badges-updated.txt
