#!/usr/bin/env bash

cd "${0%/*}" || exit

downloadNovas() {
    local indexUrl=$1 startFolder=$2

    html=$(curl -s -o - "$indexUrl")

    # Look for links to PDF files
    processedHtml=$(echo "$html" | pup 'h3 a[href*=".pdf"]' | tr -d '\n' | sed 's/> />/g')

    links=()

    while read -r line; do
        links+=("$line");
    done < <(echo "$processedHtml" | pup 'a attr{href}')

    labels=()

    while read -r line; do
        labels+=("$line");
    done < <(echo "$processedHtml" | pup 'a text{}')

    if [[ "${#links[@]}" != "${#labels[@]}" ]]; then
        echo "Number of links and labels do not match"
        exit 1
    fi

    i=0

    while [[ $i -lt "${#links[@]}" ]]; do
        link="${links[i]}"
        label="${labels[i]}"

        # shellcheck disable=SC2018 disable=SC2019
        saveAsBase="$(echo "$label" | tr A-Z a-z | tr -cs a-z0-9 - | sed 's/^-//' | sed 's/-$//')"
        echo "$link ... $label ... $saveAsBase"

        (
            outputFolder="$startFolder/$saveAsBase"
            cd "$outputFolder" || (echo "Output folder not found: $outputFolder" ; echo "Using current folder as a fallback")
            curl -s -o "${saveAsBase}.pdf" "$link"
            pdftotext -nopgbrk "${saveAsBase}.pdf" "${saveAsBase}.txt"
        )

        i=$((i + 1))
    done
}

downloadNovas "https://www.scouting.org/stem-nova-awards/awards/cub-scout/" "site/nova-lab/cub-scouts/"

date -I > novas-updated.txt
