#!/usr/bin/env bash

cd "${0%/*}" || exit

# Download the list of merit badges
html=$(curl -s -o - https://www.scouting.org/programs/scouts-bsa/advancement-and-awards/merit-badges/)

# Look for links formatted like this:
# <a href="https://filestore.scouting.org/filestore/Merit_Badge_ReqandRes/Swimming.pdf">Swimming</a></h3>
# Change lines containing those links to look like
# MERITBADGE_FOUND Swimming|https://filestore.scouting.org/filestore/Merit_Badge_ReqandRes/Swimming.pdf
processedHtml=$(echo "$html" | sed 's/.*href="\([^"]*.pdf\)\(?[^"]*\)\{0,1\}">\s*\([^<]*\)\s*<\/a><\/h3>.*/MERITBADGE_FOUND \3|\1/')

# Extract just the merit badges
list=$(echo "$processedHtml" | grep MERITBADGE_FOUND | cut -d ' ' -f 2-)

while read -r line; do
    mb=${line%|*}
    mb=${mb//&amp;/and}
    pdf=${line#*|}
    # shellcheck disable=SC2018 disable=SC2019
    saveAsBase="$(echo "$mb" | tr A-Z a-z | tr -cs a-z0-9 - | sed 's/^-//' | sed 's/-$//')"
    echo "$mb"

    (
        outputFolder="site/merit-badges/${saveAsBase}"
        cd "$outputFolder" || (echo "Merit badge output folder not found: $outputFolder" ; echo "Using current folder as a fallback")
        curl -s -o "${saveAsBase}.pdf" "$pdf"
        pdftotext -nopgbrk "${saveAsBase}.pdf" "${saveAsBase}.txt"
    )
done < <( echo "$list" )
