# Had a few requirements between pages 4 and 5, between 5a3 and 5b
- requirement: 1
  text: |-
    Read the safety rules for metalwork. Discuss how to be safe while working
    with metal. Discuss with your counselor the additional safety rules that
    apply to the metalwork option you choose for requirement 5.
- requirement: 2
  text: |-
    Define the terms native metal, malleable, metallurgy, alloy, nonferrous,
    and ferrous. Then do the following:
  children:
    - requirement: a
      text: |-
        Name two nonferrous alloys used by pre–Iron Age metalworkers. Name
        the metals that are combined to form these alloys.
    - requirement: b
      text: |-
        Name three ferrous alloys used by modern metalworkers.
    - requirement: c
      text: |-
        Describe how to work-harden a metal.
    - requirement: d
      text: |-
        Describe how to anneal a nonferrous and a ferrous metal.
- requirement: 3
  text: |-
    Do the following:
  children:
    - requirement: a
      text: |-
        Work-harden a piece of 26- or 28-gauge sheet brass or sheet copper.
        Put a 45-degree bend in the metal, then heavily peen the area along
        the bend line to work-harden it. Note the amount of effort that is
        required to overcome the yield point in this unworked piece of
        metal.
    - requirement: b
      text: |-
        Soften the work-hardened piece from requirement 3a by annealing it,
        and then try to remove the 45-degree bend.  Note the amount of
        effort that is required to overcome the yield point.
    - requirement: c
      text: |-
        Make a temper color index from a flat piece of steel.  Using hand
        tools, make and temper a center punch of medium-carbon or
        high-carbon steel.
- requirement: 4
  text: |-
    Find out about three career opportunities in metalworking.  Pick one and
    find out the education, training, and experience required for this
    profession. Discuss this with your counselor, and explain why this
    profession might interest you.
- requirement: 5
  text: |-
    After completing the first four requirements, complete at least ONE of
    the options listed below.
  children:
    - requirement: a
      markdown: true
      text: |-
        **Option 1—Sheet Metal Mechanic/Tinsmith**
      children:
        - requirement: 1
          text: |-
            Name and describe the use of the basic sheet metalworking
            tools.
        - requirement: 2
          text: |-
            Create a sketch of two objects to make from sheet metal.
            Include each component’s dimensions on your sketch, which
            need not be to scale.
        - requirement: 3
          text: |-
            Make two objects out of 24- or 26-gauge sheet metal.  Use
            patterns either provided by your counselor or made by you and
            approved by your counselor.  Construct these objects using a
            metal that is appropriate to the object’s ultimate purpose,
            and using cutting, bending, edging, and either soldering or
            brazing.
          children:
            - requirement: a
              text: |-
                One object also must include at least one riveted
                component.
            - requirement: b
              text: |-
                If you do not make your objects from zinc-plated sheet
                steel or tin-plated sheet steel, preserve your work
                from oxidation.
    - requirement: b
      markdown: true
      text: |-
        **Option 2—Silversmith**
      children:
        - requirement: 1
          text: |-
            Name and describe the use of a silversmith’s basic tools.
        - requirement: 2
          text: |-
            Create a sketch of two objects to make from sheet silver.
            Include each component’s dimensions on your sketch, which
            need not be to scale.
        - requirement: 3
          text: |-
            Make two objects out of 18- or 20-gauge sheet copper. Use
            patterns either provided by your counselor or made by you and
            approved by your counselor.  Both objects must include a
            soldered joint. If you have prior silversmithing experience,
            you may substitute sterling silver, nickel silver, or
            lead-free pewter.
          children:
            - requirement: a
              text: |-
                At least one object must include a sawed component you
                have made yourself.
            - requirement: b
              text: |-
                At least one object must include a sunken part you have
                made yourself.
            - requirement: c
              text: |-
                Clean and polish your objects.
    - requirement: c
      markdown: true
      text: |-
        **Option 3—Founder**
      children:
        - requirement: 1
          text: |-
            Name and describe the use of the basic parts of a two-piece
            mold. Name at least three different types of molds.
        - requirement: 2
          text: |-
            Create a sketch of two objects to cast in metal. Include each
            component’s dimensions on your sketch, which need not be to
            scale.
        - requirement: 3
          text: |-
            Make two molds, one using a pattern provided by your
            counselor and another one you have made yourself that has
            been approved by your counselor.  Position the pouring gate
            and vents yourself.  Do note use copyrighted materials as
            patterns.
          children:
            - requirement: a
              text: |-
                Using lead-free pewter, make a casting using a mold
                provided by your counselor.
            - requirement: b
              text: |-
                Using lead-free pewter, make a casting using the mold
                that you have made.
    - requirement: d
      markdown: true
      text: |-
        **Option 4—Blacksmith**
      children:
        - requirement: 1
          text: |-
            Name and describe the use of a blacksmith’s basic tools.
        - requirement: 2
          text: |-
            Make a sketch of two objects to hot-forge. Include each
            component’s dimensions on your sketch, which need not be to
            scale.
        - requirement: 3
          text: |-
            Using low-carbon steel at least 1⁄4 inch thick, perform the
            following exercises:
          children:
            - requirement: a
              text: |-
                Draw out by forging a taper.
            - requirement: b
              text: |-
                Use the horn of the anvil by forging a U-shaped bend.
            - requirement: c
              text: |-
                Form a decorative twist in a piece of square steel.
            - requirement: d
              text: |-
                Use the edge of the anvil to bend metal by forging an
                L-shaped bend.
        - requirement: 4
          text: |-
            Using low-carbon steel at least 1⁄4 inch thick, make the two
            objects you sketched that require hot-forging.  Be sure you
            have your counselor’s approval before you begin.
          children:
            - requirement: a
              text: |-
                Include a decorative twist on one object.
            - requirement: b
              text: |-
                Include a hammer-riveted joint in one object.
            - requirement: c
              text: |-
                Preserve your work from oxidation.
