- requirement: 1
  text: |-
      Do the following:
  children:
      - requirement: a
        text: |-
            Tour your community and list the different types of buildings you
            see. Try to identify buildings that can be associated with a
            specific period of history or style of architecture. Make a sketch
            of the building you most admire.
        workbook:
            - lines: 8
              text: |-
                  List the different types of buildings you see
            - lines: 20
              text: |-
                  Sketch of the building you most admire
      - requirement: b
        text: |-
            Select an architectural achievement that has had a major impact on
            society. Using resources such as the Internet (with your parent’s
            permission), books, and magazines, find out how this achievement
            has influenced the world today. Tell your counselor what you
            learned.
        workbook:
            - lines: 8
      - note:
            - inPerson
            - online
        text: |-
            Scouts should prepare their work prior to the class and bring their
            completed work to the class ready to share for review.  Pictures
            are encouraged to be gathered as a part of this requirement (but
            not required) to help enhance the sharing of information Scouts
            have learned in their research and so that others in the class,
            including the counselor, might have a better understanding of the
            Scouts choices. Scouts will share their work and findings during
            the class with the counselor and other Scouts.
- requirement: 2
  text: |-
      In the Outdoor Code, a Scout pledges to “be conservation-minded.” Discuss
      the following with your counselor:
  children:
      - requirement: a
        markdown: true
        text: |-
            The term *sustainable architecture*. Identify three features
            typical of green buildings.
        workbook:
            - lines: 4
            - lines: 4
            - lines: 4
      - requirement: b
        text: |-
            The difference between renewable building materials and recycled
            building materials, and how each can be used in construction.
        workbook:
            - lines: 8
      - requirement: c
        text: |-
            The relationship of architecture with its surrounding environment
            and the community.
        workbook:
            - lines: 8
      - requirement: d
        text: |-
            How entire buildings can be reused rather than torn down when they
            no longer serve their original purpose.
        workbook:
            - lines: 8
      - note:
            - inPerson
            - online
        text: |-
            Scouts should review their merit badge pamphlet and come with an
            understanding for discussion in the class the terms and methods
            identified in this requirement. It is highly recommended to utilize
            a Merit Badge Workbook to make notes of your findings. Scouts in
            attendance that have not reviewed their merit badge pamphlet on
            these topics and/or do not actively participate in the class
            discussion will find it difficult to complete this requirement.
- requirement: 3
  text: |-
      Do ONE of the following:
  children:
      - requirement: a
        text: |-
            With your parent’s and counselor’s permission and approval, arrange
            to meet with an architect. Ask to see the scale model of a building
            and the drawings that a builder would use to construct this
            building.  Discuss why the different building materials were
            selected. Look at the details in the drawings and the model to see
            how the materials and components are attached to each other during
            construction.
        workbook:
            - lines: 8
      - requirement: b
        markdown: true
        text: |-
            With your parent’s and counselor’s permission and approval, arrange
            to meet with an architect at a construction site. Ask the architect
            to bring drawings that the builder uses to construct the building.
            While at the site, discuss why the different building materials
            being used were selected. Discuss how the different building
            materials and components are attached to each other during
            construction.

            **Note:** To visit a construction site will require advance
            planning. You will need permission from your parents, counselor,
            the architect, and the construction site manager. A construction
            site is a very dangerous place.  While there, you will need to
            closely follow the site manager’s directions and comply with all
            the safety procedures, including wearing a hard hat, protective
            eyewear, and proper footwear. Be aware of the changing conditions
            at the site, and stay with the architect or site manager.
        workbook:
            - lines: 8
      - note:
            - inPerson
            - online
        text: |-
            Scouts wishing to work on requirement component(s) 3a or 3b, may
            work on these prior to the class, but please note that the
            counselor reserves the right to accept or deny your work on the
            basis of meeting the expectations of these requirement components
            to their satisfaction. Make sure your work is pertinent to the
            requirement components focus and be prepared to share your work.
            Scouts should consider bringing a note signed by the architect they
            met with during their visit in addition to any other supporting
            photo or document proof.
      - requirement: c
        text: |-
            Interview someone who might be your client (such as a prospective
            homeowner or business owner) if you were an architect. Find out
            what your client’s requirements would be for designing a new home
            or business building. Write a short program including a list of
            requirements for the project, the functions of the building and
            site, how the functions relate to one another, and the goals of the
            project.
        workbook:
            - lines: 20
      - note:
            - inPerson
        text: |-
            Requirement 3c will be covered during the class through the
            guidance of the merit badge counselor/instructor. However, Scouts
            wishing to work on requirement component(s) 3a or 3b, may work on
            these prior to the class, but please note that the counselor
            reserves the right to accept or deny your work on the basis of
            meeting the expectations of these requirement components to their
            satisfaction. Make sure your work is pertinent to the requirement
            components focus and be prepared to share your work.  Scouts should
            consider bringing a note signed by the architect they met with
            during their visit in addition to any other supporting photo or
            document proof.
      - note:
            - online
        text: |-
            Requirement 3c MAY be covered during the class through the guidance
            of the merit badge counselor/instructor.  Keep in mind that there
            is a writing aspect required for this requirement component that
            some Scouts may find challenging to complete during the class. If
            choosing to work on this requirement component, consider preapraing
            for it prior to the class.
- requirement: 4
  text: |-
      Measure a room such as one where you live or where your troop meets. Make
      an accurately scaled drawing of the room’s floor plan showing walls,
      doors, closets, windows, and any built-in furniture or cabinets. Neatly
      label your drawing with the following: your name, the date, what room you
      drew, and the scale of the drawing.  (Drawing scale: ¼ inch = 1 foot)
  workbook:
      - split:
            - lines: 2
              text: |-
                  Your name
            - lines: 2
              text: |-
                  The date
      - split:
            - lines: 2
              text: |-
                  What room you drew
            - lines: 2
              text: |-
                  Scale of the drawing
      - grid: 40
  children:
      - note:
            - inPerson
        text: |-
            This requirement will be covered in the class through the guidance
            of the merit badge counselor. However, Scouts are encouraged to
            take pictures and measurements of a room where they reside or their
            Scout meeting area in preparation for this requirement and to
            ensure the highest probability for completion of this requirement
            during the class.
      - note:
            - online
        text: |-
            This requirement will NOT be covered in the class however time will
            be allotted for Scouts to share their work with the merit badge
            counselor/instructor during the class. Scouts are encouraged to
            take pictures and measurements of a room where they reside or their
            Scout meeting area in preparation for sharing their work during the
            class. Be Prepared!
- requirement: 5
  text: |-
      Find out about three career opportunities in architecture.  Pick one and
      find out the education, training, and experience required for this
      profession. Discuss this with your counselor, and explain why this
      profession might interest you.
  workbook:
      - lines: 8
        text: |-
            Three career opportunities in architecture
      - lines: 8
        text: |-
            Education, training, and experience required for one profession
  children:
      - note:
            - inPerson
            - online
        text: |-
            Scouts should review this requirement and its components and be
            prepared to discuss. It is strongly recommended that Scouts bring
            any notes or supporting documents they may have to help show the
            counselor that they have prepared for completion of this
            requirement.
