- requirement: 1
  text: |-
    Discuss with your counselor the roles a veterinarian plays in the
    following:
  children:
    - requirement: a
      text: |-
        Companion or small animal medicine, and equine medicine
    - requirement: b
      text: |-
        Food animal or large animal medicine
    - requirement: c
      text: |-
        Exotic animal medicine
    - requirement: d
      text: |-
        Marine animal medicine (mammal and fish)
    - requirement: e
      text: |-
        Poultry medicine
    - requirement: f
      text: |-
        Wildlife medicine and aquaculture medicine
- requirement: 2
  text: |-
    Discuss with your counselor the roles a veterinarian plays in the
    following:
  children:
    - requirement: a
      text: |-
        Public health medicine and zoonotic disease surveillance and
        control
    - requirement: b
      text: |-
        The military
    - requirement: c
      text: |-
        Food safety and inspection
    - requirement: d
      text: |-
        Laboratory animal medicine and research
    - requirement: e
      text: |-
        Teaching and government
- requirement: 3
  text: |-
    Describe the training required to become a veterinarian.  Where is the
    veterinary medical college nearest you?  Describe the prerequisites for
    applying to veterinary school.
- requirement: 4
  text: |-
    Tell your counselor what a registered veterinary technician (R.V.T.) or
    animal health technician (A.H.T.) is. Describe the training required to
    become an R.V.T. or A.H.T. Where is the school or facility for R.V.T. or
    A.H.T. training nearest you? Describe the role an R.V.T. or A.H.T. would
    play in assisting a veterinarian working in three of the practice types
    listed in requirement 1.
- requirement: 5
  text: |-
    Discuss with your merit badge counselor the role a veterinarian plays in
    the human-animal bond.
- requirement: 6
  text: |-
    Do ONE of the following:
  children:
    - requirement: a
      text: |-
        Visit a veterinary clinic, hospital, or veterinary referral
        teaching hospital that does work in one of the practices listed in
        requirement 1. Spend as much time as you can observing the
        veterinarians and their staff. Write a report on what you observed
        and learned at the facility.  Share your report with your
        counselor.
    - requirement: b
      text: |-
        Spend as much time as possible with a veterinarian who works in one
        of the fields listed in requirement 2. Learn what special training
        beyond veterinary medical school may have been required for that
        position. Learn about any special or unusual activities required of
        this position.  Write a report on what you have learned about this
        field of veterinary medicine. Include in your report how this field
        serves the needs of the general public. Share your report with your
        counselor.
