- requirement: 1
  text: |-
      Do the following:
  children:
      - requirement: a
        text: |-
            Discuss how you can better understand people, places, institutions,
            history, and geography as a result of collecting stamps.
        workbook:
            - lines: 8
      - requirement: b
        text: |-
            Briefly describe some aspects of the history, growth, and
            development of the United States postal system.  Tell how it is
            different from postal systems in other countries.
        workbook:
            - lines: 8
      - note:
            - inPerson
            - online
        text: |-
            Scouts should review the Stamp Collecting Merit Badge pamphlet and
            come with an understanding for discussion in the class their
            thoughts on collecting stamps as well as the history and growth of
            the US postal system. It is highly recommended to utilize a Merit
            Badge Workbook to make notes of findings and research. Scouts in
            attendance that have not reviewed their merit badge pamphlet on the
            topics of this requirement and its components and/or do not
            actively participate in the class discussion will find it difficult
            to complete this requirement or its components.
- requirement: 2
  text: |-
      Define topical stamp collecting. Name and describe three other types of
      stamp collections.
  workbook:
      - lines: 8
  children:
      - note:
            - inPerson
            - online
        text: |-
            Scouts should consider using a notebook or Merit Badge workbook to
            make notes while preparing for class discussion on this
            requirement.  The Stamp Collecting Merit Badge pamphlet is a great
            resource to reference when doing preparation work for this
            requirement.
- requirement: 3
  text: |-
      Show at least ONE example of each of the following:
  workbook:
      - split:
            - area: 8
              text: |-
                  Perforated and imperforate stamps
            - area: 8
              text: |-
                  Mint and used stamps
      - split:
            - area: 8
              text: |-
                  Sheet, booklet, and coil stamps
            - area: 8
              text: |-
                  Numbers on plate block, booklet, or coil, or marginal
                  markings
      - split:
            - area: 8
              text: |-
                  Overprint and surcharge
            - area: 8
              text: |-
                  Metered mail
      - split:
            - area: 8
              text: |-
                  Definitive, commemorative, semipostal, and airmail stamps
            - area: 8
              text: |-
                  Cancellation and postmark
      - split:
            - area: 8
              text: |-
                  First day cover
            - area: 8
              text: |-
                  Postal stationery (aerogramme, stamped envelope, and postal
                  card)
  children:
      - requirement: a
        text: |-
            Perforated and imperforate stamps
        workbookHide: true
      - requirement: b
        text: |-
            Mint and used stamps
        workbookHide: true
      - requirement: c
        text: |-
            Sheet, booklet, and coil stamps
        workbookHide: true
      - requirement: d
        text: |-
            Numbers on plate block, booklet, or coil, or marginal markings
        workbookHide: true
      - requirement: e
        text: |-
            Overprint and surcharge
        workbookHide: true
      - requirement: f
        text: |-
            Metered mail
        workbookHide: true
      - requirement: g
        text: |-
            Definitive, commemorative, semipostal, and airmail stamps
        workbookHide: true
      - requirement: h
        text: |-
            Cancellation and postmark
        workbookHide: true
      - requirement: i
        text: |-
            First day cover
        workbookHide: true
      - requirement: j
        text: |-
            Postal stationery (aerogramme, stamped envelope, and postal card)
        workbookHide: true
      - note:
            - inPerson
            - online
        text: |-
            Scouts will need to prepare for the class by gathering examples of
            stamps that meet each of these requirement components'
            descriptions. Scouts will find the use of the Stamp Collecting
            Merit Badge pamphlet to be very useful in helping define and
            clarify the specifics being asked for in each requirement
            component.  The class instructor / counsleor will help validate
            Scouts findings.  Only Scouts that have made a reasonable effort to
            gather samples and are able to share, will be considered for sign
            off on this requirement and its components.
- requirement: 4
  text: |-
      Do the following:
  children:
      - requirement: a
        text: |-
            Demonstrate the use of ONE standard catalog for several different
            stamp issues. Explain why catalog value can vary from the
            corresponding purchase price.
        workbook:
            - lines: 8
        children:
            - note:
                  - inPerson
                  - online
              text: |-
                  Scouts will need to prepare ahead of the class in order to be
                  ready to demonstrate their ability to accurately look up
                  stamps in a stamp catalog.  If Scouts are unable to secure a
                  catalog, there will be one available during the class,
                  however, despite this catalog's availability during the
                  class, only Scouts who arrive at the class knowing how to use
                  a stamp catalog and properly will be considered for sign off
                  on this requirement component. Scouts should also have
                  prepared their explanation of why value and purchase price
                  may vary.  Only Scouts who actively participate in class
                  discussion, and have prepared for this requirement component,
                  will be considered for sign off.
      - requirement: b
        markdown: true
        text: |-
            Explain the meaning of the term *condition* as used to describe a
            stamp. Show examples that illustrate the different factors that
            affect a stamp’s value.
        workbook:
            - lines: 8
            - split:
                  - area: 8
                    text: |-
                        Example
                  - area: 8
                    text: |-
                        Example
                  - area: 8
                    text: |-
                        Example
        children:
            - note:
                  - inPerson
                  - online
              text: |-
                  Scouts will find the use of the Stamp Collecting Merit Badge
                  pamphlet to be a valuable resource in preparing for this
                  requirement component. Scouts will need to also have examples
                  to share during the class, along with their explanation for
                  the first part of this requirement component, for
                  consideration of completion.
- requirement: 5
  text: |-
      Demonstrate the use of at least THREE of the following stamp collector’s
      tools:
  children:
      - requirement: a
        text: |-
            Stamp tongs
        workbook:
            - lines: 4
      - requirement: b
        text: |-
            Water and tray
        workbook:
            - lines: 4
      - requirement: c
        text: |-
            Magnifiers
        workbook:
            - lines: 4
      - requirement: d
        text: |-
            Hinges and stamp mounts
        workbook:
            - lines: 4
      - requirement: e
        text: |-
            Perforation gauge
        workbook:
            - lines: 4
      - requirement: f
        text: |-
            Glassine envelopes and cover sleeves
        workbook:
            - lines: 4
      - requirement: g
        text: |-
            Watermark fluid
        workbook:
            - lines: 4
      - note:
            - inPerson
        text: |-
            Scouts should be prepared to demonstrate their ability to use three
            of the listed stamp collecting tools during the class.  While the
            merit badge instructor / counselor will have most of these tools
            available at the class, Scouts should be prepared with their own
            tools if possible, to ensure they are able to demonstrate their
            abilities without excuse.
      - note:
            - online
        text: |-
            Scouts will need to have the stamp collecting tools when attending
            online in order to be considered for sign off on this requirement
            and its components. All Scouts will share their work during the
            class for review.
- requirement: 6
  text: |-
      Do the following:
  children:
      - requirement: a
        text: |-
            Show a stamp album and how to mount stamps with or without hinges.
            Show at least ONE page that displays several stamps.
        workbook:
            - lines: 4
        children:
            - note:
                  - inPerson
                  - online
              text: |-
                  Scouts will need to have their own stamp album, stamps, and
                  mounting materials / tools in order to complete this
                  requirement component. The class instructor / counselor will
                  give guidance to Scouts who may need it for completion of
                  this requirement component. Be Prepared.
      - requirement: b
        text: |-
            Discuss at least THREE ways you can help to preserve stamps,
            covers, and albums in first-class condition.
        workbook:
            - lines: 8
        children:
            - note:
                  - inPerson
                  - online
              text: |-
                  While the merit badge instructor / counselor will help
                  facilitate discussion on this requirement component, only
                  Scouts who have prepared for this discussion and actively
                  participate in the class discussion will be considered for
                  sign off.
- requirement: 7
  text: |-
      Do at least TWO of the following:
  children:
      - requirement: a
        text: |-
            Design a stamp, cancellation, or cachet.
        workbook:
            - area: 8
      - requirement: b
        text: |-
            Visit a post office, stamp club, or stamp show with an experienced
            collector. Explain what you saw and learned.
        workbook:
            - lines: 8
      - requirement: c
        text: |-
            Write a review of an interesting article from a stamp newspaper,
            magazine, book, or website (with your parent’s permission).
        workbook:
            - lines: 8
      - requirement: d
        text: |-
            Research and report on a famous stamp-related personality or the
            history behind a particular stamp.
        workbook:
            - lines: 8
      - requirement: e
        text: |-
            Describe the steps taken to produce a stamp. Include the methods of
            printing, types of paper, perforation styles, and how they are
            gummed.
        workbook:
            - lines: 8
      - requirement: f
        text: |-
            Prepare a two- to three-page display involving stamps.  Using
            ingenuity, as well as clippings, drawings, etc., tell a story about
            the stamps and how they relate to history, geography, or a favorite
            topic of yours.
        workbook:
            - lines: 8
      - note:
            - inPerson
            - online
        text: |-
            This requirement will NOT be done as a part of the class HOWEVER,
            Scouts attending the class having done work for two selected
            components will have the opportunity to share their work with the
            merit badge counselor during the class for consideration of sign
            off. Be Prepared.
- requirement: 8
  text: |-
      Mount and show, in a purchased or homemade album, ONE of the following:
  children:
      - requirement: a
        text: |-
            A collection of 250 or more different stamps from at least 15
            countries.
        workbook:
            - lines: 4
      - requirement: b
        text: |-
            A collection of a stamp from each of 50 different countries,
            mounted on maps to show the location of each.
        workbook:
            - lines: 4
      - requirement: c
        text: |-
            A collection of 100 or more different stamps from either one
            country or a group of closely related countries.
        workbook:
            - lines: 4
      - requirement: d
        text: |-
            A collection of 75 or more different stamps on a single topic.
            (Some interesting topics are Scouting, birds, insects, the
            Olympics, sports, flowers, animals, ships, holidays, trains, famous
            people, space, and medicine.) Stamps may be from different
            countries.
        workbook:
            - lines: 4
      - requirement: e
        text: |-
            A collection of postal items discovered in your mail by monitoring
            it over a period of 30 days. Include at least five different types
            listed in requirement 3.
        workbook:
            - lines: 4
      - note:
            - inPerson
            - online
        text: |-
            This requirement will NOT be done as a part of the class, HOWEVER,
            Scouts will have an opportunity to share their album with the
            counselor during the class for review and sign off on this
            requirement.
