- requirement: 1
  text: |-
      Choose A or B or C or D and complete ALL the requirements.
  children:
      - requirement: A
        text: |-
            Watch about three hours total of math-related shows or
            documentaries that involve scientific models and modeling, physics,
            sports equipment design, bridge building, or cryptography. Then do
            the following:
        children:
            - requirement: 1
              text: |-
                  Make a list of at least five questions or ideas from the
                  show(s) you watched.
            - requirement: 2
              text: |-
                  Discuss two of the questions or ideas with your counselor.
            - detail: true
              text: |-
                  Some examples include—but are not limited to—shows found on
                  PBS (“NOVA”), Discovery Channel, Science Channel, National
                  Geographic Channel, and TED Talks (online videos). You may
                  choose to watch a live performance or movie at a science
                  museum instead of watching a media production. You may watch
                  online productions with your counselor’s approval and under
                  your parent’s or guardian’s supervision.
      - requirement: B
        text: |-
            Research (about three hours total) several websites (with your
            parent’s or guardian’s permission) that discuss and explain
            cryptography or the discoveries of people who worked extensively
            with cryptography. Then do the following:
        children:
            - requirement: 1
              text: |-
                  List and record the URLs of the websites you visited and
                  major topics covered on the websites you visited. (You may
                  use the copy and paste function— eliminate the words—if you
                  include your sources.)
            - requirement: 2
              text: |-
                  Discuss with your counselor how cryptography is used in the
                  military and in everyday life and how a cryptographer uses
                  mathematics.
            - detail: true
              markdown: true
              text: |-
                  Helpful Link

                  “The Mathematics of Cryptology”: University of Massachusetts<br />
                  Website: http://www.math.umass.edu/~gunnells/talks/crypt.pdf
      - requirement: C
        text: |-
            Read at least three articles (about three hours total) about
            physics, math, modeling, or cryptography. You may wish to read
            about how technology and engineering are changing sports equipment,
            how and why triangles are used in construction, bridge building,
            engineering, climate and/or weather models, how banks keep
            information secure, or about the stock market. Then do the
            following:
        children:
            - requirement: 1
              text: |-
                  Make a list of at least two questions or ideas from each
                  article.
            - requirement: 2
              text: |-
                  Discuss two of the questions or ideas with your counselor.
            - detail: true
              text: |-
                  Examples of magazines include—but are not limited to—beanZ,
                  Plus, Owl, How it Works, Discover, National Geographic,
                  Nature, Odyssey, Popular Mechanics, Popular Science, Science
                  Illustrated, Air & Space, Popular Astronomy, Astronomy,
                  Science News, Sky & Telescope, Natural History, Robot, Servo,
                  Nuts and Volts, and Scientific American.
      - requirement: D
        text: |-
            Do a combination of reading, watching, and researching (about three
            hours total). Then do the following:
        children:
            - requirement: 1
              text: |-
                  Make a list of at least two questions or ideas from each
                  article, website, or show.
            - requirement: 2
              text: |-
                  Discuss two of the questions or ideas with your counselor.
- requirement: 2
  markdown: true
  text: |-
      Complete ONE merit badge from the following list. (Choose one that you
      have not already used toward another Nova award.) After completion,
      discuss with your counselor how the merit badge you earned uses
      mathematics.

      * <a href="../../../merit-badges/american-business/">American Business</a>
      * <a href="../../../merit-badges/animation/">Animation</a>
      * <a href="../../../merit-badges/chess/">Chess</a>
      * <a href="../../../merit-badges/digital-technology/">Digital Technology</a>
      * <a href="../../../merit-badges/drafting/">Drafting</a>
      * <a href="../../../merit-badges/entrepreneurship/">Entrepreneurship</a>
      * <a href="../../../merit-badges/orienteering/">Orienteering</a>
      * <a href="../../../merit-badges/personal-management/">Personal Management</a>
      * <a href="../../../merit-badges/radio/">Radio</a>
      * <a href="../../../merit-badges/signs-signals-and-codes/">Signs, Signals, and Codes</a>
      * <a href="../../../merit-badges/surveying/">Surveying</a>
      * <a href="../../../merit-badges/weather/">Weather</a>
- requirement: 3
  text: |-
      Choose TWO from A or B or C or D and complete ALL the requirements for
      the two you choose. (Write down your data and calculations to support
      your explanation to your counselor. You may use a spreadsheet. Do not use
      someone else’s data or calculations.)
  children:
      - requirement: a
        text: |-
            Calculate your horsepower when you run up a flight of stairs.
        children:
            - detail: true
              markdown: true
              text: |-
                  Horsepower is a unit of power. One horsepower equals 33,000
                  foot-pounds of work per minute, or 745.6 watts. James Watt,
                  who invented steam engines, based his unit of power on how
                  much weight a real horse could pull from a coal mine in one
                  minute. See “What Is Horsepower” at
                  www.web-cars.com/math/horsepower.html.
            - detail: true
              markdown: true
              text: |-
                  Helpful Links

                  “How to Calculate Your Horsepower”: wikiHow<br />
                  Website: http://www.wikihow.com/Calculate-Your-Horsepower
            - detail: true
              markdown: true
              text: |-
                  1. Find out how much you weigh in kilograms and write it down.
                  (Multiply your weight in pounds by 0.454 to get kilograms.)

                  2. Find a stair, ladder, or something similar (as long as it gets
                  you upward).

                  3. Measure the height (not the length) of the stairs (or whatever
                  you use) from the bottom to the ending point at the top and write
                  it down. This can be done by multiplying the height of one stair by
                  the number of stairs (it doesn’t matter how long the stairs are).

                  4. Take a running start toward the stairs. When you step on the
                  first step, start the timer; when both feet are on the top step,
                  stop the timer. (You may skip stairs.) Now you have all the numbers
                  needed.

                  5. Calculate the Power (P) with this formula: `mah/t (m*9.80*h)/t`,
                  where:

                      * `m` = mass (your weight) in kilograms
                      * `a` = acceleration (9.80 m/sec2 is the acceleration caused by Earth’s gravity)
                      * `h` = height of staircase in meters
                      * `t` = time in seconds

                      The number you get is in watts, which is equal to joules per
                      second (J/s) and newton meters per second (Nm/s). If you don’t
                      divide by time, you will calculate the energy needed to climb
                      the stairs.

                      * Work = mah
                      * Power = mah/t

                      Work (or energy) is measured in newton meters or joules; power
                      is measured in joules/second or watts.

                  6. Divide the number of watts by 745.6 w/hp to get the number in
                  horsepower.
            - requirement: 1
              text: |-
                  How does your horsepower compare to the power of a horse?
            - requirement: 2
              text: |-
                  How does your horsepower compare to the horsepower of your
                  favorite car?
            - detail: true
              text: |-
                  Most car information packets and many websites list the
                  horsepower of cars.
            - detail: true
              text: |-
                  Share your calculations with your counselor and discuss what you
                  learned about horsepower.
      - requirement: B
        text: |-
            Attend at least two track, cross country, or swim meets. You may
            substitute any sport where there are timed events.
        children:
            - requirement: 1
              text: |-
                  For each meet, time at least three racers. (Time the same
                  racers at each meet.)
            - requirement: 2
              text: |-
                  Calculate the average speed of the racers you timed. (Make
                  sure you record your data and calculations.)
            - requirement: 3
              text: |-
                  Compare the average speeds of your racers to each other, to
                  the official time, and to their times at the two meets you
                  attended. Share your calculations with your counselor, and
                  discuss your conclusions about the racers’ strengths and
                  weaknesses.
            - detail: true
              text: |-
                  Average speed = Distance / Time
      - requirement: C
        text: |-
            Attend a soccer, baseball, softball, or basketball game. Then
            choose two players. Keep track of their efforts during the game.
            (Make sure you record your data and calculations.) Calculate their
            statistics using the following as examples:
        children:
            - requirement: 1
              text: |-
                  Soccer—Goals, assists, corner kicks, keeper saves, fouls,
                  offsides
            - requirement: 2
              text: |-
                  Baseball or softball—Batting average, runs batted in,
                  fielding statistics, pitching statistics
            - requirement: 3
              text: |-
                  Basketball—Points, baskets attempted, rebounds, steals,
                  turnovers, and blocked shots
            - detail: true
              markdown: true
              text: |-
                  Helpful Links

                  The following are some suggested sites. You may find other
                  sources on your own.

                  “SoccerXpert.com Soccer Stats”: SoccerXpert.com<br />
                  Website: https://www.soccerxpert.com/docs/GameStats.pdf<br />
                  Local copy: [Soccer Stat Sheet](soccer-stat-sheet.pdf)

                  The Baseball Scorecard<br />
                  Website: https://www.baseball.org.il/images/Scorecard.pdf<br />
                  Local copy: [Baseball Score Card](baseball-score-card.pdf)

                  “How to Take Statistics at a Basketball Game”<br />
                  Website: https://www.basketballforcoaches.com/basketball-stat-sheet/<br />
                  Local copy: [Basketball Stat Sheet](basketball-stat-sheet.pdf)
            - detail: true
              text: |-
                  Share your calculations with your counselor and discuss your
                  conclusions about the players’ strengths and weaknesses.
      - requirement: D
        text: |-
            Attend a football game or watch one on TV. (This is a fun activity
            to do with a parent or friend.) Keep track of the efforts of your
            favorite team during the game. (Make sure you record your data and
            calculations.) Then calculate your team’s statistics using the
            following as examples:
        children:
            - requirement: 1
              text: |-
                  Kicks/punts
              children:
                  - requirement: a
                    text: |-
                        Kickoff—Kick return yards
                  - requirement: b
                    text: |-
                        Punt—Number, yards
                  - requirement: d
                    text: |-
                        Field goals—Attempted, percent completed, yards
                  - requirement: d
                    text: |-
                        Extra points—Attempted, percent completed
            - requirement: 2
              text: |-
                  Offense
              children:
                  - requirement: a
                    text: |-
                        Number of first downs
                  - requirement: b
                    text: |-
                        Forward passes—Attempted, percent completed, total
                        length of passes, longest pass, number and length of
                        passes caught by each receiver, yardage gained by each
                        receiver after catching a pass
                  - requirement: c
                    text: |-
                        Running plays—Number, yards gained or lost for each
                        run, longest run from scrimmage line, total yards
                        gained or lost, and number of touchdowns
            - requirement: 3
              text: |-
                  Defense—Number of quarterback sacks, interceptions,
                  turnovers, and safeties
            - detail: true
              text: |-
                  Share your calculations with your counselor, and discuss your
                  conclusions about your team’s strengths and weaknesses.
- requirement: 4
  text: |-
      Do ALL the following:
  children:
      - requirement: A
        text: |-
            Investigate your calculator and explore the different functions.
      - requirement: B
        text: |-
            Discuss the functions, abilities, and limitations of your
            calculator with your counselor. Talk about how these affects what
            you can and cannot do with a calculator. (See your counselor for
            some ideas to consider.)
      - requirement: C
        text: |-
            Discuss with your counselor how math affects your everyday life.
      - detail: true
        markdown: true
        text: |-
            Here are some ideas for your Scout to consider. Pick a few or think of others.

            * How can you add fractions using your calculator and get an answer
            in fraction form?
            * How can you perform repeated calculations efficiently?
            * How many digits in a numerical answer can your calculator
            display? What if the answer to your calculation has more digits
            than your calculator can display? Can you figure out how many
            digits your answer has? Can you figure out the hidden digits?
            * How can you enter, store, recall, and use a list of data to
            perform data analysis calculations?
            * For a calculator with graphing capabilities, how can you display
            a graph? Will a graphing calculator always show the entire graph or
            does it sometimes show only a portion of the graph? If it shows
            only a portion of the graph, how can you be certain that the
            portion you are viewing shows the features you want to see?
            * For numerical calculations, when does your calculator give exact
            answers and when does it give approximate answers? What is the
            difference? How can you tell? Does it matter?
            * If your calculator defaults to giving you an approximate answer,
            but you need an exact answer, what do you do?
            * If an approximate answer will do, how might your calculator’s
            internal calculation limitations affect the accuracy of the
            approximation?
            * For a calculator with graphing capabilities, how might pixel
            limitations affect its depiction of a graph?
            * Is the calculator always right? Why or why not? How might you
            tell? What might cause a calculator to give you an incorrect
            answer? (For a graphing calculator, what might cause the calculator
            to give you an incorrect graph, no graph, or a graph that cannot be
            readily interpreted?)
            * Are there numerical calculations that calculators can’t do? If
            possible, give an example.
