# 7b missing period at end. Added one.
- requirement: 1
  text: |-
    Do the following:
  children:
    - requirement: a
      text: |-
        Choose an item that your family might want to purchase that is
        considered a major expense.
    - requirement: b
      text: |-
        Write a plan that tells how your family would save money for the
        purchase identified in requirement 1a.
      children:
        - requirement: 1
          text: |-
            Discuss the plan with your counselor.
        - requirement: 2
          text: |-
            Discuss the plan with your family.
        - requirement: 3
          text: |-
            Discuss how other family needs must be considered in this plan.
    - requirement: c
      text: |-
        Develop a written shopping strategy for the purchase identified in
        requirement 1a.
      children:
        - requirement: 1
          text: |-
            Determine the quality of the item or service (using consumer
            publications or rating systems).
        - requirement: 2
          text: |-
            Comparison shop for the item. Find out where you can buy the item
            for the best price. (Provide prices from at least two different
            price sources.) Call around; study ads. Look for a sale or discount
            coupon. Consider alternatives. Can you buy the item used? Should
            you wait for a sale?
- requirement: 2
  text: |-
    Do the following:
  children:
    - requirement: a
      text: |-
        Prepare a budget reflecting your expected income (allowance, gifts,
        wages), expenses, and savings for a period of 13 consecutive weeks.
    - requirement: b
      text: |-
        Compare expected income with expected expenses.
      children:
        - requirement: 1
          text: |-
            If expenses exceed budget income, determine steps to balance your
            budget.
        - requirement: 2
          text: |-
            If income exceeds budget expenses, state how you would use the
            excess money (new goal, savings).
    - requirement: c
      text: |-
        Track and record your actual income, expenses, and savings for 13
        consecutive weeks (the same 13-week period for which you budgeted).
        (You may use the forms provided in this pamphlet, devise your own, or
        use a computer-generated version.) When complete, present the records
        showing the results to your counselor.
    - requirement: d
      text: |-
        Compare your budget with your actual income and expenses to understand
        when your budget worked and when it did not work. With your counselor,
        discuss what you might do differently the next time.
- requirement: 3
  text: |-
    Discuss with your counselor FIVE of the following concepts:
  children:
    - requirement: a
      text: |-
        The emotions you feel when you receive money.
    - requirement: b
      text: |-
        Your understanding of how the amount of money you have with you affects
        your spending habits.
    - requirement: c
      text: |-
        Your thoughts when you buy something new and your thoughts about the
        same item three months later. Explain the concept of buyer's remorse.
    - requirement: d
      text: |-
        How hunger affects you when shopping for food items (snacks,
        groceries).
    - requirement: e
      text: |-
        Your experience of an item you have purchased after seeing or hearing
        advertisements for it. Did the item work as well as advertised?
    - requirement: f
      text: |-
        Your understanding of what happens when you put money into a savings
        account.
    - requirement: g
      text: |-
        Charitable giving. Explain its purpose and your thoughts about it.
    - requirement: h
      text: |-
        What you can do to better manage your money.
- requirement: 4
  text: |-
    Explain the following to your counselor:
  children:
    - requirement: a
      text: |-
        The differences between saving and investing, including reasons for
        using one over the other.
    - requirement: b
      text: |-
        The concepts of return on investment and risk and how they are related.
    - requirement: c
      text: |-
        The concepts of simple interest and compound interest.
    - requirement: d
      text: |-
        The concept of diversification in investing.
    - requirement: e
      text: |-
        Why it is important to save and invest for retirement.
- requirement: 5
  text: |-
    Explain to your counselor what the following investments are and how each
    works:
  children:
    - requirement: a
      text: |-
        Common stocks
    - requirement: b
      text: |-
        Mutual funds
    - requirement: c
      text: |-
        Life insurance
    - requirement: d
      text: |-
        A certificate of deposit (CD)
    - requirement: e
      text: |-
        A savings account
    - requirement: f
      text: |-
        A U.S. savings bond
- requirement: 6
  text: |-
    Explain to your counselor why people might purchase the following types of
    insurance and how they work:
  children:
    - requirement: a
      text: |-
        Automobile
    - requirement: b
      text: |-
        Health
    - requirement: c
      text: |-
        Homeowner's/renter's
    - requirement: d
      text: |-
        Whole life and term life
- requirement: 7
  text: |-
    Explain to your counselor the following:
  children:
    - requirement: a
      text: |-
        What a loan is, what interest is, and how the annual percentage rate
        (APR) measures the true cost of a loan.
    - requirement: b
      text: |-
        The different ways to borrow money.
    - requirement: c
      text: |-
        The differences between a charge card, debit card, and credit card.
        What are the costs and pitfalls of using these financial tools? Explain
        why it is unwise to make only the minimum payment on your credit card.
    - requirement: d
      text: |-
        Credit reports and how personal responsibility can affect your credit
        report.
    - requirement: e
      text: |-
        Ways to reduce or eliminate debt.
- requirement: 8
  text: |-
    Demonstrate to your counselor your understanding of time management by
    doing the following:
  children:
    - requirement: a
      text: |-
        Write a "to do" list of tasks or activities, such as homework
        assignments, chores, and personal projects, that must be done in the
        coming week. List these in order of importance to you.
    - requirement: b
      text: |-
        Make a seven-day calendar or schedule. Put in your set activities, such
        as school classes, sports practices or games, jobs or chores, and/or
        Scout or place of worship or club meetings, then plan when you will do
        all the tasks from your "to do" list between your set activities.
    - requirement: c
      text: |-
        Follow the one-week schedule you planned. Keep a daily diary or journal
        during each of the seven days of this week's activities, writing down
        when you completed each of the tasks on your "to do" list compared to
        when you scheduled them.
    - requirement: d
      text: |-
        With your counselor, review your "to do" list, one-week schedule, and
        diary/journal to understand when your schedule worked and when it did
        not work. Discuss what you might do differently the next time.
- requirement: 9
  text: |-
    Prepare a written project plan demonstrating the steps below, including the
    desired outcome. This is a project on paper, not a real-life project.
    Examples could include planning a camping trip, developing a community
    service project or a school or religious event, or creating an annual
    patrol plan with additional activities not already included in the troop
    annual plan. Discuss your completed project plan with your counselor.
  children:
    - requirement: a
      text: |-
        Define the project. What is your goal?
    - requirement: b
      text: |-
        Develop a timeline for your project that shows the steps you must take
        from beginning to completion.
    - requirement: c
      text: |-
        Describe your project.
    - requirement: d
      text: |-
        Develop a list of resources. Identify how these resources will help you
        achieve your goal.
    - requirement: e
      text: |-
        Develop a budget for your project.
- requirement: 10
  text: |-
    Do the following:
  children:
    - requirement: a
      text: |-
        Choose a career you might want to enter after high school or college
        graduation. Discuss with your counselor the needed qualifications,
        education, skills, and experience.
    - requirement: b
      text: |-
        Explain to your counselor what the associated costs might be to pursue
        this career, such as tuition, school or training supplies, and room and
        board. Explain how you could prepare for these costs and how you might
        make up for any shortfall.
- detail: true
  text: |-
    NOTE: Always be sure to have proper permission before using the internet.
    It is strongly advised that Scouts view the Personal Safety Awareness
    videos before starting work. Find details at <a
    href="http://www.scouting.org/training/youth-protection/scouts-bsa"
    >www.scouting.org/training/youth-protection/scouts-bsa</a>
