- requirement: 1
  markdown: true
  text: |-
      Choose A *or* B *or* C and complete ALL the requirements.
  children:
      - requirement: A
        text: |-
            Watch not less than three hours total of shows or documentaries
            that discuss genetics and/or genomics. Then do the following:
        children:
            - requirement: 1
              text: |-
                  Make a list of at least five questions or ideas from the
                  show(s) you watched.
            - requirement: 2
              text: |-
                  Discuss two of the questions or ideas with your counselor.
            - detail: true
              text: |-
                  Some examples include—but are not limited to—shows found on
                  PBS (NOVA: “Cracking the Code”), Discovery Channel, Science
                  Channel, National Geographic Channel, and TED Talks (online
                  videos). The Human Genome Institute at NIH website at
                  www.genome.gov/10000002/education/ has educational
                  information and activities related with human genetics. You
                  may choose to watch a live performance or movie developed by
                  a local science museum or state or federal agency. You may
                  watch online productions with your counselor’s approval and
                  under your parent’s or guardian’s supervision.
      - requirement: B
        text: |-
            Read (not less than three hours total) about genetics or genomics.
            Then do the following:
        children:
            - requirement: 1
              text: |-
                  Make a list of at least five questions or ideas from each
                  article.
            - requirement: 2
              text: |-
                  Discuss two of the questions or ideas with your counselor.
            - detail: true
              text: |-
                  Examples of magazines include—but are not limited to—Odyssey,
                  Popular Science, Science Illustrated, Natural History,
                  Scientific American, Nature Conservancy, Sage, The Scientist,
                  and Smithsonian. Books might include The Immortal Life of
                  Henrietta Lacks or The Gene: An Intimate History.
      - requirement: C
        text: |-
            Do a combination of reading and watching (not less than three hours
            total). Then do the following:
        children:
            - requirement: 1
              text: |-
                  Make a list of at least two questions or ideas from each
                  article or show.
            - requirement: 2
              text: |-
                  Discuss two of the questions or ideas with your counselor.
            - note:
                  - counselor
              markdown: true
              text: |-
                  Some resources that may prove useful are listed below.

                  National Institute of General Medical Sciences:
                  www.nigms.nih.gov/Pages/default.aspx

                  Your Genome—Organisms That Have Had Their Genomes Sequenced:
                  www.yourgenome.org/facts/timeline-organisms-that-have-had-their-genomes-sequenced
- requirement: 2
  markdown: true
  text: |-
      Complete one merit badge from the following list. (Choose one that you
      have not already used toward another Nova Award.) After completion,
      discuss with your counselor the genetic component of the merit badge you
      selected.

      * <a href="animal-science">Animal Science</a>
      * <a href="bird-study">Bird Study</a>
      * <a href="forestry">Forestry</a>
      * <a href="gardening">Gardening</a>
      * <a href="health-care-professions">Health Care Professions</a>
      * <a href="insect-study">Insect Study</a>
      * <a href="mammal-study">Mammal Study</a>
      * <a href="nature">Nature</a>
      * <a href="public-health">Public Health</a>
      * <a href="reptile-and-amphibian-study">Reptile and Amphibian Study</a>
      * <a href="veterinary-medicine">Veterinary Medicine</a>
- requirement: 3
  text: |-
      Complete two of the following activities:
  children:
      - requirement: A
        text: |-
            Teach the basics of genetic inheritance to your patrol (or similar
            group), using gummy bear genetics or a similar method.
      - requirement: B
        text: |-
            Extract DNA from saliva, strawberries, or a banana.
      - requirement: C
        text: |-
            Grow at least three generations of pea plants and explain the
            inheritance patterns.
      - requirement: D
        text: |-
            Create a three-dimensional model of DNA and explain how it leads to
            the production of proteins.
- requirement: 4
  text: |-
      Present a report of at least 800 words or 10 minutes (with visual aids)
      on one of the following topics. Make sure to include the ethical issues
      involved in your topic. If possible, present your report to your unit or
      another group in addition to presenting to your counselor.
  children:
      - requirement: A
        text: |-
            Mendelian inheritance, DNA, RNA, genetics, genomics, sequencing,
            and Punnett squares
      - requirement: B
        text: |-
            Genetic diseases, personalized medicine, and genetic counseling
      - requirement: C
        text: |-
            Genetically modified food, transgenic animals, and hybrid foods
      - requirement: D
        text: |-
            Use of large genetics databases for forensic analysis/solving
            crimes, genealogical research, or medical studies (The Cancer
            Genome Atlas (TCGA), Catalogue of Somatic Mutations in Cancer
            (COSMIC), Exome Aggregation Consortioum (ExAC), 100,000 Genomes
            Project, mitochondrial DNA, etc.)
      - requirement: E
        text: |-
            Pharmacogenetics and oncogenomics
      - requirement: F
        text: |-
            Human Genome Project
      - requirement: G
        text: |-
            CRISPR (Clustered Regularly-Interspaced Short Palindromic Repeats)
      - requirement: H
        text: |-
            Biotechnology, biologics, and biosimilar drugs
      - requirement: I
        text: |-
            Another related topic approved by your counselor in advance
- requirement: 5
  text: |-
      Visit a place where genetic and genomic information is being used, e.g.,
      a biotechnology company or research lab, genetic counselor, a physician’s
      office, crime lab, zoo, natural history museum, farm, hatchery,
      nursery/greenhouse, etc. Discuss the work done there with one (or more)
      of the employees. Find out how they are using genetic information, how it
      has changed their work, and what they look forward to in the future.
- requirement: 6
  text: |-
      Discuss with your counselor how genetics and genomics affect your
      everyday life and how you think it will affect your life in the future.
