- requirement: 1
  text: |-
      Do the following:
  children:
      - requirement: a
        text: |-
            Explain to your counselor the hazards you are most likely to
            encounter while wood carving, and what you should do to anticipate,
            help prevent, mitigate, or lessen these hazards.
        workbook:
            - lines: 8
      - requirement: b
        text: |-
            Show that you know first aid for injuries that could occur while
            wood carving, including minor cuts and scratches and splinters.
        workbook:
            - lines: 8
- requirement: 2
  text: |-
      Do the following:
  children:
      - requirement: a
        text: |-
            Earn the Totin’ Chip recognition.
        workbook:
            - signature: Adult Leader
              checkbox: Approved
      - requirement: b
        text: |-
            Discuss with your merit badge counselor your understanding of the
            Safety Checklist for Carving.
        workbook:
            - lines: 8
- requirement: 3
  text: |-
      Do the following:
  children:
      - requirement: a
        text: |-
            Explain to your counselor, orally or in writing, the care and use
            of five types of tools that you may use in a carving project.
        workbook:
            - lines: 8
      - requirement: b
        text: |-
            Tell your counselor how to care for and use several types of
            sharpening devices, then demonstrate that you know how to use these
            devices.
        workbook:
            - lines: 8
- requirement: 4
  text: |-
      Using a piece of scrap wood or a project on which you are working, show your merit badge counselor that you know how to do the following:
  children:
      - requirement: a
        text: |-
            Paring cut
        workbook:
            - gridHeight: 8
      - requirement: b
        text: |-
            Basic cut and push cut
        workbook:
            - gridHeight: 8
      - requirement: c
        text: |-
            “V” cut
        workbook:
            - gridHeight: 8
      - requirement: d
        text: |-
            Stop cut or score line
        workbook:
            - gridHeight: 8
- requirement: 5
  text: |-
      Tell why different woods are used for different projects.  Explain why
      you chose the type of wood you did for your projects in requirements 6
      and 7.
  workbook:
      - lines: 8
- requirement: 6
  text: |-
      Plan your own or select a project from this merit badge pamphlet and
      complete a simple carving in the round.
  workbook:
      - gridHeight: 8
- requirement: 7
  text: |-
      Complete a simple low-relief OR a chip carving project.
  workbook:
      - gridHeight: 8
