- requirement: 1
  text: |-
    Explain to your counselor the precautions that must be followed for the
    safe use and operation of a potter's tools, equipment, and other materials.
- requirement: 2
  text: |-
    Do the following:
  children:
    - requirement: a
      text: |-
        Explain the properties and ingredients of a good clay body for the
        following:
      children:
        - requirement: 1
          text: |-
            Making sculpture using the hand-building method.
        - requirement: 2
          text: |-
            Throwing on the wheel.
    - requirement: b
      text: |-
        Tell how three different kinds of potter's wheels work.
- requirement: 3
  text: |-
    Make two drawings of pottery forms, each on an 8 1/2-by-11-inch sheet of
    paper. One must be a historical pottery style. The other must be of your
    own design.
- requirement: 4
  text: |-
    Explain the meaning of the following pottery terms: bat, wedging, throwing,
    leather hard, bone dry, greenware, bisque, terra-cotta, grog, slip, score,
    earthenware, stoneware, porcelain, pyrometric cone, and glaze.
- requirement: 5
  text: |-
    Do the following. Each piece is to be painted, glazed, or otherwise
    decorated by you:
  children:
    - requirement: a
      text: |-
        Make a slab pot, a coil pot, and a pinch pot.
    - requirement: b
      text: |-
        Make a human or animal figurine or decorative sculpture.
    - requirement: c
      text: |-
        Throw a functional form on a potter's wheel.
    - requirement: d
      text: |-
        Help an experienced adult to load and fire a kiln OR describe in detail
        how to load and fire a kiln.
- requirement: 6
  text: |-
    Explain the scope of the ceramic industry in the United States. Tell some
    things made other than craft pottery.
- requirement: 7
  text: |-
    With your parent or guardian's permission and your counselor's approval, do
    ONE of the following:
  children:
    - requirement: a
      text: |-
        Visit the kiln yard at a local college or other craft school. Learn how
        the different kinds of kilns work, including low fire electric, gas or
        propane high fire, wood or salt/soda, and raku.
    - requirement: b
      text: |-
        Visit a museum, art exhibit, art gallery, artists' co-op, or artist's
        studio that features pottery. After your visit, share with your
        counselor what you have learned.
    - requirement: c
      text: |-
        Using resources from the library, magazines, the Internet (with your
        parent's permission), and other outlets, learn about the historical and
        cultural importance of pottery. Share what you discover with your
        counselor.
- requirement: 8
  text: |-
    Find out about career opportunities in pottery. Pick one and find out the
    education, training, and experience required for this profession. Discuss
    this with your counselor, and explain why this profession might interest
    you.
