- requirement: 1
  text: |-
      Explain to your counselor the precautions that must be followed for the
      safe use and operation of a potter’s tools, equipment, and other
      materials.
  workbook:
      - lines: 8
- requirement: 2
  text: |-
      Do the following:
  children:
      - requirement: a
        text: |-
            Explain the properties and ingredients of a good clay body for the
            following:
        workbook:
            - lines: 8
              text: |-
                  1. Making sculpture
            - lines: 8
              text: |-
                  2. Throwing on the wheel
        children:
            - requirement: 1
              text: |-
                  Making sculpture
              workbookHide: true
            - requirement: 2
              text: |-
                  Throwing on the wheel
              workbookHide: true
      - requirement: b
        text: |-
            Tell how three different kinds of potter’s wheels work.
        workbook:
            - lines: 8
- requirement: 3
  text: |-
      Make two drawings of pottery forms, each on an 8½-by-11-inch sheet of
      paper. One must be a historical pottery style. The other must be of your
      own design.
  workbook:
      - split:
            - area: 40
              text: |-
                  Historical pottery style
            - area: 40
              text: |-
                  Your own design
- requirement: 4
  text: |-
      Explain the meaning of the following pottery terms: bat, wedging,
      throwing, leather hard, bone dry, greenware, bisque, terra-cotta, grog,
      slip, score, earthenware, stoneware, porcelain, pyrometric cone, and
      glaze.
  workbook:
      - lines: 3
        text: |-
            Bat
      - lines: 3
        text: |-
            Wedging
      - lines: 3
        text: |-
            Leather hard
      - lines: 3
        text: |-
            Bone dry
      - lines: 3
        text: |-
            Greenware
      - lines: 3
        text: |-
            Bisque
      - lines: 3
        text: |-
            Terra-cotta
      - lines: 3
        text: |-
            Grog
      - lines: 3
        text: |-
            Slip
      - lines: 3
        text: |-
            Score
      - lines: 3
        text: |-
            Earthenware
      - lines: 3
        text: |-
            Stoneware
      - lines: 3
        text: |-
            Porcelain
      - lines: 3
        text: |-
            Pyrometric cone
      - lines: 3
        text: |-
            Glaze
- requirement: 5
  text: |-
      Do the following. Each piece is to be painted, glazed, or otherwise
      decorated by you:
  children:
      - requirement: a
        text: |-
            Make a slab pot, a coil pot, and a pinch pot.
        workbook:
            - task: true
      - requirement: b
        text: |-
            Make a human or animal figurine or decorative sculpture.
        workbook:
            - task: true
      - requirement: c
        text: |-
            Throw a functional form on a potter’s wheel.
        workbook:
            - task: true
      - requirement: d
        text: |-
            Help to fire a kiln.
        workbook:
            - task: true
- requirement: 6
  text: |-
      Explain the scope of the ceramic industry in the United States.  Tell
      some things made other than craft pottery.
  workbook:
      - lines: 8
- requirement: 7
  text: |-
      With your parent’s permission and your counselor’s approval, do ONE of
      the following:
  workbook:
      - header: true
        markdown: true
        text: |-
            a. Visit the kiln yard at a local college or other craft school.
            Learn how the different kinds of kilns work, including low fire
            electric, gas or propane high fire, wood or salt/soda, and raku.

            b. Visit a museum, art exhibit, art gallery, artists’ co-op, or
            artist’s studio that features pottery. After your visit, share with
            your counselor what you have learned.

            c. Using resources from the library, magazines, the Internet (with
            your parent’s permission), and other outlets, learn about the
            historical and cultural importance of pottery.  Share what you
            discover with your counselor.
      - lines: 8
  children:
      - requirement: a
        text: |-
            Visit the kiln yard at a local college or other craft school.
            Learn how the different kinds of kilns work, including low fire
            electric, gas or propane high fire, wood or salt/soda, and raku.
        workbookHide: true
      - requirement: b
        text: |-
            Visit a museum, art exhibit, art gallery, artists’ co-op, or
            artist’s studio that features pottery. After your visit, share with
            your counselor what you have learned.
        workbookHide: true
      - requirement: c
        text: |-
            Using resources from the library, magazines, the Internet (with
            your parent’s permission), and other outlets, learn about the
            historical and cultural importance of pottery.  Share what you
            discover with your counselor.
        workbookHide: true
- requirement: 8
  text: |-
      Find out about career opportunities in pottery. Pick one and find out the
      education, training, and experience required for this profession. Discuss
      this with your counselor, and explain why this profession might interest
      you.
  workbook:
      - lines: 8
