- requirement: 1
  text: |-
    Demonstrate to your counselor that you have current knowledge of all
    first-aid requirements for Tenderfoot, Second Class, and First Class
    ranks.
- requirement: 2
  text: |-
    Explain how you would obtain emergency medical assistance from:
  children:
    - requirement: a
      text: |-
        Your home
    - requirement: b
      text: |-
        A remote location on a wilderness camping trip
- requirement: 3
  markdown: true
  text: |-
    Define the term *triage*. Explain the steps necessary to assess and
    handle a medical emergency until help arrives.
- requirement: 4
  text: |-
    Explain the precautions you must take to reduce the risk of transmitting an
    infection between you and the victim while administering first aid.
- requirement: 5
  text: |-
    Do the following:
  children:
    - requirement: a
      text: |-
        Prepare a first-aid kit for your home. Display and discuss its
        contents with your counselor.
    - requirement: b
      text: |-
        With an adult leader, inspect your troop’s first-aid kit. Evaluate
        it for completeness. Report your findings to your counselor and
        Scout leader.
- requirement: 6
  text: |-
    Describe the early signs and symptoms of each of the following and
    explain what actions you should take:
  children:
    - requirement: a
      text: |-
        Shock
    - requirement: b
      text: |-
        Heart attack
    - requirement: c
      text: |-
        Stroke
- requirement: 7
  text: |-
    Do the following:
  children:
    - requirement: a
      text: |-
        Describe the conditions that must exist before performing CPR on a
        person.
    - requirement: b
      text: |-
        Demonstrate proper CPR technique using a training
        device approved by your counselor.
    - requirement: c
      text: |-
        Explain the use of an automated external defibrillator (AED).
    - requirement: d
      text: |-
        Demonstrate or simulate the proper use of an automated external
        defibrillator (AED), using an AED training device if available.
    - requirement: e
      text: |-
        Identify the location of the AED at your school, place of worship,
        and troop meeting place, if one is present.
- requirement: 8
  text: |-
    Do the following:
  children:
    - requirement: a
      text: |-
        Show the steps that need to be taken for someone who has a large
        open wound or cut that is not bleeding severely.
    - requirement: b
      text: |-
        Show the steps that need to be taken for someone who has a large
        open wound or cut that is severely bleeding.
    - requirement: c
      text: |-
        Explain when it is appropriate and not appropriate to use a
        tourniquet. List some of the benefits and dangers of the use of a
        tourniquet.
    - requirement: d
      text: |-
        Demonstrate the application of a tourniquet without tightening it.
- requirement: 9
  text: |-
    Explain when an insect or bee sting could be life threatening and what action should
    be taken for prevention and for first aid.
- requirement: 10
  text: |-
    Describe the signs, symptoms, and potential complications of a fracture and
    dislocation.
- requirement: 11
  # Lowercased "fingers"  in c for consistency
  text: |-
    Demonstrate the proper procedures for handling and immobilizing suspected
    closed or open fractures or dislocations of the:
  children:
    - requirement: a
      text: |-
        Finger
    - requirement: b
      text: |-
        Forearm
    - requirement: c
      text: |-
        Wrist
    - requirement: d
      text: |-
        Upper leg
    - requirement: e
      text: |-
        Lower leg
    - requirement: f
      text: |-
        Ankle
- requirement: 12
  text: |-
    Describe the signs, symptoms, and possible complications and demonstrate
    care for someone with a suspected injury to the neck or back.
- requirement: 13
  text: |-
    Describe the symptoms, proper first-aid procedures, and possible prevention
    measures for the following conditions:
  children:
    - requirement: a
      text: |-
        Concussion
    - requirement: b
      text: |-
        Anaphylaxis/allergic reactions
    - requirement: c
      text: |-
        Asthma attack
    - requirement: d
      text: |-
        Bruises
    - requirement: e
      text: |-
        Sprains or strains
    - requirement: f
      text: |-
        Hypothermia
    - requirement: g
      text: |-
        Frostbite
    - requirement: h
      text: |-
        Burns-first, second, and third degree
    - requirement: i
      text: |-
        Convulsions/seizures
    - requirement: j
      text: |-
        Dehydration
    - requirement: k
      text: |-
        Muscle cramps
    - requirement: l
      text: |-
        Heat exhaustion
    - requirement: m
      text: |-
        Heat stroke
    - requirement: n
      text: |-
        Abdominal pain
    - requirement: o
      text: |-
        Broken, chipped, or loosened tooth
- requirement: 14
  text: |-
    Do the following:
  children:
    - requirement: a
      text: |-
        Describe the conditions under which an injured person should be
        moved.
    - requirement: b
      text: |-
        If a sick or an injured person must be moved, tell how you would
        determine the best method.  Demonstrate this method.
    - requirement: c
      text: |-
        With helpers under your supervision, improvise a stretcher and move
        a presumably unconscious person.
- requirement: 15
  text: "Describe the following:"
  children:
      - requirement: a
        text: |-
            The indications that someone might be a danger to themselves or others.
      - requirement: b
        text: |-
            What action you should take if you suspect that someone might be a
            danger to themselves or others.
- requirement: 16
  text: |-
    Teach another Scout a first-aid skill selected by your counselor.
