- requirement: 1
  text: |-
    Do the following:
  children:
    - requirement: a
      text: |-
        Explain to your counselor the most likely hazards you may encounter
        while participating in whitewater activities, including branches and
        trees in water along a shore and stretching across the stream, rocks,
        hydraulics over ledges or lowhead dams, strong wind, low water or air
        temperature, and thunder and lightning storms. Explain what you should
        do to anticipate, help prevent, mitigate, and respond to these hazards.
    - requirement: b
      text: |-
        Review with your counselor the prevention, symptoms, and first aid
        treatment for the following injuries or illnesses that could occur
        while participating in whitewater activities including cold-water
        shock; hypothermia; head, neck, and back injuries; heat-related
        illnesses; sunburn; dehydration; blisters; bruises; cuts; sprains and
        strains; shoulder dislocation; and submersion injuries.
    - requirement: c
      text: |-
        Discuss with your counselor the Scouting America Safety Afloat policy
        and the American Whitewater safety guidelines, including the use of
        helmet and life jackets.
- requirement: 2
  text: |-
    Do the following:
  children:
    - requirement: a
      text: |-
        Demonstrate understanding of the following river features by drawing
        lines to show the flow of water: upstream V, downstream V, riffle, eddy
        with an eddy line, ledge, river bend, shallows, current at different
        depths, drop, horizon line, hydraulic.
    - requirement: b
      text: |-
        Describe how waves form including standing waves and wave trains.
    - requirement: c
      text: |-
        Explain how to tilt or edge the boat without leaning your body
      children:
        - requirement: 1
          text: |-
            When entering and exiting an eddy.
        - requirement: 2
          text: |-
            When ferrying in downstream and upstream directions.
    - requirement: d
      text: |-
        Explain when, why, and how you should scout a river while ashore, while
        on the river, and when you should portage your boat.
- requirement: 3
  markdown: true
  text: |-
    Before doing requirements 4 through 12, earn the <a
    href="/merit-badges/canoeing/">Canoeing</a> merit badge if you will be
    using a canoe to earn this merit badge. If you will be using a kayak,
    earn the <a href="/merit-badges/kayaking/">Kayaking</a> merit badge. Then
    do ONE of the following:
  children:
    - requirement: a
      markdown: true
      text: |-
        If you will be using a canoe to earn this merit badge, demonstrate
        strokes and maneuvers from the <a
        href="/merit-badges/canoeing/">Canoeing</a> merit badge to the
        satisfaction of your counselor.
    - requirement: b
      markdown: true
      text: |-
        If you will be using a kayak to earn this merit badge, demonstrate
        strokes and maneuvers from the <a
        href="/merit-badges/kayaking/">Kayaking</a> merit badge to the
        satisfaction of your counselor.
- requirement: 4
  text: |-
    Do ONE of the following:
  children:
    - requirement: a
      markdown: true
      text: |-
        <b>Option A: Tandem Canoest.</b> (perform the following on calm water):
      children:
        - requirement: 1
          text: |-
            Demonstrate the following strokes in the bow: cross forward, bow
            draw, cross bow draw, bow pry, and sculling draw.
        - requirement: 2
          text: |-
            Demonstrate the following strokes in the stern: stern draw, stern
            pry, sculling draw, and forward with stern pry.
        - requirement: 3
          text: |-
            Demonstrate a high brace, low brace, and righting pry.
    - requirement: b
      markdown: true
      text: |-
        <b>Option B: Solo Canoest.</b> (perform the following on calm water):
      children:
        - requirement: 1
          text: |-
            Demonstrate the following strokes: cross forward, bow draw, cross
            bow draw, stern draw, pry, stern pry, sculling draw, and forward
            with stern pry.
        - requirement: 2
          text: |-
            Demonstrate a high brace, low brace, and righting pry.
    - requirement: c
      markdown: true
      text: |-
        <b>Option C: Solo Kayaker.</b> (perform the following on calm water):
      children:
        - requirement: 1
          text: |-
            Demonstrate the following strokes: bow draw, rudder, and sculling
            draw.
        - requirement: 2
          text: |-
            Demonstrate a high brace and low brace.
- requirement: 5
  text: |-
    Do the following:
  children:
    - requirement: a
      text: |-
        Explain the International Scale of River Difficulty and apply the scale
        to the stretch of river approved by your counselor.
    - requirement: b
      text: |-
        Identify the specific characteristics of the river that are factors in
        your classification according to the International Scale.
    - requirement: c
      text: |-
        Discuss how the level of flow changes a river from one class to another
        and what effects different flow rates have on the features of a river
        and its hazards.
- requirement: 6
  text: |-
    Explain the importance of communication during every whitewater outing.
    Demonstrate knowledge and ability to use the following American Whitewater
    Universal River Signals, both visual and auditory: "Stop," "Are you OK?,"
    "Help/emergency," "Run river right," "Run river left," "All clear-come
    ahead."
- requirement: 7
  text: |-
    Do ONE of the following:
  children:
    - requirement: a
      text: |-
        If completing this merit badge in a canoe, describe the various types
        of canoes used on moving water and how they differ in design,
        materials, and purpose.
    - requirement: b
      text: |-
        If completing this merit badge in a kayak, describe the various types
        of kayaks used on moving water and explain how they differ in design,
        materials, and purpose.
- requirement: 8
  text: |-
    Review with your counselor the personal and group equipment necessary for a
    safe whitewater outing and how and why it is used.
- requirement: 9
  text: |-
    Demonstrate your ability to read a Class II section of river approved by
    your counselor. Describe the most desirable paths or lines of travel as
    well as alternative routes and options. Point out how to use the existing
    water features to your advantage, and explain how to best avoid the hazards
    present.
- requirement: 10
  text: |-
    Wearing a proper life jacket and being appropriately dressed for the
    weather and water conditions, perform the following skills in moving water
    in a properly equipped whitewater craft of your choice (tandem canoe, solo
    canoe, or solo kayak).  If a tandem canoe is used, the skills must be
    demonstrated from both the bow and stern positions.
  children:
    - requirement: a
      text: |-
        Launch and land.
    - requirement: b
      text: |-
        Paddle forward in a straight line at least 10 boat lengths.
    - requirement: c
      text: |-
        Backpaddle in a straight line at least five boat lengths.
    - requirement: d
      text: |-
        Ferry upstream from both sides of the river.
    - requirement: e
      text: |-
        Ferry downstream from both sides of the river.
    - requirement: f
      text: |-
        Eddy turn from both sides of an eddy.
    - requirement: g
      text: |-
        Peel out from both sides of an eddy.
- requirement: 11
  text: |-
    Explain and demonstrate the following to your counselor:
  children:
    - requirement: a
      text: |-
        Self-rescue and procedures when capsized in moving water, including a
        wet exit if necessary
    - requirement: b
      text: |-
        Proper use of a throw rope to rescue a swimmer in whitewater
    - requirement: c
      text: |-
        Proper technique for receiving a throw rope as a swimmer
    - requirement: d
      text: |-
        Portaging-where portaging would be appropriate, and when and how to do
        it
    - requirement: e
      text: |-
        The whitewater buddy system using at least three persons and three
        craft.
- requirement: 12
  text: |-
    Participate in one or more whitewater trips using either a canoe or kayak
    on a Class I and/or Class II river. The trip(s) must involve at least six
    hours of paddling time. For each trip:
  children:
    - requirement: a
      text: |-
        Help to prepare a written plan, specifying the route (put-ins and
        takeouts), schedule, equipment, safety precautions, and emergency
        procedures.
    - requirement: b
      text: |-
        Determine local rules and obtain permission from landowners and land
        managers in advance.
    - requirement: c
      text: |-
        Explain what steps have been taken to comply with Scouting America
        Safety Afloat and the American Whitewater safety guidelines.
    - requirement: d
      text: |-
        Show how to protect personal and group equipment from water and how to
        load and secure the containers in boats to be used in the trip. Execute
        the plans with other paddlers.
    - requirement: e
      text: |-
        Explain to your counselor how well your plans worked for each trip
        taken.
