- requirement: 1
  text: |-
    Do the following:
  children:
    - requirement: a
      text: |-
        Explain to your counselor the most likely hazards you may encounter
        while participating in climbing and rappelling activities and what
        you should do to anticipate, help prevent, mitigate, and respond to
        these hazards.
    - requirement: b
      text: |-
        Show that you know first aid for and how to prevent injuries or
        illnesses that could occur during climbing activities, including
        heat and cold reactions, dehydration, stopped breathing, sprains,
        abrasions, fractures, rope burns, blisters, snakebite, concussions,
        and insect bites or stings.
    - requirement: c
      text: |-
        Identify the conditions that must exist before performing CPR on a
        person.
- requirement: 2
  text: |-
    Learn the Leave No Trace principles and Outdoor Code, and explain what
    they mean.
- requirement: 3
  text: |-
    Present yourself properly dressed for belaying, climbing, and rappelling
    (i.e., appropriate clothing, footwear, and a helmet; rappellers can also
    wear gloves).
- requirement: 4
  markdown: true
  text: |-
    **Location.** Do the following:
  children:
    - requirement: a
      text: |-
        Explain how the difficulty of climbs is classified, and apply
        classifications to the rock faces or walls where you will
        demonstrate your climbing skills.
    - requirement: b
      text: |-
        Explain the following: top-rope climbing, lead climbing, and
        bouldering.
    - requirement: c
      text: |-
        Evaluate the safety of a particular climbing area.  Consider
        weather, visibility, the condition of the climbing surface, and any
        other environmental hazards.
    - requirement: d
      text: |-
        Determine how to summon aid to the climbing area in case of an
        emergency.
- requirement: 5
  markdown: true
  text: |-
    **Verbal signals.** Explain the importance of using verbal signals during
    every climb and rappel, and while bouldering. With the help of the merit
    badge counselor or another Scout, demonstrate the verbal signals used by
    each of the following:
  children:
    - requirement: a
      text: |-
        Climbers
    - requirement: b
      text: |-
        Rappellers
    - requirement: c
      text: |-
        Belayers
    - requirement: d
      text: |-
        Boulderers and their spotters
- requirement: 6
  markdown: true
  text: |-
    **Rope.** Do the following:
  children:
    - requirement: a
      text: |-
        Describe the kinds of rope acceptable for use in climbing and
        rappelling.
    - requirement: b
      text: |-
        Show how to examine a rope for signs of wear or damage.
    - requirement: c
      text: |-
        Discuss ways to prevent a rope from being damaged.
    - requirement: d
      text: |-
        Explain when and how a rope should be retired.
    - requirement: e
      text: |-
        Properly coil a rope.
- requirement: 7
  markdown: true
  text: |-
    **Knots.** Demonstrate the ability to tie each of the following knots.
    Give at least one example of how each knot is used in belaying, climbing,
    or rappelling.
  children:
    - requirement: a
      text: |-
        Figure eight on a bight
    - requirement: b
      text: |-
        Figure eight follow-through
    - requirement: c
      text: |-
        Water knot
    - requirement: d
      text: |-
        Double fisherman’s knot (grapevine knot)
    - requirement: e
      text: |-
        Safety knot
- requirement: 8
  markdown: true
  text: |-
    **Harnesses.** Correctly put on a commercially made climbing harness.
- requirement: 9
  markdown: true
  text: |-
    **Belaying.** Do the following:
  children:
    - requirement: a
      text: |-
        Explain the importance of belaying climbers and rappellers and when
        it is necessary.
    - requirement: b
      text: |-
        Belay three different climbers ascending a rock face or climbing
        wall.
    - requirement: c
      text: |-
        Belay three different rappellers descending a rock face or climbing
        wall using a top rope.
- requirement: 10
  markdown: true
  text: |-
    **Climbing.** Do the following:
  children:
    - requirement: a
      text: |-
        Show the correct way to directly tie into a belay rope.
    - requirement: b
      text: |-
        Climb at least three different routes on a rock face or climbing
        wall, demonstrating good technique and using verbal signals with a
        belayer.
- requirement: 11
  markdown: true
  text: |-
    **Rappelling.** Do the following:
  children:
    - requirement: a
      text: |-
        Using a carabiner and a rappel device, secure your climbing harness
        to a rappel rope.
    - requirement: b
      text: |-
        Tie into a belay rope set up to protect rappellers.
    - requirement: c
      text: |-
        Rappel down three different rock faces or three rappel routes on a
        climbing wall. Use verbal signals to communicate with a belayer,
        and demonstrate good rappelling technique.
- requirement: 12
  text: |-
    Demonstrate ways to store rope, hardware, and other gear used for
    climbing, rappelling, and belaying.
