- requirement: 1
  text: |-
      Show your counselor your current, up-to-date Cyber Chip.
  workbook:
      - task: true
  children:
      - note:
            - inPerson
            - online
        text: |-
            It is strongly recommended and encouraged that Scouts complete
            their Cyber Chip requirements (age appropriate) ahead of time and
            bring their current / recharged Cyber Chip proof with them to
            class. It is not acceptable to just say you have your Cyber Chip,
            you must bring proof.  Some counselors may choose to integrate this
            requirement into the instruction at the class, but Scouts will find
            having it done ahead of time is best. If time allows, the counselor
            MAY offer the chance to complete parts of the Cyber Chip at the end
            of the class, this of course is at the discretion of the counselor.
- requirement: 2
  text: |-
      Do the following:
  children:
      - requirement: a
        text: |-
            Give a brief history of the changes in digital technology over
            time. Discuss with your counselor how digital technology in your
            lifetime compares with that of your parent’s, grandparent’s, or
            other adult’s lifetime.
        workbook:
            - lines: 8
              text: |-
                  Brief history of the changes in digital technology over time
            - lines: 8
              text: |-
                  How digital technology in your lifetime compares with that of
                  your parent's, grandparent's, or other adult's lifetime
        children:
            - note:
                  - inPerson
                  - online
              text: |-
                  Scouts should make notes to assist them with the discussion
                  component of this requirement.  Scouts will only be able to
                  complete this component of Requirement 2 if they come to the
                  class having talked to some adults and how digital technology
                  has changed in their lifetimes. It is strongly recommended
                  that Scouts bring any notes or supporting documents they may
                  have to help show the counselor that they have prepared for
                  discussion of this requirement. Only Scouts who have done the
                  preparation work and actively participate in the class
                  discussion will be considered for sign off on this part of
                  the requirement.
      - requirement: b
        text: |-
            Describe what kinds of computers or devices you imagine might be
            available when you are an adult.
        workbook:
            - lines: 8
        children:
            - note:
                  - inPerson
                  - online
              text: |-
                  Scouts will be required to share their thoughts as this part
                  of the requirement states. Only Scouts who participate
                  actively in the group discussion will be signed off on this
                  part of the requirement. This not a listening only
                  requirement.
- requirement: 3
  text: |-
      Do the following:
  children:
      - requirement: a
        text: |-
            Explain to your counselor how text, sound, pictures, and videos are
            digitized for storage.
        workbook:
            - lines: 8
              text: |-
                  How text is digitized for storage
            - lines: 8
              text: |-
                  How sound is digitized for storage
            - lines: 8
              text: |-
                  How pictures are digitized for storage
            - lines: 8
              text: |-
                  How videos are digitized for storage
      - requirement: b
        text: |-
            Describe the difference between lossy and lossless data
            compression, and give an example where each might be used.
        workbook:
            - lines: 8
              text: |-
                  Difference between lossy and lossless data compression
            - lines: 8
              text: |-
                  An example where each might be used
      - requirement: c
        text: |-
            Describe two digital devices and how they are made more useful by
            their programming.
        workbook:
            - lines: 8
            - lines: 8
      - requirement: d
        text: |-
            Discuss the similarities and differences between computers, mobile
            devices, and gaming consoles.
        workbook:
            - lines: 8
      - requirement: e
        text: |-
            Explain what a computer network is and describe the network’s
            purpose.
        workbook:
            - lines: 8
      - note:
            - inPerson
            - online
        text: |-
            Scouts will need to do some research and reading in order to
            prepare for this requirement.  It is recommended that Scouts make
            notes of their findings to help show the counselor their efforts in
            preparing for the class.  These notes can also serve to help Scouts
            successfully perform their explanation or discussion elements of
            this requirement. It will be very difficult for Scouts who do not
            come prepared for this requirement to successfully complete the
            requirement in the class.
- requirement: 4
  text: |-
      Do the following:
  children:
      - requirement: a
        text: |-
            Explain what a program or software application or “app” is and how
            it is created.
        workbook:
            - lines: 8
      - requirement: b
        text: |-
            Name four software programs or mobile apps you or your family use,
            and explain how each one helps you.
        workbook:
            - lines: 8
            - lines: 8
            - lines: 8
            - lines: 8
      - requirement: c
        text: |-
            Describe what malware is, and explain how to protect your digital
            devices and the information stored on them.
        workbook:
            - lines: 8
      - note:
            - inPerson
            - online
        text: |-
            While the counselor will help mentor in the class, Scouts should
            have reviewed the merit badge pamphlet and any other sources they
            have access to in order to best build their knowledge for
            completing this requirement in the class.  Scouts will be required
            to actively partake in providing explanations on all components of
            this requirement in one-on-one discussion with the counselor and/or
            with the class group environment.
- requirement: 5
  text: |-
      Do the following:
  children:
      - requirement: a
        text: |-
            Describe how digital devices are connected to the internet.
        workbook:
            - lines: 8
      - requirement: b
        text: |-
            Using an internet search engine (with a parent or guardian’s
            permission),find ideas from at least three different websites about
            how to conduct a troop court of honor or campfire program. Present
            the ideas to your counselor and explain how you used a search
            engine to find this information.
        workbook:
            - lines: 8
      - requirement: c
        text: |-
            Use a web browser to connect to an HTTPS (secure) website (with
            your parent’s permission). Explain to your counselor how to tell
            whether the site’s security certificate can be trusted, and what it
            means to use this kind of connection.
        workbook:
            - lines: 8
      - note:
            - inPerson
            - online
        text: |-
            While most of this requirement will be completed in the class,
            Scout's must still do some preparation work.  Ideally bring a note
            or signed statement from a parent (as a couple of the components
            reference) validating you have worked on this requirement to the
            best of your ability prior to the class to prepare for completion.
- requirement: 6
  text: |-
      Do THREE of the following. For each project you complete, copy the files
      to a backup device and share the finished projects with your counselor.
  children:
      - requirement: a
        text: |-
            Using a spreadsheet or database program, develop a food budget for
            a patrol weekend campout OR create a troop roster that includes the
            name, rank, patrol, and telephone number of each Scout. Show your
            counselor that you can sort the roster by each of the following
            categories: rank, patrol, and alphabetically by name.
        workbook:
            - task: true
      - requirement: b
        text: |-
            Using a word processor, write a draft letter to the parents of your
            troop’s Scouts, inviting them to a troop event.
        workbook:
            - task: true
      - requirement: c
        text: |-
            Using a graphics program, design and draw a campsite plan for your
            troop OR create a flier for an upcoming troop event, incorporating
            text and some type of visual such as a photograph or an
            illustration.
        workbook:
            - task: true
      - requirement: d
        text: |-
            Using a presentation software program, develop a report about a
            topic approved by your counselor. For your presentation, create at
            least five slides, with each one incorporating text and some type
            of visual such as a photograph or an illustration.
        workbook:
            - task: true
      - requirement: e
        text: |-
            Using a digital device, take a picture of a troop activity.  Send
            or transfer this image to a device where it can be shared with your
            counselor.
        workbook:
            - task: true
      - requirement: f
        text: |-
            Make a digital recording of your voice, transfer the file to a
            different device, and have your counselor play back the recording.
        workbook:
            - task: true
      - requirement: g
        text: |-
            Create a blog and use it as an online journal of your Scouting
            activities, including group discussions and meetings, campouts, and
            other events. Include at least five entries and two photographs or
            illustrations.  Share your blog with your counselor. You need not
            post the blog to the internet; however, if you choose to go live
            with your blog, you must first share it with your parents AND
            counselor AND get their approval.
        workbook:
            - task: true
      - requirement: h
        text: |-
            Create a webpage for your troop, patrol, school, or place of
            worship. Include at least three articles and two photographs or
            illustrations. Include at least one link to a website of interest
            to your audience. You need not post the page to the internet;
            however, if you decide to do so, you must first share the webpage
            with your parents AND counselor AND get their approval.
        workbook:
            - task: true
      - note:
            - inPerson
            - online
        text: |-
            Scouts will need to come to the class with these items already in
            the works, if not already completed.  Time will be allotted in the
            class to review any of these components that Scouts have completed
            or are nearly completed with for consideration by the counselor for
            sign off.  Some of the concepts required for these different
            components may be demonstrated and discussed for general knowledge
            purposes within the class.
- requirement: 7
  text: |-
      Do the following:
  children:
      - requirement: a
        text: |-
            Explain to your counselor each of these protections and why they
            exist: copyright, patents, trademarks, trade secrets.
        workbook:
            - lines: 8
              text: |-
                  Copyright
            - lines: 8
              text: |-
                  Patents
            - lines: 8
              text: |-
                  Trademarks
            - lines: 8
              text: |-
                  Trade secrets
      - requirement: b
        text: |-
            Explain when it is permissible to accept a free copy of a program
            from a friend.
        workbook:
            - lines: 8
      - requirement: c
        text: |-
            Discuss with your counselor an article or a news report about a
            recent legal case involving an intellectual property dispute.
        workbook:
            - lines: 8
      - note:
            - inPerson
            - online
        text: |-
            Scouts should review this requirement and its components and be
            prepared to explain.  It is strongly recommended that Scouts bring
            any notes or supporting documents they may have to help show the
            counselor that they have prepared for discussion of these items.
- requirement: 8
  text: |-
      Do TWO of the following:
  children:
      - requirement: a
        text: |-
            Describe why it is important to properly dispose of digital
            technology. List at least three dangerous chemicals that could be
            used to create digital devices or used inside a digital device.
        workbook:
            - lines: 8
              text: |-
                  Why it is important to properly dispose of digital technology
            - lines: 8
              text: |-
                  At least three dangerous chemicals that could be used to
                  create digital devices or used inside a digital device
      - requirement: b
        text: |-
            Explain to your counselor what is required to become a certified
            recycler of digital technology hardware or devices.
        workbook:
            - lines: 8
      - requirement: c
        text: |-
            Do an internet search for an organization that collects discarded
            digital technology hardware or devices for repurposing or
            recycling. Find out what happens to that waste. Share with your
            counselor what you found.
        workbook:
            - lines: 8
      - requirement: d
        text: |-
            Visit a recycling center that disposes of digital technology
            hardware or devices. Find out what happens to that waste. Share
            what you learned with your counselor.
        workbook:
            - lines: 8
      - requirement: e
        text: |-
            Find a battery recycling center near you and find out what it does
            to recycle batteries. Share what you have learned with your
            counselor about the proper methods for recycling batteries.
        workbook:
            - lines: 8
      - note:
            - inPerson
            - online
        text: |-
            Scouts will need to come to the class with these items already in
            the works, if not already completed.  Time will be allotted in the
            class to review any of these components that Scouts have completed
            or are nearly completed with for consideration by the counselor for
            sign off.  Some of the concepts required for these different
            components may be demonstrated and discussed for general knowledge
            purposes within the class.
- requirement: 9
  text: |-
      Do ONE of the following:
  children:
      - requirement: a
        text: |-
            Investigate three career opportunities that involve digital
            technology. Pick one and find out the education, training, and
            experience required for this profession. Discuss this with your
            counselor, and explain why this profession might interest you.
        workbook:
            - lines: 8
              text: |-
                  Three career opportunities that involve digital technology
            - lines: 8
              text: |-
                  Education, training, and experience required for one
                  profession
      - requirement: b
        text: |-
            Visit a business or an industrial facility that uses digital
            technology. Describe four ways digital technology is being used
            there. Share what you learned with your counselor.
        workbook:
            - lines: 8
      - note:
            - inPerson
            - online
        text: |-
            Scouts should review this requirement and choose one of the two
            components and be prepared to discuss during the class.
