# PDF has lots of extra stuff from Animal Science, American Business, Family Life, Environmental Science, Geology, and perhaps others
- requirement: 1
  text: |-
    Do the following:
  children:
    - requirement: a
      text: |-
        Select 10 different minerals. For each one, name a product for
        which the mineral is used.
    - requirement: b
      text: |-
        Explain the role mining has in producing and processing things that
        are grown.
    - requirement: c
      text: |-
        From the list of minerals you chose for requirement 1a, determine
        the countries where those minerals can be found, and discuss what
        you learned from your counselor.
- requirement: 2
  text: |-
    Obtain a map of your state or region showing major cities, highways,
    rivers, and railroads. Mark the locations of five mining enterprises.
    Find out what resource is processed at each location, and identify the
    mine as a surface or underground operation. Discuss with your counselor
    how the resources mined at these locations are used.
- requirement: 3
  text: |-
    Discuss with your counselor the potential hazards a miner may encounter
    at an active mine and the protective measures used by miners. In your
    discussion, explain how:
  children:
    - requirement: a
      text: |-
        The miner’s personal protective equipment is worn and used,
        including a hard hat, safety glasses, earplugs, dust mask or
        respirator, self-rescue device, and high-visibility vest.
    - requirement: b
      text: |-
        Miners protect their hands and feet from impact, pinch, vibration,
        slipping, and tripping/falling hazards.
    - requirement: c
      text: |-
        Monitoring equipment warns miners of imminent danger, and how
        robots, drones  and other technology may be used in mine rescues.
- requirement: 4
  # Fixed typos in "counselor" and "encounter"
  text: |-
    Discuss with your counselor the dangers someone might encounter at an
    abandoned mine or quarry.
- requirement: 5
  text: |-
    Do ONE of the following:
  children:
    - requirement: a
      text: |-
        With your parent or guardian’s approval and your counselor’s assistance, use
        the internet to find and take a virtual tour of two types of mines.
        Determine the similarities and differences between them regarding
        resource exploration, mine planning, and permitting, types of
        equipment used, and the minerals produced. Discuss with your
        counselor what you learned from your internet-based mine tours.
    - requirement: b
      text: |-
        With your parent or guardian’s permission and counselor’s approval, visit a
        mining or minerals exhibit at a museum. Find out about the history
        of the museum’s exhibit and the type of mining it represents. Give
        three examples of how mineral resources have influenced history.
    - requirement: c
      markdown: true
      text: |-
        With your parent or guardian’s permission and counselor’s approval, visit an
        active mine.`*` Find out about the tasks required to explore, plan,
        permit, mine, and process the resource mined at that site. Take
        photographs if allowed, and request brochures from your visit.
        Share photos, brochures, and what you have learned with your
        counselor.
    - requirement: d
      markdown: true
      text: |-
        With your parent or guardian’s permission and counselor’s approval, visit a
        mining equipment manufacturer or supplier.`*` Discuss the types of
        equipment produced or supplied there, and in what part of the
        mining process this equipment is used. Take photographs if allowed,
        and request brochures from your visit. Share photos, brochures, and
        what you have learned with your counselor.
    - requirement: e
      text: |-
        Discuss with your counselor two methods used to reduce rock in
        size, one of which uses a chemical process to extract a mineral.
        Explain the difference between smelting and refining.
    - requirement: f
      text: |-
        Learn about the history of a local mine, including what is or was
        mined there, how the deposit was found, the mining techniques and
        processes used, and how the mined resource is or was used. Find out
        from a historian, community leader, or business person how mining
        has affected your community.  Note any social, cultural, or
        economic consequences of mining in your area. Share what you have
        learned with your counselor.
    - detail: true
      markdown: true
      text: |-
        `*` Visiting a mine site, a mining equipment manufacturer, or an
        equipment supplier requires advance planning.  These sites can be
        potentially dangerous. You will need permission from your parent
        and counselor, and the manager of the mine site, or equipment
        manufacturer or supplier. While there, you will be required to
        follow closely the site manager’s instructions and comply with all
        safety rules and procedures, including wearing appropriate
        clothing, footwear, and personal safety equipment.
- requirement: 6
  text: |-
    Do the following:
  children:
    - requirement: a
      text: |-
        Choose a modern mining site. Find out what is being done to help
        control environmental impacts. Share what you have learned about
        mining and sustainability.
    - requirement: b
      text: |-
        Explain reclamation as it is used in mining and how mine
        reclamation pertains to Scouting’s no-trace principles.
    - requirement: c
      text: |-
        Discuss with your counselor what values society has about returning
        the land to the benefit of wildlife and people after mining has
        ended. Discuss the transformation of the BSA Summit Bechtel Family
        National Scout Reserve from a mine site to its current role.
- requirement: 7
  text: |-
    Do ONE of the following:
  children:
    - requirement: a
      text: |-
        Explore the anticipated benefits of interplanetary mining.  Learn
        how NASA and private investors may search for, extract, and process
        minerals in outer space, and the primary reasons for mining the
        moon, other planets, or near-Earth asteroids. Find out how
        exploration and mineral processing in space differ from exploration
        on Earth. Share what you have learned with your counselor, and
        discuss the difficulties encountered in exploring, collecting, and
        analyzing surface or near-surface samples in space.
    - requirement: b
      text: |-
        Identify three minerals found dissolved in seawater or found on the
        ocean floor, and list three places where the ocean is mined today.
        Share this information with your counselor, and discuss the chief
        incentives for mining the oceans for minerals, the reclamation
        necessary after mining is over, and any special concerns when
        mining minerals from the ocean.  Find out what sustainability
        problems arise from mining the oceans. Discuss what you learn with
        your counselor.
    - requirement: c
      text: |-
        Learn what metals and minerals are recycled after their original
        use has ended. List four metals and two nonmetals, and find out how
        each can be recycled. Find out how recycling affects the
        sustainability of natural resources and how this idea is related to
        mining. Discuss what you learn with your counselor.
    - requirement: d
      text: |-
        With your parent or guardian’s permission, use the internet and other resources
        to determine the current price of gold, copper, aluminum, or other
        commodities like cement or coal, and find out the five-year price
        trend for two of these. Report your findings to your counselor.
- requirement: 8
  text: |-
    Do ONE of the following:
  children:
    - requirement: a
      text: |-
        With your parent or guardian’s and counselor’s approval, interview a worker in
        the mining industry. Discuss the work, equipment, and technology
        used in this individual’s position, and learn about a current
        project. Ask to see reports, drawings, and/or maps made for the
        project. Find out about the educational and professional
        requirements for this individual’s position.  Ask how the
        individual’s mining career began. Discuss with your counselor what
        you have learned.
    - requirement: b
      text: |-
        Find out about three career opportunities in the mining industry.
        Pick one and find out the education, training, and experience
        required for this profession. Discuss this with your counselor, and
        explain why this profession might interest you.
    - requirement: c
      text: |-
        With your parent or guardian’s permission and counselor’s approval, visit a
        college, university, or trade school to learn about educational and
        training requirements for a position in the mining industry that
        interests you. Find out why this position is critical to the mining
        industry, and discuss what you learned with your counselor.
