- requirement: 1
  text: |-
      Show that you know first aid for the types of injuries that could occur
      while surveying, including cuts, scratches, snakebite, insect stings,
      tick bites, heat and cold reactions, and dehydration. Explain to your
      counselor why a surveyor should be able to identify the poisonous plants
      and poisonous animals that are found in your area.
  workbook:
      - lines: 3
        text: |-
            Cuts, scratches
      - lines: 3
        text: |-
            Snakebite
      - lines: 3
        text: |-
            Insect stings
      - lines: 3
        text: |-
            Tick bites
      - lines: 3
        text: |-
            Heat reactions
      - lines: 3
        text: |-
            Cold reactions
      - lines: 3
        text: |-
            Dehydration
      - lines: 3
        text: |-
            Why able to locate poisonous plants and animals
- requirement: 2
  text: |-
      Find and mark the corners of a five-sided lot that has been laid out by
      your counselor to fit the land available. Set an instrument over each of
      the corners and record the angle turned between each line and the
      distance measured between each corner. With the assistance of the
      counselor, compute the error of closure from the recorded notes. The
      error of closure must not be more than 5 feet. From the corners, take
      compass readings or turn angles to trees, shrubs, and rocks, and measure
      to them. All measurements should be made using instruments, methods, and
      accuracies consistent with current technology.
  workbook:
      - lines: 8
- requirement: 3
  text: |-
      From the field notes gathered for requirement 2, draw to scale a map of
      your survey. Submit a neatly drawn copy.
  workbook:
      - grid: 8
- requirement: 4
  text: |-
      Write a metes and bounds description for the five-sided lot in
      requirement 2.
  workbook:
      - lines: 8
- requirement: 5
  text: |-
      Use one of the corner markers from requirement 2 as a benchmark with an
      assumed elevation of 100 feet. Using a level and rod, determine the
      elevation of the other four corner markers.
  workbook:
      - lines: 8
- requirement: 6
  text: |-
      Get a copy of the deed to your property, or a piece of property assigned
      by your counselor, from the local courthouse or title agency.
  workbook:
      - task: true
- requirement: 7
  text: |-
      Tell what GPS is; discuss with your counselor the importance of GPS and
      how it is changing the field of surveying.
  workbook:
      - lines: 8
- requirement: 8
  text: |-
      Discuss the importance of surveying with a licensed surveyor. Also
      discuss the various types of surveying and mapping, and applications of
      surveying technology to other fields. Discuss career opportunities in
      surveying and related fields. Discuss the qualifications and preparation
      for such a career.
  workbook:
      - lines: 8
