# 3b has "where collecting is prohibite(d) In" - changed to "is prohibited. In"
# 7a has "and humankin(d) Explain" - changed to "and humankind. Explain"
- requirement: 1
  markdown: true
  text: |-
    <b>Safety.</b> Do the following:
  children:
    - requirement: a
      text: |-
        Explain to your counselor the most likely hazards associated with
        exposure to ants and bees and what you should do to anticipate, help
        prevent, mitigate, and respond to these hazards.
    - requirement: b
      text: |-
        Discuss the prevention of and treatment for health concerns that could
        occur while working with ants and bees, including insect bites and
        anaphylactic shock.
- requirement: 2
  markdown: true
  text: |-
    <b>Anatomy.</b> Do the following:
  children:
    - requirement: a
      text: |-
        Tell how insects are different from other animals.
    - requirement: b
      text: |-
        Show how insects are different from millipedes and spiders.
    - requirement: c
      text: |-
        Point out and name the main parts of an insect.
    - requirement: d
      text: |-
        Describe the characteristics that distinguish the major orders of
        insects.
- requirement: 3
  markdown: true
  text: |-
    <b>Life Cycles.</b> Do the following:
  children:
    - requirement: a
      text: |-
        Compare the life histories of a butterfly and a grasshopper. Tell how
        they are different.
    - requirement: b
      text: |-
        Raise an insect through complete metamorphosis from its larval stage
        to its adult stage (e.g., raise a butterfly or moth from a caterpillar).
        (Some insects are endangered species and are protected by federal or
        state law. Every species is found only in its own special type of
        habitat. Be sure to check natural resources authorities in advance to be
        sure that you will not be collecting any species that is known to be
        protected or endangered, or in any habitat where collecting is
        prohibited. In most cases, all specimens should be returned at the
        location of capture after the requirement has been met. Check with your
        counselor for those instances where the return of these specimens would
        not be appropriate.)
- requirement: 4
  markdown: true
  text: |-
    <b>Observation and Analysis.</b> Do the following:
  children:
    - requirement: a
      text: |-
        Discuss the importance of the Leave No Trace Seven Principles and the
        Outdoor Code as they relate to insect study. Explain how you have
        followed the Leave No Trace Seven Principles and the Outdoor Code
        during field observation, specimen collection, and identification.
    - requirement: b
      text: |-
        Observe 20 different live species of insects in their habitat. In your
        observations, include at least four orders of insects.
    - requirement: c
      text: |-
        Make a scrapbook of the 20 insects you observe in 5(b) Include
        photographs, sketches, illustrations, and articles. Label each insect
        with its common and scientific names, where possible. Share your
        scrapbook with your merit badge counselor.
    - requirement: d
      text: |-
        From your scrapbook collection, select eight species of insects and
        identify what role they play in the ecosystem.
- requirement: 5
  markdown: true
  text: |-
    <b>Social Insects.</b> Do the following:
  children:
    - requirement: a
      text: |-
        Tell things that make social insects different from solitary
        insects.
    - requirement: b
      text: |-
        Do ONE of the following:
      children:
        - requirement: 1
          text: |-
            Observe an ant colony in a formicarium (ant farm). Find the queen
            and worker ants. Explain to your counselor the different chambers
            found within an ant colony.
        - requirement: 2
          text: |-
            Study a hive of bees. Remove the combs and find the queen. Estimate
            the amount of brood and count the number of queen cells. Explain
            how to determine the amount of honey in the hive. (If you are
            allergic to bee stings, pick option 1 above.)
- requirement: 6
  text: |-
    <b>Ecology.</b> Do the following:
  children:
    - requirement: a
      text: |-
        Tell how insects fit in the food web of other insects, fish, birds, and
        mammals.
    - requirement: b
      text: |-
        Explain the role insects serve as pollinators for plants.
- requirement: 7
  markdown: true
  text: |-
    <b>Insects and People.</b> Do the following:
  children:
    - requirement: a
      text: |-
        Explain the symbiotic relationship between bees and humankind. Explain
        what colony collapse disorder (CCD) is and some of the possible causes.
        Discuss how CCD affects our food supply.
    - requirement: b
      text: |-
        Describe three alternatives to insecticides as a way of preventing crop
        injury and subsequent yield loss. Explain the advantages and
        disadvantages of these alternatives.
- requirement: 8
  markdown: true
  text: |-
    <b>Conservation.</b> Do the following:
  children:
    - requirement: a
        Tell the migration route of an insect (e.g., monarch butterfly).
        Discuss the challenges they face and how Scouts can contribute to their
        success.
      text: |-
    - requirement: b
      text: |-
        Find out about an insect that is a threatened or endangered species.
        Discuss the challenges they face and how Scouts can contribute to their
        success.
- requirement: 9
  markdown: true
  text: |-
    <b>Careers and Hobbies.</b> Do ONE of the following:
  children:
    - requirement: a
      text: |-
        Identify three career opportunities that would use skills and knowledge
        in Insect Study. Pick one and research the training, education,
        certification requirements, experience, and expenses associated with
        entering the field. Research the prospects for employment, starting
        salary, advancement opportunities and career goals associated with this
        career. Discuss what you learned with your counselor and whether you
        might be interested in this career.
    - requirement: b
      text: |-
        Identify how you might use the skills and knowledge in Insect Study to
        pursue a personal hobby. Research the additional training required,
        expenses, and affiliation with organizations that would help you
        maximize the enjoyment and benefit you might gain from it. Discuss what
        you learned with your counselor and share what short-term and long-term
        goals you might have if you pursued this.
