- requirement: 1
  text: |-
      Before fulfilling the following requirements, success- fully
      complete the BSA swimmer test.
- requirement: 2
  text: |-
      Do the following:
  children:
      - requirement: a
        text: |-
            Describe various types of kayaks and how they differ in
            design, materials, and purpose.
      - requirement: b
        text: |-
            Name the parts of the kayak you are using for this exercise.
      - requirement: c
        text: |-
            Demonstrate how to choose an appropriately sized kayak paddle
            and how to position your hands.
- requirement: 3
  text: |-
      Do the following:
  children:
      - requirement: a
        text: |-
            Tell what precautions must be taken for a safe trip afloat.
      - requirement: b
        text: |-
            Demonstrate how to select and properly fit a life jacket.
      - requirement: c
        text: |-
            Explain the importance of safety equipment such as life
            jackets, air bags, grab loops, and helmets.
- requirement: 4
  text: |-
      Demonstrate your ability to aid yourself and others in the event of
      a capsize:
  children:
      - requirement: a
        text: |-
            Capsize your kayak in water at least seven feet deep, perform
            a wet exit if necessary, and swim the boat to shore.
      - requirement: b
        text: |-
            With assistance, if needed, ready the capsized craft for use.
      - requirement: c
        text: |-
            Show how to approach a capsized paddler in your kayak and tow
            him to shore.
      - requirement: d
        text: |-
            While upright in your kayak, right a capsized kayak, empty it
            of water, and assist the paddler aboard without returning to
            shore.
- requirement: 5
  text: |-
      As a solo paddler, demonstrate the following:
  children:
      - requirement: a
        text: |-
            Entering and launching a kayak from shore or dock
      - requirement: b
        text: |-
            Landing or docking and exiting a kayak
      - requirement: c
        text: |-
            Forward stroke
      - requirement: d
        text: |-
            Sweep stroke
      - requirement: e
        text: |-
            Reverse sweep
      - requirement: f
        text: |-
            Draw stroke
      - requirement: g
        text: |-
            Rudder stroke
      - requirement: h
        text: |-
            Back stroke
- requirement: 6
  text: |-
      As a solo paddler, do the following:
  children:
      - requirement: a
        text: |-
            Paddle forward in a reasonably straight line.
      - requirement: b
        text: |-
            Move the kayak sideways to the right and to the left.
      - requirement: c
        text: |-
            Pivot 360 degrees to the right and left.
      - requirement: d
        text: |-
            Stop the kayak.
