- requirement: 1
  text: |-
    Explain the need for bird study and why birds are useful indicators of the
    quality of the environment. Describe how birds are part of the ecosystem.
- requirement: 2
  text: |-
    Show that you are familiar with the terms used to describe birds by doing
    the following:
  children:
    - requirement: a
      text: |-
        Sketch or trace a perched bird and then label 15 different parts of the
        bird.
    - requirement: b
      text: |-
        Sketch or trace an extended wing and label six types of wing feathers.
- requirement: 3
  text: |-
    Demonstrate that you know how to properly use and care for binoculars, a
    spotting scope, or a monocular.
  children:
    - requirement: a
      text: |-
        Explain what the specification numbers mean on binoculars, a spotting
        scope, or a monocular.
    - requirement: b
      text: |-
        Show how to adjust the eyepiece and how to focus for proper viewing.
    - requirement: c
      text: |-
        Show how to properly care for and clean the lenses.
    - requirement: d
      text: |-
        Describe when and where each type of viewing device would be most
        effective.
- requirement: 4
  text: |-
    Demonstrate that you know how to use a bird field guide. Show your
    counselor that you are able to understand a range map by locating in the
    book and pointing out:
  children:
    - requirement: a
      text: |-
        Seabird
    - requirement: b
      text: |-
        Plover
    - requirement: c
      text: |-
        Falcon or hawk
    - requirement: d
      text: |-
        Warbler or vireo
    - requirement: e
      text: |-
        Heron or egret
    - requirement: f
      text: |-
        Sparrow.
- requirement: 5
  text: |-
    Observe and be able to identify 20 species of wild birds. Prepare a field
    notebook, making a separate entry for each species, and record the
    following information from your field observations and other references.
  children:
    - requirement: a
      text: |-
        Note the date and time.
    - requirement: b
      text: |-
        Note the location and habitat.
    - requirement: c
      text: |-
        Describe the bird's main feeding habitat and list two types of food
        that the bird is likely to eat.
    - requirement: d
      text: |-
        Note whether the bird is a migrant or a summer, winter, or year-round
        resident of your area.
- requirement: 6
  text: |-
    Describe to your counselor how certain orders of birds are uniquely adapted
    to a specific habitat. In your description, include characteristics such as
    the size and shape of the following:
  children:
    - requirement: a
      text: |-
        Beak
    - requirement: b
      text: |-
        Body
    - requirement: c
      text: |-
        Leg and foot
    - requirement: d
      text: |-
        Feathers/plumage.
- requirement: 7
  text: |-
    Explain the function of a bird's song. Be able to identify five of the 20
    species in your field notebook by song or call alone. Explain the
    difference between songs and calls. For each of these five species, enter a
    description of the song or call, and note the behavior of the bird making
    the sound. Note why you think the bird was making the call or song that you
    heard.
- requirement: 8
  text: |-
    Do ONE of the following:
  children:
    - requirement: a
      text: |-
        Go on a field trip with a local club or with others who are
        knowledgeable about birds in your area.
      children:
        - requirement: 1
          text: |-
            Keep a list or fill out a checklist of all the birds your group
            observed during the field trip.
        - requirement: 2
          text: |-
            Tell your counselor which birds your group saw and why some species
            were common and some were present in small numbers.
        - requirement: 3
          text: |-
            Tell your counselor what makes the area you visited good for
            finding birds.
    - requirement: b
      text: |-
        By using a public library, the internet, or contacting the National
        Audubon Society, find the name and location of the Christmas Bird Count
        nearest your home and obtain the results of a recent count.
      children:
        - requirement: 1
          text: |-
            Explain what kinds of information are collected during the annual
            event.
        - requirement: 2
          text: |-
            Tell your counselor which species are most common, and explain why
            these birds are abundant.
        - requirement: 3
          text: |-
            Tell your counselor which species are uncommon, and explain why
            these were present in small numbers. If the number of birds of
            these species is decreasing, explain why, and what, if anything,
            could be done to reverse their decline.
    - requirement: c
      text: |-
        Participate in a bird banding program with an approved federal or state
        agency, university researcher, bird observatory, or certified private
        individual.
      children:
        - requirement: 1
          text: |-
            Explain who is able to band birds and why.
        - requirement: 2
          text: |-
            Explain why birds get banded.
        - requirement: 3
          text: |-
            Explain what kinds of birds get banded.
        - requirement: 4
          text: |-
            Tell how the birds were captured, the number of bird species
            recorded during your visit, and your role in the program.
- requirement: 9
  text: |-
    Do ONE of the following. For the option you choose, describe what birds you
    hope to attract, and why.
  children:
    - requirement: a
      text: |-
        Build a bird feeder and put it in an appropriate place in your yard
        or another location.
    - requirement: b
      text: |-
        Build a birdbath and put it in an appropriate place.
    - requirement: c
      text: |-
        Build a backyard sanctuary for birds by planting trees and shrubs for
        food and cover.
    - requirement: d
      text: |-
        Build a nest box for a species of your choice using plans approved by
        your counselor.
- requirement: 10
  text: |-
    Do the following:
  children:
    - requirement: a
      text: |-
        Explain the differences between extinct, endangered, and threatened.
    - requirement: b
      text: |-
        Identify a bird species that is on the endangered or threatened list.
        Explain what caused their decline. Discuss with your counselor what can
        be done to reverse this trend and what can be done to help remove the
        species from the endangered or threatened list.
- requirement: 11
  text: |-
    Identify a non-native bird (introduced to North America from a foreign
    country since 1800).  Describe how non-native birds may become damaging to
    the ecosystem.
- requirement: 12
  text: |-
    Identify three career opportunities connected to the study of birds. Pick
    one and find out the education, training, and experience required for this
    profession. Discuss with your counselor if this profession might interest
    you.
