- requirement: 1
  text: |-
      Choose A or B or C and complete ALL the requirements.
  children:
      - requirement: A
        text: |-
            Watch about three hours total of technology-related shows or
            documentaries that involve transportation or transportation
            technology. Then do the following:
        children:
            - requirement: 1
              text: |-
                  Make a list of at least two questions or ideas from each
                  show.
            - requirement: 2
              text: |-
                  Discuss two of the questions or ideas with your counselor.
            - detail: true
              text: |-
                  Some examples include—but are not limited to—shows found on
                  PBS (“NOVA”), Discovery Channel, Science Channel, National
                  Geographic Channel, and TED Talks (online videos). You may
                  choose to watch a live performance or movie at or science
                  museum instead of watching a media production. You may watch
                  online productions with your counselor’s approval and under
                  your parent’s or guardian’s supervision.
      - requirement: B
        text: |-
            Read (about three hours total) about transportation or
            transportation technology. Then do the following:
        children:
            - requirement: 1
              text: |-
                  Make a list of at least two questions or ideas from each
                  article.
            - requirement: 2
              text: |-
                  Discuss two of the questions or ideas with your counselor.
            - detail: true
              text: |-
                  Examples of magazines include—but are not limited to—Odyssey,
                  Popular Mechanics, Popular Science, Science Illustrated,
                  Discover, Air & Space, Aviation Week, Astronomy, Science
                  News, Natural History, Robot, Servo, and Scientific American.
      - requirement: C
        text: |-
            Do a combination of reading and watching (about three hours total).
            Then do the following:
        children:
            - requirement: 1
              text: |-
                  Make a list of at least two questions or ideas from each
                  article or show.
            - requirement: 2
              text: |-
                  Discuss two of the questions or ideas with your counselor.
- requirement: 2
  markdown: true
  text: |-
      Choose ONE STEM field of interest from the following list. Complete ALL
      the requirements for a STEM exploration in that field. See [STEM
      Explorations](../../explorations/) for the requirements. (If you have
      already completed a Venturing STEM exploration in one of these fields,
      please choose a different field for this award.)

      Automotive Maintenance, Aviation, Canoeing, Cycling, Drafting,
      Electricity, Energy, Farm Mechanics, Kayaking, Motorboating, Nuclear
      Science, Railroading, Rowing, Small-Boat Sailing, Space Exploration,
      Truck Transportation
- requirement: 3
  text: |-
      Do ALL the following.
  children:
      - requirement: A
        text: |-
            Using the requirements from the above list of STEM explorations:
        children:
            - requirement: 1
              text: |-
                  Tell your counselor the energy source(s) used in these STEM
                  explorations.
              children:
                  - note:
                      - counselor
                    markdown: true
                    text: |-
                        Automotive Maintenance—Gasoline, diesel fuel, electric, blended gasoline, biodiesel, hybrid

                        Aviation—Aviation fuel and kerosene

                        Canoeing—Human power

                        Cycling—Human power

                        Drafting—Human power, electricity

                        Electricity—Electromagnetism, chemical

                        Energy—Biomass digesters, cogeneration, fossil fuel power, fuel cells, geothermal power, nuclear power, solar power, tidal energy, wave energy, ocean thermal energy, wind

                        Farm Mechanics—Diesel fuel

                        Kayaking - Human power

                        Motorboating—Gasoline, diesel fuel, blended gasoline, biodiesel

                        Nuclear Science—Nuclear energy

                        Railroading—Diesel fuel

                        Small-Boat Sailing—Wind

                        Space Exploration—Most common solid: ammonium perchlorate mixed with powdered aluminum

                        * Liquids for first-stage rockets—RP-1
                        * Liquids for second-stage rockets—Liquid hydrogen, liquid oxygen

                        Truck Transportation—Diesel fuel
            - requirement: 2
              text: |-
                  Discuss the pros and cons of each energy source with your counselor.
              children:
                  - note:
                      - counselor
                    markdown: true
                    text: |-
                        Helpful Links

                        The following links are places to start when researching the pros and cons of fuel types.

                        “Diesel Reborn”: Edmunds.com<br>
                        Website: https://www.edmunds.com/fuel-economy/diesel-reborn.html

                        “Aviation Jet Fuel Information”: CSGNetwork.com<br>
                        Website: http://www.csgnetwork.com/jetfuel.html
      - requirement: B
        text: |-
            Make a list of sources of energy that may be possible to use in
            transportation. (See the list earlier in this section.)
      - requirement: C
        text: |-
            With your counselor:
        children:
            - requirement: 1
              text: |-
                  Discuss alternative sources of energy.
            - requirement: 2
              text: |-
                  Discuss the pros and cons of using alternative energy
                  sources.
            - note:
                - counselor
              markdown: true
              text: |-
                  Helpful Links

                  The following links are places to start when researching alternative fuels. You can also search “Air Force alternative fuels” using your favorite search engine. Be sure you have your parent’s or guardian’s permission to use the Internet.

                  “Alternative& Advanced Vehicles”: U.S. Department of Energy<br>
                  Website: https://www.afdc.energy.gov/afdc/vehicles/electric_benefits.html

                  Energy Sources and Uses: U.S. Department of Energy, Energy Information Administration:
                  https://www.eia.gov/

                  “Alternative Fuels”: U.S. Department of Energy<br>
                  Website: https://www.fueleconomy.gov/feg/current.shtml

                  “Alternative Fuel”: Popular Mechanics<br>
                  Website: https://www.popularmechanics.com/cars/alternative-fuel

                  “Nuclear Power: U.S. Department of Energy, Energy Information Administration:<br>
                  https://www.eia.gov/energyexplained/nuclear/
- requirement: 4
  text: |-
      Design and build a working model vehicle (not from a kit).
  children:
      - requirement: A
        text: |-
            Make drawings and specifications of your model vehicle before you
            begin to build.
      - requirement: B
        text: |-
            Include one of the following energy sources to power your vehicle
            (do not use gasoline or other combustible fuel source): solar
            power, wind power, or battery power.
      - requirement: C
        text: |-
            Test your model. Then answer the following questions:
        children:
            - requirement: 1
              text: |-
                  How well did it perform?
            - requirement: 2
              text: |-
                  Did it move as well as you thought it would?
            - requirement: 3
              text: |-
                  Did you encounter problems? How can these problems be
                  corrected?
      - requirement: D
        text: |-
            Discuss with your counselor:
        children:
            - requirement: 1
              text: |-
                  Any difficulties you encountered in designing and building
                  your model
            - requirement: 2
              text: |-
                  Why you chose a particular energy source
            - requirement: 3
              text: |-
                  Whether your model met your specifications
            - requirement: 4
              text: |-
                  How you would modify your design to make it better
- requirement: 5
  text: |-
      Discuss with your counselor how technology affects your everyday life.
