- requirement: 1
  text: |-
    Do the following:
  children:
    - requirement: a
      text: |-
        Describe how a properly working plumbing system protects your
        family’s health and safety.
    - requirement: b
      text: |-
        List five important local health regulations related to plumbing
        and tell how they protect health and safety.
    - requirement: c
      text: |-
        Describe the safety precautions you must take when making home
        plumbing repairs.
- requirement: 2
  text: |-
    Do the following:
  children:
    - requirement: a
      text: |-
        Make a drawing and explain how a home hot- and cold-water supply
        system works. Tell how you would make it safe from freezing.
    - requirement: b
      text: |-
        Make a drawing and explain the drainage system of the plumbing in a
        house. Show and explain the use of drains and vents.
- requirement: 3
  text: |-
    Show how to use five important plumber’s tools.
- requirement: 4
  text: |-
    Identify and describe the use of each of the following: washer, retaining
    nut, plunger (rubber force cup), solder, flux, elbow, tee, nipple,
    coupling, plug, union, trap, drainpipe, and water meter.
- requirement: 5
  text: |-
    Name the kinds of pipe that are used most often in a plumbing system.
    Explain why these pipes are used.
- requirement: 6
  text: |-
    Cut, thread, and connect two pieces of metal pipe.
- requirement: 7
  text: |-
    Under the supervision of a knowledgeable adult, solder three copper tube
    connections using a gas torch. Include one tee, two straight pieces, and
    one coupling.
- requirement: 8
  text: |-
    Do the following:
  children:
    - requirement: a
      text: |-
        Replace a washer in a faucet.
    - requirement: b
      text: |-
        Clean out a sink or lavatory trap.
