- requirement: 1
  text: |-
      Do the following:
  children:
      - requirement: a
        text: |-
            Demonstrate the technique of stop, drop, cover, roll, cover your
            face, and cool. Explain how burn injuries can be prevented.
        workbook:
            - task: true
              text: |-
                  Demonstrated
            - lines: 8
      - requirement: b
        text: |-
            List the most frequent causes of burn injuries.
        workbook:
            - lines: 8
      - requirement: c
        text: |-
            Explain how to safely discard and store flammable liquids.
        workbook:
            - lines: 8
- requirement: 2
  text: |-
      Explain the chemistry and physics of fire. Name the parts of the fire
      tetrahedron.  Explain why vapors are important to the burning process.
      Name the products of combustion. Give an example of how fire grows and
      what happens.
  workbook:
      - lines: 8
        text: |-
            Chemistry and physics of fire
      - lines: 8
        text: |-
            Parts of the fire tetrahedron
      - lines: 8
        text: |-
            Why vapors are important to the burning process
      - lines: 8
        text: |-
            The products of combustion
      - lines: 8
        text: |-
            An example of how fire grows and what happens
- requirement: 3
  text: |-
      Name the most frequent causes of fire in the home, and give examples of
      ways they can be prevented. Include a discussion about fires caused by
      smoking in the home, cooking, candles, fireplaces, and electrical
      appliances.
  workbook:
      - lines: 8
        text: |-
            Most frequent causes of fire in the home
      - lines: 8
        text: |-
            Examples of ways they can be prevented
- requirement: 4
  text: |-
      Explain the role of human behavior in the arson problem in this country.
  workbook:
      - lines: 8
- requirement: 5
  text: |-
      List the actions and common circumstances that cause seasonal and
      holiday-related fires. Explain how these fires can be prevented.
  workbook:
      - lines: 8
- requirement: 6
  text: |-
      Conduct a home safety survey with the help of an adult. Then do the
      following:
  children:
      - requirement: a
        text: |-
            Draw a home fire-escape plan, create a home fire-drill schedule,
            and conduct a home fire drill.
        workbook:
            - split:
                  - task: true
                    text: |-
                        Drew a home fire-escape plan
                  - task: true
                    text: |-
                        Created a home fire-drill schedule
                  - task: true
                    text: |-
                        Conducted a home fire drill
      - requirement: b
        text: |-
            Test a smoke alarm and demonstrate regular maintenance of a smoke
            alarm.
        workbook:
            - task: true
      - requirement: c
        text: |-
            Explain what to do when you smell gas and when you smell smoke.
        workbook:
            - lines: 8
      - requirement: d
        text: |-
            Explain how you would report a fire alarm.
        workbook:
            - lines: 8
      - requirement: e
        text: |-
            Explain what fire safety equipment can be found in public
            buildings.
        workbook:
            - lines: 8
      - requirement: f
        text: |-
            Explain who should use fire extinguishers and when these devices
            can be used.
        workbook:
            - lines: 8
      - requirement: g
        text: |-
            Explain how to extinguish a grease pan fire.
        workbook:
            - lines: 8
      - requirement: h
        text: |-
            Explain what fire safety precautions you should take when you are
            in a public building.
        workbook:
            - lines: 8
- requirement: 7
  text: |-
      Do the following:
  children:
      - requirement: a
        text: |-
            Demonstrate lighting a match safely.
        workbook:
            - task: true
      - requirement: b
        text: |-
            Demonstrate the safe way to start a charcoal fire.
        workbook:
            - task: true
      - requirement: c
        text: |-
            Demonstrate how to safely light a candle. Discuss with your
            counselor how to safely use candles.
        workbook:
            - task: true
            - lines: 8
- requirement: 8
  text: |-
      Explain the difference between combustible and noncombustible liquids and
      between combustible and noncombustible fabrics.
  workbook:
      - lines: 8
- requirement: 9
  text: |-
      Do the following:
  children:
      - requirement: a
        text: |-
            Describe for your counselor the safe way to refuel a liquid fuel
            engine, such as a lawn mower, weed eater, an outboard motor, farm
            machine, or an automobile with gas from an approved gas can.
        workbook:
            - lines: 8
      - requirement: b
        text: |-
            Demonstrate the safety factors, such as proper ventilation, for
            auxiliary heating devices and the proper way to fuel those devices.
        workbook:
            - task: true
- requirement: 10
  text: |-
      Do the following:
  children:
      - requirement: a
        text: |-
            Explain the cost of outdoor and wildland fires and how to prevent
            them.
        workbook:
            - lines: 8
      - requirement: b
        text: |-
            Demonstrate setting up and putting out a cooking fire.
        workbook:
            - task: true
      - requirement: c
        text: |-
            Demonstrate using a camp stove and lantern.
        workbook:
            - task: true
      - requirement: d
        text: |-
            Explain how to set up a campsite safe from fire.
        workbook:
            - lines: 8
- requirement: 11
  text: |-
      Visit a fire station. Identify the types of fire trucks. Find out about
      the fire prevention activities in your community.
  workbook:
      - lines: 8
        text: |-
            Types of fire trucks
      - lines: 8
        text: |-
            Fire prevention activites in your community
- requirement: 12
  text: |-
      Determine if smoke detectors are required in all dwellings within your
      municipality. If so, explain which specific types are required. Tell your
      counselor what type of smoke detectors your house has or needs.
  workbook:
      - lines: 8
- requirement: 13
  text: |-
      Choose a fire safety–related career that interests you and describe the
      level of education required and responsibilities of a person in that
      position. Tell why this position interests you.
  workbook:
      - lines: 8
