- requirement: 1
  text: |-
    Do the following:
  children:
    - requirement: a
      text: |-
        Demonstrate the technique of stop, drop, cover, roll, cover your
        face, and cool. Explain how burn injuries can be prevented.
    - requirement: b
      text: |-
        List the most frequent causes of burn injuries.
    - requirement: c
      text: |-
        Explain how to safely discard and store flammable liquids.
- requirement: 2
  text: |-
    Explain the chemistry and physics of fire. Name the parts of the fire
    tetrahedron.  Explain why vapors are important to the burning process.
    Name the products of combustion. Give an example of how fire grows and
    what happens.
- requirement: 3
  text: |-
    Name the most frequent causes of fire in the home, and give examples of
    ways they can be prevented. Include a discussion about fires caused by
    smoking in the home, cooking, candles, fireplaces, and electrical
    appliances.
- requirement: 4
  text: |-
    Explain the role of human behavior in the arson problem in this country.
- requirement: 5
  text: |-
    List the actions and common circumstances that cause seasonal and
    holiday-related fires. Explain how these fires can be prevented.
- requirement: 6
  text: |-
    Conduct a home safety survey with the help of an adult. Then do the
    following:
  children:
    - requirement: a
      text: |-
        Draw a home fire-escape plan, create a home fire-drill schedule,
        and conduct a home fire drill.
    - requirement: b
      text: |-
        Test a smoke alarm and demonstrate regular maintenance of a smoke
        alarm.
    - requirement: c
      text: |-
        Explain what to do when you smell gas and when you smell smoke.
    - requirement: d
      text: |-
        Explain how you would report a fire alarm.
    - requirement: e
      text: |-
        Explain what fire safety equipment can be found in public
        buildings.
    - requirement: f
      text: |-
        Explain who should use fire extinguishers and when these devices
        can be used.
    - requirement: g
      text: |-
        Explain how to extinguish a grease pan fire.
    - requirement: h
      text: |-
        Explain what fire safety precautions you should take when you are
        in a public building.
- requirement: 7
  text: |-
    Do the following:
  children:
    - requirement: a
      text: |-
        Demonstrate lighting a match safely.
    - requirement: b
      text: |-
        Demonstrate the safe way to start a charcoal fire.
    - requirement: c
      text: |-
        Demonstrate how to safely light a candle. Discuss with your
        counselor how to safely use candles.
- requirement: 8
  text: |-
    Explain the difference between combustible and noncombustible liquids and
    between combustible and noncombustible fabrics.
- requirement: 9
  text: |-
    Do the following:
  children:
    - requirement: a
      text: |-
        Describe for your counselor the safe way to refuel a liquid fuel
        engine, such as a lawn mower, weed eater, an outboard motor, farm
        machine, or an automobile with gas from an approved gas can.
    - requirement: b
      text: |-
        Demonstrate the safety factors, such as proper ventilation, for
        auxiliary heating devices and the proper way to fuel those devices.
- requirement: 10
  text: |-
    Do the following:
  children:
    - requirement: a
      text: |-
        Explain the cost of outdoor and wildland fires and how to prevent
        them.
    - requirement: b
      text: |-
        Demonstrate setting up and putting out a cooking fire.
    - requirement: c
      text: |-
        Demonstrate using a camp stove and lantern.
    - requirement: d
      text: |-
        Explain how to set up a campsite safe from fire.
- requirement: 11
  text: |-
    Visit a fire station. Identify the types of fire trucks. Find out about
    the fire prevention activities in your community.
- requirement: 12
  text: |-
    Determine if smoke detectors are required in all dwellings within your
    municipality. If so, explain which specific types are required. Tell your
    counselor what type of smoke detectors your house has or needs.
- requirement: 13
  text: |-
    Choose a fire safety–related career that interests you and describe the
    level of education required and responsibilities of a person in that
    position. Tell why this position interests you.
