- requirement: 1
  text: |-
      Do the following:
  children:
      - requirement: a
        text: |-
            Explain to your counselor the most likely hazards you may encounter
            while participating in canoeing activities and what you should do
            to anticipate, help prevent, mitigate, and respond to these
            hazards.
        workbook:
            - lines: 8
              text: |-
                  Most likely hazards
            - lines: 8
              text: |-
                  Anticipate hazards
            - lines: 8
              text: |-
                  Prevent hazards
            - lines: 8
              text: |-
                  Mitigate hazards
            - lines: 8
              text: |-
                  Respond to hazards
      - requirement: b
        text: |-
            Review prevention, symptoms, and first-aid treatment for the
            following injuries or illnesses that could occur while canoeing:
            blisters, cold-water shock and hypothermia, dehydration,
            heat-related illnesses, sunburn, sprains, and strains.
        workbook:
            - lines: 8
              text: |-
                  Blisters
            - lines: 8
              text: |-
                  Cold-water shock and hypothermia
            - lines: 8
              text: |-
                  Dehydration
            - lines: 8
              text: |-
                  Heat-related illnesses
            - lines: 8
              text: |-
                  Sunburn
            - lines: 8
              text: |-
                  Sprains and strains
      - requirement: c
        text: |-
            Discuss the BSA Safety Afloat policy. Tell how it applies to
            canoeing activities.
        workbook:
            - lines: 8
- requirement: 2
  text: |-
      Before doing the following requirements, successfully complete the BSA
      swimmer test: Jump feetfirst into water over the head in depth. Level off
      and swim 75 yards in a strong manner using one or more of the following
      strokes: sidestroke, breaststroke, trudgen, or crawl; then swim 25 yards
      using an easy, resting backstroke. The 100 yards must be completed in one
      swim without stops and must include at least one sharp turn. After
      completing the swim, rest by floating.
  workbook:
      - signature: Swim Test Observer
- requirement: 3
  text: |-
      Do the following:
  children:
      - requirement: a
        text: |-
            Name and point out the major parts of a canoe.
        workbook:
            - lines: 8
      - requirement: b
        text: |-
            Describe how the length and shape of a canoe affect its
            performance.
        workbook:
            - lines: 8
      - requirement: c
        text: |-
            Discuss the advantages and disadvantages of the different materials
            used to make canoes.
        workbook:
            - lines: 8
- requirement: 4
  text: |-
      Do the following:
  children:
      - requirement: a
        text: |-
            Name and point out the parts of a paddle.
        workbook:
            - lines: 8
      - requirement: b
        text: |-
            Demonstrate how to size correctly a paddle for a paddler in a
            sitting position and a kneeling position.
        workbook:
            - lines: 8
- requirement: 5
  text: |-
      Do the following:
  children:
      - requirement: a
        text: |-
            Discuss with your counselor the characteristics of life jackets
            most appropriate for canoeing and tell why a life jacket must
            always be worn while paddling.
        workbook:
            - lines: 8
              text: |-
                  Characteristics of life jackets most appropriate for canoeing
            - lines: 8
              text: |-
                  Why a life jacket must always be worn while paddling
      - requirement: b
        text: |-
            Demonstrate how to select and properly fit the correct size life
            jacket.
        workbook:
            - task: true
      - requirement: c
        text: |-
            Review the importance of safety and rescue equipment such as a
            sound signal device, extra paddle, sponge, bailer, bilge pump,
            rescue sling, ropes and throw bag.
        workbook:
            - lines: 8
- requirement: 6
  text: |-
      Discuss with your counselor the general care and maintenance of canoes,
      paddles, and other canoeing equipment.
  workbook:
      - lines: 8
- requirement: 7
  text: |-
      Do the following:
  children:
      - requirement: a
        text: |-
            Discuss what personal and group equipment would be appropriate for
            a canoe camping trip. Describe how personal and group equipment can
            be packed and protected from water.
        workbook:
            - lines: 8
              text: |-
                  What personal and group equipment would be appropriate for a
                  canoe camping trip
            - lines: 8
              text: |-
                  How personal and group equipment can be packed and protected
                  from water
      - requirement: b
        text: |-
            Using the containers and packs from requirement 7a, demonstrate how
            to load and secure the containers and other equipment in the canoe.
        workbook:
            - task: true
      - requirement: c
        text: |-
            Using appropriate knots, including a trucker’s hitch, tautline
            hitch, and bowline, demonstrate how to secure a canoe to a vehicle
            or a trailer, or if these are not available, a rack on land.
        workbook:
            - task: true
- requirement: 8
  text: |-
      With a companion, use a properly equipped canoe to demonstrate the
      following:
  workbook:
      - task: true
        text: |-
            a. Safely carry and launch the canoe from a dock or shore (both, if
            possible).
      - task: true
        text: |-
            b. Safely land the canoe on a dock or shore (both, if possible) and
            return it to its proper storage location.
      - task: true
        text: |-
            c. Demonstrate kneeling and sitting positions in a canoe and
            explain the proper use for each position.
      - task: true
        text: |-
            d. Change places while afloat in the canoe.
  children:
      - requirement: a
        text: |-
            Safely carry and launch the canoe from a dock or shore (both, if
            possible).
        workbookHide: true
      - requirement: b
        text: |-
            Safely land the canoe on a dock or shore (both, if possible) and
            return it to its proper storage location.
        workbookHide: true
      - requirement: c
        text: |-
            Demonstrate kneeling and sitting positions in a canoe and explain
            the proper use for each position.
        workbookHide: true
      - requirement: d
        text: |-
            Change places while afloat in the canoe.
        workbookHide: true
- requirement: 9
  text: |-
      With a companion, use a properly equipped canoe to demonstrate the
      following:
  workbook:
      - task: true
        text: |-
            a. In deep water, exit the canoe and get back in without capsizing.
      - task: true
        text: |-
            b. Safely perform a controlled capsize of the canoe and demonstrate
            how staying with a capsized canoe will support both paddlers.
      - task: true
        text: |-
            c. Swim, tow, or push a swamped canoe 50 feet to shallow water. In
            the shallow water, empty the swamped canoe and reenter it.
      - task: true
        text: |-
            d. In deep water, rescue a swamped canoe and its paddlers by
            emptying the swamped canoe and helping the paddlers safely reenter
            their boat without capsizing.
  children:
      - requirement: a
        text: |-
            In deep water, exit the canoe and get back in without capsizing.
        workbookHide: true
      - requirement: b
        text: |-
            Safely perform a controlled capsize of the canoe and demonstrate
            how staying with a capsized canoe will support both paddlers.
        workbookHide: true
      - requirement: c
        text: |-
            Swim, tow, or push a swamped canoe 50 feet to shallow water. In the
            shallow water, empty the swamped canoe and reenter it.
        workbookHide: true
      - requirement: d
        text: |-
            In deep water, rescue a swamped canoe and its paddlers by emptying
            the swamped canoe and helping the paddlers safely reenter their
            boat without capsizing.
        workbookHide: true
- requirement: 10
  text: |-
      With a companion, use a properly equipped canoe to demonstrate the
      following paddling strokes as both a bow and stern paddler:
  workbook:
      - split:
            - task: true
              text: |-
                  a. Forward stroke
            - task: true
              text: |-
                  b. Backstroke
            - task: true
              text: |-
                  c. Draw
      - header: true
        text: |-
            For stern paddling only:
      - split:
            - task: true
              text: |-
                  d. J-stroke
            - task: true
              text: |-
                  e. Pushaway
            - task: true
              text: |-
                  f. Forward sweep
      - split:
            - task: true
              text: |-
                  g. Reverse sweep
            - task: true
              text: |-
                  h. Rudder stroke
            - task: true
              text: |-
                  i. Stern pry
  children:
      - requirement: a
        text: |-
            Forward stroke
        workbookHide: true
      - requirement: b
        text: |-
            Backstroke
        workbookHide: true
      - requirement: c
        text: |-
            Draw
        workbookHide: true
      - detail: true
        text: |-
            For stern paddling only:
        workbookHide: true
      - requirement: d
        text: |-
            J-stroke
        workbookHide: true
      - requirement: e
        text: |-
            Pushaway
        workbookHide: true
      - requirement: f
        text: |-
            Forward sweep
        workbookHide: true
      - requirement: g
        text: |-
            Reverse sweep
        workbookHide: true
      - requirement: h
        text: |-
            Rudder stroke
        workbookHide: true
      - requirement: i
        text: |-
            Stern pry
        workbookHide: true
- requirement: 11
  text: |-
      Using the strokes in requirement 10, and in an order determined by your
      counselor, use a properly equipped canoe to demonstrate the following
      tandem maneuvers while paddling on opposite sides and without changing
      sides.  Each paddler must demonstrate these maneuvers in both the bow and
      stern and on opposite paddling sides:
  workbook:
      - header: true
        text: |-
            a. Pivot or spin the canoe in either direction.
      - split:
            - task: true
              text: |-
                  Bow, left side
            - task: true
              text: |-
                  Bow, right side
      - split:
            - task: true
              text: |-
                  Stern, left side
            - task: true
              text: |-
                  Stern, right side
      - header: true
        text: |-
            b. Move the canoe sideways or abeam in either direction.
      - split:
            - task: true
              text: |-
                  Bow, left side
            - task: true
              text: |-
                  Bow, right side
      - split:
            - task: true
              text: |-
                  Stern, left side
            - task: true
              text: |-
                  Stern, right side
      - header: true
        text: |-
            c. Stop the canoe.
      - split:
            - task: true
              text: |-
                  Bow, left side
            - task: true
              text: |-
                  Bow, right side
      - split:
            - task: true
              text: |-
                  Stern, left side
            - task: true
              text: |-
                  Stern, right side
      - header: true
        text: |-
            d. Move the canoe in a straight line for 50 yards.
      - split:
            - task: true
              text: |-
                  Bow, left side
            - task: true
              text: |-
                  Bow, right side
      - split:
            - task: true
              text: |-
                  Stern, left side
            - task: true
              text: |-
                  Stern, right side
  children:
      - requirement: a
        text: |-
            Pivot or spin the canoe in either direction.
        workbookHide: true
      - requirement: b
        text: |-
            Move the canoe sideways or abeam in either direction.
        workbookHide: true
      - requirement: c
        text: |-
            Stop the canoe.
        workbookHide: true
      - requirement: d
        text: |-
            Move the canoe in a straight line for 50 yards.
        workbookHide: true
- requirement: 12
  text: |-
      Use a properly equipped canoe to demonstrate solo canoe handling:
  workbook:
      - task: true
        text: |-
            a. Launch from shore or a pier (both, if possible).
      - task: true
        text: |-
            b. Using a single-blade paddle and paddling only on one side,
            demonstrate proper form and use of the forward stroke, backstroke,
            draw stroke, pushaway stroke, forward sweep, reverse sweep,
            J-stroke, and rudder stroke. Repeat while paddling on the other
            side.
      - task: true
        text: |-
            c. Using a single-blade paddle and paddling only on one side,
            demonstrate proper form and use of a combination of a forward
            stroke, rudder stroke, and stern pry by canoeing to a target 50
            yards away. Repeat while paddling on the other side.
      - task: true
        text: |-
            d. Make a proper landing at a dock or shore (both, if possible).
            Store canoe properly (with assistance, if needed).
  children:
      - requirement: a
        text: |-
            Launch from shore or a pier (both, if possible).
        workbookHide: true
      - requirement: b
        text: |-
            Using a single-blade paddle and paddling only on one side,
            demonstrate proper form and use of the forward stroke, backstroke,
            draw stroke, pushaway stroke, forward sweep, reverse sweep,
            J-stroke, and rudder stroke. Repeat while paddling on the other
            side.
        workbookHide: true
      - requirement: c
        text: |-
            Using a single-blade paddle and paddling only on one side,
            demonstrate proper form and use of a combination of a forward
            stroke, rudder stroke, and stern pry by canoeing to a target 50
            yards away. Repeat while paddling on the other side.
        workbookHide: true
      - requirement: d
        text: |-
            Make a proper landing at a dock or shore (both, if possible). Store
            canoe properly (with assistance, if needed).
        workbookHide: true
