- requirement: 1
  text: |-
      Using resources available to you, learn about working people and
      work-related concerns. List and briefly describe or give examples of at
      least EIGHT concerns of American workers. These may include, but are not
      limited to, working conditions, workplace safety, hours, wages,
      seniority, job security, equal-opportunity employment and discrimination,
      guest workers, automation and technologies that replace workers,
      unemployment, layoffs, outsourcing, and employee benefits such as health
      care, child care, profit sharing, continuing education, and retirement
      benefits.
  workbook:
      - lines: 8
      - lines: 8
      - lines: 8
      - lines: 8
      - lines: 8
      - lines: 8
      - lines: 8
      - lines: 8
  children:
      - note:
            - inPerson
            - online
        text: |-
            It is strongly recommended that Scouts use the Scoutmaster Bucky
            American Labor Merit Badge Workbook to assist in readying
            themselves for the class. Having written notes for all of the items
            required will prove to be beneficial when sharing their brief
            descriptions with the counselor and class. Scouts not choosing to
            prepare ahead of time may find it difficult to complete this
            requirement as well as many of the others.
- requirement: 2
  text: |-
      With your counselor’s and parent’s approval and permission, visit the
      office or attend a meeting of a local union, a central labor council, or
      an employee organization, or contact one of these organizations via the
      internet. Then do EACH of the following:
  workbook:
      - signature: Counselor
      - signature: Parent
  children:
      - requirement: a
        text: |-
            Find out what the organization does.
        workbook:
            - lines: 8
      - requirement: b
        text: |-
            Share the list of issues and concerns you made for requirement 1.
            Ask the people you communicate with which issues are of greatest
            interest or concern to them and why.
        workbook:
            - lines: 8
      - requirement: c
        text: |-
            Draw a diagram showing how the organization is structured, from the
            local to the national level, if applicable.
        workbook:
            - area: 40
      - note:
            - inPerson
            - online
        text: |-
            Scouts may work on this prior to the class, but please note that
            the counselor reserves the right to accept or deny your work on the
            basis of meeting the expectations of this requirement and it's
            components to their satisfaction. Make sure your work is pertinent
            to the requirement and be prepared to share your work.

            Scouts not having done preparation work on this requirement will
            have an opportunity to review options with the counselor to pursue
            after the class.
- requirement: 3
  text: |-
      Explain to your counselor what labor unions are, what they do, and what
      services they provide to members. In your discussion, show that you
      understand the concepts of labor, management, collective bargaining,
      negotiation, union shops, open shops, grievance procedures, mediation,
      arbitration, work stoppages, strikes, and lockouts.
  workbook:
      - lines: 8
        text: |-
            What labor unions are
      - lines: 8
        text: |-
            What labor unions do
      - lines: 8
        text: |-
            What services labor unions provide to members
      - header: true
        text: |-
            Show that you understand the concepts
      - lines: 8
        text: |-
            Labor
      - lines: 8
        text: |-
            Management
      - lines: 8
        text: |-
            Collective bargaining
      - lines: 8
        text: |-
            Negotiation
      - lines: 8
        text: |-
            Union shops
      - lines: 8
        text: |-
            Open shops
      - lines: 8
        text: |-
            Grievance procedure
      - lines: 8
        text: |-
            Mediation
      - lines: 8
        text: |-
            Arbitration
      - lines: 8
        text: |-
            Work stoppages
      - lines: 8
        text: |-
            Strikes
      - lines: 8
        text: |-
            Lockouts
  children:
      - note:
            - inPerson
            - online
        text: |-
            Scouts should have this written out to show the counselor that some
            thought and research has gone into this requirement and Scouts
            should be prepared to explain their findings.
- requirement: 4
  text: |-
      Explain what is meant by the adversarial model of labor-management
      relations, compared with a cooperative-bargaining style.
  workbook:
      - lines: 8
  children:
      - note:
            - inPerson
            - online
        text: |-
            This requirement will be covered in class however Scouts should
            have read the section in the merit badge pamphlet that references
            this subject and be prepared to help give explanation from their
            readings and research in the class in order to complete this
            requirement.
- requirement: 5
  text: |-
      Do ONE of the following:
  children:
      - requirement: a
        text: |-
            Develop a time line of significant events in the history of the
            American labor movement from the 1770s to the present.
        workbook:
            - lines: 8
      - requirement: b
        text: |-
            Prepare an exhibit, a scrapbook, or a computer presentation, such
            as a slide show, illustrating three major achievements of the
            American labor movement and how those achievements affect American
            workers.
        workbook:
            - task: true
      - requirement: c
        text: |-
            With your counselor’s and parent’s approval and permission, watch a
            movie that addresses organized labor in the United States.
            Afterward, discuss the movie with your counselor and explain what
            you learned.
        workbook:
            - lines: 2
              text: |-
                  Movie title
            - signature: Councelor
            - signature: Parent
            - lines: 8
              text: |-
                  What you have learned
      - requirement: d
        text: |-
            Read a biography (with your counselor’s approval) of someone who
            has made a contribution to the American labor movement. Explain
            what contribution this person has made to the American labor
            movement.
        workbook:
            - lines: 2
              text: |-
                  Biography title
            - signature: Counselor
            - lines: 8
              text: |-
                  What contribution this person has made to the American labor
                  movement
      - note:
            - inPerson
            - online
        text: |-
            Scouts should choose one of the options in this requirement to work
            on prior to the class and bring their completed work to the class
            ready to share for completion.
- requirement: 6
  markdown: true
  text: |-
      Explain the term *globalization*. Discuss with your counselor some
      effects of globalization on the workforce in the United States. Explain
      how this global workforce fits into the economic system of this country.
  workbook:
      - lines: 8
        markdown: true
        text: |-
            Explain the term *globalization*.
      - lines: 8
        text: |-
            Some effects of globalization on the workforce in the United States
      - lines: 8
        text: |-
            How this global workforce fits into the economic system of this
            country
  children:
      - note:
            - inPerson
            - online
        text: |-
            Scouts should review this requirement and its elements and be
            prepared to explain. It is strongly recommended that Scouts bring
            any notes or supporting documents they may have to help show the
            counselor that they have prepared for explanation of these items.
- requirement: 7
  text: |-
      Choose a labor issue of widespread interest to American workers—an issue
      in the news currently or known to you from your work on this merit badge.
      Before your counselor, or in writing, argue both sides of the issue,
      first taking management’s side, then presenting labor’s or the employee’s
      point of view.  In your presentation, summarize the basic rights and
      responsibilities of employers and employees, including union members and
      nonunion members.
  workbook:
      - lines: 2
        text: |-
            Selected labor issue
      - lines: 8
        text: |-
            Managements' points on this issue
      - lines: 8
        text: |-
            Laborers' points on this issue
      - lines: 8
        text: |-
            Summary of basic rights and responsibilities of employer
      - lines: 8
        text: |-
            Summary of basic rights and responsibilities of employee
  children:
      - note:
            - inPerson
            - online
        text: |-
            Scouts should be prepared to share their findings with the class
            and should be prepared with this requirement prior to the class.
            1/2 of this requirement is preparation and research, the other 1/2
            which will be facilitated in the class is the presentation. Scouts
            cannot complete this requirement by only doing one or the other,
            both parts must be done. Scouts not coming to class with
            preparation work will find it difficult, if not impossible, to
            complete this requirement on the day of the class. Preparation is a
            MUST for this requirement along with active class participation.
- requirement: 8
  text: |-
      Discuss with your counselor the different goals that may motivate the
      owners of a business, its stockholders, its customers, its employees, the
      employees’ representatives, the community, and public officials. Explain
      why agreements and compromises are made and how they affect each group in
      achieving its goals.
  workbook:
      - header: true
        text: |-
            Different goals that may motivate
      - lines: 8
        text: |-
            Owners of a business
      - lines: 8
        text: |-
            Stockholders
      - lines: 8
        text: |-
            Customers
      - lines: 8
        text: |-
            Employees
      - lines: 8
        text: |-
            Employees' representatives
      - lines: 8
        text: |-
            The community
      - lines: 8
        text: |-
            Public officals
      - header: true
        text: |-
            Agreements and compromises
      - lines: 8
        text: |-
            Why agreements and compromises are made
      - lines: 8
        text: |-
            How agreements and compromises affect owners of a business
      - lines: 8
        text: |-
            How agreements and compromises affect stockholders
      - lines: 8
        text: |-
            How agreements and compromises affect customers
      - lines: 8
        text: |-
            How agreements and compromises affect employees
      - lines: 8
        text: |-
            How agreements and compromises affect employees' representatives
      - lines: 8
        text: |-
            How agreements and compromises affect the community
      - lines: 8
        text: |-
            How agreements and compromises affect public officals
  children:
      - note:
            - inPerson
            - online
        text: |-
            This requirement will be completed as a part of this class. Scouts
            should come prepared having reviewed the information in the merit
            badge pamphlet and be knowledgeable of the components of this
            requirement.
- requirement: 9
  text: |-
      Learn about opportunities in the field of labor relations. Choose one
      career in which you are interested and discuss with your counselor the
      major responsibilities of that position and the qualifications,
      education, and training such a position requires.
  workbook:
      - lines: 8
        text: |-
            Opportunities in the field of labor relations
      - lines: 2
        text: |-
            Selected career opportunity
      - lines: 8
        text: |-
            Major responsibilities
      - lines: 8
        text: |-
            Qualifications
      - lines: 8
        text: |-
            Education
      - lines: 8
        text: |-
            Training
  children:
      - note:
            - inPerson
            - online
        text: |-
            Scouts should review this requirement and its components and be
            prepared to share their findings in class.
