- requirement: 1
  text: |-
    Do the following:
  children:
    - requirement: a
      text: |-
        Explain to your counselor how Scouting's Safe Swim Defense plan
        anticipates, helps prevent and mitigate, and provides responses to
        likely hazards you may encounter during swimming activities.
    - requirement: b
      text: |-
        Discuss the prevention and treatment of health concerns that could
        occur while swimming, including hypothermia, dehydration, sunburn, heat
        exhaustion, heatstroke, muscle cramps, hyperventilation, spinal injury,
        stings and bites, and cuts and scrapes.
- requirement: 2
  text: |-
      Before doing the following requirements, successfully complete the BSA
      swimmer test: Jump feetfirst into water over the head in depth. Level off
      and swim 75 yards in a strong manner using one or more of the following
      strokes: sidestroke, breaststroke, trudgen, or crawl; then swim 25 yards
      using an easy, resting backstroke. The 100 yards must be completed in one
      swim without stops and must include at least one sharp turn. After
      completing the swim, rest by floating.
- requirement: 3
  text: |-
      Correctly perform the following strokes:
  children:
    - requirement: a
      text: |-
          Demonstrate the front crawl or the trudgen using good form.
    - requirement: b
      text: |-
          Demonstrate the back crawl using good form.
    - requirement: c
      text: |-
          Demonstrate the sidestroke using good form.
    - requirement: d
      text: |-
          Demonstrate the breaststroke using good form.
    - requirement: e
      text: |-
          Demonstrate the elementary backstroke using good form.
- requirement: 4
  text: |-
    Swim continuously for 150 yards in a strong manner using each of the
    following strokes in any order; front crawl or trudgen (25 yards); back
    crawl (25 yards); sidestroke (25 yards); breaststroke (25 yards); and
    elementary backstroke (50 yards).
- requirement: 5
  text: |-
    Do the following:
  children:
    - requirement: a
      text: |-
        Demonstrate water rescue methods by reaching with your arm or leg, by
        reaching with a suitable object, and by throwing lines and objects.
        Explain why swimming rescues should not be attempted when a reaching or
        throwing rescue is possible, and explain why and how a rescue swimmer
        should avoid contact with the victim.
    - requirement: b
      text: |-
        With a helper and a practice victim, show a line rescue both as tender
        and as rescuer. The practice victim should be approximately 30 feet
        from shore in deep water.
- requirement: 6
  text: |-
    Do the following:
  children:
    - requirement: a
      text: |-
        Float faceup in a resting position for at least three minutes with
        minimal movement.
    - requirement: b
      text: |-
        Demonstrate survival floating for at least five minutes.
    - requirement: c
      text: |-
        While wearing a properly fitted U.S. Coast Guard-approved life jacket,
        demonstrate the HELP and huddle positions. Explain their purposes.
    - requirement: d
      text: |-
        Explain why swimming or survival floating will hasten the onset of
        hypothermia in cold water.
- requirement: 7
  text: |-
    In water over your head, but not to exceed 10 feet, do the following:
  children:
    - requirement: a
      text: |-
        Use the feetfirst method of surface diving and bring an object up from
        the bottom.
    - requirement: b
      text: |-
        Do a headfirst surface dive (pike or tuck), and bring the object up
        again.
    - requirement: c
      text: |-
        Do a headfirst surface dive to a depth of at least 5 feet and swim
        underwater for three strokes. Come to the surface, take a breath, and
        repeat the sequence twice.
- requirement: 8
  markdown: true
  text: |-
    Following the guidelines set in the BSA Safe Swim Defense, in water at
    least 7 feet deep`*`, show a standing headfirst dive from a dock or pool
    deck. Show a long shallow dive, also from the dock or pool deck.

    *`*` If your state, city, or local community requires a water depth greater
    than 7 feet, it is important to abide by that mandate.*
- requirement: 9
  text: |-
    Explain the health benefits of regular aerobic exercise, and discuss why
    swimming is favored as both fitness and therapeutic exercise.
