- requirement: 1
  text: |-
    Do the following:
  children:
    - requirement: a
      text: |-
        Explain to your counselor the hazards you are most likely to encounter while participating in kayaking activities, including weather and water-related hazards, and what you should do to anticipate, help prevent, mitigate, and respond to these hazards.
    - requirement: b
      text: |-
        Review prevention, symptoms, and first-aid treatment for the following injuries or illnesses that can occur while kayaking: blisters, cold-water shock and hypothermia, heat-related illnesses, dehydration, sunburn, sprains, and strains.
    - requirement: c
      text: |-
        Review the BSA Safety Afloat policy. Explain to your counselor how this applies to kayaking.
- requirement: 2
  text: |-
    Before doing requirements 3 through 8, successfully complete the BSA swimmer test: Jump feetfirst into water over the head in depth. Level off and swim 75 yards in a strong manner using one or more of the following strokes: sidestroke, breaststroke, trudgen, or crawl; then swim 25 yards using an easy, resting backstroke.  The 100 yards must be completed in one swim without stops and must include at least one sharp turn. After completing the swim, rest by floating.
- requirement: 3
  text: |-
    Do the following:
  children:
    - requirement: a
      text: |-
        Review the characteristics of life jackets most appropriate for kayaking and understand why one must always be worn while paddling. Then demonstrate how to select and fit a life jacket for kayaking.
    - requirement: b
      text: |-
        Review the importance of safety equipment such as a signal device, extra paddle, sponge, bilge pump, flotation bags, and throw bag.
- requirement: 4
  text: |-
    Do the following:
  children:
    - requirement: a
      text: |-
        Name and point out the major parts of a kayak.
    - requirement: b
      text: |-
        Review the differences in the design between recreational, whitewater, and sea or touring kayaks. Include how length, width, stability, and rocker are involved in the design of each type.
    - requirement: c
      text: |-
        Explain the care, maintenance, and storage of a kayak.
- requirement: 5
  text: |-
    Discuss the following:
  children:
    - requirement: a
      text: |-
        How to use a kayak paddle.
    - requirement: b
      text: |-
        Parts of a paddle.
    - requirement: c
      text: |-
        The care and maintenance of a paddle.
- requirement: 6
  text: |-
    Using a properly equipped kayak with an open cockpit, a sit-on-top, or an inflatable kayak, do the following:
  children:
    - requirement: a
      text: |-
        Safely capsize and perform a wet exit.
    - requirement: b
      text: |-
        Reenter the kayak with assistance from a buddy boat.
    - requirement: c
      text: |-
        Demonstrate a kayak-over-kayak rescue.
    - requirement: d
      text: |-
        Demonstrate the HELP position.
    - requirement: e
      text: |-
        Capsize the kayak, swim it and the paddle to shore, and empty water from the kayak with assistance, if needed.
- requirement: 7
  text: |-
    As a solo paddler, use a properly equipped kayak to demonstrate the following:
  children:
    - requirement: a
      text: |-
        Forward stroke
    - requirement: b
      text: |-
        Reverse stroke
    - requirement: c
      text: |-
        Forward sweep
    - requirement: d
      text: |-
        Reverse sweep
    - requirement: e
      text: |-
        Draw stroke
    - requirement: f
      text: |-
        Stern draw
- requirement: 8
  text: |-
    As a solo paddler, use a properly equipped kayak to demonstrate the following:
  children:
    - requirement: a
      text: |-
        Paddle a straight line for 15 to 20 boat lengths using appropriate strokes while maintaining trim and balance of the kayak.
    - requirement: b
      text: |-
        Spin or pivot from a stationary position 180 degrees (half circle) to the right and left within two boat lengths.
    - requirement: c
      text: |-
        Move abeam to the right 10 feet and to the left 10 feet.
    - requirement: d
      text: |-
        Stop the boat in one boat length.
    - requirement: e
      text: |-
        While maintaining forward motion, turn the kayak 90 degrees to the right and left.
    - requirement: f
      text: |-
        Move the kayak backward three to four boat lengths using appropriate and effective reverse strokes.
    - requirement: g
      text: |-
        Paddle the kayak in a buoyed figure 8 course around markers three to four boat lengths apart.
