- requirement: 1
  text: |-
    Do the following:
  children:
    - requirement: a
      text: |-
        Explain the five range safety rules.
    - requirement: b
      text: |-
        Explain the four whistle commands used on the range.
    - requirement: c
      text: |-
        Explain how to safely remove arrows from the target and return them
        to your quiver.
    - requirement: d
      text: |-
        Tell about your local and state laws for owning and using archery
        equipment.
- requirement: 2
  text: |-
    Do the following:
  children:
    - requirement: a
      text: |-
        Name and point to the parts of an arrow.
    - requirement: b
      text: |-
        Describe three or more different types of arrows.
    - requirement: c
      text: |-
        Name the four principal materials for making arrow shafts.
    - requirement: d
      text: |-
        Do ONE of the following
      children:
        - requirement: 1
          text: |-
            Make a complete arrow from a bare shaft using appropriate
            equipment available to you.
        - callout: true
          text: |-
            OR
        - requirement: 2
          text: |-
            To demonstrate arrow repair, inspect the shafts and prepare
            and replace at least three vanes, one point, and one nock.
            You may use as many arrows as necessary to accomplish this.
            The repairs can be done on wood, fiberglass, or aluminum
            arrows.
    - requirement: e
      text: |-
        Explain how to properly care for and store arrows.
- requirement: 3
  text: |-
    Do the following:
  children:
    - requirement: a
      text: |-
        Explain the proper use, care, and storage of, as well as the
        reasons for using tabs, arm guards, shooting gloves, and quivers.
    - requirement: b
      text: |-
        Explain the following terms: draw length, draw weight, mechanical
        release and barebow.
    - requirement: c
      text: |-
        Make a bowstring using appropriate materials.
- requirement: 4
  text: |-
    Explain the following:
  children:
    - requirement: a
      text: |-
        The difference between an end and a round
    - requirement: b
      text: |-
        The differences among field, target, and 3-D archery
    - requirement: c
      text: |-
        How the five-color World Archery Federation target is scored
    - requirement: d
      text: |-
        How the National Field Archery Association (NFAA) black-and-white
        field targets and blue indoor targets are scored
- requirement: 5
  text: |-
    Do ONE of the following options.
  children:
    - detail: true
      markdown: true
      text: |-
        **Option A—Using a Recurve Bow or Longbow**
    - requirement: a
      text: |-
        Name and point to the parts of the recurve or longbow you are
        shooting.
    - requirement: b
      text: |-
        Explain how to properly care for and store recurve bows and
        longbows.
    - requirement: c
      text: |-
        Demonstrate and explain USA Archery's "Steps of Shooting" for the bow you are shooting.
    - requirement: d
      text: |-
        Demonstrate the proper way to string a recurve bow or longbow.
    - requirement: e
      text: |-
        Using a bow square, locate and mark with dental floss, crimp-on, or
        other method, the nocking point on the bowstring of the bow that
        you are using.
    - requirement: f
      text: |-
        Do ONE of the following:
      children:
        - requirement: 1
          text: |-
            Using a recurve or longbow and arrows with a finger release,
            shoot a single round of one of the following BSA, USA
            Archery, or NFAA rounds:
          children:
            - requirement: a
              text: |-
                An NFAA field round of 14 targets and make a score of
                60 points
            - requirement: b
              text: |-
                A BSA Scout field round of 14 targets and make a score
                of 80 points
            - requirement: c
              markdown: true
              text: |-
                A World Archery/USA Archery indoor`*` round and make a score of 80 points
            - requirement: d
              markdown: true
              text: |-
                An NFAA indoor * `round and make a score of 50 points
        - requirement: 2
          text: |-
            Shooting 30 arrows in five-arrow ends at an 80-centimeter
            (32-inch) five-color target at 10 yards and using the 10
            scoring regions, make a score of 150.
        - requirement: 3
          text: |-
            As a member of the USA Archery Junior Olympic Archery
            Development program (JOAD), earn your indoor or outdoor
            green, purple, and gray achievement award pins using a
            recurve bow or longbow.
        - requirement: 4
          text: |-
            As a member of the NFAA’s Junior Division, earn a Cub or
            Youth 100-score Progression Patch.
        - detail: true
          markdown: true
          text: |-
            `*` The indoor rounds can be shot outdoors if this is more convenient.
    - detail: true
      markdown: true
      text: |-
        **Option B—Using a Compound Bow**
    - requirement: a
      text: |-
        Name and point to the parts of the compound bow you are shooting.
    - requirement: b
      text: |-
        Explain how to properly care for and store compound bows.
    - requirement: c
      text: |-
        Demonstrate and explain USA Archery's "Steps of Shooting" for the
        bow you are shooting.
    - requirement: d
      text: |-
        Explain why it is necessary to have the string or cable on a
        compound bow replaced at an archery shop.
    - requirement: e
      text: |-
        Locate and mark with dental floss, crimp-on, or other method, the
        nocking point on the bowstring of the bow that you are using.
    - requirement: f
      text: |-
        Do ONE of the following:
      children:
        - requirement: 1
          text: |-
            Using a compound bow and arrows with a finger release, shoot
            a single round of one of the following BSA, USA Archery, or
            NFAA rounds:
          children:
            - requirement: a
              text: |-
                An NFAA field round of 14 targets and make a score of
                70 points
            - requirement: b
              text: |-
                A BSA Scout field round of 14 targets and make a score
                of 90 points
            - requirement: c
              markdown: true
              text: |-
                A World Archery/USA Archery indoor`*` round and make
                a score of 90 points
            - requirement: d
              markdown: true
              text: |-
                An NFAA indoor`*` round and make a score of 60 points
        - requirement: 2
          text: |-
            Shooting at an 80-centimeter (32-inch) five-color target
            using the 10 scoring regions, make a minimum score of 160
            points. Accomplish this in the following manner:
          children:
            - detail: true
              text: |-
                Shoot 15 arrows in five-arrow ends, at a distance of 10
                yards
            - callout: true
              text: |-
                AND
            - detail: true
              text: |-
                Shoot 15 arrows in five-arrow ends, at a distance of 15
                yards.
        - requirement: 3
          text: |-
            As a member of the USA Archery Junior Olympic Archery
            Development program (JOAD), earn your indoor or outdoor
            green, purple, and gray achievement award pins using a
            compound bow.
        - requirement: 4
          text: |-
            As a member of the NFAA’s Junior Division, earn a Cub or
            Youth 100-score Progression Patch.
        - detail: true
          markdown: true
          text: |-
            `*` The indoor rounds can be shot outdoors if this is more
            convenient.
