- requirement: 1
  text: |-
    Using X-ray (radiographic) films and with your counselor’s guidance,
    study the tooth structure and look for decay.  Then do the following:
  children:
    - requirement: a
      text: |-
        Using the radiographs as a guide, draw a lower molar.  Label its
        parts and surfaces. Show surrounding structures such as bone and
        gum tissues.
    - requirement: b
      text: |-
        Show on your drawing where the nerves and blood vessels enter and
        leave the tooth.
    - requirement: c
      text: |-
        Show on your drawing where bacterial plaque is most likely to be
        found.
- requirement: 2
  text: |-
    Do the following:
  children:
    - requirement: a
      text: |-
        Tell or write about what causes dental decay and gum disease. Tell
        how each of the following contributes to dental decay and gum
        disease: bacterial plaque, sugars, and acid.
    - requirement: b
      text: |-
        Tell the possible causes for traumatic tooth loss, describe the
        types of mouth guards used to help prevent tooth trauma, and list
        the athletic activities during which a person should wear a mouth
        guard.
    - requirement: c
      text: |-
        Explain the first-aid procedure for saving a tooth that has been
        knocked out.
    - requirement: d
      text: |-
        Discuss how the use of tobacco products can negatively affect your
        oral health.
- requirement: 3
  text: |-
    Arrange for a visit with a dentist. Before you go, ask whether your visit
    can include a dental examination and a plaque-control demonstration.
    Afterward, ask questions about things you want to know. Then tell your
    counselor what the dentist does during a checkup examination.
- requirement: 4
  text: |-
    Do TWO of the following:
  children:
    - requirement: a
      text: |-
        Name at least five instruments and five pieces of equipment a
        dentist uses.
    - requirement: b
      text: |-
        With the help of a dentist, prepare a dental stone cast using a
        vibrator, a mixing bowl, a water measure, a plastic measure, model
        stone, and a spatula.
    - requirement: c
      text: |-
        Keep a record of everything you eat for three days.  Circle those
        items that may provide the sugars that bacterial plaque needs to
        make acid. List snacks that you should avoid to help maintain the
        best oral health.
- requirement: 5
  text: |-
    Discuss with your merit badge counselor the following:
  children:
    - requirement: a
      text: |-
        How fluorides help prevent tooth decay and the ways fluorides can
        be provided to the teeth.
    - requirement: b
      text: |-
        How the mouth is related to the rest of the body.  Topics might
        include chewing, saliva, enzymes, nutrition, and speech.
- requirement: 6
  text: |-
    Do TWO of the following:
  children:
    - requirement: a
      text: |-
        Make a model tooth out of soap, clay, papier-mâché, or wax. Using a
        string and a large hand brush, show your troop or a school class
        proper toothbrushing and flossing procedures.
    - requirement: b
      text: |-
        Make a poster on the prevention of dental disease.  Show the
        importance of good oral health.
    - requirement: c
      text: |-
        Collect at least five advertisements for different toothpastes.
        List the claims that each one makes.  Tell about the accuracy of
        the advertisements.
    - requirement: d
      text: |-
        Write a feature story for your school newspaper on the proper care
        of teeth and gums. Include in your story how the use of tobacco
        products can negatively affect a person’s oral health.
    - requirement: e
      text: |-
        Make drawings and write about the progress of dental decay.
        Describe the types of dental filling and treatments a dentist can
        use to repair dental decay problems.
- requirement: 7
  text: |-
    Learn about career opportunities for both Doctor of Dental Surgery
    (D.D.S.) and auxiliary dental professions. Pick either general dentistry
    OR a dental specialty, plus one auxiliary dental profession. Find out
    about the education, training, and experience required for these two
    professions.  Discuss these with your counselor, and explain why these
    professions interest you.
