- requirement: 1
  text: |-
      Using X-ray (radiographic) films and with your counselor’s guidance,
      study the tooth structure and look for decay.  Then do the following:
  workbook:
      - task: true
        text: |-
          Studied the tooth structure and looked for decay
      - header: true
        markdown: true
        text: |-
            a. Using the radiographs as a guide, draw a lower molar.  Label its
            parts and surfaces. Show surrounding structures such as bone and
            gum tissues.

            b. Show on your drawing where the nerves and blood vessels enter
            and leave the tooth.

            c. Show on your drawing where bacterial plaque is most likely to be
            found.
      - area: 25
  children:
      - requirement: a
        text: |-
            Using the radiographs as a guide, draw a lower molar.  Label its
            parts and surfaces. Show surrounding structures such as bone and
            gum tissues.
        workbookHide: true
      - requirement: b
        text: |-
            Show on your drawing where the nerves and blood vessels enter and
            leave the tooth.
        workbookHide: true
      - requirement: c
        text: |-
            Show on your drawing where bacterial plaque is most likely to be
            found.
        workbookHide: true
      - note:
            - inPerson
            - online
        text: |-
            Scouts will find the use of the Dentistry Merit Badge Pamphlet to
            be the best resource to use when preparing for the class on this
            requirement.  The counselor / instructor will have the x-rays for
            Scouts to use during the class to help with finishing part of this
            requirement.  Scouts should consider doing as much preparation
            work, including understanding the terms and practices outlined in
            this requirement, to best be prepared for wok on this requirement
            in the class.
- requirement: 2
  text: |-
      Do the following:
  children:
      - requirement: a
        text: |-
            Tell or write about what causes dental decay and gum disease. Tell
            how each of the following contributes to dental decay and gum
            disease: bacterial plaque, sugars, and acid.
        workbook:
            - lines: 8
              text: |-
                  What causes dental decay and gum disease
            - lines: 8
              text: |-
                  How bacterial plaque contributes to dental decay and gum
                  disease
            - lines: 8
              text: |-
                  How sugars contribute to dental decay and gum disease
            - lines: 8
              text: |-
                  How acids contribute to dental decay and gum disease
      - requirement: b
        text: |-
            Tell the possible causes for traumatic tooth loss, describe the
            types of mouth guards used to help prevent tooth trauma, and list
            the athletic activities during which a person should wear a mouth
            guard.
        workbook:
            - lines: 8
              text: |-
                  Possible causes for traumatic tooth loss
            - lines: 8
              text: |-
                  Types of mouth guards used to help prevent tooth trauma
            - lines: 8
              text: |-
                  Athletic activities during which a person should wear a mouth
                  guard
      - requirement: c
        text: |-
            Explain the first-aid procedure for saving a tooth that has been
            knocked out.
        workbook:
            - lines: 8
      - requirement: d
        text: |-
            Discuss how the use of tobacco products can negatively affect your
            oral health.
        workbook:
            - lines: 8
      - note:
            - inPerson
            - online
        text: |-
            Scouts should review this requirement and its components and be
            prepared to discuss.  It is strongly recommended that Scouts bring
            any notes or supporting documents they may have to help show the
            counselor / instructor that they have prepared for discussion of
            these items.
- requirement: 3
  text: |-
      Arrange for a visit with a dentist. Before you go, ask whether your visit
      can include a dental examination and a plaque-control demonstration.
      Afterward, ask questions about things you want to know. Then tell your
      counselor what the dentist does during a checkup examination.
  workbook:
      - lines: 8
  children:
      - note:
            - inPerson
        text: |-
            Scouts will have an opportunity to complete this requirement during
            the class.  Before the class Scouts will need to work with their
            parents and visit a dentist and arrange for a dental examination.
            Bringing proof to the class is important to help show the counselor
            / instructor that the requirement has been worked on.  While a
            dental bill or slip will show that Scouts have visited their
            dentist, this is only part of the requirement.  As the requirement
            states Scouts are to ask questions of the dentist about things they
            want to know or observe during their visit.  It is strongly
            recommended that Scouts get a note from their dentist stating
            specifically their visit, as well as discussion, to ensure proper
            sign off on this requirement may be considered.
      - note:
            - online
        text: |-
            Scouts will need to work with their parents and visit a dentist and
            arrange for a dental examination.  Bringing proof to the class is
            important to help show the counselor / instructor that the
            requirement has been worked on.  While a dental bill or slip will
            show that Scouts have visited their dentist, this is only part of
            the requirement.  As the requirement states Scouts are to ask
            questions of the dentist about things they want to know or observe
            during their visit.  It is strongly recommended that Scouts get a
            note from their dentist stating specifically their visit, as well
            as discussion, to ensure proper sign off on this requirement may be
            considered.
- requirement: 4
  text: |-
      Do TWO of the following:
  children:
      - requirement: a
        text: |-
            Name at least five instruments and five pieces of equipment a
            dentist uses.
        workbook:
            - split:
                  - header: true
                    text: |-
                        Instruments
                  - header: true
                    text: |-
                        Pieces of equipment
            - split:
                  - lines: 2
                  - lines: 2
            - split:
                  - lines: 2
                  - lines: 2
            - split:
                  - lines: 2
                  - lines: 2
            - split:
                  - lines: 2
                  - lines: 2
            - split:
                  - lines: 2
                  - lines: 2
      - requirement: b
        text: |-
            With the help of a dentist, prepare a dental stone cast using a
            vibrator, a mixing bowl, a water measure, a plastic measure, model
            stone, and a spatula.
        workbook:
            - task: true
      - requirement: c
        text: |-
            Keep a record of everything you eat for three days.  Circle those
            items that may provide the sugars that bacterial plaque needs to
            make acid. List snacks that you should avoid to help maintain the
            best oral health.
        workbook:
            - lines: 20
              text: |-
                  Record of everything you eat for three days
            - lines: 8
              text: |-
                  List of snacks you should avoid to help maintain the best
                  oral health
      - note:
            - inPerson
        text: |-
            In most instances, Requirement 4b will be covered in the class
            (depending on the counselor), however Scouts should not assume this
            will be done and should consider doing Requirement 4b or 4c on
            their own in preparation for the class and to ensure the highest
            potential of completing Requirement 4 during the class.
      - note:
            - online
        text: |-
            Scouts will need to choose either Requirement component 4b or 4c to
            have completed and prepared for prior to the class.  Time will be
            given in the class to share and discuss their work with the
            counselor / instructor for consideration for sign off. Be Prepared.
- requirement: 5
  text: |-
      Discuss with your merit badge counselor the following:
  children:
      - requirement: a
        text: |-
            How fluorides help prevent tooth decay and the ways fluorides can
            be provided to the teeth.
        workbook:
            - lines: 8
      - requirement: b
        text: |-
            How the mouth is related to the rest of the body.  Topics might
            include chewing, saliva, enzymes, nutrition, and speech.
        workbook:
            - lines: 8
      - note:
            - inPerson
            - online
        text: |-
            Scouts should utilize the Dentistry Merit Badge pamphlet to read
            and prepare for discussion on this requirement during the class.
            It will be difficult to complete this requirement without
            preparation ahead of time and only those who actively and
            positively participate in the class discussion will be considered
            for sign off on this requirement.
- requirement: 6
  text: |-
      Do TWO of the following:
  children:
      - requirement: a
        text: |-
            Make a model tooth out of soap, clay, papier-mâché, or wax. Using a
            string and a large hand brush, show your troop or a school class
            proper toothbrushing and flossing procedures.
        workbook:
            - task: true
      - requirement: b
        text: |-
            Make a poster on the prevention of dental disease.  Show the
            importance of good oral health.
        workbook:
            - task: true
      - requirement: c
        text: |-
            Collect at least five advertisements for different toothpastes.
            List the claims that each one makes.  Tell about the accuracy of
            the advertisements.
        workbook:
            - task: true
      - requirement: d
        text: |-
            Write a feature story for your school newspaper on the proper care
            of teeth and gums. Include in your story how the use of tobacco
            products can negatively affect a person’s oral health.
        workbook:
            - task: true
      - requirement: e
        text: |-
            Make drawings and write about the progress of dental decay.
            Describe the types of dental filling and treatments a dentist can
            use to repair dental decay problems.
        workbook:
            - task: true
      - note:
            - inPerson
            - online
        text: |-
            This requirement may be done prior to or after the class.  Time MAY
            be given during the class to work on this requirement with the
            guidance of the counselor / instructor, however Scouts should
            consider choosing two of the components from this requirement and
            prepare their work ahead of time.  Bring this work with to share
            with the counselor / instructor and class for review and sign off.
- requirement: 7
  text: |-
      Learn about career opportunities for both Doctor of Dental Surgery
      (D.D.S.) and auxiliary dental professions. Pick either general dentistry
      OR a dental specialty, plus one auxiliary dental profession. Find out
      about the education, training, and experience required for these two
      professions.  Discuss these with your counselor, and explain why these
      professions interest you.
  workbook:
      - lines: 8
        text: |-
            Career opportunities
      - lines: 8
        text: |-
            Education, training, and experience required for a general
            dentistry or dental specialty
      - lines: 8
        text: |-
            Education, training, and experience required for an auxiliary
            dental profession
  children:
      - note:
            - inPerson
            - online
        text: |-
            Scouts should review this requirement and its components and be
            prepared to discuss.  It is strongly recommended that Scouts bring
            any notes or supporting documents they may have to help show the
            counselor that they have prepared for discussion of these items.
