- requirement: 1
  text: |-
      Do the following:
  children:
      - requirement: a
        text: |-
            Define “aircraft.” Describe some kinds and uses of aircraft today.
            Explain the operation of piston, turboprop, and jet engines.
        workbook:
            - lines: 8
              text: |-
                  Define "aircraft."
            - lines: 8
              text: |-
                  Describe some kinds and uses of aircraft today
            - lines: 8
              text: |-
                  Explain the operation of piston engines
            - lines: 8
              text: |-
                  Explain the operation of turboprop engines
            - lines: 8
              text: |-
                  Explain the operation of jet engines
        children:
            - note:
                  - inPerson
                  - online
              text: |-
                  Scouts should review the Merit Badge Pamphlet and be prepared
                  to share their findings during the class.
      - requirement: b
        text: |-
            Point out on a model airplane the forces that act on an airplane in
            flight.
        workbook:
            - lines: 8
        children:
            - note:
                  - inPerson
                  - online
              text: |-
                  While a portion of this requirement will be done in class,
                  Scouts will need to review the expectations of this part of
                  the requirement and be prepared to share their knowledge and
                  proficiency during the class to complete this part of the
                  requirement.
      - requirement: c
        text: |-
            Explain how an airfoil generates lift, how the primary control
            surfaces (ailerons, elevators, and rudder) affect the airplane’s
            attitude, and how a propeller produces thrust.
        workbook:
            - lines: 8
              text: |-
                  How an airfoil generates lift
            - lines: 8
              text: |-
                  How the primary control surfaces affect the airplane's
                  attitude
            - lines: 8
              text: |-
                  How a propeller produces thrust
        children:
            - note:
                  - inPerson
                  - online
              text: |-
                  Scouts will need to review the Merit Badge Pamphlet and find
                  information that will assist them in completing this part of
                  Requirement 1. It is recommended that Scouts make notes in a
                  Merit Badge Workbook to utilize in providing an explanation,
                  as required, during the class.
      - requirement: d
        text: |-
            Demonstrate how the control surfaces of an airplane are used for
            takeoff, straight climb, level turn, climbing turn, descending
            turn, straight descent, and landing.
        workbook:
            - task: true
        children:
            - note:
                  - inPerson
                  - online
              text: |-
                  While the counselor / instructor will assist in ensuring
                  Scouts have an understanding of the physics referenced within
                  this requirement, only Scouts who have reviewed the Merit
                  Badge Pamphlet and can demonstrate these principles will have
                  the ability to be signed off on this part of the requirement.
                  Scouts arriving at the class not having prepared for this
                  requirement will NOT be able to fully complete it exclusively
                  during the class. Be Prepared.
      - requirement: e
        text: |-
            Explain the following: the sport pilot, the recreational pilot, and
            the private pilot certificates; the instrument rating.
        workbook:
            - lines: 8
              text: |-
                  Explain the sport pilot certificate
            - lines: 8
              text: |-
                  Explain the recreational pilot certificate
            - lines: 8
              text: |-
                  Explain the private pilot certificate
            - lines: 8
              text: |-
                  Explain the instrument rating
        children:
            - note:
                  - inPerson
                  - online
              text: |-
                  Scouts will find preparing for this component of Requirement
                  1 will be most easily completed by reviewing the Merit Badge
                  Pamphlet. Scouts should mark their Merit Badge Pamphlet or
                  utilize a Merit Badge Workbook to record their findings for
                  easy reference when required to give explanation on this
                  component during the class.
- requirement: 2
  text: |-
      Do TWO of the following:
  children:
      - requirement: a
        text: |-
            Take a flight in an aircraft, with your parent’s permission.
            Record the date, place, type of aircraft, and duration of flight,
            and report on your impressions of the flight.
        workbook:
            - lines: 8
      - requirement: b
        text: |-
            Under supervision, perform a preflight inspection of a light
            airplane.
        workbook:
            - task: true
      - requirement: c
        text: |-
            Obtain and learn how to read an aeronautical chart.  Measure a true
            course on the chart. Correct it for magnetic variation, compass
            deviation, and wind drift to determine a compass heading.
        workbook:
            - task: true
      - requirement: d
        text: |-
            Using one of many flight simulator software packages available for
            computers, “fly” the course and heading you established in
            requirement 2c or another course you have plotted.
        workbook:
            - task: true
      - requirement: e
        text: |-
            Explain the purposes and functions of the various instruments found
            in a typical single-engine aircraft: attitude indicator, heading
            indicator, altimeter, airspeed indicator, turn and bank indicator,
            vertical speed indicator, compass, navigation (GPS and VOR) and
            communication radios, tachometer, oil pressure gauge, and oil
            temperature gauge.
        workbook:
            - lines: 8
              text: |-
                  Attitude indicator
            - lines: 8
              text: |-
                  Heading indicator
            - lines: 8
              text: |-
                  Altimeter
            - lines: 8
              text: |-
                  Airspeed indicator
            - lines: 8
              text: |-
                  Turn and bank indicator
            - lines: 8
              text: |-
                  Vertical speed indicator
            - lines: 8
              text: |-
                  Compass
            - lines: 8
              text: |-
                  Navigation (GPS and VOR) and communication radios
            - lines: 8
              text: |-
                  Tachometer
            - lines: 8
              text: |-
                  Oil pressure gauge
            - lines: 8
              text: |-
                  Oil temperature gauge
      - requirement: f
        text: |-
            Create an original poster of an aircraft instrument panel.  Include
            and identify the instruments and radios discussed in requirement
            2e.
        workbook:
            - area: 45
      - note:
            - inPerson
        text: |-
            Most classes will focus on Requirements 2e and 2f. Scouts should
            come prepared to participate in completion of these two
            requirements that will be led by the counselor during the class.
            Remember that sign off on ANY requirement is at the discretion of
            the counselor and active participation during the class will be one
            way the counselor can best assess a Scout's understanding and
            successful completion. Scouts attending the class that have NOT
            done preparation work should expect to complete Requirement 2.
            Scouts choosing to work on a different option(s) may do so and
            bring their work to class for review and consideration by the
            counselor, however, Scouts will still be expected to willingly and
            appropriately participate in any class activities.
      - note:
            - online
        text: |-
            Scouts should select the two requirement components they want to do
            and be prepared with their work to share during the class with the
            counselor / instructor. Scouts not having done pre-work on this
            requirement will not be able to receive sign off on this
            requirement.  Any signed off partial or completion of this
            requirement will be at the discretion and satisfaction of the merit
            badge counselor / instructor.
- requirement: 3
  text: |-
      Do ONE of the following:
  children:
      - requirement: a
        text: |-
            Build and fly a fuel-driven or battery-powered electric model
            airplane. Describe safety rules for building and flying model
            airplanes. Tell safety rules for use of glue, paint, dope,
            plastics, fuel, and battery pack.
        workbook:
            - lines: 8
              text: |-
                  Safety rules for building and flying model airplanes
            - lines: 8
              text: |-
                  Safety rules for use of glue, paint, dope, plastics, fuel,
                  and battery pack
      - requirement: b
        text: |-
            Build a model FPG-9. Get others in your troop or patrol to make
            their own model, then organize a competition to test the precision
            of flight and landing of the models.
        workbook:
            - task: true
      - note:
            - inPerson
            - online
        text: |-
            This requirement will NOT be done in the class. Scouts may choose
            to complete this requirement ahead of time or complete this after
            the class. The class will focus some time for discussion of this
            requirement as well as the sharing of any video, pictures, and/or
            documentation to support their completion of this requirement. Only
            Scouts that share their work to the satisfaction of the counselor
            will have an opportunity to complete this requirement during the
            class.
- requirement: 4
  text: |-
      Do ONE of the following:
  children:
      - requirement: a
        text: |-
            Visit an airport. After the visit, report on how the facilities are
            used, how runways are numbered, and how runways are determined to
            be “active.”
        workbook:
            - lines: 8
      - requirement: b
        text: |-
            Visit a Federal Aviation Administration facility—a control tower,
            terminal radar control facility, air route traffic control center,
            or Flight Standards District Office. (Phone directory listings are
            under U.S. Government Offices, Transportation Department, Federal
            Aviation Administration. Call in advance.) Report on the operation
            and your impressions of the facility.
        workbook:
            - lines: 8
      - requirement: c
        text: |-
            Visit an aviation museum or attend an air show. Report on your
            impressions of the museum or show.
        workbook:
            - lines: 8
      - note:
            - inPerson
            - online
        text: |-
            Scouts should bring with them to class some sort of proof (a note
            signed by the host, your parent, teacher, Scoutmaster, or other) to
            help validate to the counselor / instructor completion of the visit
            that is noted in this requirement along with some sort of summary
            for the option selected. Ideally Scouts should include some sort of
            additional information to share from their visit (a brochure, a
            ticket stub, pictures, etc). Scouts will be asked to share their
            experience with the counselor / instructor and other attending
            Scouts. It is suggested Scouts may want to consider making notes in
            order to organize and formulate their description and explanation
            required for this requirement.
- requirement: 5
  text: |-
      Find out about three career opportunities in aviation. Pick one and find
      out the education, training, and experience required for this profession.
      Discuss this with your counselor, and explain why this profession might
      interest you.
  workbook:
      - lines: 8
        text: |-
            Three career opportunities in aviation
      - lines: 8
        text: |-
            Education, training, and experience required for one profession
  children:
      - note:
            - inPerson
            - online
        text: |-
            Scouts should review this requirement and its components and be
            prepared to discuss.  It is strongly recommended that Scouts bring
            any notes or supporting documents they may have to help show the
            counselor that they have prepared for completion of this
            requirement.
