- requirement: 1
  text: |-
    Select three of the professions from Group 1 listed below which interest
    you, then complete the following:
  children:
    - requirement: a
      text: |-
        Briefly describe to your counselor the roles these professionals
        play in the delivery of health care.
    - requirement: b
      text: |-
        Describe to your counselor the educational and licensing
        requirements for the professionals you selected.
    - detail: true
      markdown: true
      text: |-
        **Group 1:**<br/>
        (1) Allopathic physician (MD) — all specialties<br/>
        (2) Osteopathic physician (DO) — all specialties<br/>
        (3) Podiatrist (DPM)<br/>
        (4) Chiropractor (DC)<br/>
        (5) Nurse Practitioner (NP)<br/>
        (6) Psychologist (PhD or PsyD)<br/>
        (7) Optometrist (OD)<br/>
        (8) Audiologist (AudD)
    - note:
        - inPerson
        - online
      text: |-
        Scouts should review this requirement and its components and be
        prepared to discuss. This should be done prior to the class. Scouts
        should have this written out to show the counselor that thought and
        research has gone into this requirement and Scouts should be
        prepared to explain their findings. Scouts will not automatically
        be signed off on this requirement just for attending as the
        requirement states that they must explain a number of items and
        will be required to partake in group and/or individual explanation
        to obtain credit.
- requirement: 2
  text: |-
    Select three of the professions from Group 2 listed below which interest
    you, then complete the following:
  children:
    - requirement: a
      text: |-
        Briefly describe to your counselor the roles these professionals
        play in the delivery of health care.
    - requirement: b
      text: |-
        Describe to your counselor the educational and licensing
        requirements for the professionals you selected.
    - detail: true
      markdown: true
      text: |-
        **Group 2:**<br/>
        (1) Physician Assistant (PA)<br/>
        (2) Registered Nurse (RN)<br/>
        (3) Certified Nurse Midwife (CNM)<br/>
        (4) Certified Nurse Assistant (CNA)<br/>
        (5) Licensed Practical Nurse (LPN/LVN)<br/>
        (6) Nurse Anesthetist (CRNA)<br/>
        (7) Pharmacist (PharmD)<br/>
        (8) Pharmacy Technician<br/>
        (9) Emergency Medical Technician (EMT)/Paramedic
    - note:
        - inPerson
        - online
      text: |-
        Scouts should review this requirement and its components and be
        prepared to discuss. This should be done prior to the class. Scouts
        should have this written out to show the counselor that thought and
        research has gone into this requirement and Scouts should be
        prepared to explain their findings. Scouts will not automatically
        be signed off on this requirement just for attending as the
        requirement states that they must explain a number of items and
        will be required to partake in group and/or individual explanation
        to obtain credit.
- requirement: 3
  text: |-
    Select three of the professions from Group 3 listed below which interest
    you, then complete the following:
  children:
    - requirement: a
      text: |-
        Briefly describe to your counselor the roles these professionals
        play in the delivery of health care.
    - requirement: b
      text: |-
        Describe to your counselor the educational and licensing
        requirements for the professionals you selected.
    - detail: true
      markdown: true
      text: |-
        **Group 3:**<br/>
        (1) Physical Therapist (DPT)<br/>
        (2) Occupational Therapist (OT)<br/>
        (3) Orthotist/Prosthetist<br/>
        (4) Medical Appliance Technician<br/>
        (5) Respiratory Therapist (RT)<br/>
        (6) Medical Assistant<br/>
        (7) Dietitian (RD)<br/>
        (8) Speech-Language Pathologist (Speech Therapist) (SLP)
    - note:
        - inPerson
        - online
      text: |-
        Scouts should review this requirement and its components and be
        prepared to discuss. This should be done prior to the class. Scouts
        should have this written out to show the counselor that thought and
        research has gone into this requirement and Scouts should be
        prepared to explain their findings. Scouts will not automatically
        be signed off on this requirement just for attending as the
        requirement states that they must explain a number of items and
        will be required to partake in group and/or individual explanation
        to obtain credit.
- requirement: 4
  text: |-
    Select three of the professions from Group 4 listed below which interest
    you, then complete the following:
  children:
    - requirement: a
      text: |-
        Briefly describe to your counselor the roles these professionals
        play in the delivery of health care.
    - requirement: b
      text: |-
        Describe to your counselor the educational and licensing
        requirements for the professionals you selected.
    - detail: true
      markdown: true
      text: |-
        **Group 4:**<br/>
        (1) Biomedical Engineer (BME)<br/>
        (2) Medical Technologist<br/>
        (3) Phlebotomist<br/>
        (4) Radiology Technologist<br/>
        (5) Sonographer<br/>
        (6) Medical Records Specialist<br/>
        (7) Cytopathologist<br/>
        (8) Histotechnologist
    - note:
        - inPerson
        - online
      text: |-
        Scouts should review this requirement and its components and be
        prepared to discuss. This should be done prior to the class. Scouts
        should have this written out to show the counselor that thought and
        research has gone into this requirement and Scouts should be
        prepared to explain their findings. Scouts will not automatically
        be signed off on this requirement just for attending as the
        requirement states that they must explain a number of items and
        will be required to partake in group and/or individual explanation
        to obtain credit.
- requirement: 5
  text: |-
    Select one career from any of the lists in Requirements 1, 2, 3, or 4 and
    arrange to visit that professional at their workplace. Discuss with your
    counselor the following:
  children:
    - requirement: a
      text: |-
        Why did they choose their particular career?
    - requirement: b
      text: |-
        What do they most like about their job?
    - requirement: c
      text: |-
        What are their biggest challenges in doing their job?
    - requirement: d
      text: |-
        Identify the tools/instruments that may be used in their jobs.
    - requirement: e
      text: |-
        What has been the most surprising aspect of their career?
    - requirement: f
      # Added a question mark at the end for consistency
      text: |-
        What continuing education requirements are required to maintain
        certification?
    - note:
        - inPerson
        - online
      text: |-
        Requirement 5 will NOT be completed as a part of the class,
        however, Scouts will have an opportunity to complete this
        requirement an its components during the class if they have
        completed their visit with their selected health care professional.
        It is not enough to have just visited with a health care
        professional, the other parts of this requirement require questions
        to be asked and answers to be shared during the class and counselor
        review. Only Scouts who actively share their findings to the
        satisfaction of the counselor / instructor will have the
        opportunity for completion of this requirement.
- requirement: 6
  text: |-
    Discuss with your counselor your understanding of the meaning of the
    Physician’s Oath.
  children:
    - note:
        - inPerson
        - online
      text: |-
        Scouts will find reviewing the Health Care Professions Merit Badge
        pamphlet will yield a better understanding of this requirement and
        aid them in preparation for their explanation during the class.
- requirement: 7
  # Corrected spelling of confidentiality
  text: |-
    Describe the role of confidentiality between a patient and the health
    care provider. What is HIPAA?
  children:
    - note:
        - inPerson
        - online
      text: |-
        While the counselor / instructor will help facilitate the class
        discussion on this requirement, Scouts will need to prepare by
        referencing the Health Care Professions Merit Badge pamphlet
        section covering these topics. Additional resource may be utilized
        to prepare for class discussion.
- requirement: 8
  text: |-
    Identify a medical advancement or discovery that has been in the news
    recently. Discuss with your counselor how this can affect patient care.
  children:
    - note:
        - inPerson
        - online
      text: |-
        Scouts will need to do preparation work for this requirement prior
        to the class.  The counselor / instrucotr will allot time for
        discussion to those Scouts who come to the class with this
        requirement prepared for discussion.  Scouts should not expect to
        gain credit for this requirement if they have not done proper
        preparation work. Be Prepared!
- requirement: 9
  text: |-
    With approval of your counselor and parents/guardian, serve as a
    volunteer at a health-related event or facility in your community (e.g.
    blood drive, health fair, blood pressure screening event). Report to your
    counselor what you did and learned from the experience.
  children:
    - note:
        - inPerson
        - online
      text: |-
        This requirement will NOT be covered within the class, however
        Scouts wishing to be considered for completion of this requirement
        should bring adequate documentation to show that they have
        completed the volunteer activity at a health-related event or
        facility. Adequate documentation is not a letter from your parent,
        but rather a letter or note on organizational letterhead from a
        representative of the organization where you performed your
        volunteer time. Please remember that the merit badge counselor
        reserves the right to accept or reject your chosen activity if they
        do not feel it meets their interpretation of the requirement.
