- requirement: 1
  text: |-
      Explain the meaning of “animal,” “invertebrate,” “vertebrate,” and “mammal.” Name three characteristics that distinguish mammals from all other animals.
  workbook:
    - lines: 8
      text: |-
        Animal
    - lines: 8
      text: |-
        Invertebrate
    - lines: 8
      text: |-
        Vertebrate
    - lines: 8
      text: |-
        Mammal
    - lines: 8
      text: |-
        Three characteristics
- requirement: 2
  text: |-
      Explain how the animal kingdom is classified. Explain where mammals fit in the classification of animals.  Classify three mammals from phylum through species.
  workbook:
    - lines: 8
      text: |-
        How the animal kingdom is classified
    - lines: 8
      text: |-
        First animal
    - lines: 8
      text: |-
        Second animal
    - lines: 8
      text: |-
        Third animal
- requirement: 3
  text: |-
      Do ONE of the following:
  children:
      - requirement: a
        text: |-
            Spend three hours in each of two different kinds of natural habitats or at different elevations. List the different mammal species and individual members that you identified by sight or sign. Tell why all mammals do not live in the same kind of habitat.
        workbook:
          - lines: 8
      - requirement: b
        text: |-
            Spend three hours on each of five days on at least a 25-acre area (about the size of 31/2 football fields).  List the mammal species you identified by sight or sign.
        workbook:
          - lines: 8
      - requirement: c
        text: |-
            From study and reading, write a simple life history of one nongame mammal that lives in your area. Tell how this mammal lived before its habitat was affected in any way by humans. Tell how it reproduces, what it eats, and its natural habitat. Describe its dependency upon plants and other animals (including humans), and how they depend upon it. Tell how it is helpful or harmful to humankind.
        workbook:
          - lines: 8
- requirement: 4
  text: |-
      Do ONE of the following:
  children:
      - requirement: a
        text: |-
            Under the guidance of a nature center or natural history museum, make two study skins of rats or mice. Tell the uses of study skins and mounted specimens respectively.
        workbook:
          - split: 
            - task: true
              text: |-
                First study skin
            - task: true
              text: |-
                Second study skin
          - lines: 8
      - requirement: b
        text: |-
            Take good pictures of two kinds of mammals in the wild. Record the date(s), time of day, weather conditions, approximate distance from the animal, habitat conditions, and any other factors you feel may have influenced the animal’s activity and behavior.
        workbook:
          - task: true
            text: |-
              Taken pictures
          - lines: 8
      - requirement: c
        text: |-
            Write a life history of a native game mammal that lives in your area, covering the points outlined in requirement 3c. List sources for this information.
        workbook:
          - task: true
      - requirement: d
        text: |-
            Make and bait a tracking pit. Report what mammals and other animals came to the bait.
        workbook:
          - lines: 8
      - requirement: e
        text: |-
            Visit a natural history museum. Report on how specimens are prepared and cataloged. Explain the purposes of museums.
        workbook:
          - lines: 8
      - requirement: f
        text: |-
            Write a report of 500 words on a book about a mammal species.
        workbook:
          - task: true
      - requirement: g
        text: |-
            Trace two possible food chains of carnivorous mammals from soil through four stages to the mammal.
        workbook:
          - lines: 8
            text: |-
              First food chain
          - lines: 8
            text: |-
              Second food chain
- requirement: 5
  text: |-
      Working with your counselor, select and carry out one project that will influence the numbers of one or more mammals.
  workbook:
    - task: true
