- requirement: 1
  text: |-
      Describe the identifying characteristics of six species of reptiles and
      four species of amphibians found in the United States. For any four of
      these, make sketches from your own observations or take photographs. Show
      markings, color patterns, or other characteristics that are important in
      the identification of each of the four species. Discuss the habits and
      habitats of all 10 species.
  workbook:
      - lines: 8
- requirement: 2
  text: |-
      Discuss with your merit badge counselor the approximate number of species
      and general geographic distribution of reptiles and amphibians in the
      United States.  Prepare a list of the most common species found in your
      local area or state.
  workbook:
      - lines: 8
- requirement: 3
  text: |-
      Describe the main differences between
  children:
      - requirement: a
        text: |-
            Amphibians and reptiles
        workbook:
            - lines: 4
      - requirement: b
        text: |-
            Alligators and crocodiles
        workbook:
            - lines: 4
      - requirement: c
        text: |-
            Toads and frogs
        workbook:
            - lines: 4
      - requirement: d
        text: |-
            Salamanders and lizards
        workbook:
            - lines: 4
      - requirement: e
        text: |-
            Snakes and lizards
        workbook:
            - lines: 4
- requirement: 4
  text: |-
      Explain how reptiles and amphibians are an important component of the
      natural environment. List four species that are officially protected by
      the federal government or by the state you live in, and tell why each is
      protected.  List three species of reptiles and three species of
      amphibians found in your local area that are not protected. Discuss the
      food habits of all 10 species.
  workbook:
      - lines: 8
- requirement: 5
  text: |-
      Describe how reptiles and amphibians reproduce.
  workbook:
      - lines: 8
- requirement: 6
  text: |-
      From observation, describe how snakes move forward. Describe the
      functions of the muscles, ribs, and belly plates.
  workbook:
      - lines: 8
- requirement: 7
  text: |-
      Describe in detail six venomous snakes and the one venomous lizard found
      in the United States. Describe their habits and geographic range. Tell
      what you should do in case of a bite by a venomous species.
  workbook:
      - lines: 4
        text: |-
            First snake
      - lines: 4
        text: |-
            Second snake
      - lines: 4
        text: |-
            Third snake
      - lines: 4
        text: |-
            Fourth snake
      - lines: 4
        text: |-
            Fifth snake
      - lines: 4
        text: |-
            Sixth snake
      - lines: 4
        text: |-
            Lizard
      - lines: 4
        text: |-
            What to do in case of a bite
- requirement: 8
  text: |-
      Do ONE of the following:
  children:
      - requirement: a
        markdown: true
        text: |-
            Maintain one or more reptiles or amphibians for at least a month.
            Record food accepted, eating methods, changes in coloration,
            shedding of skins, and general habits; or keep the eggs of a
            reptile from the time of laying until hatching; or keep the eggs of
            an amphibian from the time of laying until their transformation
            into tadpoles (frogs) or larvae (salamanders). Whichever you chose,
            keep records of and report to your counselor how you cared for your
            animal/eggs/larvae to include lighting, habitat, temperature and
            humidity maintenance, and any veterinary care requirements.

            NOTE: Scouts must not use venomous reptiles in fulfilling
            requirement 8a. Species listed by federal or state law as
            endangered, protected, or threatened must not be used as live
            specimens in completing requirement 8a. When you decide keeping
            your specimen is no longer possible or desired, be sure to find
            another appropriate home for it or return it to the wild at the
            location of capture. Check with your merit badge counselor for
            those instances where the return of these specimens would not be
            appropriate.

            Under the Endangered Species Act of 1973, some plants and animals
            are, or may be, protected by federal law. The same ones and/or
            others may be protected by state law. Be sure that you do not
            collect protected species.

            Your state may require that you purchase and carry a license to
            collect certain species. Check with the wildlife and fish and game
            officials in your state regarding species regulations before you
            begin to collect.
        workbook:
            - lines: 8
      - requirement: b
        text: |-
            Choose a reptile or amphibian that you can observe at a local zoo,
            aquarium, nature center, or other such exhibit (such as your
            classroom or school). Study the specimen weekly for a period of
            three months. At each visit, sketch the specimen in its captive
            habitat and note any changes in its coloration, shedding of skins,
            and general habits and behavior. Discuss with your counselor how
            the animal you observed was cared for to include its housing and
            habitat, how the lighting, temperature, and humidity were
            maintained, and any veterinary care requirements.

            Find out, either from information you locate on your own or by
            talking to the caretaker, what this species eats and what are its
            native habitat and home range, preferred climate, average life
            expectancy, and natural predators.  Also identify any human-caused
            threats to its population and any laws that protect the species and
            its habitat. After the observation period, share what you have
            learned with your counselor.
        workbook:
            - lines: 8
      - requirement: 9
        text: |-
            Do TWO of the following:
        children:
            - requirement: a
              text: |-
                  Identify at night three kinds of toads or frogs by their
                  voices. Imitate the song of each for your counselor. Stalk
                  each with a flashlight and discover how each sings and from
                  where.
              workbook:
                  - lines: 8
            - requirement: b
              text: |-
                  Identify by sight eight species of reptiles or amphibians.
              workbook:
                  - lines: 8
            - requirement: c
              text: |-
                  Using visual aids, give a brief talk to a small group on
                  three different reptiles and amphibians.
              workbook:
                  - lines: 8
- requirement: 10
  text: |-
      Tell five superstitions or false beliefs about reptiles and amphibians
      and give a correct explanation for each. Give seven examples of unusual
      behavior or other true facts about reptiles and amphibians.
  workbook:
      - lines: 8
        text: |-
            Five superstitions or false beliefs and correct explanations
      - lines: 8
        text: |-
            Seven examples of unusual behavior or true facts
