- requirement: 1
  markdown: true
  text: |-
      Earn the <a href="../dr-bernard-harris/">Dr. Bernard Harris</a> Supernova
      award.
- requirement: 2
  markdown: true
  text: |-
      Complete ONE additional <a href="../../scouts-bsa">Scouts BSA Nova
      award</a> for a total of four. (Note: This may be done at any time after
      becoming a member of Scouts BSA.)
- requirement: 3
  markdown: true
  text: |-
      Earn FOUR additional Supernova-approved merit badges from <a
      href="../../scouts-bsa/">the list provided</a>, other than the four
      earned while working on the <a href="../dr-bernard-harris/">Dr. Bernard
      Harris</a> Supernova award for a total of eight. (Note: These may be
      earned at any time after becoming a Scout.)

      <a href="../../../merit-badges/animal-science/">Animal Science</a>,
      <a href="../../../merit-badges/animal-science"></a>,
      <a href="archaeology"></a>,
      <a href="architecture"></a>,
      <a href="astronomy"></a>,
      <a href="automotive-maintenance"></a>,
      <a href="aviation"></a>,
      <a href="bird-study"></a>,
      <a href="chemistry"></a>,
      <a href="composite-materials"></a>,
      <a href="dentistry"></a>,
      <a href="digital-technology"></a>,
      <a href="drafting"></a>,
      <a href="electricity"></a>,
      <a href="electronics"></a>,
      <a href="energy"></a>,
      <a href="engineering"></a>,
      <a href="environmental-science"></a>,
      <a href="farm-mechanics"></a>,
      <a href="fish-and-wildlife-management"></a>,
      <a href="forestry"></a>,
      <a href="game-design"></a>,
      <a href="gardening"></a>,
      <a href="geocaching"></a>,
      <a href="geology"></a>,
      <a href="insect-study"></a>,
      <a href="inventing"></a>,
      <a href="mammal-study"></a>,
      <a href="medicine"></a>,
      <a href="mining-in-society"></a>,
      <a href="nature"></a>,
      <a href="nuclear-science"></a>,
      <a href="oceanography"></a>,
      <a href="plant-science"></a>,
      <a href="programming"></a>,
      <a href="pulp-and-paper"></a>,
      <a href="radio"></a>,
      <a href="reptile-and-amphibian-study"></a>,
      <a href="robotics"></a>,
      <a href="scuba-diving"></a>,
      <a href="signs-signals-and-codes"></a>,
      <a href="soil-and-water-conservation"></a>,
      <a href="space-exploration"></a>,
      <a href="surveying"></a>,
      <a href="sustainability"></a>,
      <a href="veterinary-medicine"></a>,
      <a href="weather"></a>,
      <a href="welding"></a>
- requirement: 4
  markdown: true
  text: |-
      Complete TWO additional <a href="../activity-topics/">Supernova activity
      topics</a>, one each in the two STEM areas NOT completed for the <a
      href="../dr-bernard-harris/">Dr. Bernard Harris</a> Supernova award.
      (Note: The intent is that upon completion of the Thomas Alva Edison
      Supernova award the Scout will have completed one Supernova activity
      topic in each of the four STEM areas.)
- requirement: 5
  markdown: true
  text: |-
      Participate in a local, state, or national science fair or mathematics
      competition OR any other equally challenging STEM-oriented competition or
      workshop approved by your mentor. An example of this would be an X-Prize
      type competition. (Note: The intent is that upon completion of the Thomas
      Alva Edison Supernova award, the Scout will have participated in two such
      events.)
- requirement: 6
  markdown: true
  text: |-
      Working with your mentor, organize and present a Nova award or other
      STEM-related program to a Cub Scout den or pack meeting. Be sure to
      receive approval from the appropriate unit leader. If a Cub Scout den or
      pack is not available, your presentation may be given to another youth
      group, such as your troop or at your place of worship. (Note: The intent
      is that upon completion of the Thomas Alva Edison Supernova award the
      Scout will have completed two such presentations.)
- requirement: 7
  text: |-
      Research a scientific, technical, engineering, or mathematical
      breakthrough or invention of the past 100 years that has affected our
      society in a meaningful way and present your hypothesis on how it might
      further affect our society during your lifetime. Present either a
      30-minute oral report or a 1,500-word written report to your mentor.
- requirement: 8
  markdown: true
  text: |-
      Submit a <a href="../award-application.pdf">Supernova award
      application</a> to the district or council Nova or advancement committee
      for approval.
