- requirement: 1
  text: |-
      Explain the proper safety procedures to follow when preparing surfaces
      and applying coatings.
  workbook:
      - lines: 8
- requirement: 2
  text: |-
      Do the following:
  children:
      - requirement: a
        text: |-
            Explain three ways that coatings can improve a surface.
        workbook:
            - lines: 8
      - requirement: b
        text: |-
            Explain where you would apply enamel paint, flat paint, wood stain,
            and varnish, and explain the importance of sheen.
        workbook:
            - lines: 8
      - requirement: c
        text: |-
            Tell why each is best for these uses.
        workbook:
            - lines: 8
- requirement: 3
  text: |-
      Prepare and paint two different surfaces using patching materials or
      caulking and the proper primers and topcoats. Suggested projects include
      an interior or exterior wall, a door, a piece of furniture, a concrete
      wall or floor, a porch rail, or a fence. Your counselor must preapprove
      the projects.
  workbook:
      - split:
          - task: true
            text: |-
                First surface prepared and painted
          - task: true
            text: |-
                Second surface prepared and painted
- requirement: 4
  text: |-
      Prepare and paint an item using harmonizing colors that you have selected
      using the color wheel in the Painting merit badge pamphlet.
  workbook:
      - task: true
        text: |-
            Prepared and painted an item
- requirement: 5
  text: |-
      Show the right way to use, clean, maintain, and store painting equipment.
  workbook:
      - lines: 8
- requirement: 6
  text: |-
      Explain the importance of ladder safety, personal hygiene, and the use of
      personal protective equipment when painting.
  workbook:
      - lines: 8
- requirement: 7
  text: |-
      Explain some of the environmental and health issues concerning removing
      paint, applying paint, and discarding old paint.
  workbook:
      - lines: 8
- requirement: 8
  text: |-
      Find out about career opportunities in the painting craft. Discuss the
      training and experience required, and explain why this profession might
      interest you.
  workbook:
      - lines: 8
