- detail: true
  text: |-
      CAMPING AND OUTDOOR ETHICS
- requirement: 1
  text: |-
      Do the following:
  children:
      - requirement: a
        text: |-
            Present yourself to your leader, prepared for an overnight camping
            trip. Show the personal and camping gear you will use. Show the
            right way to pack and carry it.
      - requirement: b
        text: |-
            Spend at least one night on a patrol or troop campout. Sleep in a
            tent you have helped pitch.
      - requirement: c
        text: |-
            Explain how you demonstrated the Outdoor Code and Leave No Trace on
            campouts or outings.
- detail: true
  text: |-
      COOKING
- requirement: 2
  text: |-
      Do the following:
  children:
      - requirement: a
        text: |-
            On the campout, assist in preparing one of the meals. Tell why it
            is important for each patrol member to share in meal preparation
            and cleanup.
      - requirement: b
        text: |-
            While on a campout, demonstrate the appropriate method of safely
            cleaning items used to prepare, serve, and eat a meal.
      - requirement: c
        text: |-
            Explain the importance of eating together as a patrol.
- detail: true
  text: |-
      TOOLS
- requirement: 3
  text: |-
      Do the following:
  children:
      - requirement: a
        text: |-
            Demonstrate a practical use of the square knot.
      - requirement: b
        text: |-
            Demonstrate a practical use of two half-hitches.
      - requirement: c
        text: |-
            Demonstrate a practical use of the taut-line hitch.
      - requirement: d
        text: |-
            Demonstrate proper care, sharpening, and use of the knife, saw, and
            ax. Describe when each should be used.
- detail: true
  text: |-
      FIRST AID AND NATURE
- requirement: 4
  text: |-
      Do the following:
  children:
      - requirement: a
        markdown: true
        text: |-
            Show first aid for the following:

            * Simple cuts and scrapes
            * Blisters on the hand and foot
            * Minor (thermal/heat) burns or scalds (superficial, or first-degree)
            * Bites or stings of insects and ticks
            * Venomous snakebite
            * Nosebleed
            * Frostbite and sunburn
            * Choking
      - requirement: b
        text: |-
            Describe common poisonous or hazardous plants; identify any that
            grow in your local area or campsite location. Tell how to treat for
            exposure to them.
      - requirement: c
        text: |-
            Tell what you can do while on a campout or other outdoor activity
            to prevent or reduce the occurrence of injuries or exposure listed
            in Tenderfoot requirements 4a and 4b.
      - requirement: d
        text: |-
            Assemble a personal first-aid kit to carry with you on future
            campouts and hikes. Tell how each item in the kit would be used.
- detail: true
  text: |-
      HIKING
- requirement: 5
  text: |-
      Do the following:
  children:
      - requirement: a
        text: |-
            Explain the importance of the buddy system as it relates to your
            personal safety on outings and where you live. Use the buddy system
            while on a troop or patrol outing.
      - requirement: b
        text: |-
            Describe what to do if you become lost on a hike or campout.
      - requirement: c
        text: |-
            Explain the rules of safe and responsible hiking, both on the
            highway and cross-country, during the day and at night.
      - requirement: d
        text: |-
            Explain why it is important to hike on trails or other durable
            surfaces, and give examples of durable surfaces you saw on your
            outing.
- detail: true
  text: |-
      FITNESS
- requirement: 6
  text: |-
      Do the following:
  children:
      - requirement: a
        markdown: true
        text: |-
            Record your best in the following tests:

            * Pushups (Record the number done correctly in 60 seconds.)
            * Situps or curl-ups (Record the number done correctly in 60 seconds.)
            * Back-saver sit-and-reach (Record the distance stretched.)
            * 1-mile walk/run (Record the time.)
      - requirement: b
        text: |-
            Develop and describe a plan for improvement in each of the
            activities listed in Tenderfoot requirement 6a. Keep track of your
            activity for at least 30 days.
      - requirement: c
        markdown: true
        text: |-
            Show improvement (of any degree) in each activity listed in
            Tenderfoot requirement 6a after practicing for 30 days.

            * Pushups (Record the number done correctly in 60 seconds.)
            * Situps or curl-ups (Record the number done correctly in 60 seconds.)
            * Back-saver sit-and-reach (Record the distance stretched.)
            * 1-mile walk/run (Record the time.)
- detail: true
  text: |-
      CITIZENSHIP
- requirement: 7
  markdown: true
  text: |-
      Do the following:
  children:
      - requirement: a
        text: |-
            Demonstrate how to display, raise, lower, and fold the U.S. flag.
      - requirement: b
        text: |-
            Participate in a total of one hour of service in one or more
            service projects approved by your Scoutmaster. Explain how your
            service to others relates to the Scout slogan and Scout motto.
- detail: true
  text: |-
      LEADERSHIP
- requirement: 8
  text: |-
      Describe the steps in Scouting’s Teaching EDGE method. Use the Teaching
      EDGE method to teach another person how to tie the square knot.
- detail: true
  text: |-
      SCOUT SPIRIT
- requirement: 9
  text: |-
      Demonstrate Scout spirit by living the Scout Oath and Scout Law. Tell how
      you have done your duty to God and how you have lived four different
      points of the Scout Law in your everyday life.
- requirement: 10
  text: |-
      While working toward the Tenderfoot rank, and after completing Scout rank
      requirement 7, participate in a Scoutmaster conference.
- requirement: 11
  text: |-
      Successfully complete your board of review for the Tenderfoot rank.
