- requirement: 1
  text: |-
    Make a time line of the history of environmental science in America.
    Identify the contribution made by the Boy Scouts of America to
    environmental science.  Include dates, names of people or organizations,
    and important events.
- requirement: 2
  text: |-
    Define the following terms: population, community, ecosystem, biosphere,
    symbiosis, niche, habitat, conservation, threatened species, endangered
    species, extinction, pollution prevention, brownfield, ozone, watershed,
    airshed, nonpoint source, hybrid vehicle, fuel cell.
- requirement: 3
  text: |-
    Do ONE activity from EACH of the following categories (using the
    activities in this pamphlet as the basis for planning and projects):
  children:
    - requirement: A
      text: |-
        Ecology
      children:
        - requirement: 1
          text: |-
            Conduct an experiment to find out how living things respond
            to changes in their environments. Discuss your observations
            with your counselor.
        - requirement: 2
          text: |-
            Conduct an experiment illustrating the greenhouse effect.
            Keep a journal of your data and observations. Discuss your
            conclusions with your counselor.
        - requirement: 3
          text: |-
            Discuss what is an ecosystem. Tell how it is maintained in
            nature and how it survives.
    - requirement: B
      text: |-
        Air Pollution
      children:
        - requirement: 1
          text: |-
            Perform an experiment to test for particulates that
            contribute to air pollution. Discuss your findings with your
            counselor.
        - requirement: 2
          text: |-
            Record the trips taken, mileage, and fuel consumption of a
            family car for seven days, and calculate how many miles per
            gallon the car gets.  Determine whether any trips could have
            been combined (“chained”) rather than taken out and back.
            Using the idea of trip chaining, determine how many miles and
            gallons of gas could have been saved in those seven days.
        - requirement: 3
          text: |-
            Explain what is acid rain. In your explanation, tell how it
            affects plants and the environment and the steps society can
            take to help reduce its effects.
    - requirement: C
      text: |-
        Water Pollution
      children:
        - requirement: 1
          text: |-
            Conduct an experiment to show how living things react to
            thermal pollution. Discuss your observations with your
            counselor.
        - requirement: 2
          text: |-
            Conduct an experiment to identify the methods that could be
            used to mediate (reduce) the effects of an oil spill on
            waterfowl. Discuss your results with your counselor.
        - requirement: 3
          text: |-
            Describe the impact of a waterborne pollutant on an aquatic
            community. Write a 100-word report on how that pollutant
            affected aquatic life, what the effect was, and whether the
            effect is linked to biomagnification.
    - requirement: D
      text: |-
        Land Pollution
      children:
        - requirement: 1
          text: |-
            Conduct an experiment to illustrate soil erosion by water.
            Take photographs or make a drawing of the soil before and
            after your experiment, and make a poster showing your
            results. Present your poster to your counselor.
        - requirement: 2
          text: |-
            Perform an experiment to determine the effect of an oil spill
            on land.  Discuss your conclusions with your counselor.
        - requirement: 3
          text: |-
            Photograph an area affected by erosion. Share your
            photographs with your counselor and discuss why the area has
            eroded and what might be done to help alleviate the erosion.
    - requirement: E
      text: |-
        Endangered Species
      children:
        - requirement: 1
          text: |-
            Do research on one endangered species found in your state.
            Find out what its natural habitat is, why it is endangered,
            what is being done to preserve it, and how many individual
            organisms are left in the wild.  Prepare a 100-word report
            about the organism, including a drawing.  Present your report
            to your patrol or troop.
        - requirement: 2
          text: |-
            Do research on one species that was endangered or threatened
            but that has now recovered. Find out how the organism
            recovered, and what its new status is. Write a 100-word
            report on the species and discuss it with your counselor.
        - requirement: 3
          text: |-
            With your parent’s and counselor’s approval, work with a
            natural resource professional to identify two projects that
            have been approved to improve the habitat for a threatened or
            endangered species in your area. Visit the site of one of
            these projects and report on what you saw.
    - requirement: F
      text: |-
        Pollution Prevention, Resource Recovery, and Conservation
      children:
        - requirement: 1
          text: |-
            Look around your home and determine 10 ways your family can
            help reduce pollution. Practice at least two of these methods
            for seven days and discuss with your counselor what you have
            learned.
        - requirement: 2
          text: |-
            Determine 10 ways to conserve resources or use resources more
            efficiently in your home, at school, or at camp. Practice at
            least two of these methods for seven days and discuss with
            your counselor what you have learned.
        - requirement: 3
          text: |-
            Perform an experiment on packaging materials to find out
            which ones are biodegradable. Discuss your conclusion with
            your counselor.
    - requirement: G
      text: |-
        Pollination
      children:
        - requirement: 1
          text: |-
            Using photographs or illustrations, point out the differences
            between a drone and a worker bee. Discuss the stages of bee
            development (eggs, larvae, pupae). Explain the pollination
            process, and what propolis is and how it is used by honey
            bees. Tell how bees make honey and beeswax, and how both are
            harvested. Explain the part played in the life of the hive by
            the queen, the drones, and the workers.
        - requirement: 2
          text: |-
            Present to your counselor a one-page report on how and why
            honey bees are used in pollinating food crops. In your
            report, discuss the problems faced by the bee population
            today, and the impact to humanity if there were no
            pollinators. Share your report with your troop or patrol,
            your class at school, or another group approved by your
            counselor.
        - requirement: 3
          text: |-
            Hive a swarm OR divide at least one colony of honey bees.
            Explain how a hive is constructed.
        - detail: true
          markdown: true
          text: |-
            **Before you choose requirement 3G(3), you will need to first
            find out whether you are allergic to bee stings.  Visit an
            allergist or your family physician to find out. If you are
            allergic to bee stings, you should choose another option
            within requirement 3. In completing requirement 3G(3), your
            counselor can help you find an established beekeeper to meet
            with you and your buddy. Ask whether you can help hive a
            swarm or divide a colony of honey bees. Before your visit, be
            sure your buddy is not allergic to bee stings. For help with
            locating a beekeeper in your state, visit www.beeculture.com
            and click on "Resources," then select "Find Help" and "Find a
            Local Beekeeper."**
    - requirement: H
      text: |-
        Invasive Species
      children:
        - requirement: 1
          text: |-
            Learn to identify the major invasive plant species in your
            community or camp and explain to your counselor what can be
            done to either eradicate or control their spread.
        - requirement: 2
          text: |-
            Do research on two invasive plant or animal species in your
            community or camp. Find out where the species originated, how
            they were transported to the United States, their life
            history, how they are spread, and the recommended means to
            eradicate or control their spread. Report your research
            orally or in writing to your counselor.
        - requirement: 3
          text: |-
            Take part in a project of at least one hour to eradicate or
            control the spread of an invasive plant species in your
            community or camp.
- requirement: 4
  text: |-
    Choose two outdoor study areas that are very different from one another
    (e.g., hilltop vs. bottom of a hill; field vs. forest; swamp vs. dry
    land). For BOTH study areas, do ONE of the following:
  children:
    - requirement: A
      text: |-
        Mark off a plot of 4 square yards in each study area, and count the
        number of species found there. Estimate how much space is occupied
        by each plant species and the type and number of nonplant species
        you find. Write a report that adequately discusses the biodiversity
        and population density of these study areas. Discuss your report
        with your counselor.
    - requirement: B
      text: |-
        Make at least three visits to each of the two study areas (for a
        total of six visits), staying for at least 20 minutes each time, to
        observe the living and nonliving parts of the ecosystem. Space each
        visit far enough apart that there are readily apparent differences
        in the observations. Keep a journal that includes the differences
        you observe. Then, write a short report that adequately addresses
        your observations, including how the differences of the study areas
        might relate to the differences noted, and discuss this with your
        counselor.
- requirement: 5
  text: |-
    Using the construction project provided or a plan you create on your own,
    identify the items that would need to be included in an environmental
    impact statement for the project planned.
- requirement: 6
  text: |-
    Find out about three career opportunities in environmental science. Pick
    one and find out the education, training, and experience required for
    this profession. Discuss this with your counselor, and explain why this
    profession might interest you.
