- requirement: 1
  text: |-
    Do the following:
  children:
    - requirement: a
      text: |-
        Briefly discuss the historical origin and domestication of the dog.
    - requirement: b
      text: |-
        Describe some common characteristics of the dogs that make up each
        of the seven major dog groups.
    - requirement: c
      text: |-
        Tell some specific characteristics of seven breeds of dogs (one
        from each major group), OR give a short history of one breed.
    - note:
        - inPerson
        - online
      text: |-
        Scouts will find that utilizing their Merit Badge Pamphlet many of
        the answers for his requirement can easily be found.  It is high
        recommended that Scouts utilize a Merit Badge Workbook to record
        their findings and answers for easier reference during the class.
        Active participation in the group discussion lead by the counselor
        will be necessary as well in order to complete this requirement.
- requirement: 2
  text: |-
    Point out on a dog or a sketch at least 10 body parts. Give the correct
    name of each one.
  children:
    - note:
        - inPerson
        - online
      text: |-
        Scouts may either sketch their own drawing of a dog or use a sketch
        already available on the internet or in a Dog Care Merit Badge
        Workbook to complete this requirement.  It is strongly recommended
        that Scouts have this done prior to the class.  If the class will
        accommodate the bringing of your own dog Scouts should know where
        to point out these body parts on their own dog and will do so
        during the class. While this requirement will be done in the class,
        preparation will help ensure completion.
- requirement: 3
  text: |-
    Do the following:
  children:
    - requirement: a
      text: |-
        Explain the importance of house-training, obedience training, and
        socialization training for your dog.
    - requirement: b
      text: |-
        Explain what “responsible pet ownership” means.
    - requirement: c
      text: |-
        Explain what issues (including temperament) must be considered when
        deciding on what breed of dog to get as a family pet.
    - note:
        - inPerson
        - online
      text: |-
        Scouts should have their answers formulated and ready to share for
        each of the components of this requirement prior to the class.  Use
        the Merit Badge Pamphlet to assist in your research.  You may also
        reference other sources to find the answers.  The counselor will
        facilitate discussion in the class covering this requirement and
        only boys who actively and knowledgeably participate will have an
        opportunity of completing this requirement.
- requirement: 4
  markdown: true
  text: |-
    For two months, keep and care for your dog.`*` Maintain a log of your
    activities during this period that includes these items: feeding
    schedule, types of food used, amount fed, exercise periods, training
    schedule, a weekly body weight record, grooming and bathing schedules,
    veterinary care, if necessary, and costs. Also include a brief
    description of the type of housing/shelter arrangements you have for your
    dog.

    `*` The activities used to fulfill the requirements for the Dog Care merit badge may not be used to help fulfill requirements for other merit badges.
  children:
    - note:
        - inPerson
        - online
      text: |-
        It is not adequate to just say that you have done this requirement.
        Scouts should have proof of their two-month dog care
        responsibilities, and like the requirement states, have a log
        showing their efforts.  Scouts must also remember to provide a
        description of the type of housing/shelter provided for their dog.
        Have your log and description ready for the class to share with
        your counselor and fellow Scouts.
- requirement: 5
  text: |-
    Explain the correct way to obedience train a dog and what equipment you
    would need. Show with your dog any three of these commands: “come,”
    “sit,” “down,” “heel,” “stay,” “fetch” or “get it,” and “drop it.”
  children:
    - note:
        - inPerson
        - online
      text: |-
        Scouts will need to have their dog with them in order to complete
        this requirement. (Please note whether the class location allows
        your dog to be present).  It is acceptable to have video of you and
        your dog performing these commands.  Be prepared for the class to
        share your dog's obedience and give explanation on proper obedience
        training.
- requirement: 6
  text: |-
    Do the following:
  children:
    - requirement: a
      text: |-
        Discuss the proper vaccination schedule for a dog in your area from
        puppyhood through adulthood.
    - requirement: b
      text: |-
        Discuss the control methods for preventing fleas, ticks,
        heartworms, and intestinal parasites (worms) for a dog in your area
        from puppyhood through adulthood.
    - requirement: c
      text: |-
        Explain the importance of dental care and tooth brushing to your
        pet’s health.
    - requirement: d
      text: |-
        Discuss the benefits of grooming your dog’s coat and nails on a
        regular basis.
    - requirement: e
      text: |-
        Discuss with your counselor any seasonal conditions (like hot
        summers, cold winters, or extreme humidity) where you live that
        need to be considered for your dog.
    - requirement: f
      text: |-
        Discuss with your counselor the considerations and advantages of
        spaying or neutering your dog.
    - note:
        - inPerson
        - online
      text: |-
        The answers to this requirement can easily be found in the merit
        badge pamphlet and Scouts should be prepared for discussion on each
        of the components of this requirement in the class.  Some Scouts
        may find it helpful to utilize a Merit Badge Workbook to organize
        their notes and findings for easier reference during the class and
        to better ensure completion of this requirement in the class.
- requirement: 7
  text: |-
    Do the following:
  children:
    - requirement: a
      text: |-
        Explain precautions to take in handling a hurt dog.
    - requirement: b
      text: |-
        Show how to put on an emergency muzzle.
    - requirement: c
      text: |-
        Explain how to treat wounds. Explain first aid for a dog bite.
    - requirement: d
      text: |-
        Show how to put on a simple dressing and bandage the foot, body, or
        head of your dog.
    - requirement: e
      text: |-
        Explain what to do if a dog is hit by a car.
    - requirement: f
      text: |-
        List the things needed in every dog owner’s first-aid kit.
    - requirement: g
      text: |-
        Tell the dangers of home treatment of a serious ailment.
    - requirement: h
      text: |-
        Briefly discuss the cause and method of spread, the signs and
        symptoms and the methods of prevention of rabies, parvovirus,
        distemper, and heartworms in dogs.
    - note:
        - inPerson
        - online
      text: |-
        While this requirement will be covered in the class, Scouts should
        still prepare by understanding the basics of each component in this
        requirement by reviewing the merit badge pamphlet and being
        prepared to explain their findings with the counselor.
- requirement: 8
  text: |-
    Visit a veterinary hospital or an animal shelter and give a report about
    your visit to your counselor.
  children:
    - note:
        - inPerson
        - online
      text: |-
        Scouts may choose to complete this requirement ahead of time or
        complete this after the class. The class will focus some time for
        discussion of this requirement. Scouts that have completed their
        visit, and can substantiate that with the counselor, will have an
        opportunity to complete this part of the requirement during the
        class.
- requirement: 9
  text: |-
    Know the laws and ordinances involving dogs that are in force in your
    community.
  children:
    - note:
        - inPerson
        - online
      text: |-
        Scouts will need to prepare for this requirement prior to the class
        by researching their local laws and ordinances in their community.
        Scouts should be prepared with their findings to share during the
        class.
- requirement: 10
  text: |-
    Learn about three career opportunities for working with dogs. Pick one
    and find out about the education, training, and experience required for
    this career, and discuss this with your counselor. Tell why this
    profession interests you.
  children:
    - note:
        - inPerson
        - online
      text: |-
        Scouts should review this requirement and its components and be
        prepared to discuss.  It is strongly recommended that Scouts bring
        any notes or supporting documents they may have to help show the
        counselor that they have prepared for completion of this
        requirement.
