- requirement: 1
  text: |-
    Discuss the following with your counselor:
  children:
    - requirement: a
      text: |-
        What art is and what some of the different forms of art are
    - requirement: b
      text: |-
        The importance of art to humankind
      children:
        - note:
            - inPerson
            - online
          text: |-
            Scouts will need to be able to share their findings on these
            requirement components during the counselor led discussion.
            Requirements 1a and 1b can easily be found in the Merit Badge
            Pamphlet. Scouts may find it beneficial to organize their
            notes for these requirements on a separate sheet of paper or
            in a Merit Badge Workbook for easy reference during the
            class.
    - requirement: c
      text: |-
        What art means to you and how art can make you feel
      children:
        - note:
            - inPerson
            - online
          text: |-
            Requirement 1c is not a requirement you will find in the
            pamphlet, but rather are your own thoughts and feelings.
            Please be sure to have given this some thought prior to the
            class. Saying, "art makes me feel good" is not enough to
            complete this part of the requirement.
- requirement: 2
  text: |-
    Discuss with your counselor the following terms and elements of art:
    line, value, shape, form, space, color, and texture. Show examples of
    each element.
  children:
    - note:
        - inPerson
        - online
      text: |-
        Scouts should look up and learn each of these terms and be prepared
        to share their understanding of each of these terms in class
        discussion. All terms can be found in the Merit Badge Pamphlet.
        Some Scouts may find it easier to write down their findings in
        their Merit Badge Workbook for quicker and easier reference for use
        during the class.
- requirement: 3
  text: |-
    Discuss with your counselor the six principles of design: rhythm,
    balance, proportion, variety, emphasis, and unity.
  children:
    - note:
        - inPerson
        - online
      text: |-
        Scouts should review their merit badge pamphlet and come with an
        understanding for discussion in the class about the six principles
        of design; as outlined in this requirement. It is highly
        recommended to utilize a Merit Badge Workbook to make notes of your
        findings. Scouts in attendance that have not reviewed their merit
        badge pamphlet for the principles and/or do not actively
        participate in the class discussion will find it difficult to
        complete this requirement.
- requirement: 4
  text: |-
    Render a subject of your choice in FOUR of these ways:
  children:
    - requirement: a
      text: |-
        Pen and ink
    - requirement: b
      text: |-
        Watercolors
    - requirement: c
      text: |-
        Pencil
    - requirement: d
      text: |-
        Pastels
    - requirement: e
      text: |-
        Oil paints
    - requirement: f
      text: |-
        Tempera
    - requirement: g
      text: |-
        Acrylics
    - requirement: h
      text: |-
        Charcoal
    - requirement: i
      text: |-
        Computer drawing or painting
    - note:
        - inPerson
      markdown: true
      text: |-
        This requirement will be done during the class under the guidance
        and direction of the merit badge counselor / instructor. *Note that
        the requirement says A subject, meaning one subject rendered in
        four of the following methods.* Scouts may choose to work on this
        requirement prior to the class and bring their work to the class.
    - note:
        - online
      markdown: true
      text: |-
        Scouts will need to do their renderings prior to the class and have
        them ready to share during the class.  Please note that the
        requirement asks for a single subject to be rendered in four
        different ways. *Note that the requirement says A subject, meaning
        one subject rendered in four of the above methods.*
- requirement: 5
  text: |-
    Do ONE of the following:
  children:
    - requirement: a
      text: |-
        Design something useful. Make a sketch or model of your design.
        With your counselor’s approval, create a promotional piece for the
        item using a picture or pictures.
    - requirement: b
      text: |-
        Tell a story with a picture or pictures or using a 3-D rendering.
    - requirement: c
      text: |-
        Design a logo. Share your design with your counselor and explain
        the significance of your logo. Then, with your parent’s permission
        and your counselor’s approval, put your logo on Scout equipment,
        furniture, ceramics, or fabric.
    - note:
        - online
      text: |-
        Scouts will need to choose one of the requirement components prior
        to the class and prepare ahead of time so that they are ready to
        share their work during the class.
    - note:
        - inPerson
      text: |-
        This requirement will be done in the class however Scouts should
        come with an idea for their useful item, the story they want to
        tell, or logo in mind. Time will be allotted in the class to
        finalize the design and share with the counselor and class. Scouts
        may want to get a head start on this requirement by sketching out
        their idea to start with to ensure they have enough time to
        complete this requirement as a part of the class.
- requirement: 6
  text: |-
    With your parent’s permission and your counselor’s approval, visit a
    museum, art exhibit, art gallery, artists’ co-op, or artist’s workshop.
    Find out about the art displayed or created there.  Discuss what you
    learn with your counselor.
  children:
    - note:
        - inPerson
        - online
      markdown: true
      text: |-
        Scouts may work on this requirement prior to the class, but please
        note that the counselor reserves the right to accept or deny your
        work on the basis of meeting the expectations of this requirement
        to their satisfaction.

        Scouts should bring proof (a note signed by the host, your parent,
        teacher, Scoutmaster, or other) to help validate their completion
        of the visit noted in this requirement. Ideally the note
        could/should be signed by someone from the museum, gallery,
        exhibit, or workshop you visited. Pictures and items from your
        visit are an ideal way to capture this experience and will help
        enhance your presentation and discussion with the counselor and
        other Scouts in the class.

        Scouts not having done preparation work on this requirement will
        have an opportunity to review options with the counselor to pursue
        after the class.
- requirement: 7
  text: |-
    Find out about three career opportunities in art. Pick one and find out
    the education, training, and experience required for this profession.
    Discuss this with your counselor, and explain why this profession might
    interest you.
  children:
    - note:
        - inPerson
        - online
      text: |-
        Scouts should review this requirement and its components and be
        prepared to discuss. It is strongly recommended that Scouts bring
        any notes or supporting documents they may have to help show the
        counselor that they have prepared for discussion and completion of this
        requirement.
