- requirement: 1
  text: |-
    Discuss with your counselor the influence that EIGHT of the following
    people had on the history of health care:
  children:
    - requirement: a
      text: |-
        Hippocrates
    - requirement: b
      text: |-
        William Harvey
    - requirement: c
      text: |-
        Antonie van Leewenhoek
    - requirement: d
      text: |-
        Edward Jenner
    - requirement: e
      text: |-
        Florence Nightingale
    - requirement: f
      text: |-
        Louis Pasteur
    - requirement: g
      text: |-
        Gregor Mendel
    - requirement: h
      text: |-
        Joseph Lister
    - requirement: i
      text: |-
        Robert Koch
    - requirement: j
      text: |-
        Daniel Hale Williams
    - requirement: k
      text: |-
        Wilhelm Conrad Roentgen
    - requirement: l
      text: |-
        Marie and Pierre Curie
    - requirement: m
      text: |-
        Walter Reed
    - requirement: n
      text: |-
        Karl Landsteiner
    - requirement: o
      text: |-
        Alexander Fleming
    - requirement: p
      text: |-
        Charles Richard Drew
    - requirement: q
      text: |-
        Helen Taussig
    - requirement: r
      text: |-
        James Watson and Francis Crick
    - requirement: s
      text: |-
        Jonas Salk
- requirement: 2
  text: |-
    Explain the Hippocratic Oath to your counselor, and compare the original
    version to a more modern one. Discuss to whom those subscribing to the
    original version of the oath owe the greatest allegiance.
- requirement: 3
  text: |-
    Discuss the health-care provider–patient relationship with your
    counselor, and the importance of such a relationship in the ­delivery of
    quality care to the patient. Describe the role of ­confidentiality in
    this relationship.
- requirement: 4
  text: |-
    Do the following:
  children:
    - requirement: a
      text: |-
        Describe the roles the following people play in the delivery of
        health care:
      children:
        - requirement: 1
          text: |-
            Allopathic physician (M.D.) and osteopathic physician (D.O.)
        - requirement: 2
          text: |-
            Chiropractor (D.C.)
        - requirement: 3
          text: |-
            Emergency medical technician
        - requirement: 4
          text: |-
            Licensed practical/vocational nurse
        - requirement: 5
          text: |-
            Medical assistant
        - requirement: 6
          text: |-
            Medical laboratory technologist
        - requirement: 7
          text: |-
            Nurse-midwife
        - requirement: 8
          text: |-
            Nurse practitioner
        - requirement: 9
          text: |-
            Occupational therapist
        - requirement: 10
          text: |-
            Optometrist
        - requirement: 11
          text: |-
            Pharmacist
        - requirement: 12
          text: |-
            Physical therapist
        - requirement: 13
          text: |-
            Physician’s assistant
        - requirement: 14
          text: |-
            Podiatrist
        - requirement: 15
          text: |-
            Psychologist
        - requirement: 16
          text: |-
            Radiologic technologist
        - requirement: 17
          text: |-
            Registered nurse
        - requirement: 18
          text: |-
            Respiratory therapist
    - requirement: b
      text: |-
        Describe the educational and licensing requirements to practice
        health care in your state for FIVE of the professions in
        requirement 4a. (Not all professions may exist in your state.)
- requirement: 5
  # Had no text, so added the wording "Do the following":
  text: |-
    Do the following:
  children:
    - requirement: a
      text: |-
        Tell what is meant by the term “primary care” with regard to a
        medical specialty.
    - requirement: b
      text: |-
        Briefly describe the types of work done by physicians in the
        following specialties:
      children:
        - requirement: 1
          markdown: true
          text: |-
            Internal medicine`*`
        - requirement: 2
          markdown: true
          text: |-
            Family practice`*`
        - requirement: 3
          markdown: true
          text: |-
            Obstetrics/gynecology`*`
        - requirement: 4
          text: |-
            Pediatrics`*`
        - requirement: 5
          text: |-
            Psychiatry
        - requirement: 6
          text: |-
            Surgery
        - detail: true
          markdown: true
          text: |-
            `*` "Primary care" specialties
    - requirement: c
      text: |-
        Describe the additional educational requirements for these
        specialties.
- requirement: 6
  # Had no text, so added the wording "Do the following":
  text: |-
    Do the following:
  children:
    - requirement: a
      text: |-
        Briefly describe the types of work performed by physicians in FIVE
        of the following specialties or subspecialties:
      children:
        - requirement: 1
          text: |-
            Allergy/immunology
        - requirement: 2
          text: |-
            Anesthesiology
        - requirement: 3
          text: |-
            Cardiology
        - requirement: 4
          text: |-
            Colorectal surgery
        - requirement: 5
          text: |-
            Critical care medicine (intensive care medicine)
        - requirement: 6
          text: |-
            Dermatology
        - requirement: 7
          text: |-
            Emergency medicine
        - requirement: 8
          text: |-
            Endocrinology
        - requirement: 9
          text: |-
            Gastroenterology
        - requirement: 10
          text: |-
            Geriatric medicine
        - requirement: 11
          text: |-
            Hematology/oncology
        - requirement: 12
          text: |-
            Hospitalist
        - requirement: 13
          text: |-
            Infectious disease
        - requirement: 14
          text: |-
            Nephrology
        - requirement: 15
          text: |-
            Neurosurgery
        - requirement: 16
          text: |-
            Neurology
        - requirement: 17
          text: |-
            Nuclear medicine
        - requirement: 18
          text: |-
            Ophthalmology
        - requirement: 19
          text: |-
            Orthopedic surgery
        - requirement: 20
          text: |-
            Otolaryngology/head and neck surgery
        - requirement: 21
          text: |-
            Pathology
        - requirement: 22
          text: |-
            Physical medicine and rehabilitation
        - requirement: 23
          text: |-
            Plastic, reconstructive, and maxillofacial surgery
        - requirement: 24
          text: |-
            Preventive medicine
        - requirement: 25
          text: |-
            Pulmonology
        - requirement: 26
          text: |-
            Radiology
        - requirement: 27
          text: |-
            Rheumatology
        - requirement: 28
          text: |-
            Thoracic/cardiothoracic sur­gery
        - requirement: 29
          text: |-
            Urology
        - requirement: 30
          text: |-
            Vascular surgery
    - requirement: b
      text: |-
        Describe the additional educational requirements for the FIVE
        specialties or subspecialties you chose in 6a.
- requirement: 7
  # Had no text, so added the wording "Do the following":
  text: |-
    Do the following:
  children:
    - requirement: a
      markdown: true
      text: |-
        Visit a physician’s office`*`, preferably one who delivers
        ­“primary care.” (This may be that of your counselor.) Discuss the
        components of a medical history and physical examination (an
        official BSA health form may be used to guide this discussion), and
        become familiar with the instruments used.

        `*` If this cannot be arranged, demonstrate to your counselor that you
        understand the components of a medical history and physical, and
        discuss the instruments involved.
    - requirement: b
      text: |-
        Describe the characteristics of a good diagnostic test to screen
        for disease (e.g., routine blood pressure measurement). Explain
        briefly why diagnostic tests are not “perfect.”
    - requirement: c
      text: |-
        Show how to take a blood pressure and a pulse reading.
- requirement: 8
  text: |-
    Do the following:
  children:
    - requirement: a
      # Text was jumbled in extract
      text: |-
        Discuss the roles medical societies, employers, the insurance
        industry, and the government play in influencing the practice of
        medicine in the United States.
    - requirement: b
      text: |-
        Briefly tell how your state monitors the quality of health care
        within its borders, and how it provides care to those who do not
        have health insurance.
- requirement: 9
  text: |-
    Compare and discuss with your counselor at least two types of health care
    delivery systems used throughout the world.
- requirement: 10
  text: |-
    Serve as a volunteer at a health-related event or facility in your
    community (e.g., blood drive, “health fair,” blood pressure screening,
    etc.) approved by your counselor.
