- requirement: 1
  text: |-
    Discuss safety on the golf course. Show that you know first aid for injuries or illnesses that could occur while golfing, including lightning, heat reactions, dehydration, blisters, sprains, and strains.
- requirement: 2
  text: |-
    Study the USGA “Rules of Golf” now in use.
  children:
    - requirement: a
      text: |-
        Tell about the three categories of golf etiquette.
    - requirement: b
      text: |-
        Demonstrate that you understand the definitions of golf terms.
    - requirement: c
      text: |-
        Show that you understand the “Rules of Amateur Status.”
- requirement: 3
  text: |-
    Tell about your understanding of the USGA system of handicapping.
- requirement: 4
  text: |-
    Do the following:
  children:
    - requirement: a
      text: |-
        Tell about the early history of golf.
    - requirement: b
      text: |-
        Describe golf’s early years in the United States.
    - requirement: c
      text: |-
        Tell about the accomplishments of a top golfer of your choice.
- requirement: 5
  text: |-
    Discuss with your counselor vocational opportunities related to golf.
- requirement: 6
  text: |-
    Do the following:
  children:
    - requirement: a
      text: |-
        Tell how golf can contribute to a healthy lifestyle, mentally and physically.
    - requirement: b
      text: |-
        Tell how a golf exercise plan can help you play better. Show two exercises that would help improve your game.
- requirement: 7
  text: |-
    Show the following:
  children:
    - requirement: a
      text: |-
        The proper grip, stance, posture, and key fundamentals of a good swing
    - requirement: b
      text: |-
        Driver played from a tee
    - requirement: c
      text: |-
        The fairway wood shot
    - requirement: d
      text: |-
        The long iron shot
    - requirement: e
      text: |-
        The short iron shot
    - requirement: f
      text: |-
        The approach, chip-and-run, and pitch shots
    - requirement: g
      text: |-
        The sand iron shot, bunker, or heavy rough recovery shots
    - requirement: h
      text: |-
        A sound putting stroke
- requirement: 8
  text: |-
    Play a minimum of two nine-hole rounds or one 18-hole round of golf with another golfer about your age and with your counselor, or an adult approved by your counselor. Do the following:
  children:
    - requirement: a
      text: |-
        Follow the “Rules of Golf.”
    - requirement: b
      text: |-
        Practice good golf etiquette.
    - requirement: c
      text: |-
        Show respect to fellow golfers, committee, sponsor, and gallery.
