- requirement: 1
  text: |-
      Do THREE of the following:
  children:
      - requirement: a
        text: |-
            Name three types of modern freight trains. Explain why unit trains
            are more efficient than mixed freight trains.
        workbook:
            - lines: 8
      - requirement: b
        text: |-
            Name one Class I or regional railroad. Explain what major cities it
            serves, the locations of major terminals, service facilities and
            crew change points, and the major commodities it carries.
        workbook:
            - lines: 8
      - requirement: c
        text: |-
            Using models or pictures, identify 10 types of railroad freight or
            passenger cars. Explain the purpose of each type of car.
        workbook:
            - lines: 8
      - requirement: d
        text: |-
            Explain how a modern diesel or electric locomotive develops power.
            Explain the terms dynamic braking and radial steering trucks.
        workbook:
            - lines: 8
- requirement: 2
  text: |-
      Do the following:
  children:
      - requirement: a
        text: |-
            Explain the purpose and formation of Amtrak. Explain, by the use of
            a timetable, a plan for making a trip by rail between two cities at
            least 500 miles apart. List the times of departure and arrival at
            your destination, the train number and name, and the type of
            service you want.
        workbook:
            - lines: 8
      - requirement: b
        text: |-
            List and explain the various forms of public/mass transit using
            rail.
        workbook:
            - lines: 8
- requirement: 3
  text: |-
      Do ONE of the following:
  workbook:
      - header: true
        markdown: true
        text: |-
            a. Name four departments of a railroad company. Describe what each
            department does.

            b. Tell about the opportunities in railroading that interest you
            most and why.

            c. Name four rail support industries. Describe the function of each
            one.

            d. With your parent’s and counselor’s approval, interview someone
            employed in the rail industry. Learn what that person does and how
            this person became interested in railroading. Find out what type of
            schooling and training are required for this position.
      - lines: 8
  children:
      - requirement: a
        text: |-
            Name four departments of a railroad company. Describe what each
            department does.
        workbookHide: true
      - requirement: b
        text: |-
            Tell about the opportunities in railroading that interest you most
            and why.
        workbookHide: true
      - requirement: c
        text: |-
            Name four rail support industries. Describe the function of each
            one.
        workbookHide: true
      - requirement: d
        text: |-
            With your parent’s and counselor’s approval, interview someone
            employed in the rail industry. Learn what that person does and how
            this person became interested in railroading. Find out what type of
            schooling and training are required for this position.
        workbookHide: true
- requirement: 4
  text: |-
      Do the following:
  children:
      - requirement: a
        text: |-
            Explain the purpose of Operation Lifesaver and its mission.
        workbook:
            - lines: 8
      - requirement: b
        text: |-
            List 9 track basic safety tips to remember when you are around a
            railroad track.
        workbook:
            - lines: 8
      - requirement: c
        text: |-
            List 9 safety considerations that should be followed when walking
            near a railroad track.
        workbook:
            - lines: 8
      - requirement: d
        # HiddenNotes: Added "to" in this requirement
        text: |-
            Tell your counselor what a driver can do to safely operate near
            tracks.
        workbook:
            - lines: 8
      - requirement: e
        text: |-
            Explain safety precautions when using a light rail or commuter
            train.
        workbook:
            - lines: 8
- requirement: 5
  text: |-
      Explain the appearance and meaning of the following rail signs and
      signals:
  children:
      - requirement: a
        text: |-
            Passive signs and active signs.
        workbook:
            - lines: 8
      - requirement: b
        text: |-
            Devices at the crossing (flashing red lights — with or without
            bells, flashing red lights and gates, and cantilever flashing
            lights)
        workbook:
            - lines: 8
      - requirement: c
        text: |-
            Markings on the road (pavement markings and stop bars)
        workbook:
            - lines: 8
      - requirement: d
        text: |-
            Signs before the crossing (advance warning sign, advance warning
            sign for side streets, no train horn sign, and low ground clearance
            grade crossing sign)
        workbook:
            - lines: 8
      - requirement: e
        text: |-
            Signs along the railroad property (no trespassing sign)
        workbook:
            - lines: 8
      - requirement: f
        text: |-
            Signs at the crossing (crossbuck sign, emergency notification
            system sign, multiple track sign, stop sign, and yield sign).
        workbook:
            - lines: 8
- requirement: 6
  text: |-
      Do EACH of the following:
  children:
      - requirement: a
        text: |-
            Explain how railroad signals operate and show two basic signal
            types using color or configuration.
        workbook:
            - lines: 8
      - requirement: b
        text: |-
            Explain the meaning of three horn signals.
        workbook:
            - lines: 8
      - requirement: c
        text: |-
            Describe a way to signal a train for an emergency stop.
        workbook:
            - lines: 8
      - requirement: d
        text: |-
            Explain the use and function of the EOTD (end-of-train device), or
            FRED (flashing rear end device), used on the last car of most
            freight trains.
        workbook:
            - lines: 8
- requirement: 7
  text: |-
      Select ONE of the following special-interest areas and complete the
      requirements.
  children:
      - requirement: a
        markdown: true
        text: |-
            **Model Railroading**

            With your parent’s and counselor’s approval, do TWO of the
            following:
        children:
            - requirement: 1
              text: |-
                  Draw a layout of your own model railroad or one that could be
                  built in your home. Design a point-to-point track or loop with
                  different routings. Include one of the following: turnaround or
                  terminal or yard or siding.
              workbook:
                  - area: 8
            - requirement: 2
              text: |-
                  Build one model railroad car kit or one locomotive kit.
              workbook:
                  - lines: 4
            - requirement: 3
              text: |-
                  Name the scale of four popular model railroad gauges.
                  Identify the scale of four model cars or locomotives.
              workbook:
                  - lines: 4
            - requirement: 4
              text: |-
                  Locate the website of four model railroad–related
                  manufacturers or magazine publishers. Print information on
                  their products and services and discuss the information with
                  your counselor.
              workbook:
                  - lines: 4
            - requirement: 5
              text: |-
                  Build one railroad structure (from scratch or using a kit),
                  paint and weather the structure, mount it on your layout or
                  diorama, and make the surrounding area on the diorama scenic.
              workbook:
                  - lines: 4
            - requirement: 6
              text: |-
                  Alone or with others, build a model railroad or modular
                  layout including ballast and scenery. Make electrical
                  connections and operate a train. Describe what you enjoyed
                  most.
              workbook:
                  - lines: 4
            - requirement: 7
              text: |-
                  Participate in a switching contest on a timesaver layout and
                  record your time.
              workbook:
                  - lines: 4
            - requirement: 8
              text: |-
                  Explain the difference between powering and controlling a
                  model railroad by using direct current, and powering and
                  controlling a model railroad using digital command control.
              workbook:
                  - lines: 4
      - requirement: b
        markdown: true
        text: |-
            **Railfanning**

            With your parent’s and counselor’s approval, do TWO of the
            following:
        children:
            - requirement: 1
              text: |-
                  Visit a railroad museum, historical display, or a prototype
                  railroad-sponsored public event. With permission, photograph,
                  digitally record, or sketch items of interest. Explain what
                  you saw and describe your photos, sketches, or video.
              workbook:
                  - area: 8
                  - lines: 8
            - requirement: 2
              text: |-
                  Purchase tickets and ride a scenic or historic railroad.
                  Under supervision, photograph the equipment and discuss with
                  your counselor the historic significance of the operation.
              workbook:
                  - lines: 8
            - requirement: 3
              text: |-
                  Locate the website of four rail historical groups, then find
                  information on the history of the rail preservation
                  operations and purpose of each group.  Talk with a member of
                  one of the groups and find out how you might help.
              workbook:
                  - lines: 8
            - requirement: 4
              text: |-
                  Plan a trip by rail between two points. Obtain a schedule and
                  explain when the train should arrive at two intermediate
                  points. Purchase the tickets and make the trip. Explain to
                  your counselor what you saw.
              workbook:
                  - lines: 8
