- requirement: 1
  text: |-
    Define geology. Discuss how geologists learn about rock formations. In
    geology, explain why the study of the present is important to understanding
    the past.
- requirement: 2
  text: |-
    Pick three resources that can be extracted or mined from Earth for
    commercial use. Discuss with your counselor how each product is discovered
    and processed.
- requirement: 3
  text: |-
    Review a geologic map of your area or an area selected by your counselor,
    and discuss the different rock types and estimated ages of rocks
    represented. Determine whether the rocks are horizontal, folded, or
    faulted, and explain how you arrived at your conclusion.
- requirement: 4
  text: |-
    Do ONE of the following:
  children:
    - requirement: a
      text: |-
        With your parent or guardian's and counselor's approval, visit with a
        geologist, land use planner, or civil engineer. Discuss this
        professional's work and the tools required in this line of work. Learn
        about a project that this person is now working on, and ask to see
        reports and maps created for this project. Discuss with your counselor
        what you have learned.
    - requirement: b
      text: |-
        Find out about three career opportunities available in geology. Pick
        one and find out the education, training, and experience required for
        this profession. Discuss this with your counselor, and explain why this
        profession might interest you.
- requirement: 5
  text: |-
    Do ONE of the following:
  children:
    - requirement: a
      text: |-
        Surface and Sedimentary Processes Option
      children:
        - requirement: 1
          text: |-
            Conduct an experiment approved by your counselor that demonstrates
            how sediments settle from suspension in water. Explain to your
            counselor what the exercise shows and why it is important.
        - requirement: 2
          text: |-
            Using topographical maps provided by your counselor, plot the
            stream gradients (different elevations divided by distance) for
            four different stream types (straight, meandering, dendritic,
            trellis). Explain which ones flow fastest and why, and which ones
            will carry larger grains of sediment and why.
        - requirement: 3
          text: |-
            On a stream diagram, show areas where you will ,find the following
            features: cut bank, fill bank, point bar, medial channel bars, lake
            delta. Describe the relative sediment grain size found in each
            feature.
        - requirement: 4
          text: |-
            Conduct an experiment approved by your counselor that shows how
            some sedimentary material carried by water may be too small for you
            to see without a magnifier.
        - requirement: 5
          text: |-
            Visit a nearby stream. Find clues that show the direction of water
            flow, even if the water is missing. Record your observations in a
            notebook, and sketch those clues you observe. Discuss your
            observations with your counselor.
    - requirement: b
      text: |-
        Energy Resources Option
      children:
        - requirement: 1
          text: |-
            List the top five Earth resources used to generate electricity in
            the United States.
        - requirement: 2
          text: |-
            Discuss source rock, trap, and reservoir rock - the three
            components necessary for the occurrence of oil and gas underground.
        - requirement: 3
          text: |-
            Explain how each of the following items is used in subsurface
            exploration to locate oil or gas: reflection seismic, electric well
            logs, stratigraphic correlation, offshore platform, geologic map,
            subsurface structure map, subsurface isopach map, and core samples
            and cutting samples.
        - requirement: 4
          text: |-
            Using at least 20 data points provided by your counselor, create a
            subsurface structure map and use it to explain how subsurface
            geology maps are used to find oil, gas, or coal resources.
        - requirement: 5
          text: |-
            Do ONE of the following:
          children:
            - requirement: a
              text: |-
                Make a display or presentation showing how oil and gas or coal
                is found, extracted, and processed. You may use maps, books,
                articles from periodicals, and research found on the Internet
                (with your parent or guardian's permission). Share the display
                with your counselor or a small group (such as your class at
                school) in a five-minute presentation.
            - requirement: b
              text: |-
                With your parent or guardian's and counselor's permission and
                assistance, arrange for a visit to an operating drilling rig.
                While there, talk with a geologist and ask to see what the
                geologist does onsite. Ask to see cutting samples taken at the
                site.
    - requirement: c
      text: |-
        Mineral Resources Option
      children:
        - requirement: 1
          text: |-
            Define rock. Discuss the three classes of rocks including their
            origin and characteristics.
        - requirement: 2
          text: |-
            Define mineral. Discuss the origin of minerals and their chemical
            composition and identification properties, including hardness,
            specific gravity, color, streak, cleavage, luster, and crystal
            form.
        - requirement: 3
          text: |-
            Do ONE of the following:
          children:
            - requirement: a
              text: |-
                Collect 10 different rocks or minerals. Record in a notebook
                where you obtained (found, bought, traded) each one. Label each
                specimen, identify its class and origin, determine its chemical
                composition, and list its physical properties. Share your
                collection with your counselor.
            - requirement: b
              text: |-
                With your counselor's assistance, identify 15 different rocks
                and minerals. List the name of each specimen, tell whether it
                is a rock or mineral, and give the name of its class (if it is
                a rock) or list its identifying physical properties (if it is a
                mineral).
        - requirement: 4
          text: |-
            List three of the most common road building materials used in your
            area. Explain how each material is produced and how each is used in
            road building.
        - requirement: 5
          text: |-
            Do ONE of the following:
          children:
            - requirement: a
              text: |-
                With your parent or guardian's and counselor's approval, visit
                an active mining site, quarry, or sand and gravel pit. Tell
                your counselor what you learned about the resources extracted
                from this location and how these resources are used by society.
            - requirement: b
              text: |-
                With your counselor, choose two examples of rocks and two
                examples of minerals. Discuss the mining of these materials and
                describe how each is used by society.
            - requirement: c
              text: |-
                With your parent or guardian's and counselor's approval, visit
                the office of a civil engineer and learn how geology is used in
                construction. Discuss what you learned with your counselor.
    - requirement: d
      text: |-
        Earth History Option
      children:
        - requirement: 1
          text: |-
            Create a chart showing suggested geological eras and periods.
            Determine which period the rocks in your region might have been
            formed.
        - requirement: 2
          text: |-
            Explain the theory of plate tectonics. Make a chart explaining, or
            discuss with your counselor, how the processes of plate tectonics
            work. Discuss how plate tectonics determines the distribution of
            most of the Earth's volcanoes, earthquakes, and mountain belts.
        - requirement: 3
          text: |-
            Explain to your counselor the processes of burial and
            fossilization, and discuss the concept of extinction.
        - requirement: 4
          text: |-
            Explain to your counselor how fossils provide information about
            ancient life, environment, climate, and geography. Discuss the
            following terms and explain how animals from each habitat obtain
            food: benthonic, pelagic, littoral, lacustrine, open marine,
            brackish, fluvial, eolian, protected reef.
        - requirement: 5
          text: |-
            Collect 10 different fossil plants or animals OR (with your
            counselor's assistance) identify 15 different fossil plants or
            animals. Record in a notebook where you obtained (found, bought,
            traded) each one. Classify each specimen to the best of your
            ability, and explain how each one might have survived and obtained
            food. Tell what else you can learn from these fossils.
- requirement: 6
  text: |-
    Do ONE of the following:
  children:
    - requirement: a
      text: |-
        Visit a science museum or the geology department of a local university
        that has fossils on display. With your parent or guardian's and
        counselor's approval, before you go, make an appointment with a curator
        or guide who can show you how the fossils are preserved and prepared
        for display.
    - requirement: b
      text: |-
        Visit a structure in your area that was built using fossiliferous
        rocks. Determine what kind of rock was used and tell your counselor the
        kinds of fossil evidence you found there.
    - requirement: c
      text: |-
        Visit a rock outcrop that contains fossils. Determine what kind of rock
        contains the fossils, and tell your counselor the kinds of fossil
        evidence you found at the outcrop.
    - requirement: d
      text: |-
        Prepare a display or presentation on your state fossil. Include an
        image of the fossil, the age of the fossil, and its classification. You
        may use maps, books, articles from periodicals, and research found on
        the Internet (with your parent or guardian's permission). Share the
        display with your counselor or a small group (such as your class at
        school). If your state does not have a state fossil, you may select a
        state fossil from a neighboring state.
