- requirement: 1
  text: |-
      Identify the different American Indian cultural areas. Explain what makes
      them each unique.
- requirement: 2
  text: |-
      Research an American Indian tribe, group, or nation. Tell your counselor
      about traditional dwellings, way of life, tribal government, religious
      beliefs, family and clan relationships, language, clothing styles, arts and
      crafts, food cultivation, foraging and preparation, means of getting
      around, games, customs in warfare, and where and how they live today.
- requirement: 3
  text: "Do the following:"
  children:
      - requirement: a
        text: |-
            Learn 10 common terms in an American Indian language and their
            meanings.
      - requirement: b
        text: |-
            Identify the meaning of 10 place names of American Indian origin in
            the United States.
      - requirement: c
        text: |-
            Name five well-known American Indian leaders, either from the past or
            people of today. Give their tribes or nations. Describe what they did or do now
            that makes them notable.
- requirement: 4
  text: "Do the following:"
  children:
      - requirement: a
        text: |-
            Describe how life might have been different for the European settlers
            if there had been no Native Americans to meet them when they came to
            this continent.
      - requirement: b
        text: |-
            Describe eight things adopted by others from American Indians.
      - requirement: c
        text: |-
            Learn a game played by a group or tribe. Teach and lead it with a Scout group.
- requirement: 5
  text: "Do ONE of the following:"
  children:
      - requirement: a
        text: |-
            Visit a museum either in-person or virtually to see American Indian
            exhibitions and collections. Discuss with your counselor what you
            observed or learned from two exhibitions and identify 10 artifacts by
            tribe or nation, their shape, size, and use.
      - requirement: b
        text: |-
            Attend a contemporary American Indian gathering. Discuss with your
            counselor proper etiquette for attending as well as what you learned
            and observed during your visit.
