- requirement: 1
  markdown: true
  text: |-
    In your own words, define *inventing*. Then do the following:
  children:
    - note:
        - inPerson
        - online
      text: |-
        The first part of this requirement expects you to define inventing
        in your own words. Scout will need to be able to communicate to the
        counselor during the class their definition for inventing in their
        own words. Remember, there is no right or wrong answer as this part
        of the requirement is asking you how YOU define inventing. It is
        recommended that Scouts consider using a merit badge workbook or
        notebook to make notes ahead of time for easier reference and quick
        completion of this requirement during the class.
    - requirement: a
      text: |-
        Explain to your merit badge counselor the role of inventors and
        their inventions in the economic development of the United States.
      children:
        - note:
            - inPerson
            - online
          text: |-
            Scouts should be prepared with their explanation on this
            requirement component when attending the class.
    - requirement: b
      text: |-
        List three inventions and state how they have helped humankind.
      children:
        - note:
            - inPerson
            - online
          text: |-
            Scouts should come to the class with their three selected
            inventions already in mind and be prepared to share how they
            have helped humankind.  Only Scouts woo actively participate
            and contribute to the discussion will be considered for sign
            off on this requirement component.
- requirement: 2
  text: |-
    Do ONE of the following:
  children:
    - requirement: a
      text: |-
        Identify and interview with a buddy (and with your parent’s
        permission and merit badge counselor’s approval) an individual in
        your community who has invented a useful item. Report what you
        learned to your counselor.
    - requirement: b
      text: |-
        Read about three inventors. Select the one you find most
        interesting and tell your counselor what you learned.
    - note:
        - inPerson
        - online
      text: |-
        While Scouts may choose either of these options, it is recommended
        to consider doing option 2b for those Scouts desiring the highest
        chance of completion of this requirement during the class. Time
        will be allotted during the class for Scouts who come prepared to
        complete both requirements, however, remember that completion of
        this requirement (and any merit badge requirement for that matter)
        is at the discretion and satisfaction of the merit badge counselor.
        To offer Scouts the greatest chance of completion, preparation is
        must and thorough notes and documentation can help support your
        preparation efforts and work.
- requirement: 3
  text: |-
    Do EACH of the following:
  children:
    - requirement: a
      markdown: true
      text: |-
        Define the term *intellectual property*. Explain which government
        agencies oversee the protection of intellectual property, the types
        of intellectual property that can be protected, how such property
        is protected, and why protection is necessary.
      children:
        - note:
            - inPerson
            - online
          text: |-
            Scouts will find the use of the current Inventing Merit Badge
            pamphlet to give a good explanation for an understanding
            needed to complete this requirement component.  It is
            recommended that Scouts utilize this resource, or other
            comparable resources to be prepared for explanation during
            the class. Only Scouts who can share their understanding of
            this requirement component and its objective will be
            considered for sign off. Be prepared.
    - requirement: b
      text: |-
        Explain the components of a patent and the different types of
        patents available.
      children:
        - note:
            - inPerson
            - online
          text: |-
            Requirement component 3b requires Scouts to bring the item
            they selected to class so that they can report their findings
            and share their results with their counselor and fellow
            Scouts. Scouts not doing this component ahead of time will
            have no chance of completing this requirement during the
            class. Make sure you get your parent's signature in your
            Scoutmaster Bucky Inventing Merit Badge Workbook to show your
            counselor that you complied with the requirements of this
            component.
    - requirement: c
      text: |-
        Examine your Scouting gear and find a patent number on a camping
        item you have used. With your parent’s permission, use the internet
        to find out more about that patent. Compare the finished item with
        the claims and drawings in the patent. Report what you learned to
        your counselor.
      children:
        - note:
            - inPerson
            - online
          text: |-
            Scouts will need to do a little preparation work prior to the
            class for this requirement component. It is highly encouraged
            that the Scout brings their selected gear to class along with
            their research documentation and findings for the highest
            level of potential success in completing this requirement.
            Scouts should be prepared to share their work with the class
            and counselor in completing this requirement component.
    - requirement: d
      markdown: true
      text: |-
        Explain to your counselor the term *patent infringement*.
      children:
        - note:
            - inPerson
            - online
          text: |-
            Requirement 3d can easily be found in the merit badge
            pamphlet. Scouts should make notes to assist them with the
            explanation part of this requirement component. Scouts that
            attend the class with a general understanding of what patent
            infringement will find the greatest of success in completing
            this requirement component.
- requirement: 4
  text: |-
    Discuss with your counselor the types of inventions that are appropriate
    to share with others, and explain why. Tell your counselor about one
    unpatented invention and its impact on society.
  children:
    - note:
        - inPerson
        - online
      text: |-
        Scouts should have this written out to show the counselor that some
        thought and research has gone into this requirement and Scouts
        should be prepared to discuss their findings. Scouts will not
        automatically be signed off on this requirement just for attending
        as the requirement states that they must discuss a number of items
        and will be required to partake in group and/or individual
        discussion to obtain credit.
- requirement: 5
  text: |-
    Choose a commercially available product that you have used on an
    overnight camping trip with your troop. Make recommendations for
    improving the product, and make a sketch that shows your recommendations.
    Discuss your recommendations with your counselor.
  children:
    - note:
        - inPerson
        - online
      text: |-
        Scouts should bring their selected item with them to the class for
        inclusion in their discussion. Scouts wishing to offer themselves
        the greatest opportunity to complete this requirement at the class
        will need to have their sketch completed prior to the class.  Extra
        time during the class has not been allotted for completing the
        sketch, so Scouts not coming with this part of the requirement
        completed may be challenged in having all the necessary items ready
        for review by the counselor at the class.
- requirement: 6
  text: |-
    Think of an item you would like to invent that would solve a problem for
    your family, troop, chartered organization, community, or a
    special-interest group. Then do EACH of the following, while keeping a
    notebook to record your progress.
  children:
    - requirement: a
      text: |-
        Talk to potential users of your invention and determine their
        needs. Then, based on what you have learned, write a statement
        describing the invention and how it would help solve a problem.
        This statement should include a detailed sketch of the invention.
    - requirement: b
      text: |-
        Create a model of the invention using clay, cardboard, or any other
        readily available material. List the materials necessary to build a
        working prototype of the invention.
    - requirement: c
      text: |-
        Share the idea and the model with your counselor and potential
        users of your invention. Record their feedback in your notebook.
    - note:
        - inPerson
        - online
      markdown: true
      text: |-
        Scouts should complete as much of this requirement as possible
        prior to the class. The class is accommodating the time and
        opportunity for Scouts to present and share their ideas as the
        requirement necessitates. Scouts who are not able to bring the
        completed preparation work for this requirement will have an
        opportunity to receive guidance from the counselor during the class
        in order to help direct them towards completion.

        This requirement is directly related to and is a precursor to
        requirement 7. You will need to complete this requirement before
        moving on to, and completing requirement 7.
- requirement: 7
  markdown: true
  text: |-
    Build a working prototype of the item you invented for requirement 6`*`.
    Test and evaluate the invention. Among the aspects to consider in your
    evaluation are cost, usefulness, marketability, appearance, and function.
    Describe how your original vision and expectations for your invention are
    similar or dissimilar to the prototype you built. Have your counselor
    evaluate and critique your prototype.

    `*` Before you begin building the prototype, you must have your
    counselor’s approval, based on the design and building plans you have
    already shared.
  children:
    - note:
        - inPerson
        - online
      text: |-
        Scouts will NOT be able to complete this requirement until after
        the class as this requirement is associated directly with the
        successful completion of Requirement 6 prior to working on this
        one. Scouts will be presented with a few follow up options for
        sharing their prototype to complete this requirement. They will
        learn of these opportunities at the day of the class.
- requirement: 8
  text: |-
    Do ONE of the following:
  children:
    - requirement: a
      text: |-
        Participate with a club or team (robotics team, science club, or
        engineering club) that builds a useful item. Share your experience
        with your counselor.
    - requirement: b
      text: |-
        Visit a museum or exhibit dedicated to an inventor or invention,
        and create a presentation of your visit to share with a group such
        as your troop or patrol.
    - note:
        - inPerson
        - online
      text: |-
        Scouts should choose one of the options in this requirement to work
        on prior to the class and bring their completed work to the class
        ready to share. The counselor will facilitate a group discussion on
        both of these options during the class, allowing Scouts to share
        their findings and learn from other Scouts. Only Scouts who have
        done preparation work and are able to satisfactorily demonstrate
        they have completed the items within the selected option AND
        actively participate in the group discussion, will be considered
        for completion of this requirement. It is recommended that some
        proof of participation or visitation be brought along to help
        support your attendance portion of this requirement. Scouts will
        NOT be able to complete this requirement without some preparation
        work prior to the class.
- requirement: 9
  text: |-
    Discuss with your counselor the diverse skills, education, training, and
    experience it takes to be an inventor. Discuss how you can prepare
    yourself to be creative and inventive to solve problems at home, in
    school, and in your community.  Discuss three career fields that might
    utilize the skills of an inventor.
  children:
    - note:
        - inPerson
        - online
      text: |-
        Scouts should review this requirement and its elements and be
        prepared to discuss. It is strongly recommended that Scouts bring
        any notes or supporting documents they may have to help show the
        counselor that they have prepared for discussion of these items.
