- requirement: 1
  text: |-
    Demonstrate that you know how to respond to electrical emergencies by
    doing the following:
  children:
    - requirement: a
      text: |-
        Show how to rescue a person touching a live wire in the home.
    - requirement: b
      text: |-
        Show how to render first aid to a person who is unconscious from
        electrical shock.
    - requirement: c
      text: |-
        Show how to treat an electrical burn.
    - requirement: d
      text: |-
        Explain what to do in an electrical storm.
    - requirement: e
      text: |-
        Explain what to do in the event of an electrical fire.
- requirement: 2
  text: |-
    Complete an electrical home safety inspection of your home, using the
    checklist found in this pamphlet or one approved by your counselor.
    Discuss what you find with your counselor.
- requirement: 3
  text: |-
    Make a simple electromagnet and use it to show magnetic attraction and
    repulsion.
- requirement: 4
  text: |-
    Explain the difference between direct current and alternating current.
- requirement: 5
  text: |-
    Make a simple drawing to show how a battery and an electric bell work.
- requirement: 6
  text: |-
    Explain why a fuse blows or a circuit breaker trips. Tell how to find a
    blown fuse or tripped circuit breaker in your home. Show how to safely
    reset the circuit breaker.
- requirement: 7
  text: |-
    Explain what overloading an electric circuit means. Tell what you have
    done to make sure your home circuits are not overloaded.
- requirement: 8
  text: |-
    Make a floor plan wiring diagram of the lights, switches, and outlets for
    a room in your home. Show which fuse or circuit breaker protects each
    one.
- requirement: 9
  text: |-
    Do the following:
  children:
    - requirement: a
      text: |-
        Read an electric meter and, using your family’s electric bill,
        determine the energy cost from the meter readings.
    - requirement: b
      text: |-
        Discuss with your counselor five ways in which your family can
        conserve energy.
- requirement: 10
  text: |-
    Explain the following electrical terms: volt, ampere, watt, ohm,
    resistance, potential difference, rectifier, rheostat, conductor,
    ground, GFCI, circuit, and short circuit.
- requirement: 11
  text: |-
    Do any TWO of the following:
  children:
    - requirement: a
      text: |-
        Connect a buzzer, bell, or light with a battery. Have a key or
        switch in the line.
    - requirement: b
      text: |-
        Make and run a simple electric motor (not from a kit).
    - requirement: c
      text: |-
        Build a simple rheostat. Show that it works.
    - requirement: d
      text: |-
        Build a single-pole, double-throw switch. Show that it works.
    - requirement: e
      text: |-
        Hook a model electric train layout to a house circuit.
