- requirement: 1
  text: |-
      Demonstrate that you know how to respond to electrical emergencies by
      doing the following:
  children:
      - requirement: a
        text: |-
            Show how to rescue a person touching a live wire in the home.
        workbook:
            - task: true
      - requirement: b
        text: |-
            Show how to render first aid to a person who is unconscious from
            electrical shock.
        workbook:
            - task: true
      - requirement: c
        text: |-
            Show how to treat an electrical burn.
        workbook:
            - task: true
      - requirement: d
        text: |-
            Explain what to do in an electrical storm.
        workbook:
            - lines: 8
      - requirement: e
        text: |-
            Explain what to do in the event of an electrical fire.
        workbook:
            - lines: 8
      - note:
            - inPerson
            - online
        text: |-
            Scouts will need to be prepared with an understanding and skills to
            demonstrate all components of this requirement during the class.
            Many of these items can be easily found in the Electricity Merit
            Badge pamphlet or the First Aid Merit Badge pamphlet.  The
            counselor / instructor will facilitate time during the class for
            each Scout to demonstrate their knowledge and ability on each of
            these components for Requirement 1.
- requirement: 2
  text: |-
      Complete an electrical home safety inspection of your home, using the
      checklist found in this pamphlet or one approved by your counselor.
      Discuss what you find with your counselor.
  workbook:
      - lines: 8
  children:
      - note:
            - inPerson
            - online
        text: |-
            This requirement will not be able to be completed during the class
            without some preparation work at home prior to the class.  As the
            requirement states, you must use the home safety inspection
            checklist found in the Electricity Merit Badge pamphlet to work on
            this requirement.  It is requested that an adult family member
            initials or signs the checklist to validate the completion of this
            prior to the class.  Only Scouts having prepared for this
            requirement by doing the home safety inspection to the satisfaction
            of the counselor / instructor, will be considered for sign off on
            this requirement during the class. Class time will be allotted for
            discussion on this requirement for all who have come prepared.
- requirement: 3
  text: |-
      Make a simple electromagnet and use it to show magnetic attraction and
      repulsion.
  workbook:
      - task: true
  children:
      - note:
            - inPerson
        text: |-
            It is encouraged that Scouts review this requirement and attempt to
            make an electromagnet prior to the class.  The class will have this
            requirement as an activity which will allow all Scouts an
            opportunity to help build an electromagnet, however, if the class
            time is running short, this requirement will be the one that is cut
            and only Scouts who have done preparation work and can show their
            home-made electromagnet will be considered for sign off.
      - note:
            - online
        text: |-
            Scouts will need to attend the class with their electromagnet
            already constructed.  Directions on how to put one together can be
            found in the Electricity Merit Badge pamphlet and/or through a
            simple internet query.  Only Scouts that successfully create an
            electromagnet AND share it during the class will be considered for
            sign off on this requirement.  Scouts alternatively may make
            arrangemenets with the merit badge counselor for review and
            completion of this after the class.
- requirement: 4
  text: |-
      Explain the difference between direct current and alternating current.
  workbook:
      - lines: 8
  children:
      - note:
            - inPerson
            - online
        text: |-
            Scouts should review the merit badge pamphlet for an explanation
            and understanding of this requirement.  Each Scout will have an
            opportunity to explain their findings with the counselor /
            instructor.
- requirement: 5
  text: |-
      Make a simple drawing to show how a battery and an electric bell work.
  workbook:
      - grid: 30
  children:
      - note:
            - inPerson
        text: |-
            This requirement will be covered during the class however Scouts
            should consider reviewing the merit badge pamphlet on this subject
            so they have a general understanding of the requirement.
      - note:
            - online
        text: |-
            This requirement will be reviewed during the class, however Scouts
            will need to make their diagram ahead of the class to be prepared
            for this requirement during the class.
- requirement: 6
  text: |-
      Explain why a fuse blows or a circuit breaker trips. Tell how to find a
      blown fuse or tripped circuit breaker in your home. Show how to safely
      reset the circuit breaker.
  workbook:
      - lines: 8
        text: |-
            Why a fuse blows or a circuit breaker trips
      - lines: 8
        text: |-
            How to find a blown fuse or a tripped circuit breaker
      - task: true
        text: |-
            Show how to safely reset the circuit breaker
  children:
      - note:
            - inPerson
            - online
        text: |-
            While this requirement will be covered in the class, Scouts should
            review their merit badge pamphlet so they are prepared to explain
            their understanding of the requirement.
- requirement: 7
  text: |-
      Explain what overloading an electric circuit means. Tell what you have
      done to make sure your home circuits are not overloaded.
  workbook:
      - lines: 8
        text: |-
            What overloading an electric circuit means
      - lines: 8
        text: |-
            What you have done to make sure your home circuits are not
            overloaded
  children:
      - note:
            - inPerson
            - online
        text: |-
            Again, this is another requirement that will be covered in the
            class however Scouts should review the merit badge pamphlet for a
            better understanding of the requirement and be prepared to give
            explanation of their understanding.
- requirement: 8
  text: |-
      Make a floor plan wiring diagram of the lights, switches, and outlets for
      a room in your home. Show which fuse or circuit breaker protects each
      one.
  workbook:
      - area: 45
  children:
      - note:
            - inPerson
            - online
        text: |-
            Scouts should do this requirement prior to the class.  Even if it
            is simply identifying where outlets and lights are located, the
            counselor / instructor will help refine these drawings with actual
            electrical schematics.
- requirement: 9
  text: |-
      Do the following:
  children:
      - requirement: a
        text: |-
            Read an electric meter and, using your family’s electric bill,
            determine the energy cost from the meter readings.
        workbook:
            - lines: 8
        children:
            - note:
                  - inPerson
                  - online
              text: |-
                  Scouts will want to review with their parent(s) prior to the
                  class this requirement and come prepared to the class to
                  share their findings.  It is strongly recommended that any
                  supporting documentation or pictures Scouts can bring with
                  will help the counselor / instructor better assess their
                  completion of this requirement.
      - requirement: b
        text: |-
            Discuss with your counselor five ways in which your family can
            conserve energy.
        workbook:
            - lines: 8
            - lines: 8
            - lines: 8
            - lines: 8
            - lines: 8
        children:
            - note:
                  - inPerson
                  - online
              text: |-
                  This component of the requirement will be completed in the
                  class however, Scouts should come prepared with ideas that
                  they can share during the class discussion as it pertains to
                  this component of the requirement.
- requirement: 10
  text: |-
      Explain the following electrical terms: volt, ampere, watt, ohm,
      resistance, potential difference, rectifier, rheostat, conductor,
      ground, GFCI, circuit, and short circuit.
  workbook:
      - lines: 8
        text: |-
            Volt
      - lines: 8
        text: |-
            Ampere
      - lines: 8
        text: |-
            Watt
      - lines: 8
        text: |-
            Ohm
      - lines: 8
        text: |-
            Resistance
      - lines: 8
        text: |-
            Potential difference
      - lines: 8
        text: |-
            Rectifier
      - lines: 8
        text: |-
            Rheostat
      - lines: 8
        text: |-
            Conductor
      - lines: 8
        text: |-
            Ground
      - lines: 8
        text: |-
            GFCI
      - lines: 8
        text: |-
            Circuit
      - lines: 8
        text: |-
            Short circuit
  children:
      - note:
            - inPerson
            - online
        text: |-
            Scouts can easily define these terms through the review of the
            Electricity Merit Badge pamphlet.  It is recommended that Scouts
            utilize a Merit Badge Workbook or a notebook to make notes on their
            findings.  These notes can be used to help with their explanation
            of each of the terms during the class.  It should be noted that
            Scouts simply reading the answers or recycling the words from the
            merit badge pamphlet for these terms will NOT be signed off on this
            requirement.  Scouts should clearly understand the terms and not
            just read their answers.
- requirement: 11
  text: |-
      Do any TWO of the following:
  children:
      - requirement: a
        text: |-
            Connect a buzzer, bell, or light with a battery. Have a key or
            switch in the line.
        workbook:
            - task: true
      - requirement: b
        text: |-
            Make and run a simple electric motor (not from a kit).
        workbook:
            - task: true
      - requirement: c
        text: |-
            Build a simple rheostat. Show that it works.
        workbook:
            - task: true
      - requirement: d
        text: |-
            Build a single-pole, double-throw switch. Show that it works.
        workbook:
            - task: true
      - requirement: e
        text: |-
            Hook a model electric train layout to a house circuit.
        workbook:
            - task: true
      - note:
            - inPerson
        text: |-
            Scouts are encouraged to consider doing this requirement ahead of
            time, but it is not necessary as the counselor will have projects
            set up during the class for Scouts to explore and discover as they
            complete this requirement.
      - note:
            - online
        text: |-
            Scouts will need to choose two of the requirement components and
            bring their prepared work to the class for review and discussion
            with the counselor / instructor during the class.
