# Had chunk from Safety at the top
# Had chunk from Scholarship at the bottom
- requirement: 1
  text: |-
      Do the following:
  children:
      - requirement: a
        text: |-
            Explain the responsibilities of a salesperson and how a salesperson
            serves customers and helps stimulate the economy.
        workbook:
            - lines: 8
        children:
            - note:
                  - inPerson
                  - online
              text: |-
                  Scouts should think about what a salesperson does, what they
                  think their responsibilities are and how they serve
                  customers, as well as how salesperson affects the economy.
                  Scouts should consider formulating their thoughts and making
                  notes as needed, in preparation for explanation during the
                  class discussion for this requirement component.
      - requirement: b
        text: |-
            Explain the differences between a business-to-business salesperson
            and a consumer salesperson.
        workbook:
            - lines: 8
        children:
            - note:
                  - inPerson
                  - online
              text: |-
                  Scouts should review their merit badge pamphlet and come with
                  an understanding for discussion in the class the differences
                  asked for in this requirement component. It is highly
                  recommended to utilize a Merit Badge Workbook to make notes
                  of your findings. Scouts in attendance that have not reviewed
                  their merit badge pamphlet for this topic and/or do not
                  actively participate in the class discussion will find it
                  difficult to complete this requirement.
- requirement: 2
  text: |-
      Explain why it is important for a salesperson to do the following:
  children:
      - requirement: a
        text: |-
            Research the market to be sure the product or service meets the
            needs of customers.
        workbook:
            - lines: 8
      - requirement: b
        text: |-
            Learn all about the product or service to be sold.
        workbook:
            - lines: 8
      - requirement: c
        text: |-
            If possible, visit the location where the product is built and
            learn how it is constructed. If a service is being sold, learn
            about the benefits of the service to the customer.
        workbook:
            - lines: 8
      - requirement: d
        text: |-
            Follow up with customers after their purchase to confirm their
            satisfaction and discuss their concerns about the product or
            service.
        workbook:
            - lines: 8
      - note:
            - inPerson
            - online
        text: |-
            Scouts will find the use of the Scoutmaster Bucky Salesmanship
            Merit Badge pamphlet to be very helpful when preparing for this
            requirement and its components. Many of the concepts and ideas
            required for completion of these requirement components can be
            found in the merit badge pamphlet. It is highly recommended that
            Scouts consider utilizing a merit badge workbook or notebook to
            make notes for reference when sharing their research and findings
            during the class.
- requirement: 3
  text: |-
      Write and present a sales plan for a product or service and a sales
      territory assigned by your counselor.
  workbook:
      - lines: 8
  children:
      - note:
            - inPerson
            - online
        text: |-
            If possible, Scouts should try and prepare ahead of time for this
            requirement. While time will be allotted during the class to do
            this, Scouts will find it easiest to have done some planning and
            preparation ahead of time. Scouts may want to consider their
            popcorn, wreath sales, camp card, or other fundraising efforts as
            an example of salesmanship to consider when working on this
            requirement. Note that this requirement REQUIRES Scouts to "WRITE a
            sales plan", so Scouts should use a notebook or the Scoutmaster
            Bucky Salesmanship Merit Badge workbook to complete their
            preparation prior to the class for this requirement item.
- requirement: 4
  text: |-
      Make a sales presentation of a product or service assigned by your
      counselor.
  workbook:
      - lines: 8
  children:
      - note:
            - inPerson
            - online
        text: |-
            Scouts should arrive at the class prepared to make a sales
            presentation for a product or service. Again, Scouts may want to
            draw on past experience from popcorn, wreath sales, camp card, or
            other fundraising efforts to prepare for this requirement. All
            Scouts attending will have an opportunity to make their sales
            presentation for consideration of being signed off on this
            requirement. Only Scouts who do a sales presentation to the
            satisfaction of the counselor during the class will be signed off
            on this requirement.
- requirement: 5
  text: |-
      Do ONE of the following and keep a record (cost sheet). Use the sales
      techniques you have learned, and share your experience with your counselor:
  workbook:
      - header: true
        markdown: true
        text: |-
            a. Help your unit raise funds through sales of merchandise or of
            tickets to a Scout event.

            b. Sell your services such as lawn raking or mowing, pet watching,
            dog walking, snow shoveling, and car washing to your neighbors.
            Follow up after the service has been completed and determine the
            customer’s satisfaction.

            c. Earn money through retail selling.
      - lines: 8
  children:
      - requirement: a
        text: |-
            Help your unit raise funds through sales of merchandise or of
            tickets to a Scout event.
        workbookHide: true
      - requirement: b
        text: |-
            Sell your services such as lawn raking or mowing, pet watching, dog
            walking, snow shoveling, and car washing to your neighbors. Follow
            up after the service has been completed and determine the
            customer’s satisfaction.
        workbookHide: true
      - requirement: c
        text: |-
            Earn money through retail selling.
        workbookHide: true
      - note:
            - inPerson
            - online
        text: |-
            Scouts who have participated in a unit fundraising effort will find
            completion of this requirement quite easy. Come prepared to share
            your experience with the counselor during the class for sign off on
            this requirement. If you have not participated in a Scout unit
            fundraising effort, consider other opportunities you may have
            participated in to complete this requirement and be prepared to
            share your experience during the class.  Remember to bring your
            documentations, as specified in this requirement, to the class for
            full consideration for completion of this requirement.
- requirement: 6
  text: |-
      Do ONE of the following:
  children:
      - requirement: a
        text: |-
            Interview a salesperson and learn the following:
        children:
            - requirement: 1
              text: |-
                  What made the person choose sales as a profession?
              workbook:
                  - lines: 4
            - requirement: 2
              text: |-
                  What are the most important things to remember when talking
                  to customers?
              workbook:
                  - lines: 4
            - requirement: 3
              text: |-
                  How is the product or service sold?
              workbook:
                  - lines: 4
            - requirement: 4
              text: |-
                  Include your own questions.
              workbook:
                  - lines: 8
      - requirement: b
        text: |-
            Interview a retail store owner and learn the following:
        children:
            - requirement: 1
              text: |-
                  How often is the owner approached by a sales representative?
              workbook:
                  - lines: 4
            - requirement: 2
              text: |-
                  What good traits should a sales representative have? What
                  habits should the sales representative avoid?
              workbook:
                  - lines: 4
            - requirement: 3
              text: |-
                  What does the owner consider when deciding whether to
                  establish an account with a sales representative?
              workbook:
                  - lines: 4
            - requirement: 4
              text: |-
                  Include at least two of your own questions.
              workbook:
                  - lines: 8
      - note:
            - inPerson
            - online
        text: |-
            Scouts will have an opportunity to complete this requirement during
            the class, however it is encouraged that Scouts consider doing this
            requirement ahead of time to share as a part of the class.
- requirement: 7
  text: |-
      Investigate and report on career opportunities in sales, then do the
      following:
  workbook:
      - lines: 3
        text: |-
            The chosen career
  children:
      - requirement: a
        text: |-
            Prepare a written statement of your qualifications and experience.
            Include relevant classes you have taken in school and merit badges
            you have earned.
        workbook:
            - lines: 8
      - requirement: b
        text: |-
            Discuss with your counselor what education, experience, or training
            you should obtain so you are prepared to serve in a sales position.
        workbook:
            - lines: 8
      - note:
            - inPerson
            - online
        text: |-
            Scouts should consider working on this requirement prior to the
            class. While the counselor will help facilitate further insight to
            the components of this requirement, some Scouts may find it easier
            to come to the class with their required written statement
            completed, or at least started. While time will be allotted during
            the class to work on this, only Scouts who actively participate in
            the class discussion on this requirement and its components AND
            have a completed wirtten statement, will be considered for sign off
            on this requirement.
