# 1 has "Do the following:" bolded. I've removed bold from those words.
- requirement: 1
  markdown: true
  text: |-
    <strong>Safety.</strong> Do the following:
  children:
    - requirement: a
      markdown: true
      text: |-
        View the <a
        href="https://www.scouting.org/training/youth-protection/scouts-bsa/"
        >Personal Safety Awareness "Digital Safety" video</a > (with your
        parent or guardian's permission.)
    - requirement: b
      text: |-
        Discuss first aid and prevention for the types of injuries that could
        occur during programming activities, including repetitive stress
        injuries and eyestrain.
- requirement: 2
  markdown: true
  text: |-
    <strong>History.</strong> Discuss with your counselor the history of
    programming and the evolution of programming languages, including at least
    three milestones related to the advancement or development of programming
    over time.
- requirement: 3
  markdown: true
  text: |-
    <strong>General Knowledge.</strong> Do the following:
  children:
    - requirement: a
      text: |-
        Create a list of five popular programming languages in use today and
        describe which industry or industries they are primarily used in and
        why.
    - requirement: b
      text: |-
        Describe three different programmed devices you rely on every day.
- requirement: 4
  text: |-
    <strong>Intellectual Property.</strong> Do the following:
  children:
    - requirement: a
      text: |-
        Explain the four types of intellectual property used to protect
        computer programs.
    - requirement: b
      text: |-
        Describe the difference between licensing and owning software.
    - requirement: c
      text: |-
        Describe the differences between freeware, open source, and commercial
        software, and why it is important to respect the terms of use of each.
- requirement: 5
  markdown: true
  text: |-
    <strong>Project.</strong> With your counselor's guidance, select three
    different programming languages and development environments. For each
    sub-requirement below, do the following: Write or modify a program using
    the indicated programming language and development environment. The program
    must take input and produce output based on computations and decisions made
    on the input. Debug and demonstrate the program to your counselor. Explain
    how each program processes inputs, makes decisions based on those inputs,
    and provides outputs based on computations and decision making.
  children:
    - requirement: a
      markdown: true
      text: |-
        In the first language and environment, write or modify a program, debug
        and demonstrate, and explain as above.

        With your counselor's approval, choose a sample program. Modify the
        code or add a function or subroutine to it. Debug and demonstrate the
        modified program to your counselor. The Programming merit badge
        website, <a href="http://www.scoutlife.org/programming"
        >www.scoutlife.org/programming</a >, has a number of sample programs
        that you could use for requirement 5. However, you have the option of
        finding a program on your own. It's a good idea to seek your
        counselor's guidance.
    - requirement: b
      text: |-
        In the second language and environment, write or modify a program,
        debug and demonstrate, and explain as above.
    - requirement: c
      text: |-
        In the third language and environment, write or modify a program, debug
        and demonstrate, and explain as above.
- requirement: 6
  markdown: true
  text: |-
    <strong>Careers.</strong> Find out about three career opportunities that
    require knowledge in programming. Pick one and find out the education,
    training, and experience required. Discuss this with your counselor and
    explain why this career might be of interest to you.
