- requirement: 1
  text: |-
      Before doing requirements 3 through 15, review with your counselor the
      principles of Safe Swim Defense.
  workbook:
      - task: true
- requirement: 2
  text: |-
      Before doing requirements 3 through 15:
  children:
      - requirement: a
        text: |-
            Earn the Swimming merit badge.
        workbook:
            - task: true
      - requirement: b
        text: |-
            Swim continuously for 400 yards using each of the following strokes
            in a strong manner, in good form with rhythmic breathing, for at
            least 50 continuous yards: front crawl, sidestroke, breaststroke,
            and elementary backstroke.
        workbook:
            - task: true
- requirement: 3
  text: |-
      Explain the following:
  children:
      - requirement: a
        text: |-
            Common drowning situations and how to prevent them.
        workbook:
            - lines: 8
      - requirement: b
        text: |-
            How to identify persons in the water who need assistance.
        workbook:
            - lines: 8
      - requirement: c
        text: |-
            The order of methods in water rescue.
        workbook:
            - lines: 8
      - requirement: d
        text: |-
            How rescue techniques vary depending on the setting and the
            condition of the person needing assistance.
        workbook:
            - lines: 8
      - requirement: e
        text: |-
            Situations for which in-water rescues should not be undertaken.
        workbook:
            - lines: 8
- requirement: 4
  text: |-
      Demonstrate “reaching” rescues using various items such as arm, leg,
      towels, shirts, paddles, and poles.
  workbook:
      - task: true
- requirement: 5
  text: |-
      Demonstrate “throwing” rescues using various items such as a line, ring
      buoy, rescue bag, and free-floating support.  Successfully place at least
      one such aid within reach of a practice victim 25 feet from shore.
  workbook:
      - task: true
- requirement: 6
  text: |-
      With your counselor’s approval, view in-person or on video a rowing
      rescue performed using a rowboat, canoe, kayak, or stand up paddleboard.
      Discuss with your counselor how effectively and efficiently the rescue
      was performed.
  workbook:
      - lines: 8
- requirement: 7
  text: |-
      List various items that can be used as aids in a “go” rescue.  Explain
      why buoyant aids are preferred.
  workbook:
      - lines: 8
- requirement: 8
  markdown: true
  text: |-
      Correctly demonstrate rescues of a *conscious* practice subject 30 feet
      from shore in deep water using two types of buoyant aids provided by your
      counselor. Use a proper entry and a strong approach stroke. Speak to the
      subject to determine his or her condition and to provide instructions and
      encouragement.
  children:
      - requirement: a
        text: |-
            Present one aid to a subject, release it, and swim at a safe
            distance as the subject moves to safety.
        workbook:
            - task: true
      - requirement: b
        text: |-
            In a separate rescue, present the other aid to a subject and use it
            to tow the subject to safety.
        workbook:
            - task: true
- requirement: 9
  markdown: true
  text: |-
      Discuss with your counselor when it is appropriate to remove heavy
      clothing before attempting a swimming rescue. Remove street clothes in 20
      seconds or less, enter the water, and approach a *conscious* practice
      subject 30 feet from shore in deep water. Speak to the subject and use a
      nonbuoyant aid, such as a shirt or towel, to tow the subject to safety.
  workbook:
      - lines: 8
- requirement: 10
  text: |-
      Discuss with your counselor the importance of avoiding contact with an
      active subject and demonstrate lead-and-wait techniques.
  workbook:
      - lines: 8
- requirement: 11
  markdown: true
  text: |-
      Perform the following *nonequipment* rescues for a *conscious* practice
      subject 30 feet from shore. Begin in the water from a position near the
      subject. Speak to the subject to determine his or her condition and to
      provide instructions and encouragement.
  children:
      - requirement: a
        text: |-
            Perform an armpit tow for a calm, responsive, tired swimmer resting
            with a back float.
        workbook:
            - task: true
      - requirement: b
        text: |-
            Perform a cross-chest carry for an exhausted, responsive subject
            treading water.
        workbook:
            - task: true
- requirement: 12
  text: |-
      In deep water, show how to escape from a victim’s grasp on your wrist.
      Repeat for front and rear holds about the head and shoulders.
  workbook:
      - task: true
- requirement: 13
  markdown: true
  text: |-
      Perform the following rescues for an *unconscious* practice subject at or
      near the surface 30 feet from shore. Use a proper entry and strong
      approach stroke. Speak to the subject and splash water on the subject to
      determine his or her condition before making contact. Quickly remove the
      victim from the water, with assistance if needed, and position for CPR.
  children:
      - requirement: a
        text: |-
            Perform an equipment assist using a buoyant aid.
        workbook:
            - task: true
      - requirement: b
        text: |-
            Perform a front approach and wrist tow.
        workbook:
            - task: true
      - requirement: c
        text: |-
            Perform a rear approach and armpit tow.
        workbook:
            - task: true
- requirement: 14
  text: |-
      Discuss with your counselor how to respond if a victim submerges before
      being reached by a rescuer, and do the following:
  workbook:
      - lines: 8
  children:
      - requirement: a
        text: |-
            Recover a 10-pound weight in 8 to 10 feet of water using a
            feetfirst surface dive.
        workbook:
            - task: true
      - requirement: b
        text: |-
            Repeat using a headfirst surface dive.
        workbook:
            - task: true
- requirement: 15
  text: |-
      Demonstrate management of a spinal injury to your counselor:
  children:
      - requirement: a
        text: |-
            Discuss the causes, signs, and symptoms of a spinal injury.
        workbook:
            - lines: 8
      - requirement: b
        text: |-
            Support a faceup subject in calm water of standing depth.
        workbook:
            - task: true
      - requirement: c
        text: |-
            Turn a subject from a facedown to a faceup position in water of
            standing depth while maintaining support.
        workbook:
            - task: true
- requirement: 16
  text: |-
      Demonstrate knowledge of resuscitation procedure:
  children:
      - requirement: a
        text: |-
            Describe how to recognize the need for rescue breathing and CPR.
        workbook:
            - lines: 8
      - requirement: b
        text: |-
            Demonstrate CPR knowledge and skills, including rescue breathing,
            on a mannequin under the guidance of a current CPR/AED instructor
            trained by a nationally certified provider.
        workbook:
            - signature: Certified CPR Instructor
- requirement: 17
  text: |-
      With your counselor, discuss causes, prevention, and treatment of other
      injuries or illnesses that could occur while swimming or boating,
      including hypothermia, dehydration, heat-related illnesses, muscle
      cramps, sunburn, stings, and hyperventilation.
  workbook:
      - lines: 8
