- requirement: 1
  text: |-
      Choose A or B or C and complete ALL the requirements.
  children:
      - requirement: A
        text: |-
            Watch an episode or episodes (about one hour total) of a show that
            involves symmetry, mirrors, or artistic patterns. Then do the
            following:
        children:
            - requirement: 1
              text: |-
                  Make a list of at least two questions or ideas from what you
                  watched.
            - requirement: 2
              text: |-
                  Discuss two of the questions or ideas with your counselor.
      - requirement: B
        text: |-
            Read (about one hour total) about anything that involves symmetry,
            mirrors, or artistic patterns. Then do the following:
        children:
            - requirement: 1
              text: |-
                  Make a list of at least two questions or ideas from what you
                  read.
            - requirement: 2
              text: |-
                  Discuss two of the questions or ideas with your counselor.
      - requirement: C
        text: |-
            Do a combination of reading and watching (about one hour total)
            about anything that involves symmetry, mirrors, or artistic
            patterns.  Then do the following:
        children:
            - requirement: 1
              text: |-
                  Make a list of at least two questions or ideas from what you
                  read and watched.
            - requirement: 2
              text: |-
                  Discuss two of the questions or ideas with your counselor.
- requirement: 2
  text: |-
      Complete ONE adventure from the following list, or complete option A or
      B. (If you choose an adventure, choose one that you have not previously
      earned.) Discuss with your counselor what kind of science, technology,
      engineering, or math was used in the adventure.
  children:
      - detail: true
        markdown: true
        text: |-
            * **Wolf Cub Scouts:** Air of the Wolf, Code of the Wolf
      - note:
          - counselor
        markdown: true
        text: |-
            **Air of the Wolf:** The symmetry of flying objects has a big
            impact on how they fly: Does the paper airplane veer to the
            left?  Does it go up instead of down? These concerns also
            apply to kites, sleds, and boats.

            **Code of the Wolf:** Many of the shapes we see in nature
            exhibit symmetry of some kind (leaves, flowers, animals);
            indeed, they often have more interesting symmetry than the
            “pure” squares and circles we draw!  Predictions always
            depend on symmetry. We assume the future will look something
            like the past.
      - detail: true
        markdown: true
        text: |-
            **Bear Cub Scouts:** Forensics, Marble Madness
      - note:
          - counselor
        markdown: true
        text: |-
            **Forensics:** The crystal structure of various substances
            (salt, sugar, etc.) is an important way of distinguishing
            them. Lack of symmetry between two shoe imprints from the
            same pair is an important way of distinguishing an individual
            pair worn by a particular person.

            **Marble Madness:** Notice the most important fact about
            marbles: They roll because they have spherical symmetry, an
            infinite number of symmetrical sides. You also likely created
            some symmetries in your marble courses. What makes a marble
            game “fair”?
      - detail: true
        markdown: true
        text: |-
            **Webelos Scouts:** Art Explosion, Build It
      - note:
          - counselor
        markdown: true
        text: |-
            **Art Explosion:** Notice all the symmetry you can - and also
            where a symmetry you expect is lacking - in the art that you
            see and make. Symmetry tells the viewer what to expect. Lack
            of symmetry can be surprising.

            **Build It:** Look at the symmetry of what you made. Did you
            plan for this?
      - requirement: A
        markdown: true
        text: |-
            **Option A:** Complete all of the following:
        children:
            - requirement: a
              text: |-
                  Explain the difference between the symmetry of the flower of
                  a geranium and the symmetry of the flower of herbaceous
                  periwinkle.
            - requirement: b
              text: |-
                  Explain the difference in leaf arrangement (the pattern of
                  where leaves appear on the stem) between a maple tree and a
                  sweetgum tree.
            - requirement: c
              text: |-
                  Find another pair of plants that you can distinguish based on
                  some difference in symmetry.
      - requirement: B
        markdown: true
        text: |-
            **Option B:** Complete all of the following:
        children:
            - requirement: a
              text: |-
                  Using toothpicks and colored marshmallows, or other
                  appropriate materials, make a model of the crystal structure
                  of olivine.
            - requirement: b
              text: |-
                  Using toothpicks and colored marshmallows, or other
                  appropriate materials, make a model of the crystal structure
                  of halite.
            - requirement: c
              text: |-
                  Use your models to guess which of the two minerals is harder.
- requirement: 3
  text: |-
      Choose TWO options from A or B or C or D or E , and complete ALL the
      requirements for the options you choose.
  children:
      - requirement: A
        text: |-
            Make a paper lantern.
        children:
            - requirement: 1
              text: |-
                  Fold a large piece of paper in quarters lengthwise.
            - requirement: 2
              text: |-
                  Cut decorative or symbolic shapes into the two folded edges.
            - requirement: 3
              text: |-
                  Unfold, tape the two edges of the paper together, and smooth
                  into a cylinder. Hang by a string.
      - requirement: B
        text: |-
            Learn about the kolam artwork of southern India.
        children:
            - requirement: 1
              text: |-
                  Look at some pictures of kolams. Find as many similarities as
                  possible within each kolam. Is there a repeated pattern? If
                  you turn it a little, do you get the same picture? If you
                  look at it in a mirror, do you get the same picture?
            - requirement: 2
              text: |-
                  Use sand, chalk dust, flour, or some other material to make a
                  kolam of your own.
              children:
                  - note:
                      - counselor
                    markdown: true
                    text: |-
                        Here are some kolams (original artwork courtesy of Sunita Vatuk):

                        <img src="symmetry-1.png" class="W(100%) H(a)">

                        <img src="symmetry-2.png" class="W(100%) H(a)">

                        <img src="symmetry-3.png" class="W(100%) H(a)">

                        <img src="symmetry-4.png" class="W(100%) H(a)">
      - requirement: C
        text: |-
            Learn about the litema wall decorations from Lesotho and South Africa.
        children:
            - note:
                - counselor
              text: |-
                  People in certain regions of Lesotho and South Africa
                  decorate the outside walls of their houses by spreading a mud
                  plaster on the wall and then using their fingers to engrave a
                  pattern in the wet plaster. They first engrave a network of
                  squares, and then engrave the same basic pattern (possibly
                  rotated or reflected) in each square. Good examples are easy
                  to find on the internet, but "African Painted Houses: Basotho
                  Dwellings of Southern Africa" by Gary N. van Wyk (Abrams,
                  1998) also has many beautiful examples.
            - requirement: 1
              text: |-
                  Look at some pictures of litema. What does one basic tile
                  look like? In how many ways can you see that tile arranged
                  (turned a different direction, flipped backward, etc.)
            - requirement: 2
              text: |-
                  Use clay, paper, or some other material to make a litema of
                  your own.
      - requirement: D
        text: |-
            Learn about the design of Navajo rugs.
        children:
            - note:
                - counselor
              text: |-
                  The Navajo people of the southwestern part of the United
                  States have a long tradition of weaving rugs and blankets
                  with various repeating designs. While many fine examples can
                  be found on the internet, "Navajo Textiles: The William
                  Randolph Hearst Collection" by Nancy J. Blomberg (University
                  of Arizona Press, 1994) provides many examples.
            - requirement: 1
              text: |-
                  Look at some pictures of Navajo rugs. Find as many
                  similarities as possible within each rug. Is there a repeated
                  pattern? Is there a mirror image? How many?
            - requirement: 2
              text: |-
                  Using different colors of paper, or other materials, make
                  your own Navajo-like rug.
      - requirement: E
        text: |-
            Learn about Seminole or Miccosukee patchwork designs.
        children:
            - note:
                - counselor
              text: |-
                  In the early 20th century, the Seminole and Miccosukee people
                  of Florida developed a style of clothing decorated by sewing
                  together blocks of fabric with contrasting colors in an
                  alternating design. This distinctive art form was, for a long
                  time, an important source of income for the communities where
                  it was made. There are many examples available on the
                  internet. The book "Patchwork: Seminole and Miccosukee Art
                  and Activities" by Dorothy Downs (Pineapple Press, 2005)
                  contains examples and the story of the art form and is
                  accessible to Cub Scout–age children.
            - requirement: 1
              text: |-
                  Look at some pictures of Seminole or Miccosukee patchwork.
                  Find as many similarities as possible within each piece. What
                  does a basic block of each pattern look like? How many
                  different basic blocks are used in the design?
            - requirement: 2
              text: |-
                  Using different colors of paper, or other materials, make
                  your own Seminole-like patchwork.
- requirement: 4
  text: |-
      Visit a place where symmetry is important (such as an art exhibit,
      building site, or printer) or visit with a person who works with symmetry
      (such as an artist, interior designer, or landscape architect). Discuss
      with your counselor the symmetry or ideas of balance involved.
- requirement: 5
  text: |-
      Discuss with your counselor how symmetry impacts your everyday life.
