- requirement: 1
  text: |-
      Do the following:
  children:
      - requirement: a
        text: |-
            Explain to your counselor the most likely hazards you may encounter
            while participating in small-boat activities and what you should do
            to anticipate, help prevent, mitigate, and respond to these
            hazards.
        workbook:
            - lines: 8
              text: |-
                  Most likely hazards
            - lines: 8
              text: |-
                  Anticipate hazards
            - lines: 8
              text: |-
                  Prevent hazards
            - lines: 8
              text: |-
                  Mitigate hazards
            - lines: 8
              text: |-
                  Respond to hazards
      - requirement: b
        text: |-
            Review prevention, symptoms, and first-aid treatment for the
            following injuries or illnesses that can occur while sailing:
            blisters, cold-water shock and hypothermia, dehydration, and
            heat-related illnesses, sunburn, sprains, and strains.
        workbook:
            - lines: 8
              text: |-
                Blisters
            - lines: 8
              text: |-
                Cold-water shock and hypothermia
            - lines: 8
              text: |-
                Dehydration and heat-related illnesses
            - lines: 8
              text: |-
                Sunburn
            - lines: 8
              text: |-
                Sprains and strains
      - requirement: c
        text: |-
            Discuss the BSA Safety Afloat policy. Tell how it applies to
            small-boat activities.
        workbook:
          - lines: 8
- requirement: 2
  text: |-
      Before doing requirements 3 through 9, successfully complete the BSA
      swimmer test: Jump feetfirst into water over the head in depth. Level off
      and swim 75 yards in a strong manner using one or more of the following
      strokes: sidestroke, breaststroke, trudgen, or crawl; then swim 25 yards
      using an easy, resting backstroke. The 100 yards must be completed in one
      swim without stops and must include at least one sharp turn.  After
      completing the swim, rest by floating.
  workbook:
    - signature: Swim Test Observer
- requirement: 3
  markdown: true
  text: |-
      Describe the boat you will be using for the sailing requirement, naming
      all of the major parts and the function of those parts.`*`

      `*` The skills may be demonstrated on any boat available to the Scout;
      sailboards are not acceptable. While no specific sail plan is
      recommended, it is suggested that the craft be smaller than 20 feet. The
      boat must be capsizable and have the capability of sailing to windward.
  workbook:
    - lines: 8
- requirement: 4
  text: |-
      Before going afloat, do the following:
  children:
      - requirement: a
        text: |-
            Discuss the nine points of the BSA Safety Afloat plan.
        workbook:
          - lines: 4
          - lines: 4
          - lines: 4
          - lines: 4
          - lines: 4
          - lines: 4
          - lines: 4
          - lines: 4
          - lines: 4
      - requirement: b
        text: |-
            Explain the rules of the road in general and any specific rules or
            laws that apply to your area or state.
        workbook:
          - lines: 8
      - requirement: c
        text: |-
            Explain how water conditions, the hazards of weather, and heavy
            winds can affect both safety and performance in sailing.
        workbook:
          - lines: 8
      - requirement: d
        text: |-
            Discuss the warning signs of inclement weather and what to do
            should heavy winds develop or a storm approach.
        workbook:
          - lines: 8
      - requirement: e
        text: |-
            Prepare a typical float plan.
        workbook:
          - lines: 8
      - requirement: f
        text: |-
            Discuss the proper clothing, footwear, and personal gear required
            for small-boat sailing in warm weather and in cool weather. Explain
            how choosing the proper clothing, footwear, and personal gear will
            help keep you comfortable and safe while sailing.
        workbook:
          - lines: 8
- requirement: 5
  text: |-
      Discuss with your counselor how to identify the wind direction and wind
      indicators. Explain the importance of this task before setting sail.
  workbook:
    - lines: 8
- requirement: 6
  text: |-
      Following the BSA Safety Afloat plan, show that you and a buddy can sail
      a boat properly. Do the following:
  children:
      - requirement: a
        text: |-
            Prepare a boat for sailing, including a safety inspection.
        workbook:
            - task: true
      - requirement: b
        text: |-
            Get underway from a dock, mooring, or beach.
        workbook:
            - task: true
      - requirement: c
        text: |-
            Properly set sails for a round-trip course approved by your
            counselor that will include running, beating, and reaching—the
            basic points of sail. While sailing, demonstrate good helmsmanship
            skills.
        workbook:
            - task: true
      - requirement: d
        text: |-
            Change direction by tacking; change direction by jibing.
        workbook:
            - task: true
      - requirement: e
        text: |-
            Demonstrate getting out of irons.
        workbook:
            - task: true
      - requirement: f
        text: |-
            Demonstrate the safety position.
        workbook:
            - task: true
      - requirement: g
        markdown: true
        text: |-
            Demonstrate capsize procedures and the rescue of a person
            overboard.`†`

            `†` Capsize procedures should be conducted under the close
            supervision of the counselor. A rescue boat should be standing by
            to assist, if necessary, and to tow the capsized craft to shore.
            Self-bailing boats are acceptable for this requirement.  Extreme
            care should be taken to avoid personal injury and damage to the
            boat or equipment.
        workbook:
            - task: true
      - requirement: h
        text: |-
            Demonstrate the procedure to take after running aground.
        workbook:
            - task: true
      - requirement: i
        text: |-
            Accept a single line or side tow and maneuver the craft being towed
            safely for 20 boat lengths.
        workbook:
            - task: true
      - requirement: j
        text: |-
            Upon returning to the dock, mooring, or beach, properly secure all
            equipment, furl or stow sails, and prepare the craft for unattended
            docking or beaching overnight or longer.
        workbook:
            - task: true
- requirement: 7
  text: |-
      Demonstrate a working knowledge of marlinespike seamanship. Do the following:
  children:
      - requirement: a
        text: |-
            Show how to tie a square (reef) knot, clove hitch, two half
            hitches, bowline, cleat hitch, and figure-eight knot.  Demonstrate
            the use of each.
        workbook:
          - split:
              - task: true
                text: |-
                    Square (reef) knot
              - task: true
                text: |-
                    Clove hitch
              - task: true
                text: |-
                    Two half hitches
          - split:
              - task: true
                text: |-
                    Bowline
              - task: true
                text: |-
                    Cleat hitch
              - task: true
                text: |-
                    Figure-eight knot
      - requirement: b
        text: |-
            Show how to heave a line, coil a line, and fake down a line.
        workbook:
            - task: true
      - requirement: c
        text: |-
            Discuss the kinds of lines used on sailboats and the types of
            fibers used in their manufacture. Explain the advantages and
            disadvantages of each.
        workbook:
          - lines: 8
- requirement: 8
  text: |-
      Describe how you would care for and maintain a sailboat and its gear
      throughout the year.
  workbook:
    - lines: 8
- requirement: 9
  text: |-
      With your counselor, review sailing terminology and the points of sail.
      Discuss various types of sailboats in use today and explain their
      differences.
  workbook:
    - lines: 8
