- requirement: 1
  text: |-
      Do the following:
  children:
      - requirement: a
        text: |-
            Explain to your counselor the hazards you are most likely to
            encounter while participating in wilderness survival activities,
            and what you should do to anticipate, help prevent, mitigate, or
            lessen these hazards.
        workbook:
            - lines: 3
              text: |-
                  Most likely hazards
            - lines: 3
              text: |-
                  Anticipate hazards
            - lines: 3
              text: |-
                  Prevent hazards
            - lines: 3
              text: |-
                  Mitigate hazards
            - lines: 3
              text: |-
                  Lessen hazards
      - requirement: b
        text: |-
            Show that you know first aid for and how to prevent injuries or
            illnesses that could occur in backcountry settings, including
            hypothermia, heat reactions, frostbite, dehydration, blisters,
            insect stings, tick bites, and snakebites.
        workbook:
            - lines: 2
              text: |-
                  Hypothermia
            - lines: 2
              text: |-
                  Heat reactions
            - lines: 2
              text: |-
                  Frostbite
            - lines: 2
              text: |-
                  Dehydration
            - lines: 2
              text: |-
                  Blisters
            - lines: 2
              text: |-
                  Insect stings
            - lines: 2
              text: |-
                  Tick bites
            - lines: 2
              text: |-
                  Snakebites
- requirement: 2
  text: |-
      From memory, list the seven priorities for survival in a backcountry or
      wilderness location. Explain the importance of each one with your
      counselor.
  workbook:
      - lines: 2
        text: |-
            Most important priority and why it's important
      - lines: 2
        text: |-
            Second most important priority and why it's important
      - lines: 2
        text: |-
            Next priority and why it's important
      - lines: 2
        text: |-
            Next priority and why it's important
      - lines: 2
        text: |-
            Next priority and why it's important
      - lines: 2
        text: |-
            Next priority and why it's important
      - lines: 2
        text: |-
            Least important priority and why it's still important
- requirement: 3
  text: |-
      Discuss ways to avoid panic and maintain a high level of morale when
      lost, and explain why this is important.
  workbook:
      - lines: 8
- requirement: 4
  text: |-
      Describe the steps you would take to survive in the following exposure conditions:
  workbook:
      - lines: 2
        text: |-
            Cold and snowy
      - lines: 2
        text: |-
            Wet
      - lines: 2
        text: |-
            Hot and dry
      - lines: 2
        text: |-
            Windy
      - lines: 2
        text: |-
            At or on the water
  children:
      - requirement: a
        text: |-
            Cold and snowy
        workbookHide: true
      - requirement: b
        text: |-
            Wet
        workbookHide: true
      - requirement: c
        text: |-
            Hot and dry
        workbookHide: true
      - requirement: d
        text: |-
            Windy
        workbookHide: true
      - requirement: e
        text: |-
            At or on the water
        workbookHide: true
- requirement: 5
  text: |-
      Put together a personal survival kit and explain how each item in it
      could be useful.
  workbook:
      - lines: 8
- requirement: 6
  text: |-
      Using three different methods (other than matches), build and light three
      fires.
  workbook:
      - lines: 3
      - lines: 3
      - lines: 3
- requirement: 7
  text: |-
      Do the following:
  children:
      - requirement: a
        text: |-
            Show five different ways to attract attention when lost.
        workbook:
            - lines: 3
            - lines: 3
            - lines: 3
            - lines: 3
            - lines: 3
      - requirement: b
        text: |-
            Demonstrate how to use a signal mirror.
        workbook:
            - lines: 8
      - requirement: c
        text: |-
            Describe from memory five ground-to-air signals and tell what they
            mean.
        workbook:
            - lines: 2
            - lines: 2
            - lines: 2
            - lines: 2
            - lines: 2
- requirement: 8
  text: |-
      Improvise a natural shelter. For the purpose of this demonstration, use
      techniques that have little negative impact on the environment. Spend a
      night in your shelter.
  workbook:
      - lines: 8
        text: |-
            Describe concerns, materials, building process, and other details
      - area: 8
        text: |-
            Illustrate the shelter
- requirement: 9
  text: |-
      Explain how to protect yourself from insects, reptiles, bears, and other
      animals of the local region.
  workbook:
      - lines: 8
- requirement: 10
  text: |-
      Demonstrate three ways to treat water found in the outdoors to prepare it
      for drinking.
  workbook:
      - lines: 3
      - lines: 3
      - lines: 3
- requirement: 11
  text: |-
      Show that you know the proper clothing to wear while in the outdoors
      during extremely hot and cold weather and during wet conditions.
  workbook:
      - lines: 8
- requirement: 12
  text: |-
      Explain why it usually is not wise to eat edible wild plants or wildlife
      in a wilderness survival situation.
  workbook:
      - lines: 8
