- detail: true
  markdown: true
  text: |-
    **“Discussion” requirements will be either with a counselor and another
    individual (in accordance with Youth Protection Guidelines
    https://www.scouting.org/health-and-safety/gss/gss01/), or with your
    counselor and a small group (of Scouts), depending upon your
    preference.**
- requirement: 1
  text: |-
    Before beginning work on other requirements for this merit badge:
  children:
    - requirement: a
      text: |-
        Research the following terms, and then explain to your merit badge
        counselor how you feel they relate to the Scout Oath and Scout Law:
      children:
        - detail: true
          markdown: true
          text: |-
            * Identities
            * Inclusion
            * Diversity
            * Discrimination
            * Equity
            * Ethical Leadership
            * Equality
            * Upstander
- requirement: 2
  text: |-
    Document and discuss with your counselor what leadership means to you.
    Share what it means to make ethical decisions.
  children:
    - requirement: a
      text: |-
        Research and share with your counselor an individual you feel has
        demonstrated positive leadership while having to make an ethical
        decision.  (It could be someone in history, a family member, a
        teacher, a coach, a counselor, a clergy member, a Scoutmaster,
        etc.)
    - requirement: b
      text: |-
        Explain what decision and/or options that leader had, why you
        believe they chose their final course of action, and the outcome of
        that action.
- requirement: 3
  text: |-
    Consider ethical decision-making.
  children:
    - requirement: a
      markdown: true
      text: |-
        Think about a time you faced an ethical decision.

        * Discuss the situation, what you did, and how it made you feel.
        * Share if you would do anything differently in the future and if
        so, what that would be.
    - requirement: b
      markdown: true
      text: |-
        List three examples of ethical decisions you might have to make in
        the future at school, at home, in the workplace, or in your
        community, and what you would do.

        * Share how your actions represent alignment with the Scout Oath
        and Scout Law
    - requirement: c
      markdown: true
      text: |-
        Explain to your counselor how you plan to use what you have learned
        to assist you when that time comes, and what action(s) you can take
        to serve as an upstander and *help other people at all times.*
- requirement: 4
  markdown: true
  text: |-
    Repeat the Scout Oath and Scout Law for your counselor. Choose two of the
    three following scenarios and discuss what you could do as a Scout to
    demonstrate leadership and your understanding of *what it means to help
    others who may seem different from you:*
  children:
    - requirement: a
      text: |-
        Scenario 1: While at camp, a youth accidentally spills food on
        another camper. The camper who gets spilled on gets angry and says
        something that is offensive to people with disabilities; their
        friends laugh. What could/should you do?
    - requirement: b
      text: |-
        Scenario 2: Your friend confides in you that some students in
        school are making insulting comments about one of their identities,
        and that those same students created a fake social media account to
        impersonate your friend online and post messages. What could/should
        you do?
    - requirement: c
      text: |-
        Scenario 3: A new student in your class was born in another country
        (or has a parent who was born in another country). Your friends
        make rude comments to the student about their speech or clothes and
        tell the student to “go back home where you came from.” What
        could/should you do?
- requirement: 5
  text: |-
    Document and discuss with your counselor:
  children:
    - requirement: a
      text: |-
        Ideas on what you personally can do to create a welcoming
        environment in your Scouting unit.
    - requirement: b
      text: |-
        An experience you had in which you went out of your way to include
        another Scout(s) and what you did to make them feel included and
        welcomed.
    - requirement: c
      text: |-
        Things you can do to help ensure all Scouts in your unit are given
        an opportunity to be heard and included in decision-making and
        planning.
- requirement: 6
  text: |-
    With your parent’s or guardian’s approval, connect with another Scout or
    youth your own age who has an identity that’s different from yours. (This
    means a trait, belief, or characteristic different from you.)
  children:
    - requirement: a
      text: |-
        Share with each other what makes the different aspect of your
        identity meaningful/special to you.
    - requirement: b
      text: |-
        Share with each other either one of the following:
      children:
        - requirement: i
          text: |-
            A time you felt excluded from a group.
          children:
            - detail: true
              markdown: true
              text: |-
                * What was the situation?
                * How did it make you feel?
                * What did you do?
                * Did anyone stand up for you?
                * What did you learn?
                * Would you do anything differently today?
        - requirement: ii
          text: |-
            This imaginary situation:
          children:
            - detail: true
              markdown: true
              # Because of the nested lists, this one isn't converted into
              # workbook entries quite the same as others.
              text: |-
                * You’re attending a new school and don’t know anyone there
                yet. You notice they dress very differently than you do. At
                lunchtime, you decide you’ll try to sit with a group to get
                to know other students.  People at two tables tell you there
                is someone sitting at the currently empty seat at their
                table, so you end up eating by yourself.
                  * How would that make you feel?
                  * What could the students have done?
                  * If that happened at your school, what would you do?
    - requirement: c
      text: |-
        Discuss with your counselor what you learned from the discussion
        with the other Scout or youth.
- requirement: 7
  text: |-
    Identify and interview an individual in your community, school, and/or
    Scouting who has had a significant positive impact in promoting
    diversity, equity, and inclusion. If you feel your community, school, or
    local Scouting group does not have such an individual, then research a
    historical figure who meets these criteria, and discuss that person with
    your counselor.
  children:
    - requirement: a
      text: |-
        Discover what inspired the individual, learn about the challenges
        they faced, and share what you feel attributed to their success.
    - requirement: b
      text: |-
        Discuss with your counselor what you learned and how you can apply
        it in your life.
- requirement: 8
  text: |-
    With the help of your parent or guardian, study an event that had a
    positive outcome on how society viewed a group of people and made them
    feel more welcome. Describe to your counselor the event and what you
    learned.
- requirement: 9
  text: |-
    Document and discuss with your counselor three or more areas in your life
    outside of Scouting where you feel you can actively provide stronger
    leadership in.
  children:
    - requirement: a
      text: |-
        Making others feel included.
    - requirement: b
      text: |-
        Practicing active listening.
    - requirement: c
      text: |-
        Creating an environment where others feel comfortable to share
        their ideas and perspectives.
    - requirement: d
      text: |-
        Helping others feel valued for their input and suggestions.
    - requirement: e
      text: |-
        Standing up for others.
- requirement: 10
  text: |-
    Discuss with your counselor how stereotyping people can be harmful, and
    how stereotypes can lead to prejudice and discrimination. Share ideas you
    have for challenging assumptions and celebrating individuality.
- requirement: 11
  text: |-
    Scouting strives to develop young people to be future leaders in their
    workplaces, schools, and community environments. As you look at your
    current involvement in school, your family, Scouting, your job, and/or
    community, think about how you can have a positive impact in diversity,
    equity, and inclusion.
  children:
    - requirement: a
      text: |-
        Describe your ideas on how you can and will support others with
        different identities to feel included and heard at your school,
        workplace, and/or social settings in your community.
    - requirement: b
      markdown: true
      text: |-
        Explain how including diverse thoughts and opinions from others
        with different identities can:

        * Make your interactions more positive.
        * Help everyone benefit by considering different opinions.
    - requirement: c
      text: |-
        Give three examples of how limiting diverse input can be harmful.
    - requirement: d
      text: |-
        Give three examples of how considering diverse opinions can lead to
        innovation and success.
