- note:
    - inPerson
    - online
  markdown: true
  text: |-
    <b><i><span style="color: red">Note:</span><span style="color: purple">
    This merit badge requires a lot of explanation and discussion in order to
    complete most requirements. This class is structured to offer explanation
    and discussion time for Scouts in a small group setting to offer both
    learning and earning opportunity.</span> <span style="color: red">Scouts
    MUST come to the class with preparation work in order to successfully
    complete these requirements.</span> <span style="color: purple">It will
    be nearly impossible for Scouts who do not have preparation work done to
    successfully partake in the group discussions or provide acceptable
    explanation if they do not have prior knowledge of the requirements and
    answers prior to the class.</span></i></b>
- requirement: 1
  text: |-
    What is the Constitution of the United States? What does the Constitution
    do? What principles does it reflect? Why is it important to have a
    Constitution?
  children:
    - note:
        - inPerson
        - online
      text: |-
        This should be prepared prior to the class. Scouts should have this
        written out to show the counselor that some thought and research
        has gone into this requirement and Scouts should be prepared to
        discuss their findings. Scouts will not automatically be signed off
        on this requirement just for attending as the requirement states
        that they must discuss a number of items and will be required to
        partake in group and/or individual discussion to obtain credit.
- requirement: 2
  text: |-
    List the six purposes for creating the United States Constitution set
    forth in the Preamble to the Constitution.  How do these purposes affect
    your family and community?
  children:
    - note:
        - inPerson
        - online
      text: |-
        Scouts should review this requirement and its components and be
        prepared to discuss.
- requirement: 3
  text: |-
    List the three branches of the United States government. Explain:
  children:
    - note:
        - inPerson
        - online
      text: |-
        This requirement will be covered in the class however Scouts should
        review and be familiar with the components of this requirement.
    - requirement: a
      text: |-
        The function of each branch of government
    - requirement: b
      text: |-
        Why it is important to divide powers among different branches
    - requirement: c
      text: |-
        How each branch "checks" and "balances" the others
    - requirement: d
      text: |-
        How citizens can be involved in each branch of government.
- requirement: 4
  text: |-
    Discuss the importance of:
  children:
    - note:
        - inPerson
        - online
      text: |-
        Scouts should be prepared for discussion of the following
        requirement items. A good portion of the class will be spent on
        these discussions.
    - requirement: a
      text: |-
        Declaration of Independence
    - requirement: b
      text: |-
        The Bill of Rights (the first 10 Amendments to the Constitution)
        and the 14th Amendment
    - requirement: c
      markdown: true
      text: |-
        The traditional United States motto *“E Pluribus Unum.”*
- requirement: 5
  text: |-
    Watch the national evening news for five days in a row or read the main
    stories in a national media organization (e.g., a newspaper or news
    website) for five days in a row.  Discuss the national issues that you
    learned about with your counselor. Choose one issue and explain how it
    affects you, your family, and community.
  children:
    - note:
        - inPerson
        - online
      text: |-
        Scouts will be engaged in discussion on their findings, their
        source of this information, and discuss how these issues they feel
        affect them and their family. It is recommended that Scouts bring
        news clippings, internet printouts, and/or notes for this
        requirement to help support their explanation and have on hand for
        possible reference purposes.
- requirement: 6
  text: |-
    With your counselor’s approval, choose a speech of national historical
    importance. Explain:
  children:
    - requirement: a
      text: |-
        Who the author was
    - requirement: b
      text: |-
        What the historical context was
    - requirement: c
      text: |-
        What difficulties the nation faced that the author wished to
        discuss
    - requirement: d
      text: |-
        What the author said
    - requirement: e
      text: |-
        Why the speech is important to the nation’s history.
    - detail: true
      text: |-
        Choose a sentence or two from the speech that has significant
        meaning to you, and tell your counselor why.
    - note:
        - inPerson
        - online
      text: |-
        This requirement requires a good deal of work and preparation.
        Scouts will have an opportunity to be signed off on this
        requirement, but they must satisfy the detailed requirements. It is
        recommended that Scouts bring their formulated notes and sources to
        aid in their explanation and sharing during the class.
- requirement: 7
  text: |-
    Do TWO of the following:
  children:
    - note:
        - inPerson
        - online
      text: |-
        Scouts will have to perform on their own, either prior to or after
        the class, the visit or tour requirements in this requirement.
        Scouts will have an opportunity to discuss with their counselor
        their visit or tour, however just saying you went there is not
        enough to be signed off on this requirement. It is recommended that
        Scouts come with prepared notes or proof to aid the counselor in
        confirming that this requirement has been met.
    - requirement: a
      text: |-
        Visit a place that is listed as a National Historic Landmark or
        that is on the National Register of Historic Places. Tell your
        counselor what you learned about the landmark or site and what you
        found interesting about it.
    - requirement: b
      text: |-
        Tour your state capitol building or the U.S. Capitol. Tell your
        counselor what you learned about the capitol, its function, and the
        history.
    - requirement: c
      text: |-
        Tour a federal facility. Explain to your counselor what you saw
        there and what you learned about its function in the local
        community and how it serves this nation.
    - requirement: d
      text: |-
        Choose a national monument that interests you. Using books,
        brochures, the internet (with your parent’s permission), and other
        resources, find out more about the monument. Tell your counselor
        what you learned, and explain why the monument is important to this
        country’s citizens.
      children:
        - note:
            - inPerson
            - online
          text: |-
            This class session will have a section for requirement 2D
            discussion. Scouts should come prepared to share their
            findings on a national monument. As with previous
            requirements, it is recommended that Scouts bring notes to
            help support their research and be prepared to discuss their
            findings.
- requirement: 8
  text: |-
    Name your representatives in the United States Congress.  Write a letter
    to your representative in Congress explaining your views on a national
    issue. Show your letter, along with any response you might receive, to
    your counselor.
  children:
    - note:
        - inPerson
        - online
      markdown: true
      text: |-
        Scouts can work on this requirement before or after the class,
        however in order to receive credit for this requirement prior to or
        at the day of the class, Scouts should prepare their letter to
        their choice of official as listed in the requirement and if
        sending a letter by email, carbon copy Scoutmaster Bucky
        (Scoutmasterbucky@yahoo.com) in the email correspondence.

        **OR**

        If sending postal mail letter, have the letter written, envelope
        properly addressed and stamped, but NOT sealed and the counselor
        will verify the letter, seal the envelope and mail the letter for
        completion of this requirement. Discussion of the rest of this
        requirement will happen during the class session.
