- requirement: 1
  markdown: true
  text: |-
      Complete any three of the <a href="../scouts-bsa/">Scouts BSA Nova
      awards</a>. (Note: These may be done at any time after becoming a Scouts
      BSA member.)
- requirement: 2
  markdown: true
  text: |-
      Earn the <a href="../../../merit-badges/scholarship/">Scholarship</a>
      merit badge.
- requirement: 3
  text: |-
      Earn four of the Supernova approved merit badges from the list below.
      (Note: These may be earned at any time after becoming a member of Scouts
      BSA.)
- requirement: 4
  markdown: true
  text: |-
      Complete TWO Supernova activity topics, one each in two different STEM
      areas.

      * <a href="../../../merit-badges/animal-science">Animal Science</a>
      * <a href="../../../merit-badges/archaeology">Archaeology</a>
      * <a href="../../../merit-badges/architecture">Architecture</a>
      * <a href="../../../merit-badges/astronomy">Astronomy</a>
      * <a href="../../../merit-badges/automotive-maintenance">Automotive Maintenance</a>
      * <a href="../../../merit-badges/aviation">Aviation</a>
      * <a href="../../../merit-badges/bird-study">Bird Study</a>
      * <a href="../../../merit-badges/chemistry">Chemistry</a>
      * <a href="../../../merit-badges/composite-materials">Composite Materials</a>
      * <a href="../../../merit-badges/dentistry">Dentistry</a>
      * <a href="../../../merit-badges/digital-technology">Digital Technology</a>
      * <a href="../../../merit-badges/drafting">Drafting</a>
      * <a href="../../../merit-badges/electricity">Electricity</a>
      * <a href="../../../merit-badges/electronic">Electronic</a>
      * <a href="../../../merit-badges/energy">Energy</a>
      * <a href="../../../merit-badges/engineering">Engineering</a>
      * <a href="../../../merit-badges/environmental-science">Environmental Science</a>
      * <a href="../../../merit-badges/farm-mechanics">Farm Mechanics</a>
      * <a href="../../../merit-badges/fish-and-wildlife-management">Fish and Wildlife Management</a>
      * <a href="../../../merit-badges/forestry">Forestry</a>
      * <a href="../../../merit-badges/game-design">Game Design</a>
      * <a href="../../../merit-badges/gardening">Gardening</a>
      * <a href="../../../merit-badges/geocaching">Geocaching</a>
      * <a href="../../../merit-badges/geology">Geology</a>
      * <a href="../../../merit-badges/insect-study">Insect Study</a>
      * <a href="../../../merit-badges/inventing">Inventing</a>
      * <a href="../../../merit-badges/mammal-study">Mammal Study</a>
      * <a href="../../../merit-badges/medicine">Medicine</a>
      * <a href="../../../merit-badges/mining-in-society">Mining in Society</a>
      * <a href="../../../merit-badges/nature">Nature</a>
      * <a href="../../../merit-badges/nuclear-science">Nuclear Science</a>
      * <a href="../../../merit-badges/oceanography">Oceanography</a>
      * <a href="../../../merit-badges/plant-science">Plant Science</a>
      * <a href="../../../merit-badges/programming">Programming</a>
      * <a href="../../../merit-badges/pulp-and-paper">Pulp and Paper</a>
      * <a href="../../../merit-badges/radio">Radio</a>
      * <a href="../../../merit-badges/reptile-and-amphibian-study">Reptile and Amphibian Study</a>
      * <a href="../../../merit-badges/robotics">Robotics</a>
      * <a href="../../../merit-badges/scuba-diving">Scuba Diving</a>
      * <a href="../../../merit-badges/signs-signals-and-codes">Signs, Signals, and Codes</a>
      * <a href="../../../merit-badges/soil-and-water-conservation">Soil and Water Conservation</a>
      * <a href="../../../merit-badges/space-exploration">Space Exploration</a>
      * <a href="../../../merit-badges/surveying">Surveying</a>
      * <a href="../../../merit-badges/sustainability">Sustainability</a>
      * <a href="../../../merit-badges/veterinary-medicine">Veterinary Medicine</a>
      * <a href="../../../merit-badges/weather">Weather</a>
      * <a href="../../../merit-badges/welding">Welding</a>
- requirement: 5
  text: |-
      Participate in a local, state, or national science fair or mathematics
      competition OR in any equally challenging STEM-oriented competition or
      workshop approved by your mentor. An example of this would be an X-Prize
      type competition.
- requirement: 6
  text: |-
      Do ONE of the following:
  children:
      - requirement: A
        text: |-
            With your parent’s permission and your mentor’s approval, spend at
            least one day “shadowing” a local scientist or engineer and report
            on your experience and what you learned about STEM careers to your
            mentor.
      - requirement: B
        text: |-
            Learn about a career that is heavily involved with STEM. Make a
            presentation to your mentor about what you learned.
- requirement: 7
  text: |-
      Working with your mentor, organize and present a Nova award or other
      STEM-related program to a Cub Scout den or pack meeting. Be sure to
      receive approval from the appropriate unit leader and agree on a time and
      place for the presentation. If a Cub Scout den or pack is not available,
      your presentation may be given to another youth group, such as your troop
      or at your place of worship.
- requirement: 8
  text: |-
      Review the scientific method (you may know this as the scientific
      process) and note how scientists establish hypotheses, theories, and
      laws.  Compare how the establishment of “facts” or “rules” using the
      scientific method differs from the establishment of “facts” or “rules” in
      other environments, such as legal, cultural, religious, military,
      mathematical, or social environments.  Then do the following:
  children:
      - requirement: A
        text: |-
            Choose a modern scientific subject with at least two competing
            theories on the subject and learn as much as possible about each
            theory.
      - requirement: B
        text: |-
            Analyze the competing theories, decide which one is most convincing
            to you, and explain why to your mentor.
      - requirement: C
        text: |-
            Make a presentation to your mentor that describes the controversy,
            the competing theories, and your conclusions about how the
            scientific method can or cannot contribute to the resolution of the
            controversy.
- requirement: 9
  text: |-
      Submit your <a href="../award-application.pdf">Supernova Award
      application</a> to the district or council Nova or advancement committee
      for approval.
