- requirement: 1
  text: |-
      Explain what safety is and what it means to be safe. Then prepare a
      notebook to include:
  workbook:
      - lines: 8
  children:
      - requirement: a
        text: |-
            Newspaper, internet (with parent’s or guardian’s permission), or
            other articles, facts, and statistics showing common types and
            causes of injuries in the home and in the workplace, and how these
            injuries could be prevented
        workbook:
            - lines: 8
      - requirement: b
        text: |-
            Newspaper, internet (with parent’s or guardian’s permission), or
            other articles, facts, and statistics showing common types of crime
            and ways to avoid being a crime victim
        workbook:
            - lines: 8
      - requirement: c
        text: |-
            A paragraph or more, written by you, explaining how a serious fire,
            accident, or crime could change your family life
        workbook:
            - lines: 8
      - requirement: d
        text: |-
            A list of safe practices and safety devices currently used by your
            family, such as safety practices used at home, while working, and
            while driving
        workbook:
            - lines: 8
      - note:
            - inPerson
            - online
        text: |-
            Scouts will need to do the work for this requirement prior to the
            class. Scouts should plan on bringing their completed notebook to
            the class to share with the counselor and the rest of the class.
            Only Scout that come to the class with this work completed will
            have the opportunity to be signed off on this requirement and its
            components. Be Prepared.
- requirement: 2
  text: |-
      Do the following:
  children:
      - requirement: a
        text: |-
            Using a safety checklist approved by your counselor, make an
            inspection of your home. Identify any hazards found and explain how
            these can be corrected.
        workbook:
            - task: true
              text: |-
                  Inspected home using an approved safety checklist
            - lines: 8
        children:
            - note:
                  - inPerson
                  - online
              text: |-
                  Scouts may use the inspection checklist in the Safety Merit
                  Badge pamphlet (or make one of their own - which may or may
                  not be acceptable to the counselor) to prepare for sharing
                  their explanation for component 2a during the class. Scouts
                  who have not done the home inspection prior to the class will
                  not be able to have the opportunity of completing this
                  requirement during the class.
      - requirement: b
        text: |-
            Review and develop your family’s fire prevention plan. Review your
            family’s emergency action plan for fire in your home. As you
            develop these plans with family members, share with them facts
            about the common causes of fire in the home, such as smoking,
            cooking, electrical appliances, and candles.
        workbook:
            - lines: 8
        children:
            - note:
                  - inPerson
                  - online
              text: |-
                  In order to assure the highest potential of completing the 2b
                  component of this requirement, Scouts should bring a note
                  signed by a parent or guardian confirming that they have
                  completed this part of requirement 2 prior to the class.
- requirement: 3
  text: |-
      Do the following:
  children:
      - requirement: a
        text: |-
            Discuss with your counselor how you contribute to the safety of
            yourself, your family, and your community.
        workbook:
            - lines: 8
        children:
            - note:
                  - inPerson
                  - online
              text: |-
                  This requirement will be completed in the class, however only
                  Scouts who are able to actively participate in the discussion
                  to the counselor's satisfaction will be signed off on this
                  requirement component.
      - requirement: b
        text: |-
            Show your family members how to protect themselves and your home
            from accidents, fire, burglary, robbery, and assault.
        workbook:
            - task: true
        children:
            - note:
                  - inPerson
                  - online
              text: |-
                  Scouts will need to do this part of the requirement prior to
                  the class. It is strongly recommended that Scouts bring some
                  sort of documentation to validate their completion of this
                  requirement component (a note from your parent or guardian
                  should suffice.
      - requirement: c
        text: |-
            Discuss with your counselor the tips for online safety. Explain the
            steps individuals can take to help prevent identity theft.
        workbook:
            - lines: 8
      - requirement: d
        text: |-
            Discuss with your counselor the three R’s of Youth Protection and
            how to recognize child abuse.
        workbook:
            - lines: 8
        children:
            - note:
                  - inPerson
                  - online
              text: |-
                  Requirement components 3c and 3d will be discussed during the
                  class, however Scouts should review the Safety merit badge
                  pamphlet prior to the class to ensure they are prepared for
                  the discussion and get signed off on these requirement
                  components.
- requirement: 4
  text: |-
      Show your family the exits you would use from different public buildings
      (such as a theater, municipal building, library, supermarket, shopping
      center, or your place of worship) in the event of an emergency. Teach
      your family what to do in the event that they need to take shelter in or
      evacuate a public place.
  workbook:
      - task: true
  children:
      - note:
            - inPerson
            - online
        text: |-
            Scouts will need to have done this requirement prior to the class.
            It is recommended that a note from a parent or guardian clearly
            stating that this requirement has been completed which will help
            the merit badge counselor verify completion of this requirement.
- requirement: 5
  text: |-
      Make an emergency action plan for five family activities outside the home
      (at your place of worship, at a theater, on a picnic, at the beach, and
      while traveling, for example). Each plan should include an analysis of
      possible hazards, proposed action to correct hazards, and reasons for the
      correction you propose in each plan.
  workbook:
      - lines: 8
  children:
      - note:
            - inPerson
            - online
        text: |-
            Time will be allocated during the class to work on this
            requirement, however Scouts wanting to ensure they have the highest
            possibility of completing this requirement during the class should
            prepare ahead of time some examples. Every effort will be made to
            complete this requirement during the class, however those Scouts
            coming unprepared or without any examples, may find it difficult to
            complete.
- requirement: 6
  text: |-
      Plan and complete a safety project approved by your counselor for your
      home, school, place of worship, place of employment, or community.
  workbook:
      - lines: 8
        text: |-
            Describe the project
      - task: true
  children:
      - note:
            - inPerson
            - online
        text: |-
            Scouts may work on this requirement prior to the class and bring
            their work (with supporting documentation and proof of completion)
            for review and consideration by the counselor. Scouts attending the
            class not having done this requirement will not be able to complete
            this requirement in the class. Scouts should understand that the
            only projects that the counselor finds acceptable will be
            considered for sign off on this requirement - review your merit
            badge pamphlet for ideas.
- requirement: 7
  text: |-
      Explain what the National Terrorism Advisory System is and how you would
      respond to each type of alert.
  workbook:
      - lines: 8
  children:
      - note:
            - inPerson
            - online
        text: |-
            Scouts will find that reviewing the Safety Merit Badge pamphlet
            prior to the class will help them easily prepare for the class
            discussion. Since review of the merit badge pamphlet is required
            for any merit badge, Scouts will find this requirement easy to
            prepare for, therefore easy to complete.
- requirement: 8
  text: |-
      Learn about three career opportunities in the field of safety. Pick one
      career and find out the education, training, and experience required for
      this profession. Discuss this choice with your counselor, and explain why
      this profession might interest you.
  workbook:
      - lines: 8
  children:
      - note:
            - inPerson
            - online
        text: |-
            Scouts should review this requirement and its elements and be
            prepared to discuss. It is strongly recommended that Scouts bring
            any notes or supporting documents they may have to help show the
            counselor that they have prepared for discussion.
