- requirement: 1
  markdown: true
  text: |-
      Explain what public health is. Explain how *Escherichia coli* (E. coli), tetanus, AIDS, encephalitis, salmonellosis, Lyme disease, and coronavirus (COVID-19) are contracted. Then, pick any four of the following diseases and explain how each one is contracted and possibly prevented: gonorrhea, West Nile virus, botulism, influenza, syphilis, hepatitis, emphysema, meningitis, herpes, lead poisoning. For all 10 diseases, explain the type or form of the disease (viral, bacterial, environmental, toxin), any possible vectors for transmission, ways to help prevent exposure or the spread of infection, and available treatments.
  workbook:
      - lines: 4
        text: |-
            Escherichia coli (E. coli)
      - lines: 4
        text: |-
            Tetanus
      - lines: 4
        text: |-
            AIDS
      - lines: 4
        text: |-
            Encephalitis
      - lines: 4
        text: |-
            Salmonellosis
      - lines: 4
        text: |-
            Lyme disease
      - lines: 4
        text: |-
            Coronavirus (COVID-19)
      - lines: 4
        text: |-
            First additional disease
      - lines: 4
        text: |-
            Second additional disease
      - lines: 4
        text: |-
            Third additional disease
      - lines: 4
        text: |-
            Fourth additional disease
  children:
      - note:
            - inPerson
            - online
        text: |-
            This requirement and its components will take some time to complete and Scouts should have a majority, if not all, of this prepared and readied prior to the class so that class discussion and explanation can take place to potentially complete this large requirement. Preparation is a must and those Scouts who do not prepare ahead of time for this requirement will find it difficult, if not impossible, to complete this requirement in the class. Be Prepared!
- requirement: 2
  text: |-
      Do the following:
  children:
      - requirement: a
        markdown: true
        text: |-
            Explain the meaning of *immunization*.
        workbook:
            - lines: 4
      - requirement: b
        text: |-
            Name eight diseases against which a young child should be immunized, two diseases against which everyone should be reimmunized periodically, and one immunization everyone should receive annually.
        workbook:
            - lines: 4
      - requirement: c
        text: |-
            Using the list of diseases and conditions in requirement 1, discuss with your counselor those which currently have no immunization available.
        workbook:
            - lines: 4
      - note:
            - inPerson
            - online
        text: |-
            Scouts should review this requirement and its components and be prepared to explain and discuss. It is strongly recommended that Scouts bring any notes or supporting documents they may have to help show the counselor that they have prepared for discussion and explanation of these items.
- requirement: 3
  text: |-
      Discuss the importance of safe drinking water in terms of the spread of disease. Then, demonstrate two ways for making water safe to drink that can be used while at camp. In your demonstration, explain how dishes and utensils should be washed, dried, and kept sanitary at home and in camp.
  workbook:
      - lines: 8
  children:
      - note:
            - inPerson
        text: |-
            A portion of this requirement will be covered in the class with a counselor presentation however Scouts still need to research and take note on many points in fulfilling this requirement. Scouts should be prepared, with notes or other items, to show they are ready to discuss safe drinking water procedures, how disease is spread through water, and all Scouts should come ready and knowledgeable on sanitary procedures for both home and at camp for their dishes and utensils. Scouts need to know this information in order to gain rank advancement so it should already be known, but Scoutmaster Bucky recommends a strong review prior to class might serve all Scouts well.
      - note:
            - online
        text: |-
            Scouts should be prepared, with notes or other items (water safe demo), to show they understand safe drinking water procedures, how disease is spread through water, and all Scouts should come ready and knowledgeable on sanitary procedures for both home and at camp for their dishes and utensils. Scouts need to know this information in order to gain rank advancement so it should already be known, but Scoutmaster Bucky recommends a strong review prior to class might serve all Scouts well.
- requirement: 4
  text: |-
      Explain what a vector is and how insects and rodents can be controlled in your home, in your community, and at camp. Tell why this is important. In your discussion, explain which vectors can be easily controlled by individuals and which ones require long-term, collective action.
  workbook:
      - lines: 8
  children:
      - note:
            - inPerson
            - online
        text: |-
            Scouts should first start by understanding the term vector as it pertains to Public Health. Understanding what a vector is apply this to answering the other parts of this requirement and be prepared to discuss and explain your findings. This will be a very difficult requirement to complete if you have not done some preparation work. It is strongly recommended, but not required, that any notes or other supporting documentation or materials you might have should be brought with you to class to help show the counselor that you have prepared and researched this requirement. While this still does not guarantee your completion (since discussion and explanation are a part of the requirement as well), it will give you a better chance of completing the requirement during the class.
- requirement: 5
  text: |-
      With your parent’s and counselor’s approval, do ONE of the following:
  children:
      - requirement: a
        text: |-
            Visit a municipal wastewater treatment facility or a solid-waste management operation in your community.
        children:
            - requirement: 1
              text: |-
                  Describe how the facility safely treats and disposes of sewage or solid waste.
              workbook:
                  - lines: 8
            - requirement: 2
              text: |-
                  Discuss your visit and what you learned with your counselor.
              workbook:
                  - lines: 8
            - requirement: 3
              text: |-
                  Describe how sewage and solid waste should be disposed of under wilderness camping conditions.
              workbook:
                  - lines: 8
      - requirement: b
        text: |-
            Visit a food service facility, such as a restaurant or school cafeteria.
        children:
            - requirement: 1
              text: |-
                  Observe food preparation, handling, and storage. Learn how the facility keeps food from becoming contaminated.
              workbook:
                  - lines: 8
            - requirement: 2
              text: |-
                  Find out what conditions allow microorganisms to multiply in food, what can be done to help prevent them from growing and spreading, and how to kill them.
              workbook:
                  - lines: 8
            - requirement: 3
              text: |-
                  Discuss the importance of using a thermometer to check food temperatures.
              workbook:
                  - lines: 8
            - requirement: 4
              text: |-
                  Discuss your visit and what you learned with your counselor.
              workbook:
                  - lines: 8
      - note:
            - inPerson
            - online
        text: |-
            Requirement 5 will NOT be covered in the class, HOWEVER, Scouts who can bring documented proof of completing either of the components for this requirement will have an opportunity to share with the counselor their accomplishment. If the work meets the satisfaction of the merit badge counselor, (saying you did it is not enough, you need to bring proof), most counselors will sign off on the requirement. Don't forget to do all elements of the selected requirement component.
- requirement: 6
  text: |-
      Do the following:
  children:
      - requirement: a
        text: |-
            Describe the health dangers from air, water, and noise pollution.
        workbook:
            - lines: 8
      - requirement: b
        text: |-
            Describe health dangers from tobacco use and alcohol and drug abuse.
        workbook:
            - lines: 8
      - requirement: c
        text: |-
            Describe the health dangers from abusing illegal and prescription drugs.
        workbook:
            - lines: 8
      - note:
            - inPerson
            - online
        text: |-
            Coupled with what Scouts already know on these subjects and a review of the merit badge pamphlet section on this requirement, Scouts should easily complete this requirement within the class. Please note that a review of the merit badge pamphlet is stated, it will be quite evident to the counselor those Scouts who have not read the merit badge pamphlet and/or prepared for this requirement ahead of time for the class. As such if preparation is not completed, please do not be upset when completion of the requirement is not signed off. Be Prepared.
- requirement: 7
  text: |-
      With your parent’s and counselor’s approval, do ONE of the following:
  children:
      - requirement: a
        text: |-
            Visit your city, county, or state public health agency.
        workbook:
            - lines: 8
      - requirement: b
        text: |-
            Familiarize yourself with your city, county, or state health agency’s website.
        workbook:
            - lines: 8
      - detail: true
        text: |-
            After completing either 7a or 7b, do the following:
      - requirement: 1
        text: |-
            Compare the four leading causes of mortality (death) in your community for any of the past five years with the four leading causes of disease in your community. Explain how the public health agency you visited is trying to reduce the mortality and morbidity rates of these leading causes of illness and death.
        workbook:
            - lines: 8
      - requirement: 2
        text: |-
            Explain the role of your health agency as it relates to the outbreak of diseases.
        workbook:
            - lines: 8
      - requirement: 3
        text: |-
            Discuss the kinds of public assistance the agency is able to provide in case of disasters such as floods, storms, tornadoes, earthquakes, and other acts of destruction. Your discussion can include the cleanup necessary after the disaster.
        workbook:
            - lines: 8
      - note:
            - inPerson
            - online
        text: |-
            Scouts should be as prepared as possible with their work for their selected components of this requirement. Scouts should bring any notes or supporting documentation to assist them with their discussion points for this requirement in the class. Some assistance will be given in the class on this requirement, but those not coming prepared will find it difficult to complete this requirement in the class alone.
- requirement: 8
  text: |-
      Pick a profession in the public health sector that interests you. Find out the education, training, and experience required to work in this profession. Discuss what you learn with your counselor.
  workbook:
      - lines: 8
  children:
      - note:
            - inPerson
            - online
        text: |-
            Scouts should review this requirement and its components and be prepared to discuss. It is strongly recommended that Scouts bring any notes or supporting documents they may have to help show the counselor that they have prepared for discussion of these items.
