- requirement: 1
  text: |-
      Explain what radio is. Then discuss the following:
  children:
      - requirement: a
        text: |-
            The differences between broadcast radio and hobby radio
        workbook:
            - lines: 8
      - requirement: b
        text: |-
            The differences between broadcasting and two-way communications
        workbook:
            - lines: 8
      - requirement: c
        text: |-
            Radio station call signs and how they are used in broadcast radio
            and amateur radio
        workbook:
            - lines: 8
      - requirement: d
        text: |-
            The phonetic alphabet and how it is used to communicate clearly
        workbook:
            - lines: 8
- requirement: 2
  text: |-
      Do the following:
  children:
      - requirement: a
        text: |-
            Sketch a diagram showing how radio waves travel locally and around
            the world.
        workbook:
            - area: 8
      - requirement: b
        text: |-
            Explain how the radio stations WWV and WWVH can be used to help
            determine what you can expect to hear when you listen to a
            shortwave radio.
        workbook:
            - lines: 8
      - requirement: c
        text: |-
            Explain the difference between a distant (DX) and a local station.
        workbook:
            - lines: 8
      - requirement: d
        text: |-
            Discuss what the Federal Communications Commission (FCC) does and
            how it is different from the International Telecommunication Union.
        workbook:
            - lines: 8
- requirement: 3
  text: |-
      Do the following:
  workbook:
      - header: true
        markdown: true
        text: |-
            a. Draw a chart of the electromagnetic spectrum covering 300 kilohertz (kHz) to 3,000 megahertz (MHz).

            b. Label the MF, HF, VHF, UHF, and microwave portions of the spectrum on your diagram.

            c. Locate on your chart at least eight radio services, such as AM and FM commercial broadcast, citizens band (CB), television, amateur radio (at least four amateur radio bands), and public service (police and fire).
      - area: 16
  children:
      - requirement: a
        text: |-
            Draw a chart of the electromagnetic spectrum covering 300 kilohertz
            (kHz) to 3,000 megahertz (MHz).
        workbookHide: true
      - requirement: b
        text: |-
            Label the MF, HF, VHF, UHF, and microwave portions of the spectrum
            on your diagram.
        workbookHide: true
      - requirement: c
        text: |-
            Locate on your chart at least eight radio services, such as AM and
            FM commercial broadcast, citizens band (CB), television, amateur
            radio (at least four amateur radio bands), and public service
            (police and fire).
        workbookHide: true
- requirement: 4
  text: |-
      Explain how radio waves carry information. Include in your explanation:
      transceiver, transmitter, receiver, amplifier, and antenna.
  workbook:
      - lines: 8
- requirement: 5
  text: |-
      Do the following:
  children:
      - requirement: a
        text: |-
            Explain the differences between a block diagram and a schematic
            diagram.
        workbook:
            - lines: 8
      - requirement: b
        text: |-
            Draw a block diagram for a radio station that includes a
            transceiver, amplifier, microphone, antenna, and feed line.
        workbook:
            - area: 8
      - requirement: c
        text: |-
            Discuss how information is sent when using amplitude modulation
            (AM), frequency modulation (FM), continuous wave (CW) Morse Code
            transmission, single sideband (SSB) transmission, and digital
            transmission.
        workbook:
            - lines: 8
      - requirement: d
        text: |-
            Explain how NOAA Weather Radio (NWR) can alert you to danger.
        workbook:
            - lines: 8
      - requirement: e
        text: |-
            Explain how cellular telephones work. Identify their benefits and
            limitations in an emergency.
        workbook:
            - lines: 8
- requirement: 6
  text: |-
      Explain the safety precautions for working with radio gear, including the
      concept of grounding for direct current circuits, power outlets, and
      antenna systems.
  workbook:
      - lines: 8
- requirement: 7
  text: |-
      Visit a radio installation (an amateur radio station, broadcast station,
      or public service communications center, for example) approved in advance
      by your counselor. Discuss what types of equipment you saw in use, how it
      was used, what types of licenses are required to operate and maintain the
      equipment, and the purpose of the station.
  workbook:
      - lines: 8
- requirement: 8
  text: |-
      Find out about three career opportunities in radio. Pick one and find out
      the education, training, and experience required for this profession.
      Discuss this with your counselor, and explain why this profession might
      interest you.
  workbook:
      - lines: 8
- requirement: 9
  text: |-
      Do ONE of the following (a OR b OR c OR d):
  children:
      - requirement: a
        markdown: true
        text: |-
            **Amateur Radio**
        children:
            - requirement: 1
              text: |-
                  Tell why the FCC has an amateur radio service. Describe
                  activities that amateur radio operators can do on the air,
                  once they have earned an amateur radio license.
              workbook:
                  - lines: 8
            - requirement: 2
              text: |-
                  Explain differences between the Technician, General, and
                  Extra Class license requirements and privileges. Explain who
                  administers amateur radio exams.
              workbook:
                  - lines: 8
            - requirement: 3
              text: |-
                  Explain at least five Q signals or amateur radio terms.
              workbook:
                  - lines: 8
            - requirement: 4
              text: |-
                  Explain how you would make an emergency call on voice or
                  Morse code.
              workbook:
                  - lines: 8
            - requirement: 5
              text: |-
                  Explain the differences between handheld transceivers and
                  home “base” transceivers. Explain the uses of mobile amateur
                  radio transceivers and amateur radio repeaters.
              workbook:
                  - lines: 8
            - requirement: 6
              text: |-
                  Using proper call signs, Q signals, and abbreviations, carry
                  on a 10-minute real or simulated amateur radio contact using
                  voice, Morse code, or digital mode. (Licensed amateur radio
                  operators may substitute five QSL cards as evidence of
                  contacts with five amateur radio operators.) Properly log the
                  real or simulated ham radio contact, and record the signal
                  report.
              workbook:
                  - lines: 8
      - requirement: b
        markdown: true
        text: |-
            **Radio Broadcasting**
        children:
            - requirement: 1
              text: |-
                  Discuss with your counselor FCC broadcast regulations.
                  Include power levels, frequencies, and the regulations for
                  low-power stations.
              workbook:
                  - lines: 8
            - requirement: 2
              text: |-
                  Prepare a program schedule for radio station “KBSA” of
                  exactly one-half hour, including music, news, commercials,
                  and proper station identification. Record your program on
                  audiotape or in a digital audio format, using proper
                  techniques.
              workbook:
                  - lines: 8
            - requirement: 3
              text: |-
                  Listen to and properly log 15 broadcast stations. Determine
                  the program format and target audience for five of these
                  stations.
              workbook:
                  - lines: 8
            - requirement: 4
              text: |-
                  Explain to your counselor at least eight terms used in
                  commercial broadcasting, such as segue, cut, fade,
                  continuity, remote, Emergency Alert System, network, cue,
                  dead air, PSA, and playlist.
              workbook:
                  - lines: 8
            - requirement: 5
              text: |-
                  Discuss with your counselor alternative radio platforms such
                  as internet streaming, satellite radio, and podcasts.
              workbook:
                  - lines: 8
      - requirement: c
        markdown: true
        text: |-
            **Shortwave and Medium-Wave Listening**
        children:
            - requirement: 1
              text: |-
                  Listen across several shortwave bands for four one-hour
                  periods—at least one period during daylight hours and at
                  least one period at night. Log the stations properly and
                  locate them geographically on a map, globe, or web-based
                  mapping service.
              workbook:
                  - lines: 8
            - requirement: 2
              text: |-
                  Listen to several medium-wave stations for two one-hour
                  periods, one period during daylight hours and one period at
                  night. Log the stations properly and locate them on a map,
                  globe, or web-based mapping service.
              workbook:
                  - lines: 8
            - requirement: 3
              text: |-
                  Compare your daytime and nighttime shortwave logs; note the
                  frequencies on which your selected stations were loudest
                  during each session. Explain differences in the signal
                  strength from one period to the next.
              workbook:
                  - lines: 8
            - requirement: 4
              text: |-
                  Compare your medium-wave broadcast station logs and explain
                  why some distant stations are heard at your location only
                  during the night.
              workbook:
                  - lines: 8
            - requirement: 5
              text: |-
                  Demonstrate listening to a radio broadcast using a
                  smartphone/cell phone. Include international broadcasts in
                  your demonstration.
              workbook:
                  - lines: 8
      - requirement: d
        markdown: true
        text: |-
            **Amateur Radio Direction Finding**
        children:
            - requirement: 1
              text: |-
                  Describe amateur radio direction finding and explain why
                  direction finding is important as both an activity and in
                  competition.
              workbook:
                  - lines: 8
            - requirement: 2
              text: |-
                  Describe what frequencies and equipment are used for ARDF or
                  fox hunting.
              workbook:
                  - lines: 8
            - requirement: 3
              text: |-
                  Build a simple directional antenna for either of the two
                  frequencies used in ARDF.
              workbook:
                  - lines: 8
            - requirement: 4
              text: |-
                  Participate in a simple fox hunt using your antenna along
                  with a provided receiver.
              workbook:
                  - lines: 8
            - requirement: 5
              text: |-
                  Show, on a map, how you located the “fox” using your
                  receiver.
              workbook:
                  - lines: 8
