- requirement: 1
  markdown: true
  text: |-
    Choose A *or* B *or* C and complete ALL of the requirements.
  children:
    - requirement: A
      text: |-
        Watch not less than one hour total of shows or documentaries that
        discuss fluid dynamics or a show related to fluid dynamics. Then do the
        following:
      children:
        - requirement: 1
          text: |-
            Make a list of at least two questions or ideas from the show(s) you
            watched.
        - requirement: 2
          text: |-
            Discuss two of the questions with or ideas with your counselor.
        - detail: true
          markdown: true
          text: |-
            Some examples of shows to watch include - but are not limited to -
            “The STEM of Indoor Skydiving” (https://youtu.be/V5jJ5FaX1ZU ),
            Documentaries produced by PBS (such as “NOVA”), the Discovery
            Channel, Science Channel, National Geographic Channel, and the
            History Channel. Lectures or presentations focused on science,
            technology, engineering, or math (such as TED Talks www.ted.com);
            some search terms you might think of using could include “fluid
            dynamics for kids” or “the science of skydiving for kids.” You may
            watch online productions with your Counselor’s approval and under
            your parent’s supervision. You may choose to watch a live
            performance or movie at a planetarium or science museum instead of
            watching a media production.
    - requirement: B
      text: |-
        Read not less than one hour total about a topic related to fluid
        dynamics. Then do the following:
      children:
        - requirement: 1
          text: |-
            Make a list of at least two questions or ideas from the article(s)
            you read.
        - requirement: 2
          text: |-
            Discuss two of the questions with or ideas with your counselor.
        - detail: true
          text: |-
            Examples of magazines include—but are not limited to—Odyssey,
            Popular Mechanics, Popular Science, Science Illustrated, Discover,
            Air & Space, Popular Astronomy, Astronomy, Science News, Sky &
            Telescope, Robot, Servo, Nuts and Volts, and Scientific American.
    - requirement: C
      text: |-
        Do a combination of reading and watching (not less than one hour
        total). Then do the following:
      children:
        - requirement: 1
          text: |-
            Make a list of at least two questions or ideas from each article or
            show.
        - requirement: 2
          text: |-
            Discuss two of the questions with or ideas with your counselor.
- requirement: 2
  text: |-
    Complete Option A or B. Discuss with your counselor what kind of science,
    technology, engineering, and math was used in the option.
  children:
    - detail: true
      text: |-
        Option A: Do all the following. (a) Design, (b) Construct. (c) Race
        Vessel in Rain Gutter Regatta.
    - detail: true
      text: |-
        Option B: Do all the following. (a) Design, (b) Construct. (c) Race
        Vehicle in Pinewood Derby.
- requirement: 3
  markdown: true
  text: |-
    Complete two activities from A *or* B *or* C *or* D. Complete all of the
    items under each activity.
  children:
    - requirement: A
      text: |-
        Conduct a Terminal Velocity Investigation.
      children:
        - requirement: 1
          text: |-
            With your counselor, fill an empty tennis ball tube, or other clear
            plastic tube at least 12” tall, with clear corn syrup.
        - requirement: 2
          text: |-
            Drop two round objects with the same diameter but different masses
            into the syrup (example: a steel ball and a glass marble).
        - requirement: 3
          text: |-
            Note when the two balls reach terminal velocity (it should happen
            quickly). Did both objects have the same terminal velocity? Try the
            experiment again to see if it’s repeatable.
        - requirement: 4
          text: |-
            Discuss your investigation and findings with your counselor.
    - requirement: B
      text: |-
        Calculate your terminal velocity on different planets.
      children:
        - requirement: 1
          markdown: true
          text: |-
            Download the worksheet at
            https://www.iflyworld.com/plan-an-event/education/highschool/ or
            use a [similar worksheet](worksheet.pdf) such as the “Student
            Terminal Velocity Worksheet” at
            https://www.grc.nasa.gov/www/k-12/airplane/termv.html. Calculate
            the terminal velocity of a 100-pound backpack on the planet earth.
        - requirement: 2
          text: |-
            Calculate your terminal velocity on Mars (hint: you will need to
            look up the values of gravity and atmospheric density on Mars).
            Compare the two values.
        - requirement: 3
          text: |-
            Discuss the differences with your counselor. How would the
            conditions on Mars affect the engineering design of a Martian
            landing craft?
    - requirement: C
      text: |-
        Deliver rescue supplies to a community whose roads and bridges have
        been compromised by a natural disaster.
      children:
        - requirement: 1
          text: |-
            Use lightweight recycled materials or snap-together building blocks
            to construct a platform (or some shape with weight and mass) to
            carry the supplies. Once you build the "platform", add "supplies"
            that represent food, water, medicine, etc. and a way to attach a
            parachute to deliver it to the community from a plane flying
            overhead.
        - requirement: 2
          text: |-
            Use common household materials, such as trash bags, plastic
            tablecloth, string, paperclips, rubber bands, etc. to design a
            parachute that will safely deliver your "supplies" to the
            "community square" (when dropped from the top of a tall structure,
            such as a playground playscape). The platform must land upright and
            intact, so the supplies are not damaged.
        - requirement: 3
          text: |-
            Design your parachute first on paper, then create a prototype and
            test it.
        - requirement: 4
          text: |-
            Record how long it took to land and the condition of the delivered
            supplies.
        - requirement: 5
          text: |-
            What could you do to slow the descent even further? Modify your
            design and test it out again. Record the results then modify and
            test again.
        - requirement: 6
          text: |-
            Conduct a final test (at least three tests total) and record your
            best (slowest) time.
        - requirement: 7
          text: |-
            Show your parachute to your Counselor and explain how you designed
            and modified it. Talk about how the actual conditions of a rescue
            mission (flooding, few flat surfaces, downed trees, live wires,
            high winds, single chance to deliver) would affect a real-world
            drop of rescue supplies.
    - requirement: D
      text: |-
        Test out Different Airfoils
      children:
        - requirement: 1
          text: |-
            Construct simple airfoil shapes using sheets of plain paper secured
            with tape.
        - requirement: 2
          text: |-
            Make a "testing apparatus" that allows the airfoil to move freely
            in the vertical direction using drinking straws and skewers.
        - requirement: 3
          text: |-
            Using a fan or hair dryer, direct a flow of fast-moving air across
            the airfoil and observe how high it lifts off from the testing
            apparatus. Use a ruler marked with centimeters to measure results.
            Repeat changing the test parameters, e.g., how fast the air flows,
            the direction of the air flow, etc.
        - requirement: 4
          text: |-
            Research the Bernoulli Effect and have a discussion about how this
            phenomenon applies to your observations of the airfoils.
        - requirement: 5
          text: |-
            Discuss the results with your counselor.
- requirement: 4
  text: |-
    Complete one of the following A or B or C.
  children:
    - requirement: A
      text: |-
        Visit an iFLY Indoor Skydiving wind tunnel facility or other BSA
        approved indoor skydiving wind tunnel and participate in a STEM
        Education program. Discuss the STEM concepts related to the tunnel with
        your counselor.
    - requirement: B
      text: |-
        Visit an observatory, research facility, or a museum that highlights
        flight, aviation, or space. During your visit, talk to a docent or
        staff member about flight and fluid dynamics concepts covered at the
        site. Discuss what you learned with your counselor.
    - requirement: C
      markdown: true
      text: |-
        Take a real or online tour of a wind tunnel facility. A real tour may
        be obtained by contacting a local university that offers a degree in
        aerospace engineering or similar field. Virtual tours could include,
        but are not limited to, NASA wind tunnel facility tours at
        https://www.youtube.com/watch?v=bpRc9I8LMXo . Discuss with your
        counselor the science and engineering concepts associated with the
        facility, e.g., what are the parts of a wind tunnel, what a wind tunnel
        is used for, what are the advantages of testing with a wind tunnel, how
        precise are they, etc.
- requirement: 5
  text: |-
    Discuss with your counselor how fluid dynamics is present in your everyday
    life and what you learned by working on this nova.
