- detail: true
  text: |-
    Choose THREE groups that have different racial, cultural, national, or
    ethnic backgrounds, one of which comes from your own background. Use
    these groups to meet requirements 1, 2, and 3.
- requirement: 1
  text: |-
    Do TWO of the following, choosing a different group for each:
  children:
    - requirement: a
      text: |-
        Go to a festival, celebration, or other event identified with one
        of the groups. Report on what you see and learn.
    - requirement: b
      text: |-
        Go to a place of worship, school, or other institution identified
        with one of the groups. Report on what you see and learn.
    - requirement: c
      text: |-
        Talk with a person from one of the groups about the heritage and
        traditions of the group. Report on what you learn.
    - requirement: d
      text: |-
        Learn a song, dance, poem, or story that is traditional to one
        group, and teach it to a group of your friends.
    - requirement: e
      text: |-
        Go to a library or museum to see a program or exhibit featuring one
        group’s traditions. Report on what you see and learn.
    - note:
        - inPerson
        - online
      text: |-
        Scouts will find that all of these options in this requirement
        require some sort of reporting or explanation after completing the
        action specified. Scouts will have an opportunity to share their
        findings and experiences with the Counselor and other Scouts. Any
        supporting material (ticket stubs, photos, souvenirs, pamphlets,
        etc.) from the event, visit, locale, etc that Scouts can bring to
        show and share as a part of their reporting would be of great
        benefit. While Scouts are not required to "report" in writing, it
        is strongly suggested to at least use something like the
        Scoutmaster Bucky American Cultures Merit Badge Workbook to help
        manage and organize notes while completing his requirement.
- requirement: 2
  text: |-
    Imagine that one of the groups had always lived alone in a city or
    country to which no other groups ever came. Tell what you think the city
    or country might be like today. Now tell what you think it might be like
    if the three groups you chose lived there at the same time.
  children:
    - note:
        - inPerson
        - online
      text: |-
        Scouts will have an opportunity to share their findings during the
        class and should come to the class having already put some thought
        into this requirement.
- requirement: 3
  text: |-
    Tell about some differences between the religious and social customs of
    the three groups. Tell about some ideas or ways of doing things that are
    similar in the three groups.
  children:
    - note:
        - inPerson
        - online
      text: |-
        It is recommended that Scouts consider utilizing a workbook or
        notebook to make notes for reference during the class discussion on
        this requirement. This process will make it easier for Scouts to
        actively participate in class discussion and ensure completion of
        this requirement.
- requirement: 4
  text: |-
    Tell about a contribution made to our country by three different people,
    each from a different racial, ethnic, or religious background.
  children:
    - note:
        - inPerson
        - online
      text: |-
        Scouts will find preparation prior to the class to be very helpful
        when discussing this requirement during the class.  Be Prepared!
- requirement: 5
  text: |-
    Give a talk to your Scout unit or class at school on how people from
    different groups have gotten along together.  Lead a discussion on what
    can be done to help various groups understand one another better.
  children:
    - note:
        - inPerson
        - online
      markdown: true
      text: |-
        While not required, it is strongly recommended that prior to making
        any presentation, you should review the contents of your
        presentation with your Counselor. Scouts wishing to make their
        presentation during the class will have the opportunity to do so,
        however it should be noted that there will be NO time allotted for
        preparing for this during the class. Scouts choosing this option
        will need to come fully prepared and ready to present. Remember it
        is at the discretion of the Counselor as to whether the requirement
        has been satisfactorily completed. All Scouts will be given an
        opportunity to lead the discussion in order to complete this
        requirement.

        If this requirement was completed prior to the class, you will need
        to provide proof of completion (i.e. a note from your Scout Leader
        or Teacher).  Just saying so is not enough to guarantee completion
        of this requirement.  Bring proof, or be prepared to present.
