- requirement: 1
  text: |-
      Discuss with your merit badge counselor the history of the game of chess.
      Explain why it is considered a game of planning and strategy.
  workbook:
      - lines: 8
        text: |-
            History of the game of chess
      - lines: 8
        text: |-
            Why it is considered a game of planning and strategy
  children:
      - note:
            - inPerson
            - online
        text: |-
            Scouts should consider having this written out to show the
            counselor that some thought and research has gone into this
            requirement and Scouts should be prepared to discuss their
            findings. Scouts will not automatically be signed off on this
            requirement just for attending as the requirement states that they
            must discuss and explain their findings.
- requirement: 2
  text: |-
      Discuss with your merit badge counselor the following:
  children:
      - requirement: a
        text: |-
            The benefits of playing chess, including developing critical
            thinking skills, concentration skills, and decision-making skills,
            and how these skills can help you in other areas of your life
        workbook:
            - lines: 8
              text: |-
                  Benefits of playing chess
            - lines: 8
              text: |-
                  How these skills can help you in other areas of your life
      - requirement: b
        text: |-
            Sportsmanship and chess etiquette
        workbook:
            - lines: 8
      - note:
            - inPerson
            - online
        text: |-
            Scouts will engage in discussion on their findings during the
            class. Scouts should review the merit badge pamphlet book to have a
            better understanding of what this requirement is looking for them
            to understand. The counselor will facilitate discussion on this
            requirement during the class. It should be noted that only Scouts
            that actively, positively, and successfully participate in the
            discussion will be signed off on this requirement. Preparation is a
            must.
- requirement: 3
  markdown: true
  text: |-
      Demonstrate to your counselor that you know each of the following. Then,
      using Scouting’s Teaching EDGE`*`, teach someone (preferably another Scout)
      who does not know how to play chess:

      `*` You may learn about Scouting’s Teaching EDGE from your unit leader,
      another Scout, or by attending training.
  workbook:
      - task: true
        text: |-
            Using Scouting Teaching EDGE, teach someone who does not know how
            to play chess
  children:
      - requirement: a
        text: |-
            The name of each chess piece
        workbook:
            - task: true
      - requirement: b
        text: |-
            How to set up a chessboard
        workbook:
            - task: true
      - requirement: c
        text: |-
            How each chess piece moves, including castling and en passant
            captures
        workbook:
            - task: true
      - note:
            - inPerson
            - online
        text: |-
            Scouts should be familiar with and be able to identify all the
            chess pieces and their proper movement and starting points. The
            Chess Merit Badge Pamphlet as well as the Scoutmaster Bucky Chess
            Merit Badge Workbook are must use references for preparing for
            these parts of the requirement. Component 3C can easily be reviewed
            through the use of the Merit Badge Pamphlet and Scouts should have
            a basic understanding of these terms and skill. The counselor will
            work with Scouts based on preparedness to execute the EDGE method
            part of this requirement during the class.
- requirement: 4
  text: |-
      Do the following:
  children:
      - requirement: a
        text: |-
            Demonstrate scorekeeping using the algebraic system of chess
            notation.
        workbook:
            - task: true
      - requirement: b
        text: |-
            Discuss the differences between the opening, the middle game, and
            the endgame.
        workbook:
            - task: true
      - requirement: c
        text: |-
            Explain four opening principles.
        workbook:
            - task: true
      - requirement: d
        text: |-
            Explain the four rules for castling.
        workbook:
            - task: true
      - requirement: e
        text: |-
            On a chessboard, demonstrate a “scholar’s mate” and a “fool’s
            mate.”
        workbook:
            - task: true
      - requirement: f
        text: |-
            Demonstrate on a chessboard four ways a chess game can end in a
            draw.
        workbook:
            - task: true
      - note:
            - inPerson
            - online
        text: |-
            While this requirement will be reviewed in the class, Scouts will
            need to have reviewed the Chess Merit Badge Pamphlet for each of
            these components and at least have a basic understanding of these
            terms, skills, and methods as they relate to the game of Chess. It
            is highly recommended to utilize the Scoutmaster Bucky Chess Merit
            Badge Workbook to make notes when looking each of these components
            up and recording your findings for easy reference during the class.
- requirement: 5
  text: |-
      Do the following:
  children:
      - requirement: a
        text: |-
            Explain four of the following elements of chess strategy:
            exploiting weaknesses, force, king safety, pawn structure, space,
            tempo, time.
        workbook:
            - lines: 8
            - lines: 8
            - lines: 8
            - lines: 8
      - requirement: b
        text: |-
            Explain any five of these chess tactics: clearance sacrifice,
            decoy, discovered attack, double attack, fork, interposing,
            overloading, overprotecting, pin, remove the defender, skewer,
            zwischenzug.
        workbook:
            - lines: 8
            - lines: 8
            - lines: 8
            - lines: 8
            - lines: 8
        children:
            - note:
                  - inPerson
                  - online
              text: |-
                  For requirement components 5a and 5b, Scouts should prepare
                  in the same way as they are recommended to prepare in
                  Requirement 4.
      - requirement: c
        markdown: true
        text: |-
            Set up a chessboard with the white king on *`e1`*, the white rooks
            on *`a1`* and *`h1`*, and the black king on *`e5`*.  With White to
            move first, demonstrate how to force checkmate on the black king.
        workbook:
            - task: true
        children:
            - note:
                  - inPerson
                  - online
              text: |-
                  For Requirement 5c, Scouts will be asked to set up their
                  chess board and show the counselor their solution to the
                  scenario. While time will be allotted during the class for
                  this, it is recommended to make an attempt to review this
                  component and apply some thought to a solution prior to the
                  class. Beginner Chess players may find this requirement
                  difficult depending on their level of understanding. This is
                  a more advanced, beginner-level concept and practice in
                  Chess. While every attempt will be made to assist Scouts in
                  understanding and executing this component successfully,
                  please note that like setting up a tent or building a
                  campfire, there is some skill and reasoning that is involved
                  and required to complete.
      - requirement: d
        text: |-
            Set up and solve five direct-mate problems provided by your merit
            badge counselor.
        workbook:
            - split:
                  - task: true
                    text: |-
                        Solved first problem
                  - task: true
                    text: |-
                        Solved second problem
                  - task: true
                    text: |-
                        Solved third problem
            - split:
                  - task: true
                    text: |-
                        Solved fourth problem
                  - task: true
                    text: |-
                        Solved fifth problem
        children:
            - note:
                  - inPerson
                  - online
              text: |-
                  Requirement 5d, will be done in the class.
- requirement: 6
  text: |-
      Do ONE of the following:
  children:
      - requirement: a
        text: |-
            Play at least three games of chess with other Scouts and/or your
            merit badge counselor. Replay the games from your score sheets and
            discuss with your counselor how you might have played each game
            differently.
        workbook:
            - split:
                  - task: true
                    text: |-
                        Played first game
                  - task: true
                    text: |-
                        Replayed first game
            - split:
                  - task: true
                    text: |-
                        Played second game
                  - task: true
                    text: |-
                        Replayed second game
            - split:
                  - task: true
                    text: |-
                        Played third game
                  - task: true
                    text: |-
                        Replayed third game
      - requirement: b
        text: |-
            Play in a scholastic (youth) chess tournament and use your score
            sheets from that tournament to replay your games with your merit
            badge counselor. Discuss with your counselor how you might have
            played each game differently.
        workbook:
            - split:
                  - task: true
                    text: |-
                        Played in a chess tournament
                  - task: true
                    text: |-
                        Replayed games from chess tournament
      - requirement: c
        text: |-
            Organize and run a chess tournament with at least four players,
            plus you. Have each competitor play at least two games.
        workbook:
            - task: true
      - note:
            - inPerson
            - online
        text: |-
            Requirement 6 will be completed in the class. The counselor will
            either be doing Requirement 6a or 6c in the class.
      - note:
            - inPerson
            - online
        text: |-
            Requirement 6 sill NOT be completed a part of the online class,
            however Scouts able to provide proof of completion, completion to
            the satisfaction of the merit badge counselor / instructor, will be
            considered for sign off on this requirement. Be Prepared!
