- requirement: 1
  text: |-
    Discuss with your merit badge counselor the history of the game of chess.
    Explain why it is considered a game of planning and strategy.
- requirement: 2
  text: |-
    Discuss with your merit badge counselor the following:
  children:
    - requirement: a
      text: |-
        The benefits of playing chess, including developing critical
        thinking skills, concentration skills, and decision-making skills,
        and how these skills can help you in other areas of your life
    - requirement: b
      text: |-
        Sportsmanship and chess etiquette
- requirement: 3
  markdown: true
  text: |-
    Demonstrate to your counselor that you know each of the following. Then,
    using Scouting’s Teaching EDGE`*`, teach someone (preferably another Scout)
    who does not know how to play chess:

    `*` You may learn about Scouting’s Teaching EDGE from your unit leader,
    another Scout, or by attending training.
  children:
    - requirement: a
      text: |-
        The name of each chess piece
    - requirement: b
      text: |-
        How to set up a chessboard
    - requirement: c
      text: |-
        How each chess piece moves, including castling and en passant
        captures
- requirement: 4
  text: |-
    Do the following:
  children:
    - requirement: a
      text: |-
        Demonstrate scorekeeping using the algebraic system of chess
        notation.
    - requirement: b
      text: |-
        Discuss the differences between the opening, the middle game, and
        the endgame.
    - requirement: c
      text: |-
        Explain four opening principles.
    - requirement: d
      text: |-
        Explain the four rules for castling.
    - requirement: e
      text: |-
        On a chessboard, demonstrate a “scholar’s mate” and a “fool’s
        mate.”
    - requirement: f
      text: |-
        Demonstrate on a chessboard four ways a chess game can end in a
        draw.
- requirement: 5
  text: |-
    Do the following:
  children:
    - requirement: a
      text: |-
        Explain four of the following elements of chess strategy:
        exploiting weaknesses, force, king safety, pawn structure, space,
        tempo, time.
    - requirement: b
      text: |-
        Explain any five of these chess tactics: clearance sacrifice,
        decoy, discovered attack, double attack, fork, interposing,
        overloading, overprotecting, pin, remove the defender, skewer,
        zwischenzug.
    - requirement: c
      markdown: true
      text: |-
        Set up a chessboard with the white king on *`e1`*, the white rooks
        on *`a1`* and *`h1`*, and the black king on *`e5`*.  With White to
        move first, demonstrate how to force checkmate on the black king.
    - requirement: d
      text: |-
        Set up and solve five direct-mate problems provided by your merit
        badge counselor.
- requirement: 6
  text: |-
    Do ONE of the following:
  children:
    - requirement: a
      text: |-
        Play at least three games of chess with other Scouts and/or your
        merit badge counselor. Replay the games from your score sheets and
        discuss with your counselor how you might have played each game
        differently.
    - requirement: b
      text: |-
        Play in a scholastic (youth) chess tournament and use your score
        sheets from that tournament to replay your games with your merit
        badge counselor. Discuss with your counselor how you might have
        played each game differently.
    - requirement: c
      text: |-
        Organize and run a chess tournament with at least four players,
        plus you. Have each competitor play at least two games.
