- requirement: 1
  text: |-
    Define “law.” Tell some of its sources. Describe functions it serves.
- requirement: 2
  text: |-
    Discuss TWO of the following:
  children:
    - requirement: a
      text: |-
        Justinian’s Code, the Code of Hammurabi, and the Magna Carta
    - requirement: b
      text: |-
        The development of the jury system
    - requirement: c
      text: |-
        Two famous trials in history
- requirement: 3
  text: |-
    Tell what civil law is; tell what criminal law is. Tell the main
    differences between them. Give examples of each.
- requirement: 4
  text: |-
    Ask five people (not more than one from your immediate family) about the
    role of law enforcement officers in our society. Discuss their answers
    with them. Go to a law enforcement officer in your neighborhood and ask
    about his or her responsibilities and duties. Report your findings.
- requirement: 5
  text: |-
    Tell about several laws that were passed to protect the consumer and the
    seller. Tell about several organizations that provide help to consumers
    and sellers.
- requirement: 6
  text: |-
    Do ONE of the following:
  children:
    - requirement: a
      text: |-
        Attend a session of a civil or criminal court. Write 250 words or
        more on what you saw.
    - requirement: b
      text: |-
        Plan and conduct a mock trial with your troop or school class.
        After the trial is over, discuss it with the group.
- requirement: 7
  text: |-
    Arrange a visit with a lawyer who works for a business, bank, title
    company, or government agency. Find out his or her duties and
    responsibilities. Report what you have learned.
- requirement: 8
  text: |-
    Explain the requirements for becoming a lawyer in your state. Describe
    how judges are selected in your state.
- requirement: 9
  text: |-
    Make a list of 15 jobs that deal with some aspects of law or legal
    processes.  Tell which you prefer. Why?
- requirement: 10
  text: |-
    Tell where people can go to obtain the help of a lawyer if they are
    unable to pay for one. Tell what you can do if you can afford a lawyer
    but do not know of any in your area.
- requirement: 11
  text: |-
    Discuss with your counselor the importance in our society of TWO of the
    following areas of the law:
  children:
    - requirement: a
      text: |-
        Environmental law
    - requirement: b
      text: |-
        Computers and the internet
    - requirement: c
      text: |-
        Copyright and the internet
    - requirement: d
      text: |-
        Immigration
    - requirement: e
      text: |-
        Patents
    - requirement: f
      text: |-
        Biotechnology
    - requirement: g
      text: |-
        Privacy law
    - requirement: h
      text: |-
        International law
