- requirement: 1
  text: |-
    Do EACH of the following:
  children:
    - requirement: a
      text: |-
        Describe three examples of safety equipment used in a chemistry laboratory and the reason each one is used.
    - requirement: b
      text: |-
        Describe what a safety data sheet (SDS) is and tell why it is used.
    - requirement: c
      text: |-
        Obtain an SDS for both a paint and an insecticide. Compare and discuss the toxicity, disposal, and safe-handling sections for these two common household products.
    - requirement: d
      text: |-
        Discuss the safe storage of chemicals. How does safe storage apply to your home, your school, your community, and the environment?
- requirement: 2
  text: |-
    Do EACH of the following:
  children:
    - requirement: a
      text: |-
        Predict what would happen if you placed an iron nail in a copper sulfate solution. Then, put an iron nail in a copper sulfate solution. Describe your observations and make a conclusion based on your observations. Compare your prediction and original conclusion with what actually happened. Write the formula for the reaction that you described.
    - requirement: b
      text: |-
        Demonstrate how you would separate sand (or gravel) from water.  Describe how you would separate table salt from water, oil from water, and gasoline from motor oil. Name the practical processes that require these kinds of separations and how the processes may differ.
    - requirement: c
      text: |-
        Describe the difference between a chemical reaction and a physical change.
        Observe one of each and share your observation with your counselor.
- requirement: 3
  text: |-
    Construct a Cartesian diver. Describe its function in terms of how gases in general behave under different pressures and different temperatures. Describe how the behavior of gases affects a backpacker at high altitudes and a scuba diver underwater.
- requirement: 4
  text: |-
    Do EACH of the following:
  children:
    - requirement: a
      text: |-
        Cut a round onion into small chunks. Separate the onion chunks into three equal portions. Leave the first portion raw. Cook the second portion of onion chunks until the pieces are translucent. Cook the third portion until the onions are caramelized, or brown in color. Taste each type of onion. Describe the taste of raw onion versus partially cooked onion versus caramelized onion.  Explain what happens to molecules in the onion during the cooking process.
    - requirement: b
      text: |-
        Describe the chemical similarities and differences between toothpaste and an abrasive household cleanser. Explain how the end use or purpose of a product affects its chemical formulation.
    - requirement: c
      text: |-
        In a clear container, mix a half-cup of water with a tablespoon of oil.  Explain why the oil and water do not mix. Find a substance that will help the two combine, and add it to the mixture. Describe what happened, and explain how that substance worked to combine the oil and water.
- requirement: 5
  text: |-
    Discuss with your counselor the 5 classical areas of chemistry (organic,
    inorganic, physical, analytical and biological), and two others from the
    following list. Explain what they are, and how they impact your daily life.
  children:
      - requirement: a
        text: Agricultural chemistry
      - requirement: b
        text: Atmospheric chemistry
      - requirement: c
        text: Computational chemistry
      - requirement: d
        text: Electrochemistry
      - requirement: e
        text: Environmental chemistry and green chemistry
      - requirement: f
        text: Flavor chemistry, fragrance chemistry, and food chemistry
      - requirement: g
        text: Medicinal and natural products chemistry
      - requirement: h
        text: Photochemistry
      - requirement: i
        text: Polymer chemistry
      - requirement: j
        text: Or another area of chemistry of your choosing
- requirement: 6
  text: |-
    Do EACH of the following:
  children:
    - requirement: a
      text: |-
        Name two government agencies that are responsible for tracking the use of chemicals for commercial or industrial use. Pick one agency and briefly describe its responsibilities.
    - requirement: b
      text: |-
        Define pollution. Explain the chemical impacts on the ozone layer and global climate change.
    - requirement: c
      text: |-
        Using reasons from chemistry, describe the effect on the environment of ONE of the following:
      children:
        - requirement: 1
          text: |-
            The production of aluminum cans
        - requirement: 2
          text: |-
            Burning fossil fuels
        - requirement: 3
          text: |-
            Single-use items, such as water bottles, bags, straws, or paper
    - requirement: d
      text: |-
        Briefly describe the purpose of phosphates in fertilizer and in laundry detergent. Explain how the use of phosphates in fertilizers affects the environment. Explain why phosphates have been removed from laundry detergents.
- requirement: 7
  text: |-
    Do ONE of the following activities:
  children:
    - requirement: a
      text: |-
        Visit a laboratory and talk to a chemist. Ask what that chemist does and what training and education are needed to work as a chemist.
    - requirement: b
      text: |-
        Using resources found at the library and in periodicals, books, and the internet (with your parent's or guardian's permission), learn about two different kinds of work done by chemists, chemical engineers, chemical technicians, or industrial chemists. For each of the four positions, find out the education and training requirements.
    - requirement: c
      text: |-
        Visit an industrial plant that makes chemical products or uses chemical processes and describe the processes used. What, if any, by-products are produced and how are they handled?
    - requirement: d
      text: |-
        Visit a county farm agency or similar governmental agency and learn how chemistry is used to meet the needs of agriculture in your county.
