- requirement: 1
  text: |-
    <b>First Aid Merit Badge</b> Earn the <a
    href="/merit-badges/first-aid/">First Aid merit badge</a>.
- requirement: 2
  text: |-
    <b>Emergency Situations</b> Do the following:
  children:
    - requirement: a
      text: |-
        Discuss with your counselor the aspects of emergency preparedness
        and include in your discussion the kinds of questions that are
        important to ask yourself as you consider each of these:
      children:
        - requirement: 1
          text: |-
            Prevention
        - requirement: 2
          text: |-
            Protection
        - requirement: 3
          text: |-
            Mitigation
        - requirement: 4
          text: |-
            Response
        - requirement: 5
          text: |-
            Recovery
    - requirement: b
      text: |-
        Using a chart, spreadsheet, or another method approved by your
        counselor, demonstrate your understanding of each aspect of emergency
        preparedness listed in requirement 2(a) (prevention, protection,
        mitigation, response, and recovery) for 10 emergency situations from
        the list below. Discuss your findings with your counselor.
      children:
        - requirement: 1
          text: |-
            Home stovetop or oven fire
        - requirement: 2
          text: |-
            Home flammable liquid fire
        - requirement: 3
          text: |-
            Gas leak in or near a home or with outside cooking
        - requirement: 4
          text: |-
            Food poisoning
        - requirement: 5
          text: |-
            Automobile crash
        - requirement: 6
          text: |-
            Vehicle stalled in the desert
        - requirement: 7
          text: |-
            Vehicle trapped in a blizzard
        - requirement: 8
          text: |-
            Backcountry injury
        - requirement: 9
          text: |-
            Boating or water accident
        - requirement: 10
          text: |-
            Toxic chemical spills and releases
        - requirement: 11
          text: |-
            Nuclear power plant emergency
        - requirement: 12
          text: |-
            Fire or explosion in a public place
        - requirement: 13
          text: |-
            Violence in a public place
        - requirement: 14
          text: |-
            Wildland fire
        - requirement: 15
          text: |-
            Avalanche (snowslide or rockslide)
        - requirement: 16
          text: |-
            Earthquake
        - requirement: 17
          text: |-
            Tsunami
        - requirement: 18
          text: |-
            Major flooding or a flash flood with water outage
        - requirement: 19
          text: |-
            Hurricane with power outage
        - requirement: 20
          text: |-
            Tornado
        - requirement: 21
          text: |-
            Lightning storm.
- requirement: 3
  text: |-
    <b>Planning for Family Emergencies.</b> Do the following:
  children:
    - requirement: a
      text: |-
        At a family meeting, discuss the situations on the chart you created
        for requirement 2b and make emergency plans for sheltering-in-place and
        for evacuation of your home. Discuss your family meeting and plans with
        your counselor.
    - requirement: b
      text: |-
        Develop and practice a plan of escape for your family in case of fire
        in your home. Draw a floor plan with escape routes and a map with a
        safe meeting place. Discuss your family's home escape plan with your
        counselor.
    - requirement: c
      text: |-
        Using a checklist in the Emergency Preparedness Merit Badge pamphlet or
        one approved by your counselor, prepare or inspect a family disaster
        kit for sheltering-in-place and for evacuation of your home. Review the
        needs and uses of the items in a kit with your counselor.
- requirement: 4
  text: |-
    <b>Preventing Accidents and Emergencies.</b> Do ONE of the following:
  children:
    - requirement: a
      text: |-
        Using a home safety checklist included in the Emergency Preparedness
        Merit Badge pamphlet or one approved by your counselor, inspect a home
        (or a similar building near where you live or at a camp) for safety
        hazards with the help of an adult. Present your completed checklist to
        and discuss your findings with your counselor.
    - requirement: b
      text: |-
        Develop emergency prevention plans for five family activities outside
        the home, as approved by your counselor. (Examples are taking a picnic
        to a park, seeing a movie, attending a worship service, an outing at a
        beach, traveling to visit a relative, or attending a ball game or
        concert.) Each plan should include an analysis of possible hazards,
        proposals to prevent, protect from, mitigate, respond to, and recover
        from emergencies, and the reasons for the actions that you propose.
- requirement: 5
  text: |-
    <b>Dangerous Situations.</b> Show how you could save a person from the
    following dangerous situations without putting yourself in danger:
  children:
    - requirement: a
      text: |-
        Live household electric wire
    - requirement: b
      text: |-
        A structure filled with carbon monoxide
    - requirement: c
      text: |-
        Clothes on fire
    - requirement: d
      text: |-
        Drowning, using nonswimming rescues (including accidents on ice).
- requirement: 6
  text: |-
    <b>Signaling for Help.</b> Do the following:
  children:
    - requirement: a
      text: |-
        Show three ways of attracting and communicating with rescue aircraft
        or drones.
    - requirement: b
      text: |-
        Show ways to attract attention of searchers on the ground if you are
        lost in the wilderness.
    - requirement: c
      text: |-
        Show ways to attract attention of searchers on the water if you are
        stranded with a capsized or disabled motorboat or sailboat.
- requirement: 7
  text: |-
    <b>Moving an Injured Person.</b> With another person, show two good ways to
    transport an injured person out of a remote area using improvised
    stretchers to conserve the energy of rescuers while ensuring the well-being
    and protection of the injured person.
- requirement: 8
  text: |-
    <b>National Incident Management System (NIMS) and Incident Command System
    (ICS).</b> Do the following:
  children:
    - requirement: a
      text: |-
        Describe the National Incident Management System (NIMS) and the
        local Incident Command System (ICS).
    - requirement: b
      text: |-
        Find out how your community and its leaders work to manage and to train
        for disasters. Discuss this information with your counselor, using the
        information you learned from requirement 1b.
    - requirement: c
      text: |-
        Discuss how a Scout troop can help in an emergency situation using ICS.
- requirement: 9
  text: |-
    <b>Emergency Service.</b> Do the following:
  children:
    - requirement: a
      text: |-
        Discuss with your counselor the duties that a Scout troop should be
        prepared to do, the training they need, and the safety precautions
        they should take for the following emergency services:
      children:
        - requirement: 1
          text: |-
            Crowd and traffic control
        - requirement: 2
          text: |-
            Messenger service during an incident
        - requirement: 3
          text: |-
            Collection and distribution services
        - requirement: 4
          text: |-
            Group feeding, shelter, and sanitation.
    - requirement: b
      text: |-
        Prepare a written plan for mobilizing your troop when needed to do
        emergency service. If your troop already has a mobilization plan,
        present the plan to your counselor and tell your part in making the
        plan work.
    - requirement: c
      text: |-
        Using a checklist in this pamphlet or one approved by your counselor,
        prepare or inspect a personal emergency service pack for a mobilization
        call. Explain the needs and uses of the contents to your counselor.
    - requirement: d
      text: |-
        Take part in an emergency service project, either a real one or a
        practice exercise, with a Scouting troop or a community agency or at
        Scout camp or at a school. Review what you learned and practiced with
        your counselor.
- requirement: 10
  text: |-
    Do ONE of the following:
  children:
    - requirement: a
      text: |-
        Interview an emergency services coordinator or a civil servant about
        their work in disaster management. Learn about how they chose this
        career and about their duties. Discuss what you learned with your
        counselor and whether you might be interested in this career.
    - requirement: b
      text: |-
        Identify three career opportunities that would use skills and knowledge
        in emergency services. Pick one and research the training, education,
        certification requirements, experience, and expenses associated with
        entering the field. Research the prospects for employment, starting
        salary, advancement opportunities, and career goals associated with
        this career. Discuss what you learned with your counselor and whether
        you might be interested in this career.
    - requirement: c
      text: |-
        Identify how you might use the skills and knowledge in the field of
        emergency preparedness to pursue a personal hobby and/or healthy
        lifestyle. Research the additional training required, expenses, and
        affiliation with organizations that would help you maximize the
        enjoyment and benefit you might gain from it. Discuss what you learned
        with your counselor and share what short-term and long-term goals you
        might have if you pursued this.
