- requirement: 1
  markdown: true
  text: |-
    Earn the <a href="/merit-badges/first-aid/">First Aid</a> merit badge.
  children:
    - note:
        - inPerson
        - online
      text: |-
        Scouts should bring proof of their completion of the First Aid
        Merit Badge to class. Simply saying that you have completed it will
        NOT be enough for the counselor to sign off on this requirement.
        While it is preferred that Scouts have their First Aid Merit Badge
        prior to working on this merit badge, the requirement does not
        require that the First Aid Merit Badge be earned in order to work
        on the other requirements.  Scouts attending that do not have their
        First Aid Merit Badge will need to earn their First Aid Merit Badge
        before they will be able to complete this requirement for the
        Emergency Preparedness Merit Badge.
- requirement: 2
  text: |-
    Do the following:
  children:
    - requirement: a
      text: |-
        Discuss with your counselor the aspects of emergency preparedness:
      children:
        - requirement: 1
          text: |-
            Prevention
        - requirement: 2
          text: |-
            Protection
        - requirement: 3
          text: |-
            Mitigation
        - requirement: 4
          text: |-
            Response
        - requirement: 5
          text: |-
            Recovery
        - detail: true
          text: |-
            Include in your discussion the kinds of questions that are
            important to ask yourself as you consider each of these.
        - note:
            - inPerson
            - online
          text: |-
            Scouts must review the merit badge pamphlet to gain an
            initial understanding of the concepts for this requirement.
            Scouts will discuss in a group with the counselor their
            findings and should come prepared with questions that might
            be important to ask in the consideration of each of these
            components of the requirement.  It is recommended that Scouts
            utilize a Merit Badge Workbook to write down and formulate
            their thoughts and questions as it pertains to this
            requirement prior to the class so that they are prepared for
            discussion during the class.  It will be difficult, if not
            impossible for Scouts who do not prepare for this requirement
            to complete the requirement without active participation in
            the group discussion at the class.
    - requirement: b
      markdown: true
      text: |-
        Using a chart, graph, spreadsheet, or another method approved by
        your counselor, demonstrate your understanding of each aspect of
        emergency preparedness listed in requirement 2a (prevention,
        protection, mitigation, response, and recovery) for 10 emergency
        situations from the list below. **You must use the first five
        situations listed below in boldface,** plus any other five of your
        choice.  Discuss your findings with your counselor.
      children:
        - requirement: 1
          markdown: true
          text: |-
            **Home kitchen fire**
        - requirement: 2
          markdown: true
          text: |-
            **Home basement/storage room/garage fire**
        - requirement: 3
          markdown: true
          text: |-
            **Explosion in the home**
        - requirement: 4
          markdown: true
          text: |-
            **Automobile crash**
        - requirement: 5
          markdown: true
          text: |-
            **Food-borne disease (food poisoning)**
        - requirement: 6
          markdown: true
          text: |-
            Fire or explosion in a public place
        - requirement: 7
          markdown: true
          text: |-
            Vehicle stalled in the desert
        - requirement: 8
          markdown: true
          text: |-
            Vehicle trapped in a blizzard
        - requirement: 9
          markdown: true
          text: |-
            Earthquake or tsunami
        - requirement: 10
          markdown: true
          text: |-
            Mountain/backcountry accident
        - requirement: 11
          markdown: true
          text: |-
            Boating or water accident
        - requirement: 12
          markdown: true
          text: |-
            Gas leak in a home or a building
        - requirement: 13
          markdown: true
          text: |-
            Tornado or hurricane
        - requirement: 14
          markdown: true
          text: |-
            Major flooding or a flash flood
        - requirement: 15
          markdown: true
          text: |-
            Toxic chemical spills and releases
        - requirement: 16
          markdown: true
          text: |-
            Nuclear power plant emergency
        - requirement: 17
          markdown: true
          text: |-
            Avalanche (snowslide or rockslide)
        - requirement: 18
          markdown: true
          text: |-
            Violence in a public place
        - note:
            - inPerson
            - online
          text: |-
            While this requirement component will be covered in the
            class, it does need to have some preparation done ahead of
            time. The majority of time during the class will be spent
            discussing Scouts' findings and thoughts in addressing these
            scenarios.  Drawing out one's chart ahead of time will ensure
            the highest probability of completing this requirement
            component in the class.  Scouts who do not come with a chart
            and at least the required five scenarios prepared ahead of
            time will likely not have an opportunity of completing this
            requirement component.
    - requirement: c
      text: |-
        Meet with and teach your family how to get or build a kit, make a
        plan, and be informed for the situations on the chart you created
        for requirement 2b. Complete a family plan. Then meet with your
        counselor and report on your family meeting, discuss their
        responses, and share your family plan.
      children:
        - note:
            - inPerson
            - online
          text: |-
            A note from a parent or guardian living with you stating the
            scenarios from 2b discussed at home will help ensure
            completion of this requirement component. Scouts should bring
            their kit (or a photo will suffice) along with an outline of
            their plan (shown or included on your chart from requirement
            2b) to share with the counselor and the class. Scouts that
            are unable to provide clear proof of this family activity
            will find it difficult, if not impossible, to complete this
            requirement component as a part of the class.
- requirement: 3
  text: |-
    Show how you could save a person from the following dangerous situations
    without putting yourself in danger:
  children:
    - requirement: a
      text: |-
        Touching a live household electric wire
    - requirement: b
      text: |-
        A structure filled with carbon monoxide
    - requirement: c
      text: |-
        Clothes on fire
    - requirement: d
      text: |-
        Drowning, using nonswimming rescues (including accidents on ice)
    - note:
        - inPerson
        - online
      text: |-
        This requirement will be discussed in class however, Scouts should
        review these sections in the merit badge pamphlet prior to the
        class to have a basic understanding of methods to utilize for each
        scenario. Scouts should be prepared for discussion and
        demonstration of their findings. Scouts who do not come having done
        this preapration work will find it difficult, if not impossible, to
        complete this requirement and it's components as a part of the
        class.
- requirement: 4
  text: |-
    Show three ways of attracting and communicating with rescue
    planes/aircraft.
  children:
    - note:
        - inPerson
        - online
      text: |-
        Scouts will discuss this requirement in class.  The Merit Badge
        Pamphlet has a section on this subject that should be referenced
        and reviewed as a preparation exercise for this requirement.
        Scouts may find it helpful to make notes in their Merit Badge
        Workbook for easy reference during the class to aid them in showing
        and sharing their findings.
- requirement: 5
  text: |-
    With another person, show a good way to transport an injured person out
    of a remote and/or rugged area, conserving the energy of rescuers while
    ensuring the well-being and protection of the injured person.
  children:
    - note:
        - inPerson
      text: |-
        Scouts will learn, practice, and demonstrate their knowledge and
        skill for this requirement during the class.
    - note:
        - online
      text: |-
        Scouts will need to work with another person prior to the class and
        come up with a way to share their ability to show this skill to the
        counselor.  This may include, having another person and equipment
        ready during the class to demonstrate, videoing the moment, etc.
- requirement: 6
  text: |-
    Do the following:
  children:
    - requirement: a
      text: |-
        Describe the National Incident Management System (NIMS) and the
        Incident Command System (ICS).
      children:
        - note:
            - inPerson
            - online
          text: |-
            While this requirement will be covered in the class through
            group discussion, Scouts should still familiarize themselves
            with these items and be prepared to share their understanding
            during the class.  Only Scouts that are able to show that
            they have prepared for this requirement ahead of time will be
            signed off on this requirement component.  It is NOT
            acceptable to come to the class and expect to be "fed" this
            information during the class and still receive credit.
    - requirement: b
      text: |-
        Identify the local government or community agencies that normally
        handle and prepare for emergency services similar to those of the
        NIMS or ICS.  Explain to your counselor ONE of the following:
      children:
        - requirement: 1
          text: |-
            How the NIMS/ICS can assist a Boy Scout troop when responding
            in a disaster
        - requirement: 2
          text: |-
            How a group of Scouts could volunteer to help in the event of
            these types of emergencies
        - note:
            - inPerson
            - online
          text: |-
            Scouts will need to have researched and prepared ahead of
            time for this requirement to be completed during the class.
            This requirement will be discussed in the class, however only
            Scouts that have done their preparation on this will have the
            opportunity to be considered for sign off on this
            requirement. Unprepared Scouts will not necessarily be signed
            off just for listening to the counselor and others share
            their information. Scouts should organize their thoughts and
            findings in a way that they can easily share what they found
            for this requirement during the class.
    - requirement: c
      markdown: true
      text: |-
        Find out who is your community’s emergency management director and
        learn what this person does to **prevent, protect, mitigate,
        respond to, and recover from** emergency situations in your
        community.  Discuss this information with your counselor, utilizing
        the information you learned from requirement 2b.
      children:
        - note:
            - inPerson
            - online
          text: |-
            To complete this requirement, Scouts will need to share with
            the counselor the person or agency responsible for emergency
            preparedness in their community.  In some cases, this may be
            a multitude of people or organizations depending on the
            scenario. Scouts should come prepared with this information
            in order to complete this requirement at the class.
- requirement: 7
  text: |-
    Do the following:
  children:
    - requirement: a
      text: |-
        Take part in an emergency service project, either a real one or a
        practice drill, with a Scouting unit or a community agency.
      children:
        - note:
            - inPerson
          text: |-
            This requirement will be completed in the class however it
            must be noted that Scouts will be going outside to perform
            this requirement.  PLEASE BRING/WEAR WEATHER APPROPRIATE
            ATTIRE FOR THE DAY.  Scouts not found to have the proper
            outdoor attire for the day's weather conditions will not be
            allowed for safety reasons to participate and hence will not
            have an opportunity to complete this requirement.
        - note:
            - online
          text: |-
            This requirement will NOT be completed in the class, however
            Scouts that can bring satisfactory proof of having already
            completed this requirement should bring proof for review by
            the merit badge counselor. If the counselor is satisfied with
            the discussion and "proof" submitted, Scouts will have an
            opportunity to be signed off on this requirement component as
            a part of the class.
    - requirement: b
      text: |-
        Prepare a written plan for mobilizing your troop when needed to do
        emergency service. If there is already a plan, explain it. Tell
        your part in making it work.
      children:
        - note:
            - inPerson
            - online
          text: |-
            Scouts whose troop already has a written plan to do emergency
            service should bring a copy of that or notes that cover the
            plan for sharing during the class.  Scouts should be prepared
            to share their responsibility in the plan when executed. If
            your Troop does not have a plan, time may be given in the
            class in order for you to create one. Scouts will need to be
            aware that this written plan will need to be completed before
            the end of the class in order to receive credit of completion
            for this requirement. A written plan does not necessarily
            need to be hand-written, so Scouts with writing challenges
            may want to consider bringing a laptop or tablet to class for
            use to complete this requirement.
- requirement: 8
  text: |-
    Do the following:
  children:
    - requirement: a
      text: |-
        Tell the things a group of Scouts should be prepared to do, the
        training they need, and the safety precautions they should take for
        the following emergency services.
      children:
        - requirement: 1
          text: |-
            Crowd and traffic control
        - requirement: 2
          text: |-
            Messenger service and communication
        - requirement: 3
          text: |-
            Collection and distribution services
        - requirement: 4
          text: |-
            Group feeding, shelter, and sanitation
        - note:
            - inPerson
            - online
          text: |-
            While this requirement will be covered in the class through
            group discussion, Scouts should still familiarize themselves
            with methods and practices for each of these scenarios.  It
            may be helpful to us a Merit Badge Workbook to make notes
            ahead of time for easier reference and sharing during the
            class group discussion for each of the scenarios.  This type
            of preparation helps the counselor identify Scouts more
            easily that prepared and have thought out their response to
            this requirement.  Only Scouts that actively participate in
            the discussion during the class will have the opportunity of
            completing this requirement.
    - requirement: b
      text: |-
        Prepare a personal emergency service pack for a mobilization call.
        Prepare a family emergency kit (suitcase or waterproof box) for use
        by your family in case an emergency evacuation is needed. Explain
        the needs and uses of the contents.
      children:
        - note:
            - inPerson
            - online
          text: |-
            Scouts need to assemble two different kits, then bring their
            kits or photos of their kits. Be prepared to discuss the
            contents of the kits and explain the reasoning behind your
            choices of what was included and what was not. Any unprepared
            Scouts will be unable to complete this requirement during
            class.
- requirement: 9
  text: |-
    Do ONE of the following:
  children:
    - requirement: a
      text: |-
        Using a safety checklist approved by your counselor, inspect your
        home for potential hazards. Explain the hazards you find and how
        they can be corrected.
    - requirement: b
      text: |-
        Review or develop a plan of escape for your family in case of fire
        in your home.
    - requirement: c
      text: |-
        Develop an accident prevention program for five family activities
        outside the home (such as taking a picnic or seeing a movie) that
        includes an analysis of possible hazards, a proposed plan to
        correct those hazards, and the reasons for the corrections you
        propose.
    - note:
        - inPerson
        - online
      text: |-
        In order to complete this requirement Scouts will need to bring
        documentation of one of these components to share in the class.  It
        is highly recommended that a note signed by a parent or guardian
        with whom you live with stating your review and completion of one
        of these components with your family would serve to help the
        counselor validate your completion. Please note that simply having
        a signed note is not enough for completion of this requirement.  In
        each component of the requirement it requires some sort of
        additional documentation, chart, plan, etc to be included as a part
        of fulfilling this requirement.  Scouts should bring both their
        work and signed note to class.
