- requirement: 1
  markdown: true
  text: |-
    Earn the <a href="/merit-badges/first-aid/">First Aid</a> merit badge.
- requirement: 2
  text: |-
    Do the following:
  children:
    - requirement: a
      text: |-
        Discuss with your counselor the aspects of emergency preparedness:
      children:
        - requirement: 1
          text: |-
            Prevention
        - requirement: 2
          text: |-
            Protection
        - requirement: 3
          text: |-
            Mitigation
        - requirement: 4
          text: |-
            Response
        - requirement: 5
          text: |-
            Recovery
        - detail: true
          text: |-
            Include in your discussion the kinds of questions that are
            important to ask yourself as you consider each of these.
    - requirement: b
      markdown: true
      text: |-
        Using a chart, graph, spreadsheet, or another method approved by
        your counselor, demonstrate your understanding of each aspect of
        emergency preparedness listed in requirement 2a (prevention,
        protection, mitigation, response, and recovery) for 10 emergency
        situations from the list below. **You must use the first five
        situations listed below in boldface,** plus any other five of your
        choice.  Discuss your findings with your counselor.
      children:
        - requirement: 1
          markdown: true
          text: |-
            **Home kitchen fire**
        - requirement: 2
          markdown: true
          text: |-
            **Home basement/storage room/garage fire**
        - requirement: 3
          markdown: true
          text: |-
            **Explosion in the home**
        - requirement: 4
          markdown: true
          text: |-
            **Automobile crash**
        - requirement: 5
          markdown: true
          text: |-
            **Food-borne disease (food poisoning)**
        - requirement: 6
          markdown: true
          text: |-
            Fire or explosion in a public place
        - requirement: 7
          markdown: true
          text: |-
            Vehicle stalled in the desert
        - requirement: 8
          markdown: true
          text: |-
            Vehicle trapped in a blizzard
        - requirement: 9
          markdown: true
          text: |-
            Earthquake or tsunami
        - requirement: 10
          markdown: true
          text: |-
            Mountain/backcountry accident
        - requirement: 11
          markdown: true
          text: |-
            Boating or water accident
        - requirement: 12
          markdown: true
          text: |-
            Gas leak in a home or a building
        - requirement: 13
          markdown: true
          text: |-
            Tornado or hurricane
        - requirement: 14
          markdown: true
          text: |-
            Major flooding or a flash flood
        - requirement: 15
          markdown: true
          text: |-
            Toxic chemical spills and releases
        - requirement: 16
          markdown: true
          text: |-
            Nuclear power plant emergency
        - requirement: 17
          markdown: true
          text: |-
            Avalanche (snowslide or rockslide)
        - requirement: 18
          markdown: true
          text: |-
            Violence in a public place
    - requirement: c
      text: |-
        Meet with and teach your family how to get or build a kit, make a
        plan, and be informed for the situations on the chart you created
        for requirement 2b. Complete a family plan. Then meet with your
        counselor and report on your family meeting, discuss their
        responses, and share your family plan.
- requirement: 3
  text: |-
    Show how you could save a person from the following dangerous situations
    without putting yourself in danger:
  children:
    - requirement: a
      text: |-
        Touching a live household electric wire
    - requirement: b
      text: |-
        A structure filled with carbon monoxide
    - requirement: c
      text: |-
        Clothes on fire
    - requirement: d
      text: |-
        Drowning, using nonswimming rescues (including accidents on ice)
- requirement: 4
  text: |-
    Show three ways of attracting and communicating with rescue
    planes/aircraft.
- requirement: 5
  text: |-
    With another person, show a good way to transport an injured person out
    of a remote and/or rugged area, conserving the energy of rescuers while
    ensuring the well-being and protection of the injured person.
- requirement: 6
  text: |-
    Do the following:
  children:
    - requirement: a
      text: |-
        Describe the National Incident Management System (NIMS) and the
        Incident Command System (ICS).
    - requirement: b
      text: |-
        Identify the local government or community agencies that normally
        handle and prepare for emergency services similar to those of the
        NIMS or ICS.  Explain to your counselor ONE of the following:
      children:
        - requirement: 1
          text: |-
            How the NIMS/ICS can assist a Boy Scout troop when responding
            in a disaster
        - requirement: 2
          text: |-
            How a group of Scouts could volunteer to help in the event of
            these types of emergencies
    - requirement: c
      markdown: true
      text: |-
        Find out who is your community’s emergency management director and
        learn what this person does to **prevent, protect, mitigate,
        respond to, and recover from** emergency situations in your
        community.  Discuss this information with your counselor, utilizing
        the information you learned from requirement 2b.
- requirement: 7
  text: |-
    Do the following:
  children:
    - requirement: a
      text: |-
        Take part in an emergency service project, either a real one or a
        practice drill, with a Scouting unit or a community agency.
    - requirement: b
      text: |-
        Prepare a written plan for mobilizing your troop when needed to do
        emergency service. If there is already a plan, explain it. Tell
        your part in making it work.
- requirement: 8
  text: |-
    Do the following:
  children:
    - requirement: a
      text: |-
        Tell the things a group of Scouts should be prepared to do, the
        training they need, and the safety precautions they should take for
        the following emergency services.
      children:
        - requirement: 1
          text: |-
            Crowd and traffic control
        - requirement: 2
          text: |-
            Messenger service and communication
        - requirement: 3
          text: |-
            Collection and distribution services
        - requirement: 4
          text: |-
            Group feeding, shelter, and sanitation
    - requirement: b
      text: |-
        Prepare a personal emergency service pack for a mobilization call.
        Prepare a family emergency kit (suitcase or waterproof box) for use
        by your family in case an emergency evacuation is needed. Explain
        the needs and uses of the contents.
- requirement: 9
  text: |-
    Do ONE of the following:
  children:
    - requirement: a
      text: |-
        Using a safety checklist approved by your counselor, inspect your
        home for potential hazards. Explain the hazards you find and how
        they can be corrected.
    - requirement: b
      text: |-
        Review or develop a plan of escape for your family in case of fire
        in your home.
    - requirement: c
      text: |-
        Develop an accident prevention program for five family activities
        outside the home (such as taking a picnic or seeing a movie) that
        includes an analysis of possible hazards, a proposed plan to
        correct those hazards, and the reasons for the corrections you
        propose.
