# Counselor notes are messed up in the original.

- requirement: 1
  text: |-
      Choose A or B or C and complete ALL the requirements.
  children:
      - requirement: A
        text: |-
            Watch about three hours total of engineering-related shows or
            documentaries that involve motion or motion-inspired technology.
            Then do the following:
        children:
            - requirement: 1
              text: |-
                  Make a list of at least five questions or ideas from the
                  show(s) you watched.
            - requirement: 2
              text: |-
                  Discuss two of the questions or ideas with your counselor.
            - note:
                - counselor
              markdown: true
              text: |-
                  Some examples include—but are not limited to—shows found on
                  PBS (“NOVA”), Discovery Channel, Science Channel, National
                  Geographic Channel, TED Talks (online videos), and the
                  History Channel. You may choose to watch a live performance
                  or movie at a science museum instead of watching a media
                  production. You may watch online productions with your
                  counselor’s approval and under your parent’s or guardian’s
                  supervision. One example is the NOVA Lever, an Obelisk page
                  on ancient Egypt and the use of levers, available at
                  www.pbslearningmedia.org/resource/phy03.sci.phys.energy.vegypt/raising-an-obelisk-an-engineering-puzzle/?student=true&focus=true
      - requirement: B
        text: |-
            Read (about three hours total) about motion or motion-inspired
            technology. Then do the following:
        children:
            - requirement: 1
              text: |-
                  Make a list of at least two questions or ideas from each
                  article.
            - requirement: 2
              text: |-
                  Discuss two of the questions or ideas with your counselor.
            - note:
                - counselor
              text: |-
                  Examples of magazines include—but are not limited to—Odyssey,
                  Popular Mechanics, Popular Science, Science Illustrated,
                  Discover, Air & Space, Popular Astronomy, Astronomy, Science
                  News, Sky & Telescope, Natural History, Robot, Servo, Nuts
                  and Volts, and Scientific American.
      - requirement: C
        text: |-
            Do a combination of reading and watching (about three hours total).
            Then do the following:
        children:
            - requirement: 1
              text: |-
                  Make a list of at least two questions or ideas from each
                  article or show.
            - requirement: 2
              text: |-
                  Discuss two of the questions or ideas with your counselor.
# It appears that this is listing merit badges instead of STEM explorations.
- requirement: 2
  markdown: true
  text: |-
      Complete ONE STEM field of interest from the following list. Complete ALL
      the requirements for a Venturing and Sea Scout exploration in that field.
      See [STEM Explorations](../../explorations/) for the requirements. If you
      have already completed a Venturing or Sea Scout exploration in one of
      these fields, choose a different field for this award. After completion,
      discuss with your counselor how the exploration you earned uses
      engineering.

      Archery, Aviation, Composite Materials, Drafting, Electronics,
      Engineering, Inventing, Mining in Society, Model Design and Building,
      Railroading, Rifle Shooting, Robotics, Shotgun Shooting

      Composites can be found just about everywhere: in airplanes and sports
      cars, golf clubs and guitars, boats and baseball bats, bathtubs, and
      circuit boards, and even bridges. Composites make bicycles and skis
      lighter, kayaks and fishing poles stronger, houses warmer, and helmets
      tougher. Venturers and Sea Scouts can choose one of these items for their
      discussion to answer requirement 3c.
- requirement: 3
  text: |-
      Do ALL the following.
  children:
      - requirement: A
        text: |-
            Make a list or drawing of the six simple machines.
        children:
            - detail: true
              markdown: true
              text: |-
                  Helpful Links

                  “Six Simple Machines”: http://www.constructionknowledge.net/

                  https://www.livescience.com/49106-simple-machines.html

                  https://www.teachengineering.org/populartopics/simplemachines
            # Kept older images because the newer ones don't have the text
            # labels.
            - note:
                - counselor
              text: |-
                  A lever is a rigid bar that turns around a fulcrum or fixed
                  point. The force - a push or a pull that is applied to the
                  lever - is called the effort. The farther the effort is from
                  the fulcrum, the easier it is to use the lever. What the
                  lever moves is called the load or the resistance. Levers can
                  change the direction of motion, make it easier to move
                  something, or cause something to move a greater distance.
                  There are three classes, or types, of levers. Class 1 lever -
                  The fulcrum is located between the effort and the load. The
                  direction the load moves is opposite the direction of the
                  effort.  Depending on where the fulcrum is placed, a class 1
                  lever can either move the load more easily or move the load a
                  greater distance. Examples of class 1 levers include seesaws,
                  crowbars, scissors, and pliers.

                  Class 2 lever - The fulcrum is at one end, the effort is at
                  the other end, and the load is in the middle.  The effort and
                  the load move in the same direction.

                  A class 2 lever makes an object easier to move. Examples of
                  class 2 levers include catapults, screwdrivers, nutcrackers,
                  staplers, and wheelbarrows.

                  Class 3 lever - The fulcrum is at one end, and the effort is
                  applied between the fulcrum and the load.  The effort and the
                  load move in the same direction. A class 3 lever makes an
                  object harder to move but moves the object a much greater
                  distance than the effort moves. Because the load end moves
                  faster than the effort (it has to travel farther during the
                  same amount of time), the load gains speed.  Many sporting
                  activities use class 3 levers.

                  Examples of class 3 levers include bats, rackets, paddles,
                  clubs, fishing poles, and brooms.

                  <img src="levers.png" class="W(100%) H(a)">

                  <img src="simple-machines.png" class="W(100%) H(a)">

                  <img src="screw-and-pulley.png" class="W(100%) H(a)">
      - requirement: B
        text: |-
            Be able to tell your counselor the name of each machine and how
            each machine works.
      - requirement: C
        text: |-
            Discuss the following with your counselor:
        children:
            # This said "merit badge" and changed it to "STEM exploration"
            # because this is for venturers.
            - requirement: 1
              text: |-
                  The simple machines that were involved with the motion in
                  your chosen STEM exploration (Hint: Look at the moving parts
                  of an engine to find simple machines.)
              children:
                  # Kept older images because the newer ones don't have the
                  # text labels.
                  - note:
                      - counselor
                    markdown: true
                    text: |-
                        Helpful Links

                        “Six Simple Machines”: ConstructionKnowledge.net

                        Website:
                        https://www.constructionknowledge.net/general_technical_knowledge/general_tech_basic_six_simple_machines.php

                        * Archery - The bow is a lever, and the hand is the
                        fulcrum.  Crossbows use a pulley.
                        * Aviation - Wheel and axle, levers, and pulleys.
                        Propellers are a type of screw.
                        * Composite Materials - Composites can be found just
                        about everywhere: in airplanes, golf clubs, baseball
                        bats, circuit boards, and even bridges. Composites make
                        sporting equipment lighter and stronger, houses warmer,
                        and helmets tougher.  Pick a composite product and
                        discuss the machines made of the components.
                        * Drafting - Incline plane (triangle), wheel and axle,
                        and lever.
                        * Electronics - Varies. Lever used in soldering irons,
                        switches, and circuit breakers (see
                        https://electronics.howstuffworks.com/circuit-breaker.htm).
                        * Engineering - Engineering makes use of all the simple
                        machines. See
                        https://www.teachengineering.org/lessons/view/cub_simp_machines_lesson01
                        * Inventing - Inventors can use simple machines to help
                        them construct their prototypes; their inventions may
                        incorporate simple machines.
                        * Model Design and Building - Tools such as knives
                        (wedge), handsaws (wedge), vises (screw and lever),
                        files, hammers (lever), screwdrivers (lever), hand
                        drills (screw, wheel and axle), drill bits (screw), and
                        pliers (two levers working together).
                        * Railroading - Levers, wheel and axle.
                        * Rifle Shooting - The fulcrum (pivot point) in the
                        trigger mechanism is between the effort (applied by the
                        trigger finger) and where the pressure (the load or
                        resistance) is applied to the spring.
                            <img src="trigger-mechanism.png" class="W(100%) H(a)">
                        * Robotics - Robot designers and builders can use
                        simple machines to help them build their robots. Robots
                        may contain simple machines to help them function, like
                        how the human body incorporates simple machines.
                        * Shotgun Shooting - See Rifle Shooting.
            - requirement: 2
              text: |-
                  The energy source causing the motion for the subject of your
                  STEM exploration.
            - requirement: 3
              text: |-
                  What you learned about motion from earning your STEM
                  exploration.
              children:
                  - note:
                      - counselor
                    text: |-
                        Wind, gasoline/fossil fuel, electric power, and human
                        power all are sources of energy.
- requirement: 4
  text: |-
      Choose A or B and complete ALL the requirements.
  children:
      - requirement: A
        text: |-
            Visit an amusement park. Then discuss the following with your
            counselor:
        children:
            - requirement: 1
              text: |-
                  The simple machines present in at least two of the rides
            - requirement: 2
              text: |-
                  The forces involved in the motion of any two rides
      - requirement: B
        text: |-
            Visit a playground. Then discuss the following with your counselor:
        children:
            - requirement: 1
              text: |-
                  The simple machines present in the playground equipment
            - requirement: 2
              text: |-
                  The forces involved in the motion of any two playground
                  fixtures
            - note:
                - counselor
              text: |-
                  A force is a push or a pull. Many rides use the force of
                  gravity to cause changes in up and down motion. Rides that go
                  in a circle use centripetal force.
- requirement: 5
  text: |-
      Do the following:
  children:
      - requirement: A
        text: |-
            On your own, design one of the following and include a drawing or
            sketch: an amusement park ride OR a playground fixture OR a method
            of transportation.
      - requirement: B
        text: |-
            Discuss with your counselor:
        children:
            - requirement: 1
              text: |-
                  The simple machines present in your design
            - requirement: 2
              text: |-
                  The energy source powering the motion of your creation
- requirement: 6
  text: |-
      Discuss with your counselor how engineering affects your everyday life.
