- requirement: 1
  markdown: true
  text: |-
      Present evidence that you have cared for a pet for four months. Get approval before you start.`*`

      `*` Work done for other merit badges cannot be used for this requirement.
  workbook:
    - signature: Parent or Other Adult Observer
- requirement: 2
  text: |-
      Write in 200 words or more about the care, feeding, and housing of your pet. Tell some interesting facts about it.  Tell why you have this kind of pet. Give local laws, if any, relating to the pet you keep.
  workbook:
    - lines: 8
- requirement: 3
  text: |-
      Show that you have read a book or pamphlet, approved by your counselor, about your kind of pet. Discuss with your counselor what you have learned from what you read.
  workbook:
    - lines: 8
- requirement: 4
  text: |-
      Do any ONE of the following:
  workbook:
    - header: true
      markdown: true
      text: |-
            a. Show your pet in a pet show.

            b. Start a friend raising a pet like yours. Help your friend get a good start.

            c. Train a pet in three or more tricks or special abilities.
    - lines: 8
  children:
      - requirement: a
        text: |-
            Show your pet in a pet show.
        workbookHide: true
      - requirement: b
        text: |-
            Start a friend raising a pet like yours. Help your friend get a good start.
        workbookHide: true
      - requirement: c
        text: |-
            Train a pet in three or more tricks or special abilities.
        workbookHide: true
