- requirement: 1
  text: |-
    Describe the safety precautions you must exercise when using, building,
    altering, or repairing electronic devices.
- requirement: 2
  text: |-
    Do the following:
  children:
    - requirement: a
      text: |-
        Draw a simple schematic diagram. It must show resistors,
        capacitors, and transistors or integrated circuits. Use the correct
        symbols. Label all parts.
    - requirement: b
      text: |-
        Tell the purpose of each part.
- requirement: 3
  text: |-
    Do the following:
  children:
    - requirement: a
      text: |-
        Show the right way to solder and desolder.
    - requirement: b
      text: |-
        Show how to avoid heat damage to electronic components.
    - requirement: c
      text: |-
        Tell about the function of a printed circuit board.  Tell what
        precautions should be observed when soldering printed circuit
        boards.
- requirement: 4
  text: |-
    Do the following:
  children:
    - requirement: a
      text: |-
        Discuss each of the following with your merit badge counselor:
      children:
        - requirement: i
          text: |-
            How to use electronics for a control purpose
        - requirement: ii
          text: |-
            The basic principles of digital techniques
        - requirement: iii
          text: |-
            How to use electronics for three different audio applications
    - requirement: b
      text: |-
        Show how to change three decimal numbers into binary numbers and
        three binary numbers into decimal numbers.
    - requirement: c
      text: |-
        Choose ONE of the following three projects. For your project, find
        or create a schematic diagram. To the best of your ability, explain
        to your counselor how the circuit you built operates.
      children:
        - requirement: i
          text: |-
            A control device
        - requirement: ii
          text: |-
            A digital circuit
        - requirement: iii
          text: |-
            An audio circuit
- requirement: 5
  text: |-
    Do the following:
  children:
    - requirement: a
      text: |-
        Show how to solve a simple problem involving current, voltage, and
        resistance using Ohm’s law.
    - requirement: b
      text: |-
        Tell about the need for and the use of test equipment in
        electronics. Name three types of test equipment.  Tell how they
        operate.
    - requirement: c
      text: |-
        Demonstrate to your counselor how to read the colored bands of a
        resistor to determine its resistance value.
- requirement: 6
  text: |-
    Find out about three career opportunities in electronics that interest
    you. Discuss with and explain to your counselor what training and
    education are needed for each position.
