- requirement: 1
  text: |-
      Be active in your troop for at least six months as a Star Scout.
- requirement: 2
  text: |-
      As a Star Scout, demonstrate Scout spirit by living the Scout Oath and
      Scout Law. Tell how you have done your duty to God and how you have lived
      the Scout Oath and Scout Law in your everyday life.
- requirement: 3
  text: |-
      Earn five more merit badges (so that you have 11 in all), including any
      three additional badges from the required list for Eagle. You may choose
      any of the 18 merit badges on the required list for Eagle to fulfill this
      requirement.  See Eagle rank requirement 3 for this list.
- requirement: 4
  text: |-
      While a Star Scout, participate in six hours of service through one or
      more service projects approved by your Scoutmaster. At least three hours
      of this service must be conservation-related.
- requirement: 5
  markdown: true
  text: |-
      While a Star Scout, serve actively in your troop for six months in one or
      more of the following troop positions of responsibility (or carry out a
      Scoutmaster-approved leadership project to help the troop).

      **Scout troop.** Patrol leader, assistant senior patrol leader, senior
      patrol leader, troop guide, Order of the Arrow troop representative, den
      chief, scribe, librarian, historian, quartermaster, bugler, junior
      assistant Scoutmaster, chaplain aide, instructor, webmaster, or outdoor
      ethics guide.`*`

      **Venturing crew/Sea Scout ship.** President, vice president, secretary,
      treasurer, den chief, quartermaster, historian, guide, boatswain,
      boatswain’s mate, yeoman, purser, storekeeper, chaplain aide, outdoor
      ethics guide, crew leader, media specialist, specialist or webmaster.

      **Lone Scout.** Leadership responsibility in your school, religious
      organization, club, or elsewhere in your community.

      `*` Assistant patrol leader is not an approved position of responsibility
      for the Star, Life, or Eagle rank.
- requirement: 6
  markdown: true
  text: |-
      While a Star Scout, use the Teaching EDGE method to teach another Scout
      (preferably younger than you) the skills from ONE of the following
      choices, so that the Scout is prepared to pass those requirements to
      their Scoutmaster’s satisfaction.

      a. Tenderfoot 4a and 4b (first aid)<br/>
      b. Second Class 2b, 2c, and 2d (cooking/tools)<br/>
      c. Second Class 3a and 3d (navigation)<br/>
      d. First Class 3a, 3b, 3c, and 3d (tools)<br/>
      e. First Class 4a and 4b (navigation)<br/>
      f. Second Class 6a and 6b (first aid)<br/>
      g. First Class 7a and 7b (first aid)<br/>
      h. Three requirements from one of the required Eagle merit badges, as approved by your Scoutmaster
- requirement: 7
  text: |-
      While a Star Scout, participate in a Scoutmaster conference.
- requirement: 8
  markdown: true
  text: |-
      Successfully complete your board of review for the Life rank.`*`

      `*` If the board of review does not approve the Scout’s advancement, the
      decision may be appealed in accordance with Guide to Advancement topic
      8.0.4.0.
