- requirement: 1
  text: |-
      Safety. Do each of the following:
  children:
      - requirement: a
        text: |-
            Explain to your counselor the most likely hazards you may encounter
            while working with robots and what you should do to anticipate,
            mitigate and prevent, and respond to these hazards. Describe the
            appropriate safety gear and clothing that should be used when
            working with robotics.
        workbook:
            - lines: 3
              text: |-
                  Anticipate hazards
            - lines: 3
              text: |-
                  Mitigate and prevent hazards
            - lines: 3
              text: |-
                  Respond to hazards
        children:
            - note:
                  - inPerson
                  - online
              text: |-
                  Scouts will need to do some research and reading in order to
                  prepare for this requirement component.  It is recommended
                  that Scouts make notes of their findings to help show the
                  counselor their efforts in preparing for the class.  These
                  notes can also serve to help Scouts successfully perform
                  their explanation or discussion elements of this requirement
                  component. It will be very difficult for Scouts who do not
                  come prepared for this requirement component to successfully
                  complete this in the class.
      - requirement: b
        text: |-
            Discuss first aid and prevention for the types of injuries that
            could occur while participating in robotics activities and
            competitions, including cuts, eye injuries, and burns (chemical or
            heat).
        workbook:
            - lines: 3
              text: |-
                  Cuts
            - lines: 3
              text: |-
                  Eye injuries
            - lines: 3
              text: |-
                  Chemical burns
            - lines: 3
              text: |-
                  Heat burnsl
        children:
            - note:
                  - inPerson
                  - online
              text: |-
                  Scouts should review this requirement component and be
                  prepared to discuss, demonstrate, explain, and show, as
                  necessary, their first aid knowledge and proficiency as it
                  applies to this merit badge.
- requirement: 2
  text: |-
      Robotics industry. Discuss the following with your counselor:
  children:
      - requirement: a
        text: |-
            The kinds of things robots can do and how robots are best used
            today.
        workbook:
            - lines: 8
      - requirement: b
        text: |-
            The similarities and differences between remote-control vehicles,
            telerobots, and autonomous robots.
        workbook:
            - lines: 8
      - requirement: c
        text: |-
            Three different methods robots can use to move themselves other
            than wheels or tracks. Describe when it would be appropriate to use
            each method.
        workbook:
            - lines: 8
      - note:
            - inPerson
            - online
        text: |-
            This requirement and its components will be covered in the class
            however it must be noted that preparation by reading the merit
            badge pamphlet is a MUST for this requirement, and still does not
            guarantee completion as Scouts will need to actively participate in
            discussion on these items,  demonstrating their knowledge and
            understanding of the objectives of this requirement.  Having done
            preparation work by thoroughly reading the merit badge pamphlet
            prior to the class will ensure a higher chance of completion of
            this requirement for Scouts.  Written notes in your Scoutmaster
            Bucky Robotics Merit Badge Workbook can greatly increase the
            likelihood of completing this requirement and its components.
- requirement: 3
  text: |-
      General knowledge. Discuss with your counselor three of the five major
      fields of robotics (human-robot interface, mobility, manipulation,
      programming, sensors) and their importance to robotics development.
      Discuss either the three fields as they relate to a single robot system
      OR talk about each field in general. Find pictures or at least one video
      to aid your discussion.
  workbook:
      - lines: 8
  children:
      - note:
            - inPerson
            - online
        text: |-
            Scouts must do some preparation work prior to the class to even
            have a chance of completing this requirement. (Notes are highly
            recommended to help assist Scouts with their discussion points).
            Scouts will not automatically be signed off on this requirement
            just for attending as the requirement states that they must discuss
            a number of items and will be required to partake in group and/or
            individual discussion to obtain credit. Additionally, note that the
            requirement states that Scouts must bring items to help aid their
            points in the discussion. Scouts not bringing these items will NOT
            be signed off on this requirement. Be Prepared.
- requirement: 4
  text: |-
      Design, build, program, test. Do each of the following:
  children:
      - requirement: a
        text: |-
            With your counselor’s approval, choose a task for the robot or
            robotic subsystem that you plan to build.  Include sensor feedback
            and programming in the task. Document this information in your
            robot engineering notebook.
        workbook:
            - lines: 8
      - requirement: b
        text: |-
            Design your robot. The robot design should use sensors and
            programming and have at least 2 degrees of freedom.  Document the
            design in your robot engineering notebook using drawings and a
            written description.
        workbook:
            - lines: 8
      - requirement: c
        text: |-
            Build a robot or robotic subsystem of your original design to
            accomplish the task you chose for requirement 4a.
        workbook:
            - lines: 8
      - requirement: d
        text: |-
            Discuss with your counselor the programming options available for
            your robot. Then do either option 1 OR option 2.
        workbook:
            - header: true
              markdown: true
              text: |-
                  1. Option 1. Program your robot to perform the task you chose
                  for your robot in 4a. Include a sample of your program’s
                  source code in your robot engineering notebook.

                  2. Option 2. Prepare a flowchart of the desired steps to
                  program your robot for accomplishing the task in 4a. Include
                  procedures that show activities based on sensor inputs. Place
                  this in your robot engineering notebook.
            - lines: 8
        children:
            - requirement: 1
              text: |-
                  Option 1. Program your robot to perform the task you chose
                  for your robot in 4a. Include a sample of your program’s
                  source code in your robot engineering notebook.
              workbookHide: true
            - requirement: 2
              text: |-
                  Option 2. Prepare a flowchart of the desired steps to program
                  your robot for accomplishing the task in 4a. Include
                  procedures that show activities based on sensor inputs. Place
                  this in your robot engineering notebook.
              workbookHide: true
      - requirement: e
        text: |-
            Test your robot and record the results in your robot engineering
            notebook. Include suggestions on how you could improve your robot,
            as well as pictures or sketches of your finished robot.
        workbook:
            - lines: 8
      - note:
            - inPerson
        text: |-
            Scouts should be prepared by bringing a Robot Engineering Notebook
            on the day of the class.  Scouts having robotic experience may
            choose to do some of these components ahead of time increasing
            their ability to complete and be signed off on all requirements at
            the class. Scouts not having prior robotic experience will have
            time allotted during the class to get an understanding of the
            requirement and make a lot of headway on these items; if they work
            hard and stay focused.
      - note:
            - online
        text: |-
            This requirement must be done prior to the class.  Scouts will find
            it helpful to work with a school robotics coach ahead of time.
            Scouts should be prepared by bringing their completed Robot
            Engineering Notebook on the day of the class.  Scouts not having
            prior robotic experience will not likely be able to complete this
            requirement.
- requirement: 5
  text: |-
      Demonstrate. Do the following:
  children:
      - requirement: a
        text: |-
            Demonstrate for your counselor the robot you built in requirement
            4.
        workbook:
            - lines: 4
      - requirement: b
        text: |-
            Share your robot engineering notebook with your counselor. Talk
            about how well your robot accomplished the task, the improvements
            you would make in your next design, and what you learned about the
            design process.
        workbook:
            - lines: 4
      - note:
            - inPerson
        text: |-
            Some Scouts who have robotic experience and bring their pre-class
            work for requirement 4, may have an opportunity to present their
            robot. If time allows during the class, Scouts will be presenting
            their robotic creations, designs, ideas, and notebooks to the merit
            badge counselor (this may be done one-on-one or as a part of group
            discussions and sharing and is at the discretion of the counselor).
      - note:
            - online
        text: |-
            Scouts who have robotic experience and bring their pre-class work
            for requirement 4, will have an opportunity to present their robot.
            Scouts will present their robotic creations, designs, ideas, and
            notebooks to the merit badge counselor.
- requirement: 6
  text: |-
      Competitions. Do ONE of the following.
  workbook:
      - header: true
        markdown: true
        text: |-
            a. Attend a robotics competition and report to your counselor what
            you saw and learned about the competition and how teams are
            organized and managed.

            b. Learn about three youth robotics competitions. Tell your
            counselor about these, including the type of competition, time
            commitment, age of the participants, and how many teams are
            involved.
      - lines: 8
  children:
      - requirement: a
        text: |-
            Attend a robotics competition and report to your counselor what you
            saw and learned about the competition and how teams are organized
            and managed.
      - requirement: b
        text: |-
            Learn about three youth robotics competitions. Tell your counselor
            about these, including the type of competition, time commitment,
            age of the participants, and how many teams are involved.
      - note:
            - inPerson
            - online
        markdown: true
        text: |-
            Scouts should choose one of the options in this requirement to work
            on prior to the class and bring their completed work to the class
            ready to share for completion. The Counselor will facilitate a
            group discussion on both of these options during the class,
            allowing Scouts to share their findings and learn from other
            Scouts. Only Scouts who have done preparation work and are able to
            satisfactorily demonstrate they have completed the items within the
            selected option AND actively participate in the group discussion,
            will be considered for completion of this requirement.  Scouts will
            NOT be able to complete this requirement without some preparation
            work prior to the class.

            During the class Scouts will learn about the First Lego League and
            other Robotic teams and competitions in the local area. If Scouts
            are unable to come to the class prepared, they will leave with
            ideas and resources for easily finishing this requirement on their
            own.
- requirement: 7
  text: |-
      Careers. Name three career opportunities in robotics. Pick one and find
      out the education, training, and experience required for this profession.
      Discuss this with your counselor, and explain why this profession might
      interest you.
  workbook:
      - lines: 8
  children:
      - note:
            - inPerson
            - online
        text: |-
            Scouts should review this requirement and be prepared to discuss.
            It is strongly recommended that Scouts bring any notes or
            supporting documents they may have to help show the counselor that
            they have prepared for discussion of these items.
