- requirement: 1
  text: |-
      Do the following:
  children:
      - requirement: a
        text: |-
            Discuss with your counselor the safety equipment, tools, and
            clothing used while checking or repairing farm equipment. Use this
            equipment, tools, and/or clothing (when needed or called for) in
            meeting the requirements for this merit badge.
        workbook:
            - lines: 8
      - requirement: b
        text: |-
            Draw a plan showing a well-equipped farm shop. Point out the shop’s
            mandatory safety devices and features.
        workbook:
            - area: 30
      - requirement: c
        text: |-
            Find all the universal warning and safety symbols on a piece of
            equipment and explain what they mean.
        workbook:
            - lines: 8
      - requirement: d
        text: |-
            Describe what a safety data sheet (SDS) is and tell why
            it is used. Obtain the SDS for any engine coolant, oil, grease,
            fuel, hydraulic or transmission fluid, or other flammable or
            hazardous materials you use in meeting the requirements for this
            merit badge.
        workbook:
            - lines: 8
            - task: true
              text: |-
                  Obtained material safety data sheet
- requirement: 2
  text: |-
      Explain how power is produced or transferred in a:
  children:
      - requirement: a
        text: |-
            Diesel engine
        workbook:
            - lines: 8
      - requirement: b
        text: |-
            Hydraulic system
        workbook:
            - lines: 8
      - requirement: c
        text: |-
            Transmission or any other power system
        workbook:
            - lines: 8
- requirement: 3
  text: |-
      Do TWO of the following:
  children:
      - requirement: a
        text: |-
            Replace the handle of any tool found on the farm.
        workbook:
            - task: true
      - requirement: b
        text: |-
            Organize a tool rack or a storage system for nails, bolts, nuts,
            and washers.
        workbook:
            - task: true
      - requirement: c
        text: |-
            Using a hand file, properly dress the mushroomed head of a chisel
            or punch.
        workbook:
            - task: true
      - requirement: d
        text: |-
            Using a hand file, correctly dress a screwdriver tip.
        workbook:
            - task: true
- requirement: 4
  text: |-
      Do ONE of the following:
  children:
      - requirement: a
        text: |-
            On an engine-powered machine: Grease all fittings, change the oil
            and oil filter, clean the air filter, clean the radiator fins, and
            replace the fuel filters.
        workbook:
            - task: true
      - requirement: b
        text: |-
            For any engine-powered machine, create a preoperational checklist;
            include checking the engine coolant, engine oil, hydraulic and/or
            transmission fluid, and battery voltage (using a voltmeter). Using
            your checklist, conduct a preoperational check of that machinery or
            equipment.
        workbook:
            - split:
                  - task: true
                    text: |-
                        Create a preoperational checklist
                  - task: true
                    text: |-
                        Conduct a preoperational check
      - requirement: c
        text: |-
            Prepare any farm machine for winter storage.
        workbook:
            - task: true
- requirement: 5
  text: |-
      Visit an implement dealer. Interview the dealer technician or service
      manager for hints on good preventive maintenance. Ask why it is
      important, the costs, and what causes wear or damage. Report what you
      learn.
  workbook:
      - lines: 8
- requirement: 6
  text: |-
      Explain each step in ONE of the following maintenance procedures:
  workbook:
      - header: true
        markdown: true
        text: |-
            a. Tightening hydraulic fittings

            b. Checking the air filter

            c. Cleaning a work piece with a wire-brush wheel
      - lines: 20
  children:
      - requirement: a
        text: |-
            Tightening hydraulic fittings
        workbookHide: true
      - requirement: b
        text: |-
            Checking the air filter
        workbookHide: true
      - requirement: c
        text: |-
            Cleaning a work piece with a wire-brush wheel
        workbookHide: true
- requirement: 7
  text: |-
      Find out about three career opportunities in farm mechanics. Pick one and
      find out the education, training, and experience required for this
      profession. Discuss this with your counselor, and explain why this
      profession might interest you.
  workbook:
      - lines: 8
        text: |-
            Three career opportunities
      - lines: 8
        text: |-
            Education, training, and experience required for one profession
