- requirement: 1
  text: |-
      Obtain a clear and concise statement related to the nature of the
      disability from a qualified health professional.
- requirement: 2
  text: |-
      The unit leader meets with the candidate and the Scout's parent or
      guardian to determine the alternative merit badges to replace those
      impeding the Scout's advancement.
- requirement: 3
  text: |-
      The unit leader, parent or guardian, and the Scout (if possible) prepare
      supporting letters to accompany the application.
- requirement: 4
  text: |-
      The district and council advancement committees, in turn, review the
      proposed alternative merit badges. They may choose to speak with the
      Scout, the Scout's parent or guardian, or unit leader. If the council
      advancement committee approves, then the candidate may start work on the
      approved alternative merit badges.
  children:
      - detail: true
        markdown: true
        text: |-
            **Note: In approving the application, the district and council
            advancement committees must utilize the expertise of a healthcare
            professional involved with youth who have disabilities.**
- requirement: 5
  markdown: true
  text: |-
      Upon completion of the Eagle Scout rank requirements, using the
      alternative merit badges, the candidate appears before a board of review.
      The approved
      [Application for Alternative Eagle Scout Rank Merit Badges](https://filestore.scouting.org/filestore/pdf/512-730.pdf)
      must be attached to the
      [Eagle Scout Rank Application](https://filestore.scouting.org/filestore/pdf/512-728_wb_fillable.pdf).
- requirement: 6
  text: |-
      Following a successful board of review, the council processes both
      applications and forwards them to the National Advancement Program Team.
      Local council action on alternative merit badges does not require
      national approval.
