- requirement: 1
  text: |-
      Tell the history of papermaking. Describe the part paper products play in
      our society and economy.
  workbook:
      - lines: 8
  children:
      - note:
            - inPerson
            - online
        text: |-
            Scouts will find using the Pulp and Paper Merit Badge pamphlet
            helpful, if not easiest, to prepare for this requirement. It is
            highly recommended that Scouts make notes to help prepare
            themselves for discussion during the class on this requirement.  It
            is not acceptable to try and wing-it or fake their way through
            answering this requirement.
- requirement: 2
  text: |-
      Learn about the pulp and paper industry.
  children:
      - requirement: a
        text: |-
            Describe the ways the industry plants, grows, and harvests trees.
        workbook:
            - lines: 8
      - requirement: b
        text: |-
            Explain how the industry manages its forests so that the supply of
            trees keeps pace with the demand.
        workbook:
            - lines: 8
      - requirement: c
        text: |-
            Tell how the industry has incorporated the concepts of sustainable
            forest management (SFM).
        workbook:
            - lines: 8
      - requirement: d
        text: |-
            Describe two ways the papermaking industry has addressed pollution.
        workbook:
            - lines: 8
      - note:
            - inPerson
            - online
        text: |-
            Scouts will find the use of the merit badge pamphlet to be
            extremely helpful in preparing for the components of this
            requirement.  It is strongly recommended that Scouts utilize a
            notebook or merit badge workbook to help organize their findings
            for reference during class discussion (describing, telling, and
            explaining as the requirement states) on this requirement and its
            components.  Active participation in the class discussion is
            necessary for consideration in being signed off on this
            requirement.
- requirement: 3
  text: |-
      Name at least four types of trees that are major sources of papermaking
      fibers.  Then do the following:
  workbook:
    - lines: 8
  children:
      - requirement: a
        text: |-
            Discuss what other uses are made of the trees and the forestland
            owned by the pulp and paper industry.
        workbook:
            - lines: 8
      - requirement: b
        text: |-
            Describe two ways of getting fibers from wood, and explain the
            major differences between them.
        workbook:
            - lines: 8
      - requirement: c
        text: |-
            Tell why some pulps are bleached, and describe the process.
        workbook:
            - lines: 8
      - note:
            - inPerson
            - online
        text: |-
            Scouts will be led in group discussion for this requirement and its
            components during the class by the merit badge counselor.  This
            requirement will NOT be automatic, and the counselor will not
            "feed" the answers to Scouts.  Only Scouts that are prepared and
            show that they have prepared for the requirement AND actively
            participate in the group discussion will be considered for sign off
            on this requirement and its components.  All information necessary
            for completing this requirement and its components can be found in
            the merit badge pamphlet.  Notes are highly recommended for this
            requirement to help show the merit badge counselor that you have
            put some effort into preparing for the class. Be Prepared.
- requirement: 4
  text: |-
      Describe how paper is made. Discuss how paper is recycled. Make a sheet
      of paper by hand.
  workbook:
    - lines: 8
  children:
      - note:
            - inPerson
        text: |-
            Scouts will have an opportunity to describe how paper is made and
            recycled in the class, so a little preparation work ahead of time
            will be necessary for this requirement.  Scouts will make paper in
            the class under the guidance of the merit badge counselor. Scouts
            wishing to try this ahead of time may utilize the instructions
            within the Pulp and Paper Merit Badge pamphlet.  This may help
            provide a better understanding heading into the class of the paper
            making process. Scouts doing this are encouraged to bring their
            home-made paper to class to share with the counselor. Scouts may
            find the counselor has other techniques or a slightly different
            process for making paper.
      - note:
            - online
        text: |-
            Scouts will have an opportunity to describe how paper is made and
            recycled in the class, so a little preparation work ahead of time
            will be necessary for this requirement.  Scouts will need to make
            paper on their own ahead of the class. It is recommended to utilize
            the instructions within the Pulp and Paper Merit Badge pamphlet.
            Scouts doing this should bring their home-made paper to class to
            share with the counselor.
- requirement: 5
  text: |-
      Explain what coated paper is and why it is coated. Describe the major
      uses for different kinds of coated papers. Describe one other way that
      paper is changed by chemical or mechanical means to make new uses
      possible.
  workbook:
    - lines: 8
  children:
      - note:
            - inPerson
            - online
        text: |-
            Scouts will find that utilizing the merit badge pamphlet will help
            them prepare for explanation of this requirement during the class.
            As with most requirements for this merit badge, Scouts not
            preparing ahead of time will find it difficult to complete and be
            signed off without prior class preparation, research, and active
            class discussion and participation.
- requirement: 6
  text: |-
      Make a list of 15 pulp or paper products found in your home. Share
      examples of 10 such products with your counselor.
  workbook:
    - lines: 8
  children:
      - note:
            - inPerson
            - online
        text: |-
            Scouts should come to the class with their list of household paper
            products and be prepared to share some of their findings during the
            class discussion for this requirement. It is not acceptable to
            attend not having prepared for this requirement.  This is a very
            easy requirement to prepare for and should take most Scouts only
            minutes to get ready.  Scouts attending the class not having
            prepared for this requirement will NOT be signed off on the
            requirement.  The requirement does not state to make a list of
            paper products found in other people's homes, but rather your own.
            It is not acceptable to build your list from other Scouts work and
            only Scouts that can show they have made the list from their own
            home findings will be considered for sign off on this requirement.
            Of course, active participation during the class in sharing your
            findings will also be required for consideration of sign off on
            this requirement.
- requirement: 7
  text: |-
      With your parent’s and counselor’s approval, do ONE of the following:
  children:
      - requirement: a
        text: |-
            Visit a pulp mill. Describe how the mill converts wood to cellulose
            fibers.
        workbook:
          - lines: 8
      - requirement: b
        text: |-
            Visit a paper mill and get a sample of the paper made there.
            Describe the processes used for making this paper. Tell how it will
            be used.
        workbook:
          - lines: 8
      - requirement: c
        text: |-
            Visit a container plant or box plant. Describe how the plant’s
            products are made.
        workbook:
          - lines: 8
      - requirement: d
        text: |-
            Visit a recycled paper collection or sorting facility. Describe the
            operations there.
        workbook:
          - lines: 8
      - requirement: e
        text: |-
            Using books, magazines, your local library, the internet (with your
            parent’s permission), and any other suitable research tool, find
            out how paper products are developed. Find out what role research
            and development play in the papermaking industry. Share what you
            learn with your counselor.
        workbook:
          - lines: 8
      - note:
            - inPerson
            - online
        markdown: true
        text: |-
            This requirement will NOT be covered as a part of the class. Scouts
            will have to perform on their own, either prior to or after the
            class, the visit or research in this requirement. Scouts will have
            an opportunity to share their work during the class if they choose
            to bring their preparation work with them.

            In order to get signed off on this requirement at the class, Scouts
            will need to do work ahead of time. It is recommended to bring
            proof of their visit (pictures, admission ticket stub, documents,
            etc. from their visit) to share during the class with the counselor
            and other Scouts.  If 7e is selected, Scouts should be ready to
            share their sources and findings with the class and counselor.
- requirement: 8
  text: |-
      Find out about three career opportunities in the papermaking industry
      that interest you. Pick one and find out the education, training, and
      experience required for this profession. Discuss this with your
      counselor, and explain why this profession might interest you.
  workbook:
    - lines: 8
  children:
      - note:
            - inPerson
            - online
        text: |-
            Scouts should review this requirement and its components and be
            prepared to discuss.  It is strongly recommended that Scouts bring
            any notes or supporting documents they may have to help show the
            counselor that they have prepared for completion of this
            requirement.
