- detail: true
  text: |-
      If meeting any of the requirements for this merit badge is against the
      Scout’s religious convictions, the requirement does not have to be done
      if the Scout’s parents and the proper religious advisors state in writing
      that to do so would be against religious convictions. The Scout’s parents
      must also accept full responsibility for anything that might happen
      because of this exemption.
- requirement: 1
  text: |-
      Do the following:
  children:
      - requirement: a
        text: |-
            Before completing requirements 2 through 9, have your healthcare
            practitioner give you a physical examination, using the Scout
            medical examination form. Explain the following:
        workbook:
            - signature: Healthcare Practitioner
        children:
            - requirement: 1
              text: |-
                  Why physical exams are important
              workbook:
                  - lines: 8
            - requirement: 2
              text: |-
                  Why preventive habits (such as exercising regularly) are
                  important in maintaining good health, and how the use of
                  tobacco products, alcohol, and other harmful substances can
                  negatively affect your personal fitness
              workbook:
                  - lines: 8
            - requirement: 3
              text: |-
                  Diseases that can be prevented and how
              workbook:
                  - lines: 8
            - requirement: 4
              text: |-
                  The seven warning signs of cancer
              workbook:
                  - lines: 8
            - requirement: 5
              text: |-
                  The youth risk factors that affect cardiovascular health in
                  adulthood
              workbook:
                  - lines: 8
      - requirement: b
        text: |-
            Have a dental examination. Get a statement saying that your teeth
            have been checked and cared for. Tell how to care for your teeth.
        workbook:
            - lines: 8
              text: |-
                  Dentist or hygenist notes
            - signature: Dentist or Hygenist
            - lines: 8
              text: |-
                  How to care for your teeth
- requirement: 2
  text: |-
      Explain to your merit badge counselor verbally or in writing what
      personal fitness means to you, including:
  workbook:
      - lines: 8
        text: |-
            What personal fitness means to you
  children:
      - requirement: a
        text: |-
            Reasons for being mentally, physically, socially, and spiritually
            fit
        workbook:
            - lines: 8
      - requirement: b
        text: |-
            What it means to be mentally healthy
        workbook:
            - lines: 8
      - requirement: c
        text: |-
            What it means to be physically healthy
        workbook:
            - lines: 8
      - requirement: d
        text: |-
            What it means to be socially healthy
        workbook:
            - lines: 8
- requirement: 3
  text: |-
      With your counselor, answer and discuss the following questions:
  children:
      - requirement: a
        text: |-
            Are you living in such a way that your risk of preventable diseases
            is minimized?
        workbook:
            - lines: 8
      - requirement: b
        text: |-
            Are you immunized and vaccinated according to the advice of your
            healthcare provider and the direction of your
            parent(s)/guardian(s)?
        workbook:
            - lines: 8
      - requirement: c
        text: |-
            Are you free from habits relating to poor nutrition and the use of
            alcohol, tobacco, drugs, and other practices that could be harmful
            to your health?
        workbook:
            - lines: 8
      - requirement: d
        text: |-
            What are the advantages to getting a full night’s sleep?
        workbook:
            - lines: 8
      - requirement: e
        text: |-
            Define a nutritious, balanced diet and why it is important.
        workbook:
            - lines: 8
      - requirement: f
        text: |-
            Do you participate in a regular exercise program or recreational
            activities?
        workbook:
            - lines: 8
      - requirement: g
        text: |-
            What are you doing to demonstrate your duty to God?
        workbook:
            - lines: 8
      - requirement: h
        text: |-
            Do you spend quality time with your family and friends in social
            and recreational activities?
        workbook:
            - lines: 8
      - requirement: i
        text: |-
            Do you support family activities and efforts to maintain a good
            home life?
        workbook:
            - lines: 8
- requirement: 4
  text: |-
      Explain the following about physical fitness:
  children:
      - requirement: a
        text: |-
            The areas of physical fitness
        workbook:
            - lines: 8
      - requirement: b
        text: |-
            Your weakest and strongest area of physical fitness
        workbook:
            - lines: 8
      - requirement: c
        text: |-
            The need to have a balance in the four areas of physical fitness
        workbook:
            - lines: 8
      - requirement: d
        text: |-
            How a program like ScoutStrong can lead to lifelong healthful
            habits
        workbook:
            - lines: 8
      - requirement: e
        text: |-
            How the areas of personal fitness relate to the Scout Law and Scout
            Oath
        workbook:
            - lines: 8
- requirement: 5
  text: |-
      Explain the following:
  children:
      - requirement: a
        text: |-
            The importance of good nutrition
        workbook:
            - lines: 8
      - requirement: b
        text: |-
            What good nutrition means to you
        workbook:
            - lines: 8
      - requirement: c
        text: |-
            How good nutrition is related to the other components of personal
            fitness
        workbook:
            - lines: 8
      - requirement: d
        text: |-
            How to maintain a healthy weight
        workbook:
            - lines: 8
- requirement: 6
  text: |-
      Before doing requirements 7 and 8, do the following:
  children:
      - requirement: a
        # Italicized 6a's Personal Fitness to match 7.
        text: |-
            Complete the aerobic fitness, flexibility, and muscular strength
            tests, as described in the *Personal Fitness* merit badge pamphlet.
            Record your results and identify those areas where you feel you
            need to improve.
        workbook:
            - lines: 8
      - requirement: b
        text: |-
            Keep track of what you eat and drink for three days. Identify three
            healthy eating goals you want to work on.
        workbook:
            - lines: 8
              text: |-
                  First day
            - lines: 8
              text: |-
                  Second day
            - lines: 8
              text: |-
                  Third day
- requirement: 7
  text: |-
      Outline a comprehensive 12-week physical fitness program using the
      results of your fitness tests. Be sure your program incorporates the
      endurance, intensity, and warm-up guidelines discussed in the *Personal
      Fitness* merit badge pamphlet. Before beginning your exercises, have the
      program approved by your counselor and parents.
  workbook:
      - lines: 8
- requirement: 8
  text: |-
      Complete the physical fitness program you outlined in requirement 7. Keep
      a log of your fitness program activity (how long you exercised; how far
      you ran, swam, or biked; how many exercise repetitions you completed;
      your exercise heart rate; etc.). Keep a log of your weekly healthy eating
      goals. Repeat the aerobic fitness, muscular strength, and flexibility
      tests every four weeks and record your results. After the 12th week,
      repeat all of the required activities in each of the three test
      categories, record your results, and show improvement in each one.
      Discuss how well you met your healthy eating goals over these 12 weeks.
      Discuss the meaning and benefit of your experience, and describe your
      long-term plans regarding your personal fitness.
  workbook:
      - lines: 8
- requirement: 9
  text: |-
      Find out about three career opportunities in personal fitness. Pick one
      and find out the education, training, and experience required for this
      profession.  Discuss what you learned with your counselor, and explain
      why this profession might interest you.
  workbook:
      - lines: 8
