- requirement: 1
  text: |-
      Be active in your troop for at least four months as a First Class Scout.
- requirement: 2
  text: |-
      As a First Class Scout, demonstrate Scout spirit by living the Scout Oath
      and Scout Law. Tell how you have done your duty to God and how you have
      lived the Scout Oath and Scout Law in your everyday life.
- requirement: 3
  text: |-
      Earn six merit badges, including any four from the required list for
      Eagle.  You may choose any of the 18 merit badges on the required list
      for Eagle to fulfill this requirement. See Eagle rank requirement 3 for
      this list.
- requirement: 4
  text: |-
      While a First Class Scout, participate in six hours of service through
      one or more service projects approved by your Scoutmaster.
- requirement: 5
  markdown: true
  text: |-
      While a First Class Scout, serve actively in your troop for four months
      in one or more of the following positions of responsibility (or carry out
      a Scoutmaster-approved leadership project to help the troop):

      **Scout troop.** Patrol leader, assistant senior patrol leader, senior
      patrol leader, troop guide, Order of the Arrow troop representative, den
      chief, scribe, librarian, historian, quartermaster, bugler, junior
      assistant Scoutmaster, chaplain aide, instructor, webmaster, or outdoor
      ethics guide.`*`

      **Venturing crew/Sea Scout ship.** President, vice president, secretary,
      treasurer, den chief, quartermaster, historian, guide, boatswain,
      boatswain’s mate, yeoman, purser, storekeeper, chaplain aide, outdoor
      ethics guide, crew leader, media specialist, specialist or webmaster.

      **Lone Scout.** Leadership responsibility in your school, religious
      organization, club, or elsewhere in your community.

      `*` Assistant patrol leader is not an approved position of responsibility
      for the Star rank.
- requirement: 6
  markdown: true
  text: |-
      With your parent or guardian, earn the Cyber Chip Award for your grade or
      view the Personal Safety Awareness videos (with your parent or guardian’s
      permission).`*`

      `*` If your family does not have internet access at home AND you do not
      have ready internet access at school or another public place or via a
      mobile device, the Cyber Chip portion of this requirement may be waived
      by your Scoutmaster in consultation with your parent or guardian.
- requirement: 7
  text: |-
      While a First Class Scout, participate in a Scoutmaster conference.
- requirement: 8
  markdown: true
  text: |-
      Successfully complete your board of review for the Star rank.`*`

      `*` If the board of review does not approve the Scout’s advancement, the
      decision may be appealed in accordance with Guide to Advancement topic
      8.0.4.0.
