- requirement: 1
  text: |-
    Do the following:
  children:
    - requirement: a
      text: |-
        Explain why BB and pellet air guns must always be treated with the
        same respect as firearms.
    - requirement: b
      text: |-
        Describe how you would react if a friend visiting your home asked
        to see your or your family’s firearm(s).
    - requirement: c
      text: |-
        Explain the need for and use and types of eye and hearing
        protection.
    - requirement: d
      text: |-
        Explain the main points of the laws for owning and using guns in
        your community and state.
    - requirement: e
      text: |-
        Explain how hunting is related to the wise use of renewable
        wildlife resources.
    - requirement: f
      text: |-
        Successfully complete a state hunter education course, or obtain a
        copy of the hunting laws for your state, then do the following.
      children:
        - requirement: 1
          text: |-
            Explain the main points of hunting laws in your state and
            give any special laws on the use of guns and ammunition, and
        - requirement: 2
          text: |-
            List the kinds of wildlife that can be legally hunted in your
            state.
    - requirement: g
      text: |-
        Explain to your counselor the proper hygienic guidelines used in
        shooting.
    - requirement: h
      text: |-
        Identify and explain three shotgun sports. Identify places in your
        community where you could shoot these sports and explain how you
        can join or be a part of shooting sports activities.
    - requirement: i
      text: |-
        Give your counselor a list of sources that you could contact for
        information on firearms and their use.
- requirement: 2
  text: |-
    Do ONE of the following options:
  children:
    - detail: true
      markdown: true
      text: |-
        **OPTION A—SHOTGUN SHOOTING**<br />
        **(Modern Shotshell Type)**
    - requirement: a
      text: |-
        Identify the principal parts of a shotgun, action types, and how
        they function.
    - requirement: b
      text: |-
        Identify and demonstrate the rules for safely handling a shotgun.
    - requirement: c
      text: |-
        Identify the parts of a shotgun shell and their functions.
    - requirement: d
      text: |-
        Identify the various gauges of shotguns. Explain which one you
        would pick for use and why.
    - requirement: e
      text: |-
        Identify and explain the fundamentals of safely shooting a shotgun.
        Explain what a misfire, hangfire, and squib fire are, and explain
        the procedures to follow in response to each.
    - requirement: f
      text: |-
        Identify and explain each rule for safely shooting a shotgun.
    - requirement: g
      text: |-
        Demonstrate the knowledge, skills, and attitude necessary to safely
        shoot moving targets, using the fundamentals of shotgun shooting.
    - requirement: h
      text: |-
        Identify the materials needed to clean a shotgun.
    - requirement: i
      text: |-
        Demonstrate how to clean a shotgun properly and safely.
    - requirement: j
      text: |-
        Discuss what points you would consider in selecting a shotgun.
    - requirement: k
      markdown: true
      text: |-
        Shooting score required—Hit at least 12 out of 25 targets (48
        percent) in two 25-target groups. The two groups need not be shot
        in consecutive order. A minimum of 50 shots must be fired. Shooting
        skill rules:

        * Targets may be thrown by a hand trap, manual mechanical trap, or
        on any trap or skeet field. Note: If using a hand trap or manual
        mechanical trap, the trap operator should be at least 5 feet to the
        right and 3 feet to the rear of the shooter. If throwing
        left-handed with a hand trap, the trap operator should be at least
        5 feet to the left and 3 feet to the rear of the shooter.
        * All targets should be thrown at a reasonable speed and in the
        same direction.
        * Targets should be generally thrown so as to climb in the air
        after leaving the trap.
        * Scores may be fired at any time, either in formal competition or
        in practice.
        * Any gauge shotgun not exceeding 12 gauge may be used.
        * Only commercially manufactured ammunition may be used. Reloads
        may not be used in BSA shooting sports programs.
        * Shooters must shoot in rounds of 25. Rounds need not be shot
        continuously or on the same day (the term “round” refers to a
        single series of 25 shots).
        * If using a trap field, shoot station 3 with traps set to throw
        straightaway targets.
        * If using a skeet field, shoot station 7 low house.
    - detail: true
      markdown: true
      text: |-
        **OPTION B—MUZZLELOADING SHOTGUN SHOOTING**
    - requirement: a
      text: |-
        Discuss a brief history of the development of the muzzleloading
        shotgun.
    - requirement: b
      text: |-
        Identify principal parts of percussion and flintlock shotguns and
        discuss how they function.
    - requirement: c
      text: |-
        Demonstrate and explain the rules of safely handling a
        muzzleloading shotgun.
    - requirement: d
      text: |-
        Identify the various grades of black powder and their proper and
        safe use.
    - requirement: e
      text: |-
        Discuss proper safety procedures pertaining to black powder use and
        storage.
    - requirement: f
      text: |-
        Discuss proper components of a load.
    - requirement: g
      text: |-
        Identify proper procedures and accessories used for safely loading
        a muzzleloading shotgun.
    - requirement: h
      text: |-
        Demonstrate the knowledge, skills, and attitude necessary to safely
        shoot a muzzleloading shotgun on a range, including range
        procedures. Explain what a misfire, hangfire, and squibfire are,
        and explain the procedures to follow in response to each.
    - requirement: i
      text: |-
        Shoot a moving target with a muzzleloading shotgun using the five
        fundamentals of firing the shot.
    - requirement: j
      text: |-
        Identify the materials needed to clean a muzzleloading shotgun
        properly and safely.
    - requirement: k
      text: |-
        Demonstrate how to clean to clear a muzzleloading shotgun’s failure
        to fire and explain or demonstrate proper correction procedures.
    - requirement: l
      text: |-
        Identify the causes of a muzzleloading shotgun’s failure to fire
        and explain or demonstrate proper preventive procedures.
    - requirement: m
      text: |-
        Discuss what points you would consider in selecting a muzzleloading
        shotgun.
    - requirement: n
      markdown: true
      text: |-
        Shooting score required—Hit at least 5 out of 15 targets in each of
        two 15-target groups. The two groups need not be shot in
        consecutive order. A minimum of 30 shots must be fired. Shooting
        skill rules:

        * Targets may be thrown by a hand trap, manual mechanical trap, or
        on any trap or skeet field.  Note: If using a hand trap or manual
        mechanical trap, the trap operator should be at least 5 feet to the
        right and 3 feet to the rear of the shooter. If throwing
        left-handed with a hand trap, the trap operator should be at least
        5 feet to the left and 3 feet to the rear of the shooter.
        * All targets should be thrown at a reasonable speed and in the
        same direction.
        * Targets should be generally thrown so as to climb in the air
        after leaving the trap.
        * Scores may be fired at any time, either in formal competition or
        in practice.
        * Any gauge shotgun not exceeding 10 gauge may be used.
        * Standard clay targets customarily used for trap and skeet are to
        be used.
        * On a standard trap field, the shooter should be positioned 8
        yards behind the trap house. The trap should be set to throw only
        straightaway targets.
        * On a skeet field, use station 7 low house.
