- requirement: 1
  text: |-
      List the major truck lines serving your town.
  workbook:
      - lines: 8
- requirement: 2
  text: |-
      Do the following:
  children:
      - requirement: a
        text: |-
            Describe the role of truck transportation within commerce (the
            movement of goods, funds, and information).
        workbook:
            - lines: 8
      - requirement: b
        text: |-
            Describe how trucks fit into a company’s supply chain.  This could
            be a manufacturer, importer, wholesaler, or retailer.
        workbook:
            - lines: 8
      - requirement: c
        text: |-
            On paper, map out how goods that are manufactured overseas are
            transported to a retailer in this country.
        workbook:
            - gridHeight: 8
- requirement: 3
  text: |-
      Describe the difference between the gasoline engine and the diesel engine
      that power trucks. List the advantages of each.
  workbook:
      - lines: 8
- requirement: 4
  text: |-
      Visit a truck terminal and complete items 4a through 4e. After your
      visit, share what you have learned with your counselor.
  children:
      - requirement: a
        text: |-
            Find out what kind of maintenance program the company follows to
            help keep its fleet, drivers, and the roadway safe.
        workbook:
            - lines: 8
      - requirement: b
        text: |-
            Find out how dispatchers maintain communication with drivers on the
            road.
        workbook:
            - lines: 8
      - requirement: c
        text: |-
            Talk with a professional truck driver about safety. Learn about the
            truck driver’s rules of the road for safe driving. List five
            safe-driving rules every professional truck driver must follow.
        workbook:
            - lines: 8
      - requirement: d
        text: |-
            Review the driver’s log and find out what kind of information the
            log contains.
        workbook:
            - lines: 8
      - requirement: e
        text: |-
            Learn about important federal regulations that help ensure public
            safety.
- requirement: 5
  text: |-
      Do the following:
  children:
      - requirement: a
        text: |-
            Outline the general organization of a trucking company.  Describe
            what each department does.
        workbook:
            - lines: 8
      - requirement: b
        text: |-
            List five positions with trucking companies and describe each one.
        workbook:
            - lines: 8
- requirement: 6
  text: |-
      Name five government agencies that work closely with the trucking
      industry. Describe their role.
  workbook:
      - lines: 8
- requirement: 7
  text: |-
      List five different kinds of trucks. Tell the service each provides.
  workbook:
      - lines: 8
- requirement: 8
  text: |-
      Assume that you are going to ship by truck 500 pounds of goods (freight
      class 65) from your town to another town 500 miles away. Your shipment
      must arrive within three days. Explain in writing:
  children:
      - requirement: a
        text: |-
            How to prepare the shipment
        workbook:
            - lines: 8
      - requirement: b
        text: |-
            How to compare at least three carriers for time in transit and
            rates
        workbook:
            - lines: 8
      - requirement: c
        text: |-
            How to choose which carrier to use
        workbook:
            - lines: 8
      - requirement: d
        text: |-
            How to insure the shipment for damages
- requirement: 9
  text: |-
      Define the following terms: bill of lading, ETA, logbook, intermodal,
      containers, tariff, shippers, carrier, consignee, drayage, cartage.
  workbook:
      - lines: 8
- requirement: 10
  text: |-
      Learn about opportunities in the field of truck transportation. Choose
      one career in which you are interested and discuss with your counselor
      the major responsibilities of that position and the qualifications,
      education, and training such a position requires.
  workbook:
      - lines: 8
