- requirement: 1
  text: |-
    Do the following:
  children:
    - requirement: a
      text: |-
        Explain to your counselor the most likely hazards you may encounter
        while participating in camping activities and what you should do to
        anticipate, help prevent, mitigate, and respond to these hazards.
    - requirement: b
      text: |-
        Discuss with your counselor why it is important to be aware of
        weather conditions before and during your camping activities. Tell
        how you can prepare should the weather turn bad during your
        campouts.
    - requirement: c
      text: |-
        Show that you know first aid for and how to prevent injuries or
        illnesses that could occur while camping, including hypothermia,
        frostbite, heat reactions, dehydration, altitude sickness, insect
        stings, tick bites, snakebite, blisters, and hyperventilation.
    - note:
        - inPerson
        - online
      text: |-
        Scouts should review this requirement and its components and be
        prepared to discuss, demonstrate, explain, and show as necessary
        their first aid knowledge and ability as it applies to this
        merit badge.
- requirement: 2
  text: |-
    Learn the Leave No Trace principles and the Outdoor Code and explain what
    they mean. Write a personal and group plan for implementing these
    principles on your next outing.
  children:
    - note:
        - inPerson
        - online
      text: |-
        Scouts are encouraged to work on this requirement prior to
        the class. While time will be allotted in the class to covering the
        principles of Leave No Trace and the Outdoor Code, it will be
        structured more as a review of these principles rather than an
        introduction. Scouts will likely find it easier to prepare their
        personal plan ahead of time (or at least get a start on it). Time
        may be available during the class to refine or finish your personal
        plan, however those Scouts not coming to the class with preparation
        work in the way of at least having started formulating their
        personal plan will find it nearly impossible to finish this
        requirement on the day of the class.
- requirement: 3
  markdown: true
  text: |-
    Make a written plan`*` for an overnight trek and show how to get to your
    camping spot by using a topographical map and one of the following:
  children:
    - requirement: a
      text: |-
        A compass
    - requirement: b
      markdown: true
      text: |-
        A GPS receiver`**`
    - requirement: c
      markdown: true
      text: |-
        A smartphone with a GPS app`*`
    - detail: true
      markdown: true
      text: |-
        `*` To complete this requirement, you may use the Scout Planning
        Worksheet at
        http://troopleader.org/wp-content/uploads/2016/03/512-505_16_Wksht_WEB.pdf.

        `**` If a GPS-equipped device is not available, explain how to use
        one to get to your camping spot.
    - note:
        - inPerson
      text: |-
        This requirement will be covered in the class however Scouts are
        encouraged to read the sections in the merit badge pamphlet that
        relate to this requirement prior to the class.
    - note:
        - online
      text: |-
        While this requirement will be covered in the class, Scouts
        desiring to have the opportunity to complete this requirement will
        need to procure the necessary equipment (a topographical map,
        compass, and compass / GPS device.  Scouts are encouraged to read
        the sections in the merit badge pamphlet that relate to this
        requirement prior to the class.
- requirement: 4
  text: |-
    Do the following:
  children:
    - requirement: a
      text: |-
        Make a duty roster showing how your patrol is organized for an
        actual overnight campout. List assignments for each member.
    - requirement: b
      text: |-
        Help a Scout patrol or a Webelos Scout unit in your area prepare
        for an actual campout, including creating the duty roster, menu
        planning, equipment needs, general planning, and setting up camp.
    - note:
        - inPerson
        - online
      text: |-
        In order to receive credit for this requirement on the day of the
        class it is strongly recommended that Scouts use a Merit Badge
        Workbook to document their work and show sign-off by adults or
        leaders that they have completed components of this requirement.
        Utilizing the workbook will help aid the Counselor in assessing
        your completion of this requirement. Remember that just because YOU
        think you have completed a requirement, ultimately the Counselor
        determines whether you have completed a requirement to their
        satisfaction and interpretation of the requirement. The more
        prepared you are with proof of completion, the more likely you will
        be signed off when meeting with the Counselor.
- requirement: 5
  text: |-
    Do the following:
  children:
    - requirement: a
      text: |-
        Prepare a list of clothing you would need for overnight campouts in
        both warm and cold weather. Explain the term “layering.”
    - requirement: b
      text: |-
        Discuss footwear for different kinds of weather and how the right
        footwear is important for protecting your feet.
    - requirement: c
      text: |-
        Explain the proper care and storage of camping equipment (clothing,
        footwear, bedding).
    - requirement: d
      text: |-
        List the outdoor essentials necessary for any campout, and explain
        why each item is needed.
    - requirement: e
      text: |-
        Present yourself to your Scoutmaster with your pack for inspection.
        Be correctly clothed and equipped for an overnight campout.
    - note:
        - inPerson
        - online
      text: |-
        While most of these components will be discussed and reviewed as
        part of the class, the one component that cannot be completed is
        Requirement 5e. Scouts wishing to be considered for completion of
        this requirement will not only need to actively participate in the
        class when covering this requirement but will also need to bring a
        signed note, signed Scoutmaster Bucky Camping Merit Badge Workbook
        in the 5E section, or some other signed document from the
        Scoutmaster showing that you have completed satisfactorily this 5e
        component of the requirement.
- requirement: 6
  text: |-
    Do the following:
  children:
    - requirement: a
      text: |-
        Describe the features of four types of tents, when and where they
        could be used, and how to care for tents. Working with another
        Scout, pitch a tent.
    - requirement: b
      text: |-
        Discuss the importance of camp sanitation and tell why water
        treatment is essential. Then demonstrate two ways to treat water.
    - requirement: c
      text: |-
        Describe the factors to be considered in deciding where to pitch
        your tent.
    - requirement: d
      text: |-
        Tell the difference between internal- and external-frame packs.
        Discuss the advantages and disadvantages of each.
    - requirement: e
      text: |-
        Discuss the types of sleeping bags and what kind would be suitable
        for different conditions. Explain the proper care of your sleeping
        bag and how to keep it dry. Make a comfortable ground bed.
    - note:
        - inPerson
        - online
      text: |-
        Scouts should have this written out to show the counselor that some
        thought and research has gone into this requirement and Scouts
        should be prepared to discuss, describe, tell, and/or explain their
        findings. Scouts will not automatically be signed off on this
        requirement just for attending as the requirement states that they
        must discuss, describe, tell, and/or explain a number of items and
        will be needed to partake in group and/or individual discussion
        to obtain credit.
- requirement: 7
  text: |-
    Prepare for an overnight campout with your patrol by doing the following:
  children:
    - requirement: a
      text: |-
        Make a checklist of personal and patrol gear that will be needed.
    - requirement: b
      text: |-
        Pack your own gear and your share of the patrol equipment and food
        for proper carrying. Show that your pack is right for quickly
        getting what is needed first, and that it has been assembled
        properly for comfort, weight, balance, size, and neatness.
    - note:
        - inPerson
        - online
      markdown: true
      text: |-
        This requirement will most easily be completed by Scouts who have
        done Patrol/Troop camping in the past and have been a part of the
        planning. Whether the Scout has this camping experience or not, all
        Scouts will need to make the checklist as a part of this
        requirement. It is recommended to use the Scoutmaster Bucky Camping
        Merit Badge Workbook to help with this requirement.

        Scouts wishing to receive credit for this requirement will also
        have to complete requirement 7b which can be done one of
        two ways. A Scoutmaster or other adult leader (with title shown)
        from the troop may provide a note and signature saying that this
        requirement has been fulfilled, or the Scout may bring their
        camping pack with them to class for review. Realizing that
        perishable items may not be right for this, Scouts should
        accommodate for this space when presenting their camping pack. BE
        PREPARED.
- requirement: 8
  text: |-
    Do the following:
  children:
    - requirement: a
      text: |-
        Explain the safety procedures for
      children:
        - requirement: 1
          text: |-
            Using a propane or butane/propane stove
        - requirement: 2
          text: |-
            Using a liquid fuel stove
        - requirement: 3
          text: |-
            Proper storage of extra fuel
    - requirement: b
      text: |-
        Discuss the advantages and disadvantages of different types of
        lightweight cooking stoves.
      children:
        - note:
            - inPerson
            - online
          text: |-
            For components 8a and 8b Scouts should come prepared with
            formulated notes to aid them in the classroom part for
            these two components. Scouts will have to actively
            partake in the discussions and demonstration that are
            presented as a part of the class by sharing their knowledge
            and findings in preparation for the class and this
            requirement.
    - requirement: c
      text: |-
        Prepare a camp menu. Explain how the menu would differ from a menu
        for a backpacking or float trip. Give recipes and make a food list
        for your patrol. Plan two breakfasts, three lunches, and two
        suppers. Discuss how to protect your food against bad weather,
        animals, and contamination.
    - note:
        - inPerson
        - online
      markdown: true
      text: |-
        There are many parts to this requirement component and the Scout will need some
        preparation work in order to complete this component. It is
        recommended to use the Scoutmaster Bucky Camping Merit Badge
        Workbook which has a camp menu planning section, to complete
        the first item of this component. If the Scout's troop has its own
        Camp Menu planning sheet, Scouts should consider using it for
        this part.

        Scouts may consider making notes as to how the menu might differ
        for a backpacking versus a float trip to aid them in their
        explanation they will provide as a part of the class with the
        Counselor.

        Scouts are encouraged to bring 12 copies of their single favorite
        camping recipe (this is so they can exchange and share these with
        the other Scouts in the class) all Scouts should then leave with a
        nice collection of camping recipe items (make sure you credit the
        appropriate recipe maker as well as your troop on the recipe card).
        Scouts can use the section in the Scoutmaster Bucky Camping Merit
        Badge Workbook to document their food list for this recipe. Make
        sure to specify in your food list how many Scouts this food list
        will accommodate for.

        Scouts can once again use the Scoutmaster Bucky Camping Merit
        Badge Workbook to assist with documenting their meal planning.
        Scouts should bring their completed 7 meal plans (two breakfast,
        three lunches, and two suppers) to class for review by the
        Counselor. A small portion of time will be allotted during the
        class for Scouts to work on this requirement so it is strongly
        recommended that any preparation work that can be done will help
        increase the success rate of completion for this part of the
        requirement.

        Finally, Scouts cannot overlook the last part of this requirement component and
        should make notes of their research and findings on food protection
        to use in the class discussion. Active participation is needed in
        this discussion in order to receive full credit for this component
        of the requirement.
    - requirement: d
      text: |-
        While camping in the outdoors, cook at least one breakfast, one
        lunch, and one dinner for your patrol from the meals you have
        planned for requirement 8c. At least one of those meals must be a
        trail meal requiring the use of a lightweight stove.
      children:
        - note:
            - inPerson
            - online
          text: |-
            Scouts will NOT cover this component in the class; however,
            Scouts may choose to obtain a note from their Scoutmaster or
            other adult leader if they have done this on a Troop or
            Patrol camping adventure. The Counselor WILL review this
            requirement component with the Scouts as a part of the class. Please note
            that the note from your Scoutmaster or other adult leader
            does not guarantee completion. Remember that completion of
            any merit badge requirement is at the
            satisfaction and discretion of the merit badge Counselor.
- requirement: 9
  text: |-
    Show experience in camping by doing the following:
  children:
    - requirement: a
      text: |-
        Camp a total of at least 20 nights at designated Scouting
        activities or events. One long-term camping experience of up to six
        consecutive nights may be applied toward this requirement. Sleep
        each night under the sky or in a tent you have pitched. If the camp
        provides a tent that has already been pitched, you need not pitch
        your own tent.
      children:
        - note:
            - inPerson
            - online
          text: |-
            Scouts need to bring either their camping log or a note from
            their Scoutmaster or adult leader confirming their completion
            of this requirement. Only those who can show documentation of
            their camping experience will be considered for sign off on
            this requirement component.
    - requirement: b
      text: |-
        On any of these camping experiences, you must do TWO of the
        following, only with proper preparation and under qualified
        supervision.
      children:
        - requirement: 1
          text: |-
            Hike up a mountain, gaining at least 1,000 vertical feet.
        - requirement: 2
          text: |-
            Backpack, snowshoe, or cross-country ski for at least 4
            miles.
        - requirement: 3
          text: |-
            Take a bike trip of at least 15 miles or at least four hours.
        - requirement: 4
          text: |-
            Take a nonmotorized trip on the water of at least four hours
            or 5 miles.
        - requirement: 5
          text: |-
            Plan and carry out an overnight snow camping experience.
        - requirement: 6
          text: |-
            Rappel down a rappel route of 30 feet or more.
        - note:
            - inPerson
            - online
          text: |-
            This requirement will NOT be completed as a part of this
            class. Scouts are encouraged to bring a note from their
            Scoutmaster or other adult leader telling whether they have
            completed this component of the requirement or not on any
            troop outings for consideration by the counselor for
            completion.
    - requirement: c
      text: |-
        Perform a conservation project approved by the landowner or land
        managing agency. This can be done alone or with others.
      children:
        - note:
            - inPerson
            - online
          text: |-
            Requirement component 9c will NOT be covered in the class. HOWEVER,
            Scouts who can bring documented proof of performing a
            conservation project that was approved by the landowner or
            land managing agency will have an opportunity to share their
            experience with the counselor and potentially be signed off
            If the work meets the satisfaction of the merit badge a
            counselor, (saying you did it is not enough, you need to
            bring proof). Scouts not bringing supporting proof of this
            project will not be considered for sign off on this
            requirement.
- requirement: 10
  text: |-
    Discuss how the things you did to earn this badge have taught you about
    personal health and safety, survival, public health, conservation, and
    good citizenship. In your discussion, tell how Scout spirit and the Scout
    Oath and Scout Law apply to camping and outdoor ethics.
  children:
    - note:
        - inPerson
        - online
      text: |-
        This requirement will be covered as a part of the class and only
        those who have completed all necessary other requirements will have
        the possibility of being signed off on this requirement.
