# Moved footnotes to requirement 3, where they are referenced.
- requirement: 1
  text: |-
    Do the following:
  children:
    - requirement: a
      text: |-
        Explain to your counselor the most likely hazards you may encounter
        while participating in camping activities and what you should do to
        anticipate, help prevent, mitigate, and respond to these hazards.
    - requirement: b
      text: |-
        Discuss with your counselor why it is important to be aware of weather
        conditions before and during your camping activities. Tell how you can
        prepare should the weather turn bad during your campouts.
    - requirement: c
      text: |-
        Show that you know first aid for and how to prevent injuries or
        illnesses that could occur while camping, including hypothermia,
        frostbite, heat reactions, dehydration, altitude sickness, insect
        stings, tick bites, snakebite, blisters, hyperventilation.
- requirement: 2
  text: |-
    Learn the Leave No Trace Seven Principles and the Outdoor Code, and explain
    what they mean. Write a personal and group plan for implementing these
    principles on your next outing.
- requirement: 3
  markdown: true
  text: |-
    Make a written plan`*` for an overnight trek and show how to get to your
    camping spot by using a topographical map and one of the following:
  children:
    - requirement: a
      text: |-
        Compass
    - requirement: b
      markdown: true
      text: |-
        GPS receiver`**`
    - requirement: c
      markdown: true
      text: |-
        Smartphone with a GPS app`**`
    - detail: true
      markdown: true
      text: |-
        `*` To complete this requirement, you may use the <a href="/documents/scout-planning-worksheet.pdf">Scout Planning Worksheet</a>

        `**` If a GPS-equipped device is not available, explain how to use
        one to get to your camping spot.
- requirement: 4
  text: |-
    Do the following:
  children:
    - requirement: a
      text: |-
        Make a duty roster showing how your patrol is organized for an actual
        overnight campout. List assignments for each member.
    - requirement: b
      text: |-
        Help a Scout patrol or a Webelos Scout unit in your area prepare for an
        actual campout, including creating the duty roster, menu planning,
        equipment needs, general planning, and setting up camp.
- requirement: 5
  text: |-
    Do the following:
  children:
    - requirement: a
      text: |-
        Prepare a list of clothing you would need for overnight campouts in
        both warm and cold weather. Explain the term "layering."
    - requirement: b
      text: |-
        Discuss footwear for different kinds of weather and how the right
        footwear is important for protecting your feet.
    - requirement: c
      text: |-
        Explain the proper care and storage of camping equipment (clothing,
        footwear, bedding).
    - requirement: d
      text: |-
        List the outdoor essentials necessary for any campout, and explain why
        each item is needed.
    - requirement: e
      text: |-
        Present yourself to your Scoutmaster with your pack for inspection. Be
        correctly clothed and equipped for an overnight campout.
- requirement: 6
  text: |-
    Do the following:
  children:
    - requirement: a
      text: |-
        Describe the features of four types of tents, when and where they could
        be used, and how to care for tents. Working with another Scout, pitch a
        tent.
    - requirement: b
      text: |-
        Discuss the importance of camp sanitation and tell why water treatment
        is essential. Then demonstrate two ways to treat water.
    - requirement: c
      text: |-
        Describe the factors to be considered in deciding where to pitch your
        tent.
    - requirement: d
      text: |-
        Tell the difference between internal- and external-frame packs.
        Discuss the advantages and disadvantages of each.
    - requirement: e
      text: |-
        Discuss the types of sleeping bags and what kind would be suitable for
        different conditions. Explain the proper care of your sleeping bag and
        how to keep it dry. Make a comfortable ground bed.
- requirement: 7
  text: |-
    Prepare for an overnight campout with your patrol by doing the following:
  children:
    - requirement: a
      text: |-
        Make a checklist of personal and patrol gear that will be needed.
    - requirement: b
      text: |-
        Pack your own gear and your share of the patrol equipment and food for
        proper carrying. Show that your pack is right for quickly getting what
        is needed first, and that it has been assembled properly for comfort,
        weight, balance, size, and neatness.
- requirement: 8
  text: |-
    Do the following:
  children:
    - requirement: a
      text: |-
        Explain the safety procedures for:
      children:
        - requirement: 1
          text: |-
            Using a propane or butane/propane stove
        - requirement: 2
          text: |-
            Using a liquid fuel stove
        - requirement: 3
          text: |-
            Proper storage of extra fuel.
    - requirement: b
      text: |-
        Discuss the advantages and disadvantages of different types of
        lightweight cooking stoves.
    - requirement: c
      text: |-
        Prepare a camp menu. Explain how the menu would differ from a menu for
        a backpacking or float trip. Give recipes and make a food list for your
        patrol. Plan two breakfasts, three lunches, and two suppers. Discuss
        how to protect your food against bad weather, animals, and
        contamination.
    - requirement: d
      text: |-
        While camping in the outdoors, cook at least one breakfast, one lunch,
        and one dinner for your patrol from the meals you have planned for
        requirement 8c. At least one of those meals must be a trail meal
        requiring the use of a lightweight stove.
- requirement: 9
  text: |-
    Show experience in camping by doing the following:
  children:
    - requirement: a
      text: |-
        Camp for at least 20 nights at designated Scouting activities or
        events. One long-term camping experience of up to six consecutive
        nights may be applied toward this requirement. Two nights may be
        counted toward the total for each additional long-term camping trip.
        Each night must be spent either under the sky, in a tent you have
        pitched yourself (if a tent is provided and already set up, you do not
        need to pitch your own), in a hammock that is safely strung outdoors,
        in a lean-to, or other three-sided shelter with an open front. Nights
        spent in indoor lock-in events, cabin camping, hotel stays, or other
        covered accommodations do not count toward the 20 nights.
    - requirement: b
      text: |-
        On any of these camping experiences, you must do TWO of the following,
        only with proper preparation and under qualified supervision.
      children:
        - requirement: 1
          text: |-
            Hike up a mountain, gaining at least 1,000 vertical feet.
        - requirement: 2
          text: |-
            Backpack, snowshoe, or cross-country ski for at least 4 miles.
        - requirement: 3
          text: |-
            Take a bike trip of at least 15 miles or at least four hours.
        - requirement: 4
          text: |-
            Take a nonmotorized trip on the water of at least four hours or 5
            miles.
        - requirement: 5
          text: |-
            Plan and carry out an overnight snow camping experience.
        - requirement: 6
          text: |-
            Rappel down a rappel route of 30 feet or more.
    - requirement: c
      text: |-
        On any of these camping experiences, perform a conservation project
        approved by the landowner or land managing agency. This can be done
        alone or with others.
- requirement: 10
  text: |-
    Discuss how the things you did to earn this badge have taught you about
    personal health and safety, survival, public health, conservation, and good
    citizenship. In your discussion, tell how Scout spirit and the Scout Oath
    and Scout Law apply to camping and outdoor ethics.
