# Requirements are for both Architecture and Landscape Architecture.
# Text extract had a chunk from Law after the requirements.
- requirement: 1
  text: |-
    Go to a completed landscape project that a landscape architect has
    designed.  Before you visit the site, obtain a plan of the design from
    the landscape architect if one is available.
- requirement: 2
  text: |-
    After completing requirement 1, discuss the following with your merit
    badge counselor:
  children:
    - requirement: a
      text: |-
        Tell whether the design had separate spaces, a defined point of
        entry, a clear path system, and sun and shade variety.
    - requirement: b
      text: |-
        Discuss how any structures, the designated seating, eating, or
        parking areas suited the overall design.
    - requirement: c
      text: |-
        Explain how the design reflected consideration for the comfort,
        shelter, and security of the users.
    - requirement: d
      text: |-
        Discuss how the choice of trees, shrubs, and ground covers used in
        the project contributed to its appeal and function.
- requirement: 3
  text: |-
    Identify five shrubs, five trees, and one ground cover, being sure that
    you select examples of different shapes, sizes, and textures. With the
    help of your counselor or a local nursery, choose plants that will grow
    in your area. Bring pictures of the different planting materials or, if
    possible, examples of their branches, leaves, or flowers to a group such
    as your troop or class at school.  Be prepared to tell how you might use
    each in the design of a landscape and the maintenance that would follow.
- requirement: 4
  text: |-
    After obtaining permission from the appropriate authority, look at and
    study a place of worship, school grounds, or a public building and
    identify where most people arrive by bus or car. Then do the following:
  children:
    - requirement: a
      text: |-
        Using a measuring tape, measure and draw the main site entry and
        its nearby area. Define the scale of your drawing. Be sure to
        include the driveway and sidewalk or path that leads to the
        building’s main entry. Indicate any sidewalks, structures, trees
        and plants, lights, drains, utilities, or other site furnishings
        within the study area. Make two copies of this plan and save the
        original, then do 4b and 4c using the copies.
    - requirement: b
      text: |-
        On one copy of your site plan, use directional arrows to indicate
        where the water drains across the site, where ditches occur, and
        where water stands for a longer period of time.
    - requirement: c
      text: |-
        Decide how you can make the place safer and more comfortable for
        those using it. Redesign the area on another copy of the plan. You
        may want to include new walks, covered waiting areas, benches,
        space-defining plantings of trees and shrubs, and drainage
        structures.
- requirement: 5
  text: |-
    Find out about three career opportunities in landscape architecture. Pick
    one and find out the education, training, and experience required for
    this profession. Discuss this with your counselor, and explain why this
    profession might interest you.
