- requirement: 1
  text: |-
      Study and understand the requirements for personal safety when using such
      modelmaker hand tools as knives, handsaws, vises, files, hammers,
      screwdrivers, hand drills and drill bits, pliers, and portable power
      tools, and when to use proper protective equipment such as goggles when
      grinding or drilling.  Know what precautions to take when using flammable
      or hazardous products such as glue, epoxy, paint, and thinners. Discuss
      these with your counselor before you begin your modelmaking project and
      tell why they are important.
  workbook:
      - lines: 8
- requirement: 2
  text: |-
      Explain the uses for each of the following types of models:
      architectural, structural, process, mechanical, and industrial. Do
      research into the different types of materials that could be used in
      making these models.
  workbook:
      - lines: 8
        text: |-
            Architectural
      - lines: 8
        text: |-
            Structural
      - lines: 8
        text: |-
            Process
      - lines: 8
        text: |-
            Mechanical
      - lines: 8
        text: |-
            Industrial
- requirement: 3
  text: |-
      With your counselor’s advice, select a subject from requirement 4 for
      your model project. Kits may not be used. Prepare the necessary plans to
      the proper scale. This model should be your own original work. Tell your
      counselor why you selected this project
  workbook:
      - lines: 8
- requirement: 4
  text: |-
      Do ONE of the following:
  workbook:
      - lines: 8
        text: |-
            Notes for the discussion portion of the requirement
  children:
      - requirement: a
        text: |-
            Make an architectural model. Build a model of a house to a scale of
            1⁄4" = 1'0" (1:50 scale). After completing the model, present it to
            your counselor for approval. Review with your counselor the
            materials you used and the details of your model.
        workbook:
            - task: true
      - requirement: b
        text: |-
            Build a structural model. Construct a model showing corner
            construction of a wood-frame building to a scale of 11⁄2" = 1'0"
            (1:8 scale). All structures shown must be to scale. Cardboard or
            flat sheet wood stock may be used for sheeting or flooring on the
            model. Review with your counselor the problems you encountered in
            gathering the materials and supporting the structure.  Be able to
            name the parts of the floor and wall frames, such as intermediate
            girder, joist, bridging, subfloor, sill, sole plate, stud, and
            rafter.
        workbook:
            - task: true
      - requirement: c
        text: |-
            Make a process model. Build a model showing the plumbing system in
            your house. Show hot and cold water supply, all waste returns, and
            venting to a scale of 3⁄4" = 1'0" (1:15 scale). After completion,
            present the model to your counselor. Discuss the scale, the
            materials used, and any problems you encountered in building the
            model.
        workbook:
            - task: true
      - requirement: d
        text: |-
            Complete a mechanical model. Build a model of a mechanical device
            that uses at least two of the six simple machines. After completing
            the model, present it to your counselor. Be prepared to discuss
            materials used, the machine’s function, and any particular
            difficulty you might have encountered.
        workbook:
            - task: true
      - requirement: e
        text: |-
            Make an industrial model. Build a model of an actual
            passenger-carrying vehicle to a scale of 1" = 1'0" or 1⁄2" = 1'0"
            (1:10 or 1:25 scale). Take the dimensions of the vehicle and record
            the important dimensions. Draw the top, front, rear, and sides of
            the vehicle to scale. From your plans, build a model of the
            vehicle. Discuss with your counselor the most difficult part of
            completing the model.
        workbook:
            - task: true
- requirement: 5
  text: |-
      Build a special-effects model of a fantasy spacecraft or a hand-held prop
      that might appear in a Hollywood science-fiction movie. Determine an
      appropriate scale for your design. Include a cockpit or control area,
      living space, storage unit, engineering spaces, and propulsion systems.
      As you plan and build your model, do the following:
  workbook:
      - task: true
  children:
      - requirement: a
        text: |-
            Study existing designs of vehicles and hand-held devices.
        workbook:
            - task: true
      - requirement: b
        text: |-
            Arrange and assemble the parts.
        workbook:
            - task: true
      - requirement: c
        text: |-
            Sketch your completed model.
        workbook:
            - area: 45
      - requirement: d
        text: |-
            Discuss your design, scale, and materials choices with your
            counselor.  Describe how you engineered your model and discuss any
            difficulties you encountered and what you learned.
        workbook:
            - lines: 8
- requirement: 6
  text: |-
      List at least six occupations in which modelmaking is used and discuss
      with your counselor some career opportunities in this field.
  workbook:
      - lines: 8
