- note:
    - online
    - inPerson
  text: |-
    <b><i><font color="red">Note:</font color><font color="purple"> This
    merit badge requires a lot of explanation and discussion in order to
    complete most requirements.  This class is structured to offer
    explanation and discussion time for Scouts in a small group setting to
    offer both learning and earning opportunity.</font color><font
    color="red"> Scouts MUST come to the class with preparation work in order
    to successfully complete these requirements.</font color><font
    color="purple"> It will be nearly impossible for Scouts who do not have
    preparation work done to successfully partake in the group discussions or
    provide acceptable explanation if they do not have prior knowledge of the
    requirements and answers prior to the class.</font color></i></b>
- requirement: 1
  text: |-
    Do ONE of the following:
  children:
    - requirement: a
      text: |-
        For one day, keep a log in which you describe your communication
        activities. Keep track of the time and different ways you spend
        communicating, such as talking person-to-person, listening to
        teachers, listening to the radio or podcasts, watching television,
        using social media, reading books and other print media, and using
        any electronic communication device. Discuss with your counselor
        what your log reveals about the importance of communication in your
        life. Think of ways to improve your communication skills.
    - requirement: b
      text: |-
        For three days, keep a journal of your listening experiences.
        Identify one example of each of the following, and discuss with
        your counselor when you have listened to:
      children:
        - requirement: 1
          text: |-
            Obtain information
        - requirement: 2
          text: |-
            Be persuaded
        - requirement: 3
          text: |-
            Appreciate or enjoy something
        - requirement: 4
          text: |-
            Understand someone’s feelings
    - requirement: c
      text: |-
        In a small-group setting, meet with other Scouts or with friends.
        Have them share personal stories about significant events in their
        lives that affected them in some way. Take note of how each Scout
        participates in the group discussion and how effectively each Scout
        communicates their story. Report what you have learned to your
        counselor about the differences you observed in effective
        communication.
    - requirement: d
      text: |-
        List as many ways as you can think of to communicate with others
        (face-to-face, by telephone, letter, email, text messages, social
        media, and so on).  For each type of communication, discuss with
        your counselor an instance when that method might not be
        appropriate or effective.
    - note:
        - inPerson
        - online
      text: |-
        This requirement will be covered within the class, however Scouts
        should familiarize themselves with the requirement and the
        corresponding section(s) within the Merit Badge Pamphlet so as to
        have a basic understanding prior to the class. At the discretion of
        the counselor, Scouts will either do requirement 1c or 1d in the
        class.
- requirement: 2
  text: |-
    Do ONE of the following:
  children:
    - requirement: a
      text: |-
        Think of a creative way to describe yourself using, for example, a
        collage, short story or autobiography, drawing or series of
        photographs, or a song or skit.  Using the aid you created, make a
        presentation to your counselor about yourself.
    - requirement: b
      text: |-
        Choose a concept, product, or service in which you have great
        confidence.  Build a sales plan based on its good points. Try to
        persuade the counselor to agree with, use, or buy your concept,
        product, or service. After your sales talk, discuss with your
        counselor how persuasive you were.
    - note:
        - inPerson
        - online
      text: |-
        Scouts should choose and work on prior to the class one of the
        requirement options. Scouts will start off their presenting for the
        day with one of these two presentations. Scouts should come
        prepared to present.
- requirement: 3
  text: |-
    Write a five-minute speech. Give it at a meeting of a group.
  children:
    - note:
        - inPerson
        - online
      text: |-
        While the selected subject for this requirement can be anything,
        please remember it must be Scout appropriate. Scout's may want to
        consider choose a Scouting topic that they have found interesting
        or useful as their subject matter for this requirement. Scouts
        should prepare for presenting this on the day of the class. Scouts
        will spend over 25% of the class presenting and listening to other
        Scouts presentations on this requirement. Be Prepared.
- requirement: 4
  text: |-
    Interview someone you know fairly well, like, or respect because of his
    or her position, talent, career, or life experiences. Listen actively to
    learn as much as you can about the person. Then prepare and deliver to
    your counselor an introduction of the person as though this person were
    to be a guest speaker, and include reasons why the audience would want to
    hear this person speak.  Show how you would call to invite this person to
    speak.
  children:
    - note:
        - inPerson
        - online
      text: |-
        Scouts should prepare for this by interviewing an individual
        (preferably someone other than a family member, if possible) and be
        prepared to share their work in the class. Make sure you come
        prepared with your presentation for how you would introduce this
        person, and how you would communicate with them to invite them to
        speak. Just saying I would call them or email them is not enough,
        the objective here is to present how you would ask them to speak at
        an event or to your group.
- requirement: 5
  text: |-
    Attend a public meeting (city council, school board, debate) approved by
    your counselor where several points of view are given on a single issue.
    Practice active listening skills and take careful notes of each point of
    view. Prepare an objective report that includes all points of view that
    were expressed, and share this with your counselor.
  children:
    - note:
        - inPerson
        - online
      text: |-
        Scouts will need to do 1/2 of this requirement prior to the class.
        Scouts will need to choose a public meeting to attend and practice
        listening skills and take good notes to prepare for their
        presentation which will take place during the class. Scouts will be
        given an opportunity to to present their work in the class.
- requirement: 6
  text: |-
    With your counselor’s approval, develop a plan to teach a skill or inform
    someone about something. Prepare teaching aids for your plan. Carry out
    your plan. With your counselor, determine whether the person has learned
    what you intended.
  children:
    - note:
        - inPerson
        - online
      text: |-
        While the selected subject for this requirement can be anything,
        please remember it must be Scout appropriate. Scout's may want to
        consider choose a Scouting skill that they have found interesting
        or useful as their subject matter for this requirement. Scouts
        should prepare for presenting this (with teaching aids -
        presentation size will be to no more than 12 people) on the day of
        the class. Scouts will spend over 25% of the class presenting and
        listening to other Scouts presentations on this requirement. Be
        Prepared.
- requirement: 7
  text: |-
    Do ONE of the following:
  children:
    - requirement: a
      text: |-
        Write to the editor of a magazine or your local newspaper to
        express your opinion or share information on any subject you
        choose. Send your message by fax, email, or regular mail.
    - requirement: b
      markdown: true
      text: |-
        Create a webpage or blog of special interest to you (for instance,
        your troop or crew, a hobby, or a sport). Include at least three
        articles or entries and one photograph or illustration, and one
        link to some other webpage or blog that would be helpful to someone
        who visits the webpage or blog you have created. *It is not
        necessary to post your webpage or blog to the internet, but if you
        decide to do so, you must first share it with your parents and
        counselor and get their permission.*
    - requirement: c
      text: |-
        Use desktop publishing to produce a newsletter, brochure, flier, or
        other printed material for your troop or crew, class at school, or
        other group.  Include at least one article and one photograph or
        illustration.
    - note:
        - inPerson
        - online
      text: |-
        Scouts will need to complete this requirement on their own prior to
        or after the class. Scouts can bring any work completed prior to
        the class with them for the counselor to review for possible sign
        off on this requirement.
- requirement: 8
  text: |-
    Plan a troop or crew court of honor, campfire program, or interfaith
    worship service. Have the patrol leaders’ council approve it, then write
    the script and prepare the program. Serve as master of ceremonies.
  children:
    - note:
        - inPerson
        - online
      text: |-
        This requirement will NOT be covered in the class, however Scouts
        having completed this requirement prior to the class may bring
        their proof for review by the counselor. In order to receive credit
        Scouts must bring a signed sheet (there is one available in the
        Scoutmaster Bucky Communications Merit Badge Workbook) by the
        Troop's Senior Patrol Leader verifying approval of the Scout to
        plan one of the specified Troop activities by the PLC. A signed
        note from the Scoutmaster is not usually acceptable to most
        counselors as the requirement needs to be approved by the PLC which
        headed by the Senior Patrol Leader, not the Scoutmaster. If the
        event has already happened there should also be some sort of
        confirmation showing that the Scouts served as Master of Ceremony
        for the event.
- requirement: 9
  text: |-
    Find out about three career opportunities in communication. Pick one and
    find out the education, training, and experience required for this
    profession.  Discuss this with your counselor, and explain why this
    profession might interest you.
  children:
    - note:
        - inPerson
        - online
      text: |-
        Scouts should review this requirement and its components and be
        prepared to discuss. It is strongly recommended that Scouts bring
        any notes or supporting documents they may have to help show the
        counselor that they have prepared for discussion of these items.
