- requirement: 1
  text: |-
      Do the following:
  children:
      - requirement: a
        text: |-
            Explain to your counselor the hazards you are most likely to
            encounter while welding, and what you should do to anticipate, help
            prevent, mitigate, or lessen these hazards.
        workbook:
            - lines: 3
              text: |-
                  Anticipate hazards
            - lines: 3
              text: |-
                  Prevent hazards
            - lines: 3
              text: |-
                  Mitigate hazards
            - lines: 3
              text: |-
                  Lessen hazards
      - requirement: b
        text: |-
            Show that you know first aid for, and the prevention of, injuries
            or illnesses that could occur while welding, including electrical
            shock, eye injuries, burns, fume inhalation, dizziness, skin
            irritation, and exposure to hazardous chemicals, including filler
            metals and welding gases.
        workbook:
            - lines: 3
              text: |-
                  Electrical shock
            - lines: 3
              text: |-
                  Eye injuries
            - lines: 3
              text: |-
                  Burns
            - lines: 3
              text: |-
                  Fume inhalation
            - lines: 3
              text: |-
                  Dizziness
            - lines: 3
              text: |-
                  Skin irritation
            - lines: 3
              text: |-
                  Exposure to hazardous chemicals
- requirement: 2
  text: |-
      Do the following:
  children:
      - requirement: a
        text: |-
            With your counselor, discuss general safety precautions and Safety
            Data Sheets related to welding. Explain the importance of the SDS.
        workbook:
            - lines: 8
      - requirement: b
        text: |-
            Describe the appropriate safety gear and clothing that must be worn
            when welding. Then, present yourself properly dressed for
            welding—in protective equipment, clothing, and footwear.
        workbook:
            - lines: 8
      - requirement: c
        text: |-
            Explain and demonstrate the proper care and storage of welding
            equipment, tools, and protective clothing and footwear.
        workbook:
            - lines: 8
- requirement: 3
  markdown: true
  text: |-
      Explain the terms *welding*, *electrode*, *slag*, and *oxidation*.
      Describe the welding process, how heat is generated, what kind of filler
      metal is added (if any), and what protects the molten metal from the
      atmosphere.
  workbook:
      - lines: 3
        text: |-
            Welding
      - lines: 3
        text: |-
            Electrode
      - lines: 3
        text: |-
            Slag
      - lines: 3
        text: |-
            Oxidation
      - lines: 3
        text: |-
            Welding process
      - lines: 3
        text: |-
            How heat is generated
      - lines: 3
        text: |-
            Filler metals
      - lines: 3
        text: |-
            Protection from atmosphere
- requirement: 4
  text: |-
      Name the different mechanical and thermal cutting methods.  Choose one
      method and describe how to use the process.  Discuss one advantage and
      one limitation of this process.
  workbook:
      - lines: 8
- requirement: 5
  text: |-
      Do the following:
  children:
      - requirement: a
        text: |-
            Select two welding processes, and make a list of the different
            components of the equipment required for each process. Discuss one
            advantage and one limitation for each process.
        workbook:
            - split:
                  - lines: 3
                    text: |-
                        Components
                  - lines: 3
                    text: |-
                        One advantage, one limitation
            - split:
                  - lines: 3
                    text: |-
                        Components
                  - lines: 3
                    text: |-
                        One advantage, one limitation
      - requirement: b
        text: |-
            Choose one welding process. Set up the process you have chosen,
            including gas regulators, work clamps, cables, filler materials,
            and equipment settings. Have your counselor inspect and approve the
            area for the welding process you have chosen.
        workbook:
            - area: 8
- requirement: 6
  text: |-
      After successfully completing requirements 1 through 5, use the equipment
      you prepared for the welding process in 5b to do the following:
  children:
      - requirement: a
        text:
            Using a metal scribe or soapstone, sketch your initial onto a metal
            plate, and weld a bead on the plate following the pattern of your
            initial.
        workbook:
            - area: 5
      - requirement: b
        text: |-
            Cover a small plate (approximately 3" x 3" x ¼") with weld beads
            side by side.
        workbook:
            - area: 5
      - requirement: c
        text: |-
            Tack two plates together in a square groove butt joint.
        workbook:
            - area: 5
      - requirement: d
        text: |-
            Weld the two plates together from 6c on both sides.
        workbook:
            - area: 5
      - requirement: e
        text: |-
            Tack two plates together in a T joint, have your counselor inspect
            it, then weld a T joint with fillet weld on both sides.
        workbook:
            - area: 5
      - requirement: f
        text: |-
            Tack two plates together in a lap joint, have your counselor
            inspect it, then weld a lap joint with fillet weld on both sides.
        workbook:
            - area: 5
- requirement: 7
  text: |-
      Do the following:
  children:
      - requirement: a
        text: |-
            Find out about three career opportunities in the welding industry.
            Pick one and find out the education, training, and experience
            required for this profession. Discuss this with your counselor, and
            explain why the profession might interest you.
        workbook:
            - lines: 8
      - requirement: b
        text: |-
            Discuss the role of the American Welding Society in the welding
            profession.
        workbook:
            - lines: 8
