- requirement: 1
  markdown: true
  text: |-
      **General Knowledge.** Do the following:
  children:
      - requirement: a
        text: |-
            Define exploration and explain how it differs from adventure
            travel, trekking or hiking, tour-group trips, or recreational
            outdoor adventure trips.
        workbook:
          - lines: 8
            text: |-
              Define exploration
          - lines: 8
            text: |-
              How it differs
      - requirement: b
        text: |-
            Explain how approaches to exploration may differ if it occurs in
            the ocean, in space, in a jungle, or in a science lab in a city.
        workbook:
          - lines: 8
- requirement: 2
  markdown: true
  text: |-
      **History of Exploration.** Discuss with your counselor the history of
      exploration. Select a field of study with a history of exploration to
      illustrate the importance of exploration in the development of that field
      (for example, aerospace, oil industry, paleontology, oceanography, etc.).
  workbook:
    - lines: 20
- requirement: 3
  markdown: true
  text: |-
      **Importance of Exploration.** Explain to your counselor why it is
      important to explore. Discuss the following:
  children:
      - requirement: a
        text: |-
            Why it is important for exploration to have a scientific basis
        workbook:
          - lines: 8
      - requirement: b
        text: |-
            How explorers have aided in our understanding of our world
        workbook:
          - lines: 8
      - requirement: c
        text: |-
            What you think it takes to be an explorer
        workbook:
          - lines: 8
- requirement: 4
  markdown: true
  text: |-
      **Real-Life Exploration.** Do ONE of the following:
  children:
      - requirement: a
        text: |-
            Learn about a living explorer. Create a short report or
            presentation (verbal, written, or multimedia slide presentation) on
            this individual’s objectives and the achievements of one of the
            explorer’s expeditions. Share what you have learned with your
            counselor and unit.
        workbook:
          - task: true
      - requirement: b
        text: |-
            Learn about an actual scientific exploration expedition.  Gather
            information about the mission objectives and the expedition’s most
            interesting or important discoveries.  Share what you have learned
            with your counselor and unit. Tell how the information gained from
            this expedition helped scientists answer important questions.
        workbook:
          - lines: 8
      - requirement: c
        text: |-
            Learn about types of exploration that may take place in a
            laboratory or scientific research facility (medicine, biology,
            chemistry, physics, astronomy, etc.). Explain to your counselor how
            laboratory research and exploration are similar to field research
            and exploration.
        workbook:
          - lines: 8
- requirement: 5
  markdown: true
  text: |-
      **Exploration in Lab and Field.** Do ONE of the following, and share what
      you learn with your counselor:
  children:
      - requirement: a
        text: |-
            With your parent’s permission and counselor’s approval, visit
            either in person or via the internet an exploration sponsoring
            organization (such as The Explorers Club, National Geographic
            Society, Smithsonian Institution, Alpine Club, World Wildlife Fund,
            or similar organization). Find out what type(s) of exploration the
            organization supports.
        workbook:
          - lines: 8
      - requirement: b
        text: |-
            With permission and approval, visit either in person or via the
            internet a science lab, astronomical observatory, medical research
            facility, or similar site. Learn what exploration is done in this
            facility.
        workbook:
          - lines: 8
- detail: true
  text: |-
    As you work on the Exploration merit badge, remember to always use the
    buddy system. Whether you are out in the field or meeting with your merit
    badge counselor, having a buddy will help ensure everyone’s safety.  You
    and your buddy can watch out for each other wherever you may be or whatever
    you may be doing.
- requirement: 6
  markdown: true
  text: |-
      **Expedition Planning.** Discuss with your counselor each of the
      following steps for conducting a successful exploration activity. Explain
      the need for each step.
  children:
      - requirement: a
        text: |-
            Identify the objectives (establish goals).
        workbook:
          - lines: 8
      - requirement: b
        text: |-
            Plan the mission. Create an expedition agenda or schedule. List
            potential documents or permits needed.
        workbook:
          - lines: 8
      - requirement: c
        text: |-
            Budget and plan for adequate financial resources. Estimate costs
            for travel, equipment, accommodations, meals, permits or licenses,
            and other expedition expenses.
        workbook:
          - lines: 8
      - requirement: d
        text: |-
            Determine equipment and supplies required for personal and mission
            needs for the length of the expedition.
        workbook:
          - lines: 8
      - requirement: e
        text: |-
            Determine communication and transportation needs. Plan how to keep
            in contact with your base or the outside world, and determine how
            you will communicate with each other on-site.
        workbook:
          - lines: 8
      - requirement: f
        text: |-
            Establish safety and first aid procedures (including planning for
            medical evacuation). Identify the hazards that explorers could
            encounter on the expedition, and establish procedures to prevent or
            avoid those hazards.
        workbook:
          - lines: 8
      - requirement: g
        text: |-
            Determine team selection. Identify who is essential for the
            expedition to be successful and what skills are required by the
            expedition leader.
        workbook:
          - lines: 8
      - requirement: h
        text: |-
            Establish detailed recordkeeping (documentation) procedures. Plan
            the interpretation and sharing of information at the conclusion of
            the expedition.
        workbook:
          - lines: 8
- requirement: 7
  markdown: true
  text: |-
      **Prepare for an Expedition.** With your parent’s permission and
      counselor’s approval, prepare for an actual expedition to an area you
      have not previously explored; the place may be nearby or far away. Do the
      following:
  children:
      - requirement: a
        text: |-
            Make your preparations under the supervision of a trained
            expedition leader, expedition planner, or other qualified adult
            experienced in exploration (such as a school science teacher,
            museum representative, or qualified instructor).
        workbook:
          - lines: 8
      - requirement: b
        text: |-
            Use the steps listed in requirement 6 to guide your preparations.
            List the items of equipment and supplies you will need. Discuss
            with your counselor why you chose each item and how it will be of
            value on the expedition. Determine who should go on the expedition.
        workbook:
          - lines: 8
      - requirement: c
        text: |-
            Conduct a pre-expedition check, covering the steps in requirement
            6, and share the results with your counselor.  With your counselor,
            walk through the Sweet Sixteen of BSA Safety for your expedition.
            Ensure that all foreseeable hazards for your expedition are
            adequately addressed.
        workbook:
          - lines: 8
- detail: true
  markdown: true
  text: |-
        Expeditions are widely variable. You do not have to climb Mount Everest
        or go to a jungle to be an explorer. For this merit badge, an
        expedition should be viewed like a field trip or science project. While
        you cannot just hike some place and call it an expedition, you can hike
        to a location and study an aspect that interests you.

        The major difference between an expedition and a field science trip is
        that you (with your counselor’s guidance) have to plan everything. You
        have to formulate objectives and plan an agenda. As needed, you will
        need to do things like confirm transportation, arrange communication,
        plan for food and medical supplies, acquire all food and other
        supplies, construct safety and possible evacuation procedures, manage
        any adverse events, and prepare a report after the expedition.

        Evaluating the effects of a storm on the local forest or nature
        preserve, the effects of a drought on a field used by birds and
        mammals, changes in butterfly populations due to loss of wildflower
        habitat, incursions by invasive plant or animal species, insect
        diversity, and presence or absence of amphibians or fish are just some
        of the examples that can be studied and reported. Your imagination is
        your only limitation.
- requirement: 8
  markdown: true
  text: |-
      **Go on an Expedition.** Complete the following:
  children:
      - requirement: a
        text: |-
            With your parent’s permission and under the supervision of your
            merit badge counselor or a counselor-approved qualified person, use
            the planning steps you learned in requirement 6 and the
            preparations you completed in requirement 7 to personally undertake
            an actual expedition to an area you have not previously explored.
        workbook:
          - task: true
      - requirement: b
        text: |-
            Discuss with your counselor what is outdoor ethics and its role in
            exploration and enjoying the outdoors responsibly.
        workbook:
          - lines: 8
      - requirement: c
        text: |-
            After you return, compile a report on the results of your
            expedition and how you accomplished your objective(s).  Include a
            statement of the objectives, note your findings and observations,
            include photos, note any discoveries, report any problems or
            adverse events, and have a conclusion (whether you reached your
            objective or not).  The post-expedition report must be at least one
            page and no more than three; one page can be photos, graphs, or
            figures.
        workbook:
          - task: true
- requirement: 9
  markdown: true
  text: |-
      **Career Opportunities.** Identify three career opportunities in
      exploration. Pick one and explain to your counselor how to prepare for
      such a career. Discuss what education and training are required, and why
      this profession might interest you.
  workbook:
    - lines: 8
      text: |-
        Three career opportunities
    - lines: 8
      text: |-
        How to prepare for one career, including education and training
