- requirement: 1
  text: |-
      Tell the purpose of space exploration and include the following:
  workbook:
      - lines: 4
        text: |-
            Purpose
  children:
      - requirement: a
        text: |-
            Historical reasons
        workbook:
            - lines: 4
      - requirement: b
        text: |-
            Immediate goals in terms of specific knowledge
        workbook:
            - lines: 4
      - requirement: c
        text: |-
            Benefits related to Earth resources, technology, and new products
        workbook:
            - lines: 4
      - requirement: d
        text: |-
            International relations and cooperation
        workbook:
            - lines: 4
- requirement: 2
  text: |-
      Design a collector’s card, with a picture on the front and information on
      the back, about your favorite space pioneer. Share your card and discuss
      four other space pioneers with your counselor.
  workbook:
      - split:
            - area: 10
              text: |-
                  Front
            - area: 10
              text: |-
                  Back
- requirement: 3
  markdown: true
  text: |-
      Build, launch, and recover a model rocket.`*` Make a second launch to
      accomplish a specific objective. (Rocket must be built to meet the safety
      code of the National Association of Rocketry. See the “Model Rocketry”
      chapter of the *Space Exploration* merit badge pamphlet.) Identify and
      explain the following rocket parts.

      `*` If local laws prohibit launching model rockets, do the following
      activity: Make a model of a NASA rocket. Explain the functions of the
      parts.  Give the history of the rocket.
  workbook:
      - lines: 8
        text: |-
            Notes about objective and launches
  children:
      - requirement: a
        text: |-
            Body tube
        workbook:
            - lines: 4
      - requirement: b
        text: |-
            Engine mount
        workbook:
            - lines: 4
      - requirement: c
        text: |-
            Fins
        workbook:
            - lines: 4
      - requirement: d
        text: |-
            Igniter
        workbook:
            - lines: 4
      - requirement: e
        text: |-
            Launch lug
        workbook:
            - lines: 4
      - requirement: f
        text: |-
            Nose cone
        workbook:
            - lines: 4
      - requirement: g
        text: |-
            Payload
        workbook:
            - lines: 4
      - requirement: h
        text: |-
            Recovery system
        workbook:
            - lines: 4
      - requirement: i
        text: |-
            Rocket engine
        workbook:
            - lines: 4
- requirement: 4
  text: |-
      Discuss and demonstrate each of the following:
  children:
      - requirement: a
        text: |-
            The law of action-reaction
        workbook:
            - lines: 8
      - requirement: b
        text: |-
            How rocket engines work
        workbook:
            - lines: 8
      - requirement: c
        text: |-
            How satellites stay in orbit
        workbook:
            - lines: 8
      - requirement: d
        text: |-
            How satellite pictures of Earth and pictures of other planets are
            made and transmitted
        workbook:
            - lines: 8
- requirement: 5
  text: |-
      Do TWO of the following:
  children:
      - requirement: a
        text: |-
            Discuss with your counselor a robotic space exploration mission and
            a historic crewed mission. Tell about each mission’s major
            discoveries, its importance, and what was learned from it about the
            planets, moons, or regions of space explored.
        workbook:
            - lines: 8
      - requirement: b
        text: |-
            Using magazine photographs, news clippings, and electronic articles
            (such as from the internet), make a scrapbook about a current
            planetary mission.
        workbook:
            - lines: 8
      - requirement: c
        text: |-
            Design a robotic mission to another planet, moon, comet, or
            asteroid that will return samples of its surface to Earth. Name the
            planet, moon, comet, or asteroid your spacecraft will visit. Show
            how your design will cope with the conditions of the environments
            of the planet, moon, comet, or asteroid.
        workbook:
            - lines: 8
- requirement: 6
  text: |-
      Describe the purpose, operation, and components of ONE of the following:
  workbook:
      - header: true
        markdown: true
        text: |-
            Space shuttle or any other crewed orbital vehicle, whether
            government-owned (U.S. or foreign) or commercial

            OR

            International Space Station
  children:
      - requirement: a
        text: |-
            Space shuttle or any other crewed orbital vehicle, whether
            government-owned (U.S. or foreign) or commercial
        workbookHide: true
      - requirement: b
        text: |-
            International Space Station
        workbookHide: true
- requirement: 7
  text: |-
      Design an inhabited base located within our solar system, such as Titan,
      asteroids, or other locations that humans might want to explore in
      person.  Make drawings or a model of your base. In your design, consider
      and plan for the following:
  workbook:
      - area: 10
        text: Drawings of your base
  children:
      - requirement: a
        text: |-
            Source of energy
        workbook:
            - lines: 4
      - requirement: b
        text: |-
            How it will be constructed
        workbook:
            - lines: 4
      - requirement: c
        text: |-
            Life-support system
        workbook:
            - lines: 4
      - requirement: d
        text: |-
            Purpose and function
        workbook:
            - lines: 4
- requirement: 8
  text: |-
      Discuss with your counselor two possible careers in space exploration
      that interest you. Find out the qualifications, education, and
      preparation required and discuss the major responsibilities of those
      positions.
  workbook:
      - lines: 8
