- requirement: 1
  text: |-
    Do the following:
  children:
    - requirement: a
      text: |-
        Explain to your counselor the most likely hazards you may encounter
        while working with composite materials and what you should do to
        anticipate, mitigate and prevent, and respond to these hazards.
        Describe the appropriate safety gear and clothing that should be
        used when working with composite materials.
    - requirement: b
      text: |-
        Explain the precautions that must be taken when handling, storing,
        and disposing of resins, reinforcements, and other materials used
        in composites. Include in your discussion the importance of health,
        safety, and environmental responsibility and awareness.
    - requirement: c
      text: |-
        Describe what a safety data sheet (SDS) is and tell why
        it is used.
- requirement: 2
  text: |-
    Do the following:
  children:
    - requirement: a
      text: |-
        Explain what composite materials are. Include a brief history of
        composites and how they have developed.
    - requirement: b
      text: |-
        Compare the similarities and differences between composites and
        wood, aluminum, copper, and steel.  Describe the physical,
        electrical, mechanical, corrosive, flammability, cost, and other
        such properties. For each of these raw materials, give one example
        of how it can be shaped and used for a specific application.
- requirement: 3
  text: |-
    Describe how composite materials are made. Then do the following:
  children:
    - requirement: a
      text: |-
        Discuss three different composite reinforcement materials, their
        positive and negative characteristics, and their uses. Obtain the
        SDS for each one and discuss the toxicity, disposal, and
        safe-handling sections for these materials.
    - requirement: b
      text: |-
        Discuss three different resins used in composites, their positive
        and negative characteristics, and their uses. Obtain the SDS for
        each one and discuss the toxicity, disposal, and safe-handling
        sections for these materials. Include thermoset resins and
        thermoplastic resins in your discussion.
    - requirement: c
      text: |-
        For each of the three resins you chose for requirement 3b, think of
        a new application that might be worth developing.
- requirement: 4
  text: |-
    With your parent’s permission and your counselor’s approval, do ONE of
    the following:
  children:
    - requirement: a
      text: |-
        Visit a company that manufactures or repairs products made with
        composites. Discuss what you learn with your counselor.
    - requirement: b
      text: |-
        Find three composites-related websites. Share and discuss what you
        learn with your counselor.
- requirement: 5
  text: |-
    Do the following:
  children:
    - requirement: a
      markdown: true
      text: |-
        Use composite materials to complete two projects, at least one of
        which must come from the *Composite Materials* merit badge
        pamphlet. The second project may come from the pamphlet OR may be
        one you select on your own that has been approved by your counselor
        in advance.
    - requirement: b
      text: |-
        With your counselor’s assistance, find an appropriate site where
        the projects can be safely completed under your counselor’s
        supervision and/or the supervision of an adult approved by your
        counselor who is knowledgeable about composites.
    - requirement: c
      text: |-
        With your counselor, determine how the finished projects will be
        evaluated. Using those guidelines, evaluate the completed projects
        with your counselor.
- requirement: 6
  text: |-
    Find out about three career opportunities in composite materials. Pick
    one and find out the education, training, and experience required for
    this profession. Discuss this with your counselor, and explain why this
    profession might interest you.
