- requirement: 1
  text: |-
      Do the following:
  children:
      - requirement: a
        text: |-
            Explain to your counselor the most likely hazards you may encounter
            while working with composite materials and what you should do to
            anticipate, mitigate and prevent, and respond to these hazards.
            Describe the appropriate safety gear and clothing that should be
            used when working with composite materials.
        workbook:
            - lines: 8
              text: |-
                  Most likely hazards
            - lines: 8
              text: |-
                  Anticipate hazards
            - lines: 8
              text: |-
                  Mitigate and prevent hazards
            - lines: 8
              text: |-
                  Respond to these hazards
            - lines: 8
              text: |-
                  Appropriate safety gear and clothing
        children:
            - note:
                  - inPerson
                  - online
              text: |-
                  Scouts should review this requirement and its component and
                  be prepared to explain and describe as necessary their
                  ability to identify hazards likely to be encountered in when
                  working with composites and on this merit badge as well as
                  proper safety gear and clothing that should be used. Scouts
                  may find it beneficial to make notes to bring to class for
                  reference when completing this part of Requirement 1.
      - requirement: b
        text: |-
            Explain the precautions that must be taken when handling, storing,
            and disposing of resins, reinforcements, and other materials used
            in composites. Include in your discussion the importance of health,
            safety, and environmental responsibility and awareness.
        workbook:
            - lines: 8
              text: |-
                  Precautions that must be taken
            - lines: 8
              text: |-
                  Importance of health, safety, and environmental
                  responsibility and awareness
        children:
            - note:
                  - inPerson
                  - online
              text: |-
                  Scouts should utilize the Composite Materials Merit Badge
                  pamphlet to review and prepare for explanation during the
                  class to the counselor their understanding of precautions
                  that need to take place when working with composites.
      - requirement: c
        text: |-
            Describe what a safety data sheet (SDS) is and tell why
            it is used.
        workbook:
            - lines: 8
        children:
            - note:
                  - inPerson
                  - online
              text: |-
                  Scouts will have an opportunity to share their understanding
                  and findings for this requirement component during the class.
                  It is strongly recommended that Scouts review the merit badge
                  pamphlet to be prepared for completion of this requirement
                  component during the class. Only Scout that have prepared and
                  are able to show competence in understanding the details of
                  this requirement component will be considered for sign of on
                  this component of the requirement.
- requirement: 2
  text: |-
      Do the following:
  children:
      - requirement: a
        text: |-
            Explain what composite materials are. Include a brief history of
            composites and how they have developed.
        workbook:
            - lines: 8
              text: |-
                  What composite materials are
            - lines: 8
              text: |-
                  Brief history of composites and how they have developed
        children:
            - note:
                  - inPerson
                  - online
              text: |-
                  Scouts will want to utilize the Composite Materials Merit
                  Badge pamphlet and other sources to formulate their response
                  to this component. It is recommended that Scouts prepare any
                  notes or other items to bring to class in order to help
                  support their explanation during the class.
      - requirement: b
        text: |-
            Compare the similarities and differences between composites and
            wood, aluminum, copper, and steel.  Describe the physical,
            electrical, mechanical, corrosive, flammability, cost, and other
            such properties. For each of these raw materials, give one example
            of how it can be shaped and used for a specific application.
        workbook:
            - lines: 8
              text: |-
                  Composites and wood - similarities and differences
            - lines: 8
              text: |-
                  Composites and aluminum - similarities and differences
            - lines: 8
              text: |-
                  Composites and copper - similarities and differences
            - lines: 8
              text: |-
                  Composites and steel - similarities and differences
            - header: true
              text: |-
                  How each material can be shaped and used for a specific
                  application
            - lines: 8
              text: |-
                  Composites
            - lines: 8
              text: |-
                  Wood
            - lines: 8
              text: |-
                  Aluminum
            - lines: 8
              text: |-
                  Copper
            - lines: 8
              text: |-
                  Steel
        children:
            - note:
                  - inPerson
                  - online
              text: |-
                  While the counselor will help facilitate the first part of
                  this component of Requirement 2, Scouts will need to be
                  prepared to give examples of how each of the mentioned
                  materials are shaped and their applications. Only Scouts who
                  have shown they have come to the class prepared and
                  knowledgeable on this component will have an opportunity to
                  be signed off.
- requirement: 3
  text: |-
      Describe how composite materials are made. Then do the following:
  workbook:
      - lines: 8
        text: |-
            How composite materials are made
  children:
      - note:
            - inPerson
            - online
        text: |-
            Scouts should be prepared to describe and discuss how composite
            materials are made. The counselor will facilitate this discussion
            during the class.
      - requirement: a
        text: |-
            Discuss three different composite reinforcement materials, their
            positive and negative characteristics, and their uses. Obtain the
            SDS for each one and discuss the toxicity, disposal, and
            safe-handling sections for these materials.
        workbook:
            - lines: 8
              text: |-
                  First composite reinforcement material, its positive and
                  negative characteristics, and its uses
            - task: true
              text: |-
                  Obtained SDS
            - lines: 8
              text: |-
                  Second composite reinforcement material, its positive and
                  negative characteristics, and its uses
            - task: true
              text: |-
                  Obtained SDS
            - lines: 8
              text: |-
                  Third composite reinforcement material, its positive and
                  negative characteristics, and its uses
            - task: true
              text: |-
                  Obtained SDS
        children:
            - note:
                  - inPerson
                  - online
              text: |-
                  Scout will need to bring to class with them the SDS sheets
                  for the materials they chose for this component and be ready
                  to discuss and share their findings.
      - requirement: b
        text: |-
            Discuss three different resins used in composites, their positive
            and negative characteristics, and their uses. Obtain the SDS for
            each one and discuss the toxicity, disposal, and safe-handling
            sections for these materials. Include thermoset resins and
            thermoplastic resins in your discussion.
        workbook:
            - lines: 8
              text: |-
                  First resin used in composities, its positive and negative
                  characteristics, and its uses
            - task: true
              text: |-
                  Obtained SDS
            - lines: 8
              text: |-
                  Second resin used in composities, its positive and negative
                  characteristics, and its uses
            - task: true
              text: |-
                  Obtained SDS
            - lines: 8
              text: |-
                  Third resin used in composities, its positive and negative
                  characteristics, and its uses
            - task: true
              text: |-
                  Obtained SDS
      - requirement: c
        text: |-
            For each of the three resins you chose for requirement 3b, think of
            a new application that might be worth developing.
        workbook:
            - lines: 8
            - lines: 8
            - lines: 8
        children:
            - note:
                  - inPerson
                  - online
              text: |-
                  Scouts will want to be prepared for discussion by reviewing
                  the merit badge pamphlet and other available sources to
                  complete these parts (3b and 3c) of Requirement 3.
- requirement: 4
  text: |-
      With your parent’s permission and your counselor’s approval, do ONE of
      the following:
  children:
      - requirement: a
        text: |-
            Visit a company that manufactures or repairs products made with
            composites. Discuss what you learn with your counselor.
        workbook:
            - lines: 8
      - requirement: b
        text: |-
            Find three composites-related websites. Share and discuss what you
            learn with your counselor.
        workbook:
            - lines: 8
            - lines: 8
            - lines: 8
      - note:
            - inPerson
            - online
        text: |-
            This requirement will NOT be covered in the class, however Scouts
            coming to the class having already completed one of these
            components will have an opportunity to share with the class and
            review with the counselor their accomplishment and findings for
            consideration of sign off on this requirement..
- requirement: 5
  text: |-
      Do the following:
  children:
      - requirement: a
        markdown: true
        text: |-
            Use composite materials to complete two projects, at least one of
            which must come from the *Composite Materials* merit badge
            pamphlet. The second project may come from the pamphlet OR may be
            one you select on your own that has been approved by your counselor
            in advance.
        workbook:
            - split:
                  - task: true
                    text: |-
                        Completed first project
                  - task: true
                    text: |-
                        Completed second project
      - requirement: b
        text: |-
            With your counselor’s assistance, find an appropriate site where
            the projects can be safely completed under your counselor’s
            supervision and/or the supervision of an adult approved by your
            counselor who is knowledgeable about composites.
        workbook:
            - task: true
      - requirement: c
        text: |-
            With your counselor, determine how the finished projects will be
            evaluated. Using those guidelines, evaluate the completed projects
            with your counselor.
        workbook:
            - lines: 8
      - note:
            - inPerson
        text: |-
            While the class is structured to produce two projects, time will be
            the determinant as to whether they both will be completed as well
            as the Scouts attentiveness and ability to work efficiently. Each
            counselor chooses their own projects for each class. Scouts are
            welcomed and encouraged to bring any composite project they may
            have done ahead of time to share with the class and to be evaluated
            by the counselor.

            PLEASE MAKE SURE TO BRING WORK CLOTHES FOR USE WHEN WORKING WITH
            COMPOSITES.
- requirement: 6
  text: |-
      Find out about three career opportunities in composite materials. Pick
      one and find out the education, training, and experience required for
      this profession. Discuss this with your counselor, and explain why this
      profession might interest you.
  workbook:
      - lines: 8
        text: |-
            Three career opportunities in composite materials
      - lines: 8
        text: |-
            Education, training, and experience required for one profession
  children:
      - note:
            - inPerson
            - online
        text: |-
            Scouts should review this requirement and its components and be
            prepared to discuss. It is strongly recommended that Scouts bring
            any notes or supporting documents they may have to help show the
            counselor that they have prepared for completion of this
            requirement.
