- requirement: 1
  text: |-
      Explain how regular exercise contributes to good health and why
      swimming is one of the best forms of exercise.
- requirement: 2
  text: |-
      Tell what precautions and procedures a swimmer and escort must
      follow for distance swimming over open water.
- requirement: 3
  text: |-
      Under the supervision of a currently qualified counselor,
      participate in four hours of training and preparation for distance
      swimming (one hour a day maximum).
- requirement: 4
  text: |-
      Swim one mile over a measured course that has been approved by the
      counselor supervising the swim.
