- detail: true
  markdown: true
  # Updated link: http://www.scouting.org/scoutsource/HealthandSafety.aspx
  # Moved note from between requirements 6 and 7 to here.
  text: |-
      **A Note About Unauthorized and Restricted Activities**

      The BSA’s *Guide to Safe Scouting* states under “Unauthorized and
      Restricted Activities” that flying in aircraft as part of a search and
      rescue mission is an unauthorized activity for youth members. For
      complete information, see https://www.scouting.org/health-and-safety/.
- requirement: 1
  text: |-
      Do the following:
  children:
      - requirement: a
        text: |-
            Explain to your counselor the hazards you are most likely to
            encounter while participating in search and rescue (SAR)
            activities, and what you should do to anticipate, help prevent,
            mitigate, and respond to these hazards.
        workbook:
            - lines: 8
              text: |-
                  Most likely hazards
            - lines: 8
              text: |-
                  Anticipate hazards
            - lines: 8
              text: |-
                  Prevent hazards
            - lines: 8
              text: |-
                  Mitigate hazards
            - lines: 8
              text: |-
                  Respond to hazards
      - requirement: b
        text: |-
            Discuss first aid and prevention for the types of injuries or
            illnesses that could occur while participating in SAR activities,
            including: snakebites, dehydration, shock, environmental
            emergencies such as hypothermia or heatstroke, blisters, and ankle
            and knee sprains.
        workbook:
            - lines: 8
              text: |-
                  Snakebites
            - lines: 8
              text: |-
                  Dehydration
            - lines: 8
              text: |-
                  Shock
            - lines: 8
              text: |-
                  Hypothermia
            - lines: 8
              text: |-
                  Heatstroke
            - lines: 8
              text: |-
                  Blisters
            - lines: 8
              text: |-
                  Ankle and knee sprains
- requirement: 2
  text: |-
      Demonstrate knowledge to stay found and prevent yourself from becoming
      the subject of a SAR mission.
  children:
      - requirement: a
        text: |-
            How does the buddy system help in staying found and safe?
        workbook:
            - lines: 8
      - requirement: b
        text: |-
            How can knowledge of the area and its seasonal weather changes
            affect your plans?
        workbook:
            - lines: 8
      - requirement: c
        text: |-
            Explain how the Ten Essentials are similar to a “ready pack.”
        workbook:
            - lines: 8
- requirement: 3
  text: |-
      Discuss the following with your counselor:
  children:
      - requirement: a
        markdown: true
        text: |-
            The difference between *search* and *rescue*
        workbook:
            - lines: 8
      - requirement: b
        markdown: true
        text: |-
            The difference between *PLS (place last seen)* and *LKP (last known
            point)*
        workbook:
            - lines: 8
      - requirement: c
        text: |-
            The meaning of these terms:
        workbook:
            - lines: 3
              text: |-
                  AFRCC (Air Force Rescue Coordination Center)
            - lines: 3
              text: |-
                  IAP (Incident Action Plan)
            - lines: 3
              text: |-
                  ICS (Incident Command System)
            - lines: 3
              text: |-
                  Evaluating search urgency
            - lines: 3
              text: |-
                  Establishing confinement
            - lines: 3
              text: |-
                  Scent item
            - lines: 3
              text: |-
                  Area air scent dog
            - lines: 3
              text: |-
                  Briefing and debriefing
        children:
            - requirement: 1
              text: |-
                  AFRCC (Air Force Rescue Coordination Center)
              workbookHide: true
            - requirement: 2
              text: |-
                  IAP (Incident Action Plan)
              workbookHide: true
            - requirement: 3
              text: |-
                  ICS (Incident Command System)
              workbookHide: true
            - requirement: 4
              text: |-
                  Evaluating search urgency
              workbookHide: true
            - requirement: 5
              text: |-
                  Establishing confinement
              workbookHide: true
            - requirement: 6
              text: |-
                  Scent item
              workbookHide: true
            - requirement: 7
              text: |-
                  Area air scent dog
              workbookHide: true
            - requirement: 8
              text: |-
                  Briefing and debriefing
              workbookHide: true
- requirement: 4
  text: |-
      Find out who in your area has authority for search and rescue and what
      their responsibilities are. Discuss this with your counselor, and explain
      the official duties of a search and rescue team.
  workbook:
      - lines: 8
- requirement: 5
  markdown: true
  text: |-
      Working with your counselor, become familiar with the Incident Command
      System. You may use any combination of resource materials, such as
      printed or online. With your counselor, discuss the features of the ICS
      and how they compare with Scouting’s patrol method.

      To complete requirement 5, you may need to go online (with your parent’s
      permission). See the resources section for more information.
- requirement: 6
  text: |-
      Identify four types of search and rescue teams and discuss their use or
      role with your counselor. Then do the following:
  workbook:
      - lines: 8
  children:
      - requirement: a
        text: |-
            Interview a member of one of the teams you have identified above,
            and learn how this team contributes to a search and rescue
            operation. Discuss what you learned with your counselor.
        workbook:
            - lines: 8
      - requirement: b
        text: |-
            Describe the process and safety methods of working around at least
            two of the specialized SAR teams you identified above.
        workbook:
            - lines: 8
      - requirement: c
        text: |-
            Explain the differences between wilderness, urban, and water SARs.
        workbook:
            - lines: 8
- requirement: 7
  text: |-
      Discuss the Universal Transverse Mercator (UTM) system, latitude, and
      longitude. Then do the following:
  workbook:
      - lines: 8
  children:
      - requirement: a
        text: |-
            Using a 1:24,000 scale USGS topographic map, show that you can
            identify a location of your choice using UTM coordinates.
        workbook:
            - lines: 8
      - requirement: b
        text: |-
            Using a 1:24,000 scale map, ask your counselor to give you a UTM
            coordinate on the map, then identify that location.
        workbook:
            - lines: 8
      - requirement: c
        text: |-
            Show that you can identify your current location using the UTM
            coordinates on a Global Positioning System (GPS) unit and verify it
            on a 1:24,000 scale map.
        workbook:
            - lines: 8
      - requirement: d
        text: |-
            Determine a hypothetical place last seen, and point out an area on
            your map that could be used for containment using natural or
            human-made boundaries.
        workbook:
            - lines: 8
- requirement: 8
  text: |-
      Choose a hypothetical scenario, either one presented in this merit badge
      pamphlet or one created by your counselor.  Then do the following:
  workbook:
      - lines: 3
        text: |-
            Scenario
  children:
      - requirement: a
        text: |-
            Complete an incident objectives form for this scenario.
        workbook:
            - lines: 8
      - requirement: b
        text: |-
            Complete an Incident Action Plan (IAP) to address this scenario.
        workbook:
            - lines: 8
      - requirement: c
        text: |-
            Discuss with your counselor the behavior of a lost person and how
            that would impact your incident action plan (for example, the
            differences between searching for a young child versus a teen).
        workbook:
            - lines: 8
      - requirement: d
        text: |-
            After completing 8a–8c, discuss the hypothetical scenario with your
            counselor.
        workbook:
            - lines: 8
- requirement: 9
  markdown: true
  text: |-
      Discuss with your counselor the terms *hasty team* and *hasty search*.
      Then do the following:
  workbook:
      - lines: 3
        text: |-
            Hasty team
      - lines: 3
        text: |-
            Hasty search
  children:
      - requirement: a
        text: |-
            Plan and carry out a practice hasty search—either urban or
            wilderness—for your patrol or troop. Include the following elements
            in the search: clue awareness, evidence preservation, tracking the
            subject, and locating the subject using attraction or trail sweep.
        workbook:
            - lines: 8
      - requirement: b
        # The merit badge pamphlet is wrong and incorrectly has "a"
        # requirement: a
        text: |-
            When it’s over, hold a team debriefing to discuss the hasty search.
            Discuss problems encountered, successful and unsuccessful tactics,
            and ideas for improvement.
        workbook:
            - lines: 8
- requirement: 10
  text: |-
      Find out about three career or volunteer opportunities in search and
      rescue. Pick one and find out the education, training, and experience
      required for this professional or volunteer position. Discuss this with
      your counselor, and explain why this position might interest you.
  workbook:
      - lines: 8
