- requirement: 1
  markdown: true
  text: |-
      Before starting work on any other requirements for this merit badge,
      write in your own words the meaning of *sustainability*. Explain how you
      think conservation and stewardship of our natural resources relate to
      sustainability. Have a family meeting, and ask family members to write
      down what they think sustainability means. Be sure to take notes. You
      will need this information again for requirement 5.
  workbook:
      - lines: 8
- requirement: 2
  text: |-
      Do the following:
  children:
      - detail: true
        markdown: true
        text: |-
            **Water.** Do A AND either B *OR* C
      - requirement: a
        text: |-
            Develop and implement a plan that attempts to reduce your family’s
            water usage. As a family, discuss water usage. To aid in your
            discussion, if past water bills are available, you may choose to
            examine a few. As a family, choose three ways to help reduce water
            consumption. Implement those ideas for one month. Share what you
            learn with your counselor, and tell how you think your plan
            affected your family’s water usage.
        workbook:
            - lines: 8
      - requirement: b
        text: |-
            Using a diagram you have created, explain to your counselor how
            your household gets its clean water from a natural source and what
            happens with the water after you use it. Include water that goes
            down the kitchen, bathroom, and laundry drains, and any runoff from
            watering the yard or washing the car. Tell two ways to preserve
            your family’s access to clean water in the future.
        workbook:
            - header: true
              markdown: true
              text: |-
                  Select B *OR* C
            - lines: 8
      - requirement: c
        text: |-
            Discuss with your counselor two areas in the world that have been
            affected by drought over the last three years. For each area,
            identify a water conservation practice (successful or unsuccessful)
            that has been used. Tell whether the practice was effective and
            why. Discuss what water conservation practice you would have tried
            and why.
        workbook:
            - header: true
              markdown: true
              text: |-
                  Select B *OR* C
            - lines: 8
      - detail: true
        markdown: true
        text: |-
            **Food.** Do A AND either B *OR* C.
      - requirement: a
        text: |-
            Develop and implement a plan that attempts to reduce your household
            food waste. Establish a baseline and then track and record your
            results for two weeks. Report your results to your family and
            counselor.
        workbook:
            - lines: 8
      - requirement: b
        text: |-
            Discuss with your counselor the ways individuals, families, and
            communities can create their own food sources (potted plants,
            family garden, rooftop garden, neighborhood or community garden).
            Tell how this plan might contribute to a more sustainable way of
            life if practiced globally.
        workbook:
            - header: true
              markdown: true
              text: |-
                  Select B *OR* C
            - lines: 8
      - requirement: c
        text: |-
            Discuss with your counselor factors that limit the availability of
            food and food production in different regions of the world. Tell
            three ways these factors influence the sustainability of worldwide
            food supplies.
        workbook:
            - header: true
              markdown: true
              text: |-
                  Select B *OR* C
            - lines: 8
      - detail: true
        markdown: true
        text: |-
            **Community.** Do A AND either B *OR* C.
      - requirement: a
        text: |-
            Draw a rough sketch depicting how you would design a sustainable
            community. Share your sketch with your counselor, and explain how
            the housing, work locations, shops, schools, and transportation
            systems affect energy, pollution, natural resources, and the
            economy of the community.
        workbook:
            - lines: 8
      - requirement: b
        text: |-
            With your parent’s permission and your counselor’s approval,
            interview a local architect, engineer, contractor, or building
            materials supplier. Find out the factors that are considered when
            using sustainable materials in renovating or building a home. Share
            what you learn with your counselor.
        workbook:
            - header: true
              markdown: true
              text: |-
                  Select B *OR* C
            - lines: 8
      - requirement: c
        text: |-
            Review a current housing needs assessment for your town, city,
            county, or state. Discuss with your counselor how birth and death
            rates affect sufficient housing, and how a lack of housing—or too
            much housing—can influence the sustainability of a local or global
            area.
        workbook:
            - header: true
              markdown: true
              text: |-
                  Select B *OR* C
            - lines: 8
      - detail: true
        markdown: true
        text: |-
            **Energy.** Do A AND either B *OR* C.
      - requirement: a
        text: |-
            Learn about the sustainability of different energy sources,
            including fossil fuels, solar, wind, nuclear, hydropower, and
            geothermal. Find out how the production and consumption of each of
            these energy sources affects the environment and what the term
            “carbon footprint” means. Discuss what you learn with your
            counselor, and explain how you think your family can reduce its
            carbon footprint.
        workbook:
            - lines: 8
      - requirement: b
        text: |-
            Develop and implement a plan to reduce the consumption of one of
            your family’s household utilities that consume energy, such as gas
            appliances, electricity, heating systems, or cooling systems.
            Examine your family’s bills for that utility reflecting usage for
            three months (past or current). As a family, choose three ways to
            help reduce consumption and be a better steward of this resource.
            Implement those ideas for one month. Share what you learn with your
            counselor, and tell how your plan affected your family’s usage.
        workbook:
            - header: true
              markdown: true
              text: |-
                  Select B *OR* C
            - lines: 8
      - requirement: c
        text: |-
            Evaluate your family’s fuel and transportation usage. Review your
            family’s transportation-related bills (gasoline, diesel, electric,
            public transportation, etc.) reflecting usage for three months
            (past or current).  As a family, choose three ways to help reduce
            consumption and be a better steward of this resource. Implement
            those ideas for one month. Share what you learn with your
            counselor, and tell how your plan affected your family’s
            transportation habits.
        workbook:
            - header: true
              markdown: true
              text: |-
                  Select B *OR* C
            - lines: 8
      - detail: true
        markdown: true
        text: |-
            **Stuff.** Do A AND either B *OR* C.
      - requirement: a
        markdown: true
        text: |-
            Keep a log of the “stuff” your family purchases (excluding food
            items) for two weeks. In your log, categorize each purchase as an
            essential *need* (such as soap) or a desirable *want* (such as a
            DVD).  Share what you learn with your counselor.
        workbook:
            - lines: 8
      - requirement: b
        text: |-
            Plan a project that involves the participation of your family to
            identify the “stuff” your family no longer needs. Complete your
            project by donating, repurposing, or recycling these items.
        workbook:
            - header: true
              markdown: true
              text: |-
                  Select B *OR* C
            - lines: 8
      - requirement: c
        text: |-
            Discuss with your counselor how having too much “stuff” affects
            you, your family, and your community. Include the following: the
            financial impact, time spent, maintenance, health, storage, and
            waste. Include in your discussion the practices that can be used to
            avoid accumulating too much “stuff.”
        workbook:
            - header: true
              markdown: true
              text: |-
                  Select B *OR* C
            - lines: 8
- requirement: 3
  text: |-
      Do the following:
  children:
      - requirement: a
        text: |-
            Explain to your counselor how the planetary life-support systems
            (soil, climate, freshwater, atmospheric, nutrient, oceanic,
            ecosystems, and species) support life on Earth and interact with
            one another.
        workbook:
            - lines: 8
      - requirement: b
        text: |-
            Tell how the harvesting or production of raw materials (by
            extraction or recycling), along with distribution of the resulting
            products, consumption, and disposal/repurposing, influences current
            and future sustainability thinking and planning.
        workbook:
            - lines: 8
- requirement: 4
  text: |-
      Explore TWO of the following categories. Have a discussion with your
      family about the two you select. In your discussion, include your
      observations, and best and worst practices. Share what you learn with
      your counselor.
  children:
      - requirement: a
        markdown: true
        text: |-
            **Plastic waste.** Discuss the impact plastic waste has on the
            environment (land, water, air). Learn about the number system for
            plastic recyclables, and determine which plastics are more commonly
            recycled. Find out what the trash vortex is and how it was formed.
        workbook:
            - lines: 8
      - requirement: b
        markdown: true
        text: |-
            **Electronic waste.** Choose three electronic devices in your
            household. Find out the average lifespan of each, what happens to
            these devices once they pass their useful life, and whether they
            can be recycled in whole or part.  Discuss the impact of electronic
            waste on the environment.
        workbook:
            - lines: 8
      - requirement: c
        markdown: true
        text: |-
            **Food waste.** Learn about the value of composting and how to start
            a compost pile. Start a compost pile appropriate for your living
            situation. Tell what can be done with the compost when it is ready
            for use.
        workbook:
            - lines: 8
      - requirement: d
        markdown: true
        text: |-
            **Species decline.** Explain the term species (plant or animal)
            decline.  Discuss the human activities that contribute to species
            decline, what can be done to help reverse the decline, and its
            impact on a sustainable environment.
        workbook:
            - lines: 8
      - requirement: e
        markdown: true
        text: |-
            **World population.** Learn how the world’s population affects the
            sustainability of Earth. Discuss three human activities that may
            contribute to putting Earth at risk, now and in the future.
        workbook:
            - lines: 8
      - requirement: f
        markdown: true
        text: |-
            **Climate change.** Find a world map that shows the pattern of
            temperature change for a period of at least 100 years. Share this
            map with your counselor, and discuss three factors that scientists
            believe affect the global weather and temperature. Discuss with
            your counselor three impacts of climate change and how these
            changes could impact sustainability of food, water, or other
            resources.
        workbook:
            - lines: 8
- requirement: 5
  text: |-
      Do the following:
  children:
      - requirement: a
        text: |-
            After completing requirements 1 through 4, have a family meeting.
            Discuss what your family has learned about what it means to be a
            sustainable citizen. Talk about the behavioral changes and life
            choices your family can make to live more sustainably. Share what
            you learn with your counselor.
        workbook:
            - lines: 8
      - requirement: b
        text: |-
            Discuss with your counselor how living by the Scout Oath and Scout
            Law in your daily life helps promote sustainability and good
            stewardship.
        workbook:
            - lines: 8
- requirement: 6
  text: |-
      Learn about career opportunities in the sustainability field. Pick one
      and find out the education, training, and experience required. Discuss
      what you have learned with your counselor and explain why this career
      might interest you.
  workbook:
      - lines: 8
