- requirement: 1
  text: |-
    Do the following:
  children:
    - requirement: a
      text: |-
        Explain to your counselor the most likely hazards you may encounter
        while participating in rowing activities, including weather- and
        water-related hazards, and what you should do to anticipate, help
        prevent, mitigate, and respond to these hazards.
    - requirement: b
      text: |-
        Review prevention, symptoms, and first-aid treatment for the
        following injuries or illnesses that can occur while rowing:
        blisters, hypothermia, heat-related illnesses, dehydration,
        sunburn, sprains, and strains.
    - requirement: c
      text: |-
        Review the BSA Safety Afloat policy. Explain to your counselor how
        this applies to rowing activities.
- requirement: 2
  text: |-
    Before completing requirements 4, 5, 6, and 7, successfully complete the
    BSA swimmer test.
- requirement: 3
  text: |-
    Review the characteristics of life jackets most appropriate for rowing
    and why one must always be worn while rowing.  Then demonstrate how to
    select and fit a life jacket.
- requirement: 4
  text: |-
    Do ONE of the following:
  children:
    - requirement: a
      text: |-
        Alone or with a passenger, do the following in either a fixed-seat
        or sliding-seat rowboat:
      children:
        - requirement: 1
          text: |-
            Launch.
        - requirement: 2
          text: |-
            Row in a straight line for 100 yards. Stop, pivot, and return
            to the starting point.
        - requirement: 3
          text: |-
            Backwater in a straight line for 25 yards. Make a turn under
            way and return to the starting point.
        - requirement: 4
          text: |-
            Land and moor or rack your craft.
        - requirement: 5
          text: |-
            Tie the following mooring knots—clove hitch, roundturn with
            two half-hitches, bowline, Wellman’s knot, and mooring hitch.
    - requirement: b
      text: |-
        Participate as a rowing team member in a competitive rowing meet.
        The team may be sponsored by a school, club, or Scout unit. The
        meet must include competition between two or more teams with
        different sponsors.  Complete at least 10 hours of team practice
        prior to the meet.
- requirement: 5
  text: |-
    Do ONE of the following:
  children:
    - requirement: a
      markdown: true
      text: |-
        In a fixed-seat rowboat, come alongside a pier and help a passenger
        into the boat. Pull away from the pier, change positions with your
        passenger, and demonstrate sculling over the stern or side. Resume
        your rowing position, return alongside the pier, and help your
        passenger out of the boat.
    - requirement: b
      text: |-
        In a sliding-seat rowboat, come alongside a pier and, with your
        buddy assisting you, get out onto the pier.  Help your buddy into
        the boat. Reverse roles with your buddy and repeat the procedure.
- requirement: 6
  text: |-
    Participate in a swamped boat drill including righting and stabilizing
    the craft, reboarding in deep water, and making headway. Tell why you
    should stay with a swamped boat.
- requirement: 7
  text: |-
    Alone in a rowboat, push off from the shore or a pier.  Row 20 yards to a
    swimmer. While giving instructions to the swimmer, pivot the boat so that
    the swimmer can hold on to the stern. Tow the swimmer to shore.
- requirement: 8
  text: |-
    Describe the following:
  children:
    - requirement: a
      text: |-
        Types of craft used in commercial, competitive, and recreational
        rowing.
    - requirement: b
      text: |-
        Four common boatbuilding materials. Give some positive and negative
        points of each.
    - requirement: c
      text: |-
        Types of oarlocks used in competitive and recreational rowing.
- requirement: 9
  text: |-
    Discuss the following:
  children:
    - requirement: a
      text: |-
        The advantage of feathering oars while rowing
    - requirement: b
      text: |-
        Precautions regarding strong winds and heavy waves, and
        boat-handling procedures in rough water and windstorms
    - requirement: c
      text: |-
        How to properly fit out and maintain a boat in season, and how to
        prepare and store a boat for winter
    - requirement: d
      text: |-
        How to determine the proper length of oars
    - requirement: e
      text: |-
        The differences between fixed-seat and sliding-seat rowing
    - requirement: f
      markdown: true
      text: |-
        The different meanings of the term *sculling* in fixed- and
        sliding-seat rowing
    - requirement: g
      text: |-
        The health benefits from rowing for exercise
