- detail: true
  markdown: true
  text: |-
    <b>Note:</b> The activities used to fulfill the requirements for the Sports
    merit badge may not be used to help fulfill requirements for other merit
    badges.
- detail: true
  text: |-
    *The BSA has prohibited as official Scouting activities intramural,
    interscholastic, or club-sport competitions or activities. However, they
    can be acceptable for your individual participation in an organized school,
    league, or club activity if approved by your counselor.
- requirement: 1
  text: |-
    Do the following:
  children:
    - requirement: a
      text: |-
        Explain to your counselor the most likely risks you may encounter while
        participating in sports and what you should do to anticipate, help
        prevent, mitigate, and respond to these risks.
    - requirement: b
      text: |-
        Show that you know first aid or understand the treatment for injuries
        that could occur while participating in sports, including sprains;
        strains; muscle cramps; contusions; abrasions; blisters; dehydration;
        heat reactions; fractures; injured teeth; head, neck, and back
        injuries; and concussions.
- requirement: 2
  text: |-
    Explain the following:
  children:
    - requirement: a
      text: |-
        The importance of the physical exam
    - requirement: b
      text: |-
        The importance of maintaining good health habits for life (such as
        exercising regularly), and how the use of tobacco products, alcohol,
        and other harmful substances can negatively affect your health and your
        performance in sports activities
    - requirement: c
      text: |-
        The importance of maintaining a healthy diet.
- requirement: 3
  text: |-
    Discuss the following:
  children:
    - requirement: a
      text: |-
        The importance of warming up and cooling down
    - requirement: b
      text: |-
        The importance of weight training
    - requirement: c
      text: |-
        What an amateur athlete is and the differences between an amateur and a
        professional athlete
    - requirement: d
      text: |-
        The attributes (qualities) of a good sport, the importance of
        sportsmanship, and the traits of a good team leader and player who
        exhibits Scout spirit on and off the playing field.
- requirement: 4
  text: |-
    Select TWO of the following sports and discuss with your counselor how you
    will complete the requirements in 5a through 5h for each sport: badminton,
    baseball, basketball, bowling, cross-country, diving, field hockey, flag
    football, flag team, golf, gymnastics, ice hockey, lacrosse, soccer,
    softball, spirit/cheerleading, swimming, tackle football, table tennis,
    tennis, track and field, volleyball, water polo, and/or wrestling. Your
    counselor may approve in advance other recognized sports, but not any sport
    that is prohibited by Scouting America. The sports you choose must include
    regular practice sessions and at least four structured, officiated, scored
    games, meets, or contests against other competitive individuals or
    organized teams during the period of participation.
- requirement: 5
  text: |-
    Do the following:
  children:
    - requirement: a
      text: |-
        With guidance from your counselor, establish a suitable personal
        training program that you will follow throughout your competition
        season (or for three months).
    - requirement: b
      text: |-
        Create a chart or other tracking system, and document your training,
        practice, and development during this time.
    - requirement: c
      text: |-
        Demonstrate proper technique to play each sport effectively and avoid
        injury.
    - requirement: d
      text: |-
        List and describe the equipment needed for each sport, including
        protective equipment and any specialized clothing.
    - requirement: e
      text: |-
        List and explain the rules and proper etiquette of each sport.
    - requirement: f
      text: |-
        Draw and explain a diagram of the playing area for each sport.
    - requirement: g
      text: |-
        Participate in each sport as a competitive individual or as a member of
        an organized team for one season (or for three months).
    - requirement: h
      text: |-
        At the end of the season, share your completed chart with your
        counselor and discuss how your participation in the sports you chose
        has affected you mentally and physically.
- requirement: 6
  text: |-
    Do ONE of the following:
  children:
      - requirement: a
        text: |-
          Identify three career opportunities that would use skills and
          knowledge related to a sport. Pick one and research the training,
          education, certification requirements, experience, and expenses
          associated with entering the field. Research the prospects for
          employment, starting salary, advancement opportunities and career
          goals associated with this career. Discuss what you learned with your
          counselor and whether you might be interested in this career.
      - requirement: b
        text: |-
          Identify how you might use skills and knowledge related to a sport to
          pursue a personal hobby and/or healthy lifestyle. Research the
          additional training required, expenses, and affiliation with
          organizations that would help you maximize the enjoyment and benefit
          you might gain from it. Discuss what you learned with your counselor
          and share what short-term and long-term goals you might have if you
          pursued this.
