- detail: true
  markdown: true
  text: |-
      **Note:** The activities used to fulfill the requirements for the Sports merit badge may not be used to help fulfill requirements for other merit badges.
- requirement: 1
  text: |-
      Do the following:
  children:
      - requirement: a
        text: |-
            Explain to your counselor the most likely risks you may encounter during athletics activities and what you should do to anticipate, help prevent, mitigate, and respond to these risks.
        workbook:
            - lines: 3
              text: |-
                  Anticipate risks
            - lines: 3
              text: |-
                  Prevent risks
            - lines: 3
              text: |-
                  Mitigate risks
            - lines: 3
              text: |-
                  Respond to risks
      - requirement: b
        text: |-
            Show that you know first aid or understand the treatment for injuries that could occur while participating in athletics, including sprains, strains, muscle cramps, contusions, abrasions, blisters, dehydration, heat reactions, and concussions.
        workbook:
            - lines: 3
              text: |-
                Sprains, strains
            - lines: 3
              text: |-
                Muscle cramps
            - lines: 3
              text: |-
                Contusions, abrasions
            - lines: 3
              text: |-
                Blisters
            - lines: 3
              text: |-
                Dehydration
            - lines: 3
              text: |-
                Heat reactions
            - lines: 3
              text: |-
                Concussions
- requirement: 2
  text: |-
      Explain the following:
  children:
      - requirement: a
        text: |-
            Before completing requirements 4 and 5, show that you have received a physical examination from your health care practioner within the last 12 months.
        workbook:
          - signature: Parent or Guardian
            checkbox: Confirmed
      - requirement: b
        text: |-
            Explain the importance of the physical exam.
        workbook:
          - lines: 8
      - requirement: c
        text: |-
            Explain the importance of maintaining good health habits for life (such as exercising regularly), and how the use of tobacco products, alcohol, and other harmful substances can negatively affect your health and your performance in sports activities.
        workbook:
          - lines: 8
      - requirement: d
        text: |-
            Explain the importance of maintaining a healthy diet.
        workbook:
          - lines: 8
- requirement: 3
  text: |-
      Discuss the following:
  children:
      - requirement: a
        text: |-
            The importance of warming up and cooling down.
        workbook:
          - lines: 8
      - requirement: b
        text: |-
            The importance of weight training.
        workbook:
          - lines: 8
      - requirement: c
        text: |-
            What an amateur athlete is and the differences between an amateur and a professional athlete.
        workbook:
          - lines: 8
      - requirement: d
        text: |-
            The attributes (qualities) of a good sport, the importance of sportsmanship, and the traits of a good team leader and player who exhibits Scout spirit on and off the playing field.
        workbook:
          - lines: 8
- requirement: 4
  markdown: true
  text: |-
      Take part for one season (or four months) as a competitive individual or as a member of an organized team in TWO of the following sports: baseball, basketball, bowling, cross-country, field hockey, football, golf gymnastics, ice hockey, lacrosse, soccer, softball, swimming, table tennis, tennis, track and field, volleyball, water polo, wrestling, cheerleading, and/or badminton. Your counselor may approve in advance other recognized sports, but not any sport that is restricted and not authorized by the BSA:

      Then with your chosen sports do the following:
  workbook:
    - lines: 2
      text: |-
        First sport
    - lines: 2
      text: |-
        Second sport
  children:
      - requirement: a
        text: |-
            Give the rules and etiquette for the two sports you picked.
        workbook:
          - lines: 8
            text: |-
              First sport
          - lines: 8
            text: |-
              Second sport
      - requirement: b
        text: |-
            List the equipment needed for the two sports you chose.  Describe the protective equipment and appropriate clothing (if any) and explain why it is needed.
        workbook:
          - lines: 8
            text: |-
              First sport
          - lines: 8
            text: |-
              Second sport
      - requirement: c
        text: |-
            Draw diagrams of the playing area for your two sports.
        workbook:
          - area: true
            height: 8
            text: |-
              First sport
          - area: true
            height: 8
            text: |-
              Second sport
- requirement: 5
  text: |-
      With guidance from your counselor and before beginning requirement 4, establish a personal training program suited to the activities you chose for requirement 4. Do the following:
  children:
      - requirement: a
        text: |-
            Organize a chart and track your training, practice, and development in the sports for one season or four months
        workbook:
          - area: true
            height: 8
      - requirement: b
        text: |-
            Demonstrate proper technique for your two chosen sports.
        workbook:
          - lines: 8
      - requirement: c
        text: |-
            At the end of the season, share your completed chart with your counselor and discuss how your participation in the sports you chose has affected you mentally and physically.
        workbook:
          - lines: 4
