- note:
      - inPerson
      - online
  text: |-
      <b><i><font color="red">Note:</font color><font color="purple"> This
      merit badge requires a lot of explanation and discussion in order to
      complete most requirements.  This class is structured to offer
      explanation and discussion time for Scouts in a small group setting to
      offer both learning and earning opportunity.</font color><font
      color="red"> Scouts MUST come to the class with preparation work in order
      to successfully complete these requirements.</font color><font
      color="purple"> It will be nearly impossible for Scouts who do not have
      preparation work done to successfully partake in the group discussions or
      provide acceptable explanation if they do not have prior knowledge of the
      requirements and answers prior to the class.</font color></i></b>
- requirement: 1
  text: |-
      Explain what citizenship in the world means to you and what you think it
      takes to be a good world citizen.
  workbook:
      - lines: 8
  children:
      - note:
            - inPerson
            - online
        text: |-
            Scouts should formulate a written answer for this requirement prior
            to the class and be ready to share their work as a part of
            classroom discussion.
- requirement: 2
  text: |-
      Explain how one becomes a citizen in the United States, and explain the
      rights, duties, and obligations of U.S. citizenship.  Discuss the
      similarities and differences between the rights, duties, and obligations
      of U.S. citizens and the citizens of two other countries.
  workbook:
      - lines: 8
        text: |-
            How one becomes a citizen in the United States
      - lines: 8
        text: |-
            Explain the rights, duties, and obligations
      - header: true
        text: |-
            Similarities and differences between the rights, duties, and
            oblications of U.S. citizens and the citizens of two other
            countries
      - lines: 8
      - lines: 8
  children:
      - note:
            - inPerson
            - online
        text: |-
            Scouts should have this written out to show the counselor that some
            thought and research has gone into this requirement and Scouts
            should be prepared to discuss their findings. Scouts will not
            automatically be signed off on this requirement just for attending
            as the requirement states that they must discuss a number of items
            and will be required to partake in group and/or individual
            discussion to obtain credit.
- requirement: 3
  text: |-
      Do the following:
  children:
      - requirement: a
        text: |-
            Pick a current world event. In relation to this current event,
            discuss with your counselor how a country’s national interest,
            history, and its relationship with other countries might affect
            areas such as its security, its economy, its values, and the health
            of its citizens.
        workbook:
            - lines: 20
      - requirement: b
        text: |-
            Select a foreign country and discuss with your counselor how its
            geography, natural resources, and climate influence its economy and
            its global partnerships with other countries.
        workbook:
            - lines: 8
      - note:
            - inPerson
            - online
        text: |-
            Scouts should be prepared to share their findings with the class
            and should be prepared with this requirement prior to the class.
            1/2 of this requirement is preparation and research, the other 1/2
            which will be facilitated in the class is the discussion. Scouts
            cannot complete this requirement by only doing one or the other,
            both parts must be done for each component. Scouts not coming to
            class with preparation work will find it difficult, if not
            impossible to complete this requirement on the day of the class.
            Preparation is a MUST for this requirement along with active class
            participation during the discussion.
- requirement: 4
  text: |-
      Do TWO of the following:
  children:
      - requirement: a
        text: |-
            Explain international law and how it differs from national law.
            Explain the role of international law and how international law can
            be used as a tool for conflict resolution.
        workbook:
            - lines: 8
              text: |-
                  How international law differs from national law
            - lines: 8
              text: |-
                  The role of international law
            - lines: 8
              text: |-
                  How international law can be used as a tool for conflict
                  resolution
      - requirement: b
        text: |-
            Using resources such as major daily newspapers, the Internet (with
            your parent’s permission), and news magazines, observe a current
            issue that involves international trade, foreign exchange, balance
            of payments, tariffs, and free trade. Explain what you have
            learned. Include in your discussion an explanation of why countries
            must cooperate in order for world trade and global competition to
            thrive.
        workbook:
            - lines: 8
      - requirement: c
        text: |-
            Select TWO of the following organizations and describe their role
            in the world.
        workbook:
            - header: true
              markdown: true
              text: |-
                  1. The United Nations and UNICEF
                  2. The World Court
                  3. Interpol
                  4. World Organization of the Scout Movement
                  5. The World Health Organization
                  6. Amnesty International
                  7. The International Committee of the Red Cross
                  8. CARE (Cooperative for American Relief Everywhere)
                  9. European Union
            - lines: 8
            - lines: 8
        children:
            - requirement: 1
              text: |-
                  The United Nations and UNICEF
              workbookHide: true
            - requirement: 2
              text: |-
                  The World Court
              workbookHide: true
            - requirement: 3
              text: |-
                  Interpol
              workbookHide: true
            - requirement: 4
              text: |-
                  World Organization of the Scout Movement
              workbookHide: true
            - requirement: 5
              text: |-
                  The World Health Organization
              workbookHide: true
            - requirement: 6
              text: |-
                  Amnesty International
              workbookHide: true
            - requirement: 7
              text: |-
                  The International Committee of the Red Cross
              workbookHide: true
            - requirement: 8
              text: |-
                  CARE (Cooperative for American Relief Everywhere)
              workbookHide: true
            - requirement: 9
              text: |-
                  European Union
              workbookHide: true
      - note:
            - inPerson
            - online
        text: |-
            This class will focus on requirements 4A and 4C. For both
            requirements, It is recommended that Scouts should formulate an
            answer prior to the class and be ready to share their work as a
            part of the classroom discussions.
- requirement: 5
  text: |-
      Do the following:
  children:
      - requirement: a
        text: |-
            Discuss the differences between constitutional and
            nonconstitutional governments.
        workbook:
            - lines: 8
      - requirement: b
        text: |-
            Name at least five different types of governments currently in
            power in the world.
        workbook:
            - lines: 2
            - lines: 2
            - lines: 2
            - lines: 2
            - lines: 2
      - requirement: c
        text: |-
            Show on a world map countries that use each of these five different
            forms of government.
        workbook:
            - raw: true
              text: |-
                  <img src="world-map.jpg" class="W(100%)"/>
      - note:
            - inPerson
            - online
        text: |-
            For all three of the components of this requirement, it is strongly
            recommended to use the Scoutmaster Bucky Citizenship in the World
            Merit Badge Workbook to document discussion points, explanations,
            and mappings to support one's findings for this requirement. Scouts
            should be prepared to explain, discuss, and share their work in the
            class discussion of this requirement.
- requirement: 6
  text: |-
      Do the following:
  children:
      - requirement: a
        text: |-
            Explain how a government is represented abroad and how the United
            States government is accredited to international organizations.
        workbook:
            - lines: 8
              text: |-
                  How a government is represented abroad
            - lines: 8
              text: |-
                  How the United States government is accredited to
                  international organizations
      - requirement: b
        text: |-
            Describe the roles of the following in the conduct of foreign
            relations.
        workbook:
            - lines: 8
              text: |-
                  1. Ambassador
            - lines: 8
              text: |-
                  2. Consul
            - lines: 8
              text: |-
                  3. Bureau of International Information Programs
            - lines: 8
              text: |-
                  4. Agency for International Development
            - lines: 8
              text: |-
                  5. United States and Foreign Commercial Service
        children:
            - requirement: 1
              text: |-
                  Ambassador
              workbookHide: true
            - requirement: 2
              text: |-
                  Consul
              workbookHide: true
            - requirement: 3
              text: |-
                  Bureau of International Information Programs
              workbookHide: true
            - requirement: 4
              text: |-
                  Agency for International Development
              workbookHide: true
            - requirement: 5
              text: |-
                  United States and Foreign Commercial Service
              workbookHide: true
      - requirement: c
        text: |-
            Explain the purpose of a passport and visa for international
            travel.
        workbook:
            - lines: 8
      - note:
            - inPerson
            - online
        text: |-
            This requirement will be covered within the class, however, Scouts
            should familiarize themselves with the requirement and the
            corresponding section(s) within the Merit Badge Pamphlet so as to
            have a basic understanding prior to the class.
- requirement: 7
  text: |-
      Do TWO of the following (with your parent’s permission) and share with
      your counselor what you have learned:
  children:
      - requirement: a
        text: |-
            Visit the website of the U.S. State Department.  Learn more about
            an issue you find interesting that is discussed on this website.
        workbook:
            - lines: 8
      - requirement: b
        text: |-
            Visit the website of an international news organization or foreign
            government, OR examine a foreign newspaper available at your local
            library, bookstore, or newsstand.  Find a news story about a human
            right realized in the United States that is not recognized in
            another country.
        workbook:
            - lines: 8
      - requirement: c
        text: |-
            Visit with a student or Scout from another country and discuss the
            typical values, holidays, ethnic foods, and traditions practiced or
            enjoyed there.
        workbook:
            - lines: 8
      - requirement: d
        text: |-
            Attend a world Scout jamboree.
        workbook:
            - task: true
      - requirement: e
        text: |-
            Participate in or attend an international event in your area, such
            as an ethnic festival, concert, or play.
        workbook:
            - task: true
      - note:
            - inPerson
            - online
        markdown: true
        text: |-
            Currently NO components of Requirement 7 are guaranteed to be
            covered in the class and will be at the discretion and resources of
            the individual counselor who may or may not provide classroom
            support for these.

            PLEASE NOTE HOWEVER: Scouts who can bring documented proof of
            completing any of these requirements will have an opportunity to
            share with the counselor their accomplishments and potentially be
            signed off on those requirements (remember completion of
            requirements is at the discretion of each individual counselor).
            It is STRONGLY recommended Scouts interested in completing this
            merit badge bring their work for requirement 7 to the class. If the
            work meets the satisfaction of the merit badge counselor, (saying
            you did it is not enough, you need to bring proof), most counselors
            will sign off on the requirement.
