- note:
      - inPerson
      - online
  markdown: true
  text: |-
      ***BRING YOUR COLLECTION WITH YOU AS YOU WILL NEED THIS FOR
      PARTICIPATION***

      **Stamps and Coin Collecting are excluded from eligibility for this merit
      badge**
- requirement: 1
  markdown: true
  text: |-
      Prepare a short written report or outline for your counselor, giving a
      detailed description of your collection,`*` including a short history,
      why you enjoy your collection, and what you have learned from collecting.
      Be sure to include why you chose that particular type of
      collection/collecting method.

      `*` <a href="/merit-badges/stamp-collecting/">Stamp</a> and <a
      href="/merit-badges/coin-collecting/">coin collecting</a> are excluded
      from eligibility for this merit badge.
  workbook:
      - lines: 8
        text: |-
            Detailed description of your collection
      - lines: 8
        text: |-
            Short history
      - lines: 8
        text: |-
            Why you enjoy your collection
      - lines: 8
        text: |-
            What you have learned from collecting
      - lines: 8
        text: |-
            Why you chose that particular type of collection/collecting method
  children:
      - note:
            - inPerson
            - online
        text: |-
            Scouts should have this written out to show the counselor that some
            thought and preparation has gone into this requirement and Scouts
            should be prepared to discuss their findings. Scouts will not
            automatically be signed off on this requirement just for attending
            as the requirement states that they must prepare a short, written
            report to get credit.
- requirement: 2
  text: |-
      Explain the growth and development of your collection.
  workbook:
      - lines: 8
  children:
      - note:
            - inPerson
            - online
        text: |-
            Scouts should be prepared to share how they got started collecting
            what they collect, how long they have been collecting, if they have
            any specialties or requirements to consider it collectable, how
            their collection has grown, where they obtain items to add to their
            collection, etc.
- requirement: 3
  text: |-
      Demonstrate your knowledge of preserving and displaying your collection.
  children:
      - requirement: a
        text: |-
            Explain the precautions you need to take to preserve your
            collection, including
        workbook:
            - lines: 8
              text: |-
                  1. Handling
            - lines: 8
              text: |-
                  2. Cleaning
            - lines: 8
              text: |-
                  3. Storage
        children:
            - requirement: 1
              text: |-
                  Handling
              workbookHide: true
            - requirement: 2
              text: |-
                  Cleaning
              workbookHide: true
            - requirement: 3
              text: |-
                  Storage
              workbookHide: true
      - requirement: b
        text: |-
            Explain how best to display your collection, keeping in mind
            preserving as discussed above.
        workbook:
            - lines: 8
      - requirement: c
        text: |-
            Explain to your counselor the events available for a hobbyist of
            this collection, including shows, seminars, conventions, contests,
            and museum programs and exhibits.
        workbook:
            - lines: 8
              text: |-
                  Shows
            - lines: 8
              text: |-
                  Seminars
            - lines: 8
              text: |-
                  Conventions
            - lines: 8
              text: |-
                  Contests
            - lines: 8
              text: |-
                  Museum programs and exhibits
      - requirement: d
        text: |-
            Explain to your counselor how you keep track of your collection.
            Describe your cataloging method.
        workbook:
            - lines: 8
              text: |-
                  How you keep track of your collection
            - lines: 8
              text: |-
                  Describe your cataloging method
      - note:
            - inPerson
            - online
        text: |-
            Scouts will have an opportunity to explain how the proper caring
            for and displaying of a collection like they have. Scouts should
            also research if there are any clubs, organizations, events, etc
            that support or tie in with their collection. Preparation should be
            easy for this requirement.
- requirement: 4
  text: |-
      Demonstrate your knowledge of collecting and investing.  Discuss with
      your counselor:
  children:
      - requirement: a
        text: |-
            How investing and speculation would apply to your collection
        workbook:
            - lines: 8
      - requirement: b
        text: |-
            What you would look for in purchasing other collections similar to
            yours
        workbook:
            - lines: 8
      - requirement: c
        text: |-
            What you would expect in return value if you decided to sell all or
            part of the collection
        workbook:
            - lines: 8
      - note:
            - inPerson
            - online
        text: |-
            Scouts should be prepared for discussion of these items. Every type
            of collection is different, and most counselors are well-versed in
            collecting in general. This is an opportunity for the Scout to
            educate fellow Scouts, as well as the counselor / instructor, about
            their collection and knowledge.
- requirement: 5
  text: |-
      Do the following:
  children:
      - requirement: a
        text: |-
            Discuss with your counselor at least 10 terms commonly used to
            describe your collection and be prepared to discuss the definition
            of each.
        workbook:
            - lines: 8
            - lines: 8
            - lines: 8
            - lines: 8
            - lines: 8
            - lines: 8
            - lines: 8
            - lines: 8
            - lines: 8
            - lines: 8
        children:
            - note:
                  - inPerson
                  - online
              text: |-
                  Scouts should identify 10 terms particular to their type of
                  collection and be ready to share this during the class. Some
                  Scouts may find it more convenient to write this information
                  down, so they are able to more readily share this information
                  during the class..
      - requirement: b
        text: |-
            Show your counselor any two groups from your collection.  Explain
            how you organized your collection and why you chose that method.
            (Note: If your collection is too large to transport and your
            counselor is unable to view your collection directly, photographs
            should be available to share.)
        children:
            - note:
                  - inPerson
              text: |-
                  Scouts will need to have their collection or photographs (if
                  it is too large to bring) ready to share with the counselor
                  and other Scouts.
            - note:
                  - online
              text: |-
                  Scouts will need to have their collection or photographs
                  ready to share with the counselor and other Scouts.
      - requirement: c
        text: |-
            Explain the monetary value of your collection and where you learned
            about those values.
        workbook:
            - lines: 8
      - requirement: d
        text: |-
            Explain how your collection is graded for value, physical defects,
            size, and age. Show the various classifications or ratings used in
            your collection.
        workbook:
            - lines: 8
              text: |-
                  Explain how your collection is graded for value, physical
                  defect, size, and age
            - lines: 8
              text: |-
                  Various classifications or ratings used in your collection
      - requirement: e
        text: |-
            List the national, state, or local association(s) related to or
            associated with your collection.
        workbook:
            - lines: 8
        children:
            - note:
                  - inPerson
                  - online
              text: |-
                  There is some sort of group or organization for almost
                  anything that people collect. In some cases, the counselor
                  may challenge Scouts that claim there are no resources for
                  their collection, so it is advised that Scouts search the
                  internet for resources to help complete this requirement.
                  Some counselors may not sign off on this requirement if they
                  are easily able to find resources where Scouts claim there
                  are none. Dig deep, there's somewhere or someone that knows
                  something about your collection.
      - requirement: f
        text: |-
            Explain to your counselor the purpose of and reason for the
            identification number (if applicable), series, brand name (if any),
            and any other special identification marks.
        workbook:
            - lines: 8
        children:
            - note:
                  - inPerson
                  - online
              text: |-
                  Most things collected will have some sort of identification
                  marks that make it unique or identifiable, Scouts should come
                  prepared ready to share this information with the class.
- requirement: 6
  text: |-
      Discuss with your counselor the plans you have to continue with the
      collection in the future.
  workbook:
      - lines: 8
  children:
      - note:
            - inPerson
            - online
        text: |-
            One of the easiest requirements of any merit badge. Scouts will
            simply need to share their thoughts and vision for their
            collections continuation.
- requirement: 7
  text: |-
      Find out about career opportunities in collecting. Pick one and find out
      the education, training, and experience required for this profession.
      Discuss this with your counselor, and explain why this profession might
      interest you.
  workbook:
      - lines: 8
        text: |-
            Career opportunities in collecting
      - lines: 8
        text: |-
            Education, training, and experience for one profession
  children:
      - note:
            - inPerson
            - online
        text: |-
            Scouts should review this requirement and its components and be
            prepared to discuss. It is strongly recommended that Scouts bring
            any notes or supporting documents they may have to help show the
            counselor that they have prepared for completion of this
            requirement.
