- requirement: 1
  text: |-
      Do the following:
  children:
      - requirement: a
        text: |-
            Explain four features of the free enterprise system in the United
            States.  Describe the difference between freedom and license. Tell
            how the Scout Oath and Scout Law apply to business and free
            enterprise.
        workbook:
            - header: true
              text: |-
                  Four features
            - lines: 2
            - lines: 2
            - lines: 2
            - lines: 2
            - lines: 8
              text: |-
                  Difference between freedom and license
            - lines: 8
              text: |-
                  How the Scout Oath and Scout Law apply to business and free
                  enterprise
      - requirement: b
        text: |-
            Describe the Industrial Revolution and tell about the major
            developments that marked the start of the modern industrial era in
            the United States. Discuss three people who had a great influence
            on business or industry in the United States and describe what each
            did.
        workbook:
            - lines: 8
              text: |-
                  Describe the Industrial Revolution
            - lines: 8
              text: |-
                  Major developments that marked the start of the modern
                  industrial era in the United States
            - lines: 8
              text: |-
                  First person and their great influence on business or
                  industry in the United States
            - lines: 8
              text: |-
                  Second person and their great influence on business or
                  industry in the United States
            - lines: 8
              text: |-
                  Third person and their great influence on business or
                  industry in the United States
      - requirement: c
        text: |-
            Identify and describe to your counselor the five primary areas of
            business.
        workbook:
            - lines: 8
            - lines: 8
            - lines: 8
            - lines: 8
            - lines: 8
      - requirement: d
        text: |-
            Explain the history of labor unions in the United States and the
            importance of labor unions and employers working together. Identify
            two major labor unions currently in existence.
        workbook:
            - lines: 8
              text: |-
                  History of labor unions in the United States
            - lines: 8
              text: |-
                  Importance of labor unions and employers working together
            - lines: 8
              text: |-
                  Two major labor unions currently in existence
      - requirement: e
        text: |-
            Discuss with your counselor how business impacts the local,
            national, and global economy.
        workbook:
            - lines: 8
              text: |-
                  How business impacts the local economy
            - lines: 8
              text: |-
                  How business impacts the national economy
            - lines: 8
              text: |-
                  How business impacts the global economy
      - note:
            - inPerson
            - online
        text: |-
            While the majority of Requirement 1 is verbal exchange with the
            counselor and other Scouts in the class, Scouts will find it
            necessary to have done some preparation work along with active
            participation in the class led discussions to be considered for
            completion of this requirement at the class.  It is strongly
            recommended that Scouts bring any notes or supporting documents to
            aid them in their discussion points.
- requirement: 2
  text: |-
      Do the following:
  children:
      - requirement: a
        text: |-
            Explain the three basic types of financial statements (income
            statement, balance sheet, and statement of cash flows). Discuss
            with your counselor how each statement can help business leaders
            make better decisions.
        workbook:
            - lines: 8
              text: |-
                  Explain an income statement and how it can help business
                  leaders make better decisions
            - lines: 8
              text: |-
                  Explain a balance sheet and how it can help business leaders
                  make better decisions
            - lines: 8
              text: |-
                  Explain a statement of cash flows and how it can help
                  business leaders make better decisions
      - requirement: b
        text: |-
            Explain how changes in interest rates, taxes, and government
            spending affect the flow of money into or out of business and
            industry.
        workbook:
            - lines: 8
              text: |-
                  How changes in interest rates affect the flow of money into
                  or out of business and industry
            - lines: 8
              text: |-
                  How changes in taxes affect the flow of money into or out of
                  business and industry
            - lines: 8
              text: |-
                  How changes in government spending affect the flow of money
                  into or out of business and industry
      - requirement: c
        text: |-
            Explain how a sole proprietorship, partnership, or limited
            liability company gets its capital.  Discuss and explain four ways
            a corporation obtains capital.
        workbook:
            - lines: 8
              text: |-
                  How sole proprietorship or partnership gets its capital
            - lines: 8
              text: |-
                  Four ways a corporation obtains capital
      - requirement: d
        text: |-
            Name five kinds of insurance useful to business. Describe their
            purposes.
        workbook:
            - lines: 8
              text: |-
                  First kind of insurance useful to business and describe its
                  purpuse
            - lines: 8
              text: |-
                  Second kind of insurance useful to business and describe its
                  purpuse
            - lines: 8
              text: |-
                  Third kind of insurance useful to business and describe its
                  purpuse
            - lines: 8
              text: |-
                  Fourth kind of insurance useful to business and describe its
                  purpuse
            - lines: 8
              text: |-
                  Fifth kind of insurance useful to business and describe its
                  purpuse
      - note:
            - inPerson
            - online
        text: |-
            Scouts will find it necessary to review the merit badge pamphlet or
            other sources to prepare for this requirement and its components.
            Consider utilizing a workbook or notepad to make notes of your
            research in preparation for the class.
- requirement: 3
  text: |-
      Do the following:
  children:
      - requirement: a
        text: |-
            Explain the place of profit in business.
        workbook:
            - lines: 8
      - requirement: b
        text: |-
            Describe to your counselor green marketing and sustainable business
            practices.
        workbook:
            - lines: 8
              text: |-
                  Green marketing
            - lines: 8
              text: |-
                  Sustainable business practices
      - requirement: c
        text: |-
            Explain how ethics plays a role in business decision making.
        workbook:
            - lines: 8
      - requirement: d
        text: |-
            Discuss the differences between operating a brick-and-mortar
            business versus an online business.
        workbook:
            - lines: 8
      - note:
            - inPerson
            - online
        text: |-
            Scouts must be able to actively and knowledgeably participate in
            classroom discussion on the components of this requirement.  Simply
            attending does not fulfill the stated actions of Explain, describe,
            and discuss. Scout not having doen some preparation work for this
            requirement AND actively participating in the class discussion will
            find it difficult to complete this requirement in the class.
- requirement: 4
  text: |-
      Describe the role of the U.S. Department of Labor. Discuss two of the
      following topics with your counselor:
  children:
      - requirement: a
        text: |-
            Fair Labor Standards Act (FLSA)
        workbook:
            - lines: 8
      - requirement: b
        text: |-
            Occupational Safety and Health Act (OSHA)
        workbook:
            - lines: 8
      - requirement: c
        text: |-
            Family and Medical Leave Act (FMLA)
        workbook:
            - lines: 8
      - requirement: d
        text: |-
            Employee Retirement Income Security Act (ERISA)
        workbook:
            - lines: 8
      - note:
            - inPerson
            - online
        text: |-
            Choose two of the four components options for Requirement 4 and be
            prepared to share your findings within the class. This requirement
            requires preparation work ahead of time.
- requirement: 5
  text: |-
      Choose a business and research how it applies each of the primary areas
      of business (accounting, finance, economics, marketing, and management).
      Share what you have learned with your counselor.
  workbook:
      - lines: 2
        text: |-
            Choose a business
      - lines: 8
        text: |-
            Accounting
      - lines: 8
        text: |-
            Finance
      - lines: 8
        text: |-
            Economics
      - lines: 8
        text: |-
            Marketing
      - lines: 8
        text: |-
            Management
  children:
      - note:
            - inPerson
            - online
        text: |-
            Scouts will need to carefully manage their time and resources when
            working on this requirement. This is not a requirement that can be
            done in an hour or two. After selecting the business they want to
            research, they will need to spend considerable time looking into
            the numerous different areas of business for the company or
            corporation. It cannot be emphasized enough that Scouts will spend
            a lot of time preparing for sharing on this requirement which will
            require a very extensive and thorough report covering all aspects
            of the business and the stated items of this requirement shown.
            This requirement is best completed by Scouts who allot themselves
            plenty of time to complete and realize this is not just a single
            afternoon project. Time will be provided within the class for any
            Scouts interested in sharing their partial or completed progress on
            this requirement.
- requirement: 6
  text: |-
      Do ONE of the following:
  children:
      - requirement: a
        text: |-
            Choose one of the primary areas of business and identify three
            career opportunities. Select one and research the education,
            training, and experience required for this career. Discuss this
            with your counselor and explain why this interests you.
        workbook:
            - lines: 8
              text: |-
                  Three career opportunities
            - lines: 8
              text: |-
                  Education, training, and experience required for one career
        children:
            - note:
                  - inPerson
                  - online
              text: |-
                  Scouts that choose to do this requirement component will need
                  to select either accounting, finance, economics, marketing,
                  or management as their primary area of business and then
                  identify three careers where someone seeking to work in that
                  area of business might pursue.  Find out all that it takes to
                  become prepared, educated, and trained for the highest
                  probability of appeal to a potential employer.  Scouts should
                  be ready to share their findings with the counselor and class
                  during the class.
      - requirement: b
        text: |-
            Select a business leader and interview this individual to learn
            more about his or her company and career path. Discuss the role
            ethics plays in making business decisions. Share what you have
            learned with your counselor.
        workbook:
            - lines: 2
              text: |-
                  Name of business leader
            - lines: 8
              text: |-
                  Learn more about his or her company
            - lines: 8
              text: |-
                  Learn more about his or her career path
            - lines: 8
              text: |-
                  The role ethics plays in making business decisions
        children:
            - note:
                  - inPerson
                  - online
              text: |-
                  Scouts that choose this requirement component will need to
                  make sure to have proof of their interview and either a very
                  good memory or strong notes to support their findings when
                  sharing what they learned during the class. Be Prepared.
