- requirement: 1
  text: |-
    Do the following:
  children:
    - requirement: a
      text: |-
        Explain four features of the free enterprise system in the United
        States.  Describe the difference between freedom and license. Tell
        how the Scout Oath and Scout Law apply to business and free
        enterprise.
    - requirement: b
      text: |-
        Describe the Industrial Revolution and tell about the major
        developments that marked the start of the modern industrial era in
        the United States. Discuss three people who had a great influence
        on business or industry in the United States and describe what each
        did.
    - requirement: c
      text: |-
        Identify and describe to your counselor the five primary areas of
        business.
    - requirement: d
      text: |-
        Explain the history of labor unions in the United States and the
        importance of labor unions and employers working together. Identify
        two major labor unions currently in existence.
    - requirement: e
      text: |-
        Discuss with your counselor how business impacts the local,
        national, and global economy.
    - note:
        - inPerson
        - online
      text: |-
        While the majority of Requirement 1 is verbal exchange with the
        counselor and other Scouts in the class, Scouts will find it
        necessary to have done some preparation work along with active
        participation in the class led discussions to be considered for
        completion of this requirement at the class.  It is strongly
        recommended that Scouts bring any notes or supporting documents to
        aid them in their discussion points.
- requirement: 2
  text: |-
    Do the following:
  children:
    - requirement: a
      text: |-
        Explain the three basic types of financial statements (income
        statement, balance sheet, and statement of cash flows). Discuss
        with your counselor how each statement can help business leaders
        make better decisions.
    - requirement: b
      text: |-
        Explain how changes in interest rates, taxes, and government
        spending affect the flow of money into or out of business and
        industry.
    - requirement: c
      text: |-
        Explain how a sole proprietorship, partnership, or limited
        liability company gets its capital.  Discuss and explain four ways
        a corporation obtains capital.
    - requirement: d
      text: |-
        Name five kinds of insurance useful to business. Describe their
        purposes.
    - note:
        - inPerson
        - online
      text: |-
        Scouts will find it necessary to review the merit badge pamphlet or
        other sources to prepare for this requirement and its components.
        Consider utilizing a workbook or notepad to make notes of your
        research in preparation for the class.
- requirement: 3
  text: |-
    Do the following:
  children:
    - requirement: a
      text: |-
        Explain the place of profit in business.
    - requirement: b
      text: |-
        Describe to your counselor green marketing and sustainable business
        practices.
    - requirement: c
      text: |-
        Explain how ethics plays a role in business decision making.
    - requirement: d
      text: |-
        Discuss the differences between operating a brick-and-mortar
        business versus an online business.
    - note:
        - inPerson
        - online
      text: |-
        Scouts must be able to actively and knowledgeably participate in
        classroom discussion on the components of this requirement.  Simply
        attending does not fulfill the stated actions of Explain, describe,
        and discuss. Scout not having doen some preparation work for this
        requirement AND actively participating in the class discussion will
        find it difficult to complete this requirement in the class.
- requirement: 4
  text: |-
    Describe the role of the U.S. Department of Labor. Discuss two of the
    following topics with your counselor:
  children:
    - requirement: a
      text: |-
        Fair Labor Standards Act (FLSA)
    - requirement: b
      text: |-
        Occupational Safety and Health Act (OSHA)
    - requirement: c
      text: |-
        Family and Medical Leave Act (FMLA)
    - requirement: d
      text: |-
        Employee Retirement Income Security Act (ERISA)
    - note:
        - inPerson
        - online
      text: |-
        Choose two of the four components options for Requirement 4 and be
        prepared to share your findings within the class. This requirement
        requires preparation work ahead of time.
- requirement: 5
  text: |-
    Choose a business and research how it applies each of the primary areas
    of business (accounting, finance, economics, marketing, and management).
    Share what you have learned with your counselor.
  children:
    - note:
        - inPerson
        - online
      text: |-
        Scouts will need to carefully manage their time and resources when
        working on this requirement. This is not a requirement that can be
        done in an hour or two. After selecting the business they want to
        research, they will need to spend considerable time looking into
        the numerous different areas of business for the company or
        corporation. It cannot be emphasized enough that Scouts will spend
        a lot of time preparing for sharing on this requirement which will
        require a very extensive and thorough report covering all aspects
        of the business and the stated items of this requirement shown.
        This requirement is best completed by Scouts who allot themselves
        plenty of time to complete and realize this is not just a single
        afternoon project. Time will be provided within the class for any
        Scouts interested in sharing their partial or completed progress on
        this requirement.
- requirement: 6
  text: |-
    Do ONE of the following:
  children:
    - requirement: a
      text: |-
        Choose one of the primary areas of business and identify three
        career opportunities. Select one and research the education,
        training, and experience required for this career. Discuss this
        with your counselor and explain why this interests you.
      children:
        - note:
            - inPerson
            - online
          text: |-
            Scouts that choose to do this requirement component will need
            to select either accounting, finance, economics, marketing,
            or management as their primary area of business and then
            identify three careers where someone seeking to work in that
            area of business might pursue.  Find out all that it takes to
            become prepared, educated, and trained for the highest
            probability of appeal to a potential employer.  Scouts should
            be ready to share their findings with the counselor and class
            during the class.
    - requirement: b
      text: |-
        Select a business leader and interview this individual to learn
        more about his or her company and career path. Discuss the role
        ethics plays in making business decisions. Share what you have
        learned with your counselor.
      children:
        - note:
            - inPerson
            - online
          text: |-
            Scouts that choose this requirement component will need to
            make sure to have proof of their interview and either a very
            good memory or strong notes to support their findings when
            sharing what they learned during the class. Be Prepared.
