# Changed "Venturer" to "Venturer or Sea Scout"
- requirement: 1
  markdown: true
  text: |-
      Earn the <a href="../dr-sally-ride/">Dr. Sally Ride</a> Supernova award
      while a registered Venturer or Sea Scout OR earn the <a
      href="../dr-bernard-harris/">Dr. Bernard Harris</a> Supernova award while
      a registered Scout in Scouts BSA.
# Changed "Venturer" to "Venturer / Sea Scout" or "Venturer or Sea Scout"
- requirement: 2
  markdown: true
  text: |-
      As a Venturer or Sea Scout complete ONE additional <a
      href="../../venturing-and-sea-scouts/">Venturer/Sea Scout Nova award</a>
      for a total of four. The Nova award completed is to be different from any
      Nova awards previously completed.
- requirement: 3
  markdown: true
  text: |-
      Using the guidelines for <a href="../../explorations/">Venturing/Sea
      Scout STEM Explorations</a>, complete STEM explorations for four of the
      topics listed below. Use of Scouts BSA Merit Badge content is encouraged.

      Animal Science, Archaeology, Architecture, Astronomy, Automotive
      Maintenance, Aviation, Bird Study, Chemistry, Composite Materials,
      Computers, Dentistry, Drafting, Electricity, Electronics, Energy,
      Engineering, Environmental Science, Farm Mechanics, Fish and Wildlife
      Management, Forestry, Gardening, Geocaching, Geology, Insect Study,
      Inventing, Mammal Study, Medicine, Nature, Nuclear Science, Oceanography,
      Plant Science, Pulp and Paper, Radio, Reptile and Amphibian Study,
      Robotics, Scuba Diving, Soil and Water Conservation, Space Exploration,
      Surveying, Veterinary Medicine, Weather, Welding.
# Changed "Venturer" to "Venturer / Sea Scout"
- requirement: 4
  markdown: true
  text: |-
      Complete TWO additional <a href="../activity-topics/">Supernova activity
      topics</a>, one each in the two STEM areas not completed for the <a
      href="../dr-sally-ride/">Dr. Sally Ride</a> Supernova award or <a
      href="../dr-bernard-harris">Dr. Bernard Harris</a> Supernova award.
      (Upon completion of the Wright Brothers Supernova award, the Venturer/Sea
      Scout will have completed one Supernova activity topic in each of the
      four STEM areas.)
# Changed "Venturer" to "Venturer / Sea Scout"
- requirement: 5
  markdown: true
  text: |-
      Participate in a local, state, or national science fair or mathematics
      competition OR any other equally challenging STEM-oriented competition or
      workshop approved by your mentor. An example of this would be an X-Prize
      type competition. (Note: The intent is that upon completion of the Wright
      Brothers Supernova award, the Venturer/Sea Scout will have participated
      in two such events.)
# Changed "Venturer" to "Venturer / Sea Scout"
- requirement: 6
  markdown: true
  text: |-
      Working with your mentor, organize and present a Nova award or other
      STEM-related program at a Cub Scout den or pack meeting. Be sure to
      receive permission from the appropriate unit leader. If a Cub Scout den
      or pack is not available, your presentation may be given to another
      group.  (Note: The intent is that upon completion of the Wright Brothers
      Supernova award, the Venturer/Sea Scout will have completed two such
      presentations.)
- requirement: 7
  text: |-
      Research a scientific, technical, engineering, or mathematical
      breakthrough or invention of the past 100 years that has affected our
      society in a meaningful way. Develop your hypothesis on how this
      invention might further affect our society during your lifetime. Present
      either a 30- minute oral report or a 1,500-word written report to your
      mentor.
- requirement: 8
  markdown: true
  text: |-
      Submit <a href="../award-application.pdf">your application</a> to the
      district or council Nova or advancement committee for approval.
