- requirement: 1
  text: |-
      Do the following:
  children:
      - requirement: a
        text: |-
            Explain to your counselor the most likely hazards associated with
            skating and what you should do to anticipate, help prevent,
            mitigate, and respond to these hazards.
        workbook:
            - lines: 8
              text: |-
                  Most likely hazards
            - lines: 8
              text: |-
                  Anticipate hazards
            - lines: 8
              text: |-
                  Prevent hazards
            - lines: 8
              text: |-
                  Mitigate hazards
            - lines: 8
              text: |-
                  Respond to hazards
      - requirement: b
        text: |-
            Show that you know first aid for injuries or illnesses that could
            occur while skating, including hypothermia, frostbite, lacerations,
            abrasions, fractures, sprains and strains, blisters, heat-related
            reactions, and shock.
        workbook:
            - lines: 8
              text: |-
                  Hypothermia
            - lines: 8
              text: |-
                  Frostbite
            - lines: 8
              text: |-
                  Lacerations
            - lines: 8
              text: |-
                  Abrasions
            - lines: 8
              text: |-
                  Fractures
            - lines: 8
              text: |-
                  Sprains and strains
            - lines: 8
              text: |-
                  Blisters
            - lines: 8
              text: |-
                  Heat-related reactions
            - lines: 8
              text: |-
                  Shock
- requirement: 2
  text: |-
      Complete ALL of the requirements for ONE of the following options.
  children:
      - detail: true
        markdown: true
        text: |-
            **ICE SKATING**
      - requirement: a
        text: |-
            Do the following:
        children:
            - requirement: 1
              text: |-
                  Give general safety and courtesy rules for ice skating.
                  Discuss preparations that must be taken when skating outdoors
                  on natural ice. Explain how to make an ice rescue.
              workbook:
                  - lines: 8
            - requirement: 2
              text: |-
                  Discuss the parts and functions of the different types of ice
                  skates.
              workbook:
                  - lines: 8
            - requirement: 3
              text: |-
                  Describe the proper way to carry ice skates.
              workbook:
                  - lines: 8
            - requirement: 4
              text: |-
                  Describe how to store ice skates for long periods of time,
                  such as seasonal storage.
              workbook:
                  - lines: 8
      - requirement: b
        text: |-
            Do the following:
        children:
            - requirement: 1
              text: |-
                  Skate forward at least 40 feet and come to a complete stop.
                  Use either a twofooted snowplow stop or a one-footed snowplow
                  stop.
              workbook:
                  - task: true
            - requirement: 2
              text: |-
                  After skating forward, glide forward on two feet, then on one
                  foot, first right and then left.
              workbook:
                  - task: true
            - requirement: 3
              text: |-
                  Starting from a T position, stroke forward around the test
                  area, avoiding the use of toe picks if wearing figure skates.
              workbook:
                  - task: true
      - requirement: c
        text: |-
            Do the following:
        children:
            - requirement: 1
              text: |-
                  Glide backward on two feet for at least two times the
                  skater’s height.
              workbook:
                  - task: true
            - requirement: 2
              text: |-
                  Skate backward for at least 20 feet on two skates.
              workbook:
                  - task: true
            - requirement: 3
              text: |-
                  After gaining forward speed, glide forward on two feet,
                  making a turn of 180 degrees around a cone, first to the
                  right and then to the left.
              workbook:
                  - task: true
      - requirement: d
        text: |-
            Do the following:
        children:
            - requirement: 1
              text: |-
                  Perform forward crossovers in a figure-eight pattern.
              workbook:
                  - task: true
            - requirement: 2
              text: |-
                  Explain to your counselor the safety considerations for
                  running or participating in an ice skating race.
              workbook:
                  - lines: 8
            - requirement: 3
              text: |-
                  Perform a hockey stop.
              workbook:
                  - task: true
      - detail: true
        markdown: true
        text: |-
            **ROLLER SKATING**
      - requirement: a
        text: |-
            Do the following:
        children:
            - requirement: 1
              text: |-
                  Give general safety and etiquette rules for roller skating.
              workbook:
                  - lines: 8
            - requirement: 2
              text: |-
                  Discuss the parts and functions of the roller skate.
              workbook:
                  - lines: 8
            - requirement: 3
              text: |-
                  Describe five essential steps to good skate care.
              workbook:
                  - lines: 8
      - requirement: b
        text: |-
            Do the following:
        children:
            - requirement: 1
              text: |-
                  Skate forward with smooth, linked strokes on two feet for at
                  least 100 feet in both directions around the rink and
                  demonstrate proper techniques for stopping.
              workbook:
                  - task: true
            - requirement: 2
              text: |-
                  Skate forward and glide at least 15 feet on one skate, then
                  on the other skate.
              workbook:
                  - task: true
      - requirement: c
        text: |-
            Do the following:
        children:
            - requirement: 1
              text: |-
                  Perform the crosscut.
              workbook:
                  - task: true
            - requirement: 2
              text: |-
                  Skate backward for at least 40 feet on two skates, then for
                  at least 15 feet on one skate.
              workbook:
                  - task: true
            - requirement: 3
              text: |-
                  Skate forward in a slalom pattern for at least 40 feet on two
                  skates, then for at least 20 feet on one skate.
              workbook:
                  - task: true
            - requirement: 4
              text: |-
                  Skate backward in a slalom pattern for at least 15 feet on
                  two skates.
              workbook:
                  - task: true
      - requirement: d
        text: |-
            Do the following:
        children:
            - requirement: 1
              text: |-
                  Shuttle skate once around the rink, bending twice along the
                  way without stopping.
              workbook:
                  - task: true
            - requirement: 2
              text: |-
                  Perform a widespread eagle.
              workbook:
                  - task: true
            - requirement: 3
              text: |-
                  Perform a mohawk.
              workbook:
                  - task: true
            - requirement: 4
              text: |-
                  Perform a series of two consecutive spins on skates OR hop,
                  skip, and jump on skates for at least 10 feet.
              workbook:
                  - task: true
      - requirement: e
        text: |-
            Do the following:
        children:
            - requirement: 1
              text: |-
                  Race on a speed track, demonstrating proper technique in
                  starting, cornering, passing, and pacing.
              workbook:
                  - task: true
            - requirement: 2
              text: |-
                  Perform the limbo under a pole placed at least chest high OR
                  shoot-the-duck under a waist-high pole and rise while still
                  on one foot.
              workbook:
                  - task: true
            - requirement: 3
              text: |-
                  Perform the stepover.
              workbook:
                  - task: true
            - requirement: 4
              text: |-
                  While skating, dribble a basketball the length of the floor,
                  then return to your starting position OR push a hockey ball
                  with a stick around the entire rink in both directions.
              workbook:
                  - task: true
      - detail: true
        markdown: true
        text: |-
            **IN-LINE SKATING**
      - requirement: a
        text: |-
            Do the following:
        children:
            - requirement: 1
              text: |-
                  Give general and in-line skating safety rules and etiquette.
              workbook:
                  - lines: 8
            - requirement: 2
              text: |-
                  Describe the parts and functions of the in-line skate.
              workbook:
                  - lines: 8
            - requirement: 3
              text: |-
                  Describe the required and recommended safety equipment.
              workbook:
                  - lines: 8
            - requirement: 4
              text: |-
                  Describe four essential steps to good skate care.
              workbook:
                  - lines: 8
      - requirement: b
        text: |-
            Do the following:
        children:
            - requirement: 1
              text: |-
                  Skate forward with smooth, linked strokes on two feet for at
                  least 100 feet.
              workbook:
                  - task: true
            - requirement: 2
              text: |-
                  Skate forward and glide at least 15 feet on one skate, then
                  on the other skate.
              workbook:
                  - task: true
            - requirement: 3
              text: |-
                  Stop on command on flat pavement using the heel brake.
              workbook:
                  - task: true
      - requirement: c
        text: |-
            Do the following:
        children:
            - requirement: 1
              text: |-
                  Perform the forward crossover.
              workbook:
                  - task: true
            - requirement: 2
              text: |-
                  Perform a series of forward, linked swizzles for at least 40
                  feet.
              workbook:
                  - task: true
            - requirement: 3
              text: |-
                  Skate backward for at least 40 feet in a series of linked,
                  backward swizzles.
              workbook:
                  - task: true
            - requirement: 4
              text: |-
                  From a strong pace, perform a lunge turn around an object
                  predetermined by your counselor.
              workbook:
                  - task: true
            - requirement: 5
              text: |-
                  Perform a mohawk.
              workbook:
                  - task: true
      - requirement: d
        text: |-
            Do the following:
        children:
            - requirement: 1
              text: |-
                  Perform a series of at least four one-footed downhill slaloms
                  on pavement with a gentle slope.
              workbook:
                  - task: true
            - requirement: 2
              text: |-
                  Describe how to pass a pedestrian or another skater from
                  behind.
              workbook:
                  - lines: 8
            - requirement: 3
              text: |-
                  Describe at least three ways to avoid an unforeseen obstacle
                  while skating.
              workbook:
                  - lines: 8
            - requirement: 4
              text: |-
                  Describe two ways to get on and off a curb, and demonstrate
                  at least one of these methods.
              workbook:
                  - lines: 8
