# Requirements 4, 6, and 7 are listed after one page of resources
- requirement: 1
  text: |-
    Format TWO sheets of drawing paper with proper borders and title
    blocks—one for your manual project (see requirement 2) and one for your
    lettering project (see requirement 5).
  children:
    - requirement: a
      text: |-
        Make a rough sketch for each of your project drawings to determine
        the correct size of paper to format.
    - requirement: b
      text: |-
        Using either single-stroke vertical or slant Gothic lettering, fill
        in all important information in the title block sections of the
        formatted paper.
    - note:
        - inPerson
      text: |-
        While this requirement will be covered in the class, it can't be
        emphasized enough that Scouts not having reviewed the merit badge
        pamphlet will find it difficult to complete this requirement
        without a prior understanding of the methods and procedures to be
        used.  It is strongly suggested Scouts have reviewed the merit
        badge pamphlet prior to the class.
    - note:
        - online
      text: |-
        While this requirement will be reviewed in the class, it can't be
        emphasized enough that Scouts must make an attempt to have their
        two sheets started and attempted to be completed. Reviewing the
        merit badge pamphlet will aid Scouts significantly in preparing for
        the class and being ready for review by the counselor / intructor.
- requirement: 2
  text: |-
    Using the formatted sheet of paper you prepared for your manual project,
    produce a pencil drawing as it would be used for manufacturing. Fill in
    all title block information.  The manual drawing may be any one of the
    following drawing types:
  children:
    - requirement: a
      markdown: true
      text: |-
        **Architectural:** Make a scale drawing of an architectural
        project. The architectural drawing may be a floor plan; electrical,
        plumbing, or mechanical service plan; elevation plan; or
        landscaping plan. Use an architect’s scale and show dimensions to
        communicate the actual size of features. Include any important
        sectional drawings, notes, and considerations necessary for
        construction.
    - requirement: b
      markdown: true
      text: |-
        **Mechanical:** Make a scale drawing of some mechanical device or
        interesting object. The mechanical drawing may be of the
        orthographic or isometric style. Use an engineer’s scale and show
        dimensions to communicate the actual size of features. Include any
        important sectional drawings, notes, and manufacturing
        considerations.
    - requirement: c
      markdown: true
      text: |-
        **Electrical:** Draw a simple schematic of a radio or electronic
        circuit. Properly print a bill of materials including all of the
        major electrical components used in the circuit. Use standard
        drawing symbols to represent the electronic components.
    - note:
        - inPerson
      text: |-
        This requirement will comprise a majority of the time in the class,
        however Scouts should come to the class having reviewed the merit
        badge pamphlet and with a general understanding of the drafting
        techniques and procedures they will be using to complete this
        requirement.
    - note:
        - online
      text: |-
        Scouts should come to the class having reviewed the merit badge
        pamphlet and with a general understanding of the drafting
        techniques and procedures. The counselor / instructor will be able
        to give guidance on technique and review of work, however Scouts
        will need to do this work prior to the class in order for
        consideration of completion during the class.
- requirement: 3
  text: |-
    Produce a computer-aided design (CAD) drawing as it would be used in
    manufacturing. Fill in all title block information. The CAD drawing may
    be any one of the following drawing types:
  children:
    - requirement: a
      markdown: true
      text: |-
        **Architectural:** Make a scale drawing of an architectural
        project. The architectural drawing may be a floor plan; electrical,
        plumbing, or mechanical service plan; elevation plan; or
        landscaping plan. Use an architect’s scale and show dimensions to
        communicate the actual size of features. Include any important
        sectional drawings, notes, and considerations necessary for
        construction.
    - requirement: b
      markdown: true
      text: |-
        **Mechanical:** Make a scale drawing of some mechanical device or
        interesting object. The mechanical drawing may be of the
        orthographic or isometric style. Use an engineer’s scale and show
        dimensions to communicate the actual size of features. Include any
        important sectional drawings, notes, and manufacturing
        considerations.
    - requirement: c
      markdown: true
      text: |-
        **Electrical:** Draw a simple schematic of a radio or electronic
        circuit. Properly print a bill of materials including all of the
        major electrical components used in the circuit.  Use standard
        drawing symbols to represent the electronic components.
    - note:
        - inPerson
        - online
      text: |-
        This requirement will be covered in the class.  Scouts are
        encouraged to bring their laptop (no tablets), if available as some
        counselors may have resources that can be completed on one's laptop
        for this requirement.  Scouts are encouraged on their own to make
        an attempt to the best of their abilities and resources to bring
        any work they have completed for this requirement to the class for
        sharing with the counselor and rest of the Scouts.
    - note:
        - inPerson
        - online
      text: |-
        Scouts should make a best attempt to choose one of the options to
        have ready for the class and review by the counselor / instructor.
        The counselor / instructor will be able to give guidance to Scouts
        that may have question or have struggles in completing this
        requirement, however Scouts must make an effort to come to the
        class with some work attempted to be done.
- requirement: 4
  text: |-
    Discuss with your counselor how fulfilling requirements 2 and 3 differed
    from each other. Tell about the benefits derived from using CAD for
    requirement 3. Include in your discussion the software you used as well
    as other software options that are available.
  children:
    - note:
        - inPerson
        - online
      text: |-
        Scouts will have an opportunity to discuss the components of this
        requirement with the counselor and other Scouts in the class. It is
        not enough to just be present for the discussion, but active
        participation will be required in order for Scouts to complete this
        requirement. Failure to positively and actively participate in the
        discussion may negate the Scout from completion of this
        requirement.
- requirement: 5
  text: |-
    Using single-stroke slant or vertical Gothic lettering (without the aid
    of a template or lettering guide), write a brief explanation of what you
    consider to be the most important benefit in using CAD in a particular
    industry (aerospace, electronics, manufacturing, architectural, or
    other). Use the experience gained in fulfilling requirements 2, 3, and 4
    to support your opinion. Use the formatted sheet of paper you prepared in
    requirement 1 for your lettering project.
  children:
    - note:
        - inPerson
        - online
      text: |-
        This requirement will be completed during the class with guidance
        from the counselor / instructor. Scouts however are encouraged to
        attempt trying this prior to the class.
- requirement: 6
  text: |-
    Do ONE of the following (a or b):
  children:
    - requirement: a
      text: |-
        Visit a facility or industry workplace where drafting is part of
        the business. Ask to see an example of the work that is done there,
        the different drafting facilities, and the tools used.
      children:
        - requirement: 1
          text: |-
            Find out how much of the drafting done there is manual and
            how much is done using CAD. If CAD is used, find out what
            software is used and how and why it was chosen.
        - requirement: 2
          text: |-
            Ask about the drafting services provided. Ask who uses the
            designs produced in the drafting area and how those designs
            are used. Discuss how the professionals who perform drafting
            cooperate with other individuals in the drafting area and
            other areas of the business.
        - requirement: 3
          text: |-
            Ask how important the role of drafting is to producing the
            end product or service that this business supplies.  Find out
            how drafting contributes to the company’s end product or
            service.
        - note:
            - inPerson
            - online
          text: |-
            This requirement option will NOT be done in the class,
            however Scouts that choose to do this requirement option
            should bring their notes and research and be prepared to
            share their work with the counselor and class.
    - requirement: b
      text: |-
        Using resources you find on your own such as at the library and on
        the Internet (with your parent’s permission), learn more about the
        drafting trade and discuss the following with your counselor.
      children:
        - requirement: 1
          text: |-
            The drafting tools used in the past—why and how they were
            used. Explain which tools are still used today and how their
            use has changed with the advent of new tools. Discuss which
            tools are being made obsolete by newer tools in the industry.
        - requirement: 2
          text: |-
            Tell what media types were used in the past and how drawings
            were used, stored, and reproduced. Tell how the advent of CAD
            has changed the media used, and discuss how these changes
            affect the storage or reproduction of drawings.
        - requirement: 3
          text: |-
            Discuss whether the types of media have changed such that
            there are new uses for the drawings, or other outputs,
            produced by designers. Briefly discuss how new media types
            are used in the industry today.
        - note:
            - inPerson
            - online
          text: |-
            The counselor will facilitate time during the class for
            discussion of this requirement option. Scouts must note that
            they will not necessarily be spoon-fed the answers to
            complete this requirement but will be engaged by the
            counselor to share their findings in a group discussion.
            Scouts should utilize the merit badge pamphlet to familiarize
            themselves with the terms, methods, and history of drafting
            in order to positively and actively participate in the group
            discussion during the class.  Scouts not prepared and/or
            participatory in the group discussion for this requirement
            option will not complete this requirement in the class.
- requirement: 7
  text: |-
    Find out about three career opportunities in drafting. Pick one and find
    out the education, training, and experience required for this profession.
    Discuss this with your counselor, and explain why this profession might
    interest you.
  children:
    - note:
        - inPerson
        - online
      text: |-
        Scouts should review this requirement and its components and be
        prepared to discuss.  It is strongly recommended that Scouts bring
        any notes or supporting documents they may have to help show the
        counselor that they have prepared for completion of this
        requirement.
